var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,k="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,m=ba&&"em-pthread"==self.name;if(k){var ca=require("worker_threads");global.Worker=ca.Worker;m=(ba=!ca.Ii)&&"em-pthread"==ca.workerData}
var da=Object.assign({},h),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},ia="undefined"!=typeof document?document.currentScript?.src:void 0;k?ia=__filename:ba&&(ia=self.location.href);var ja="",ka,la;
if(k){var fs=require("fs"),ma=require("path");ja=__dirname+"/";la=a=>{a=na(a)?new URL(a):ma.normalize(a);return fs.readFileSync(a)};ka=a=>{a=na(a)?new URL(a):ma.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!h.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof oa||a.context instanceof oa))throw a;
});ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?ja=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ja=document.currentScript.src),ja=ja.startsWith("blob:")?"":ja.substr(0,ja.replace(/[?#].*/,"").lastIndexOf("/")+1),k||(ba&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=a=>na(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=
()=>{(200==d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url))));k&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var pa=console.log.bind(console),qa=console.error.bind(console);k&&(pa=(...a)=>fs.writeSync(1,a.join(" ")+"\n"),qa=(...a)=>fs.writeSync(2,a.join(" ")+"\n"));var ra=h.print||pa,p=h.printErr||qa;
Object.assign(h,da);da=null;h.arguments&&(ea=h.arguments);h.thisProgram&&(fa=h.thisProgram);h.quit&&(ha=h.quit);
if(m){var sa;if(k){var ta=ca.parentPort;ta.on("message",c=>onmessage({data:c}));Object.assign(globalThis,{self:global,importScripts:()=>{},postMessage:c=>ta.postMessage(c),performance:global.performance||{now:Date.now}})}var ua=!1;function a(...c){c=c.join(" ");k?fs.writeSync(2,c+"\n"):console.error(c)}h.printErr||(p=a);self.alert=function(...c){postMessage({ci:"alert",text:c.join(" "),Oi:va()})};h.instantiateWasm=(c,d)=>new Promise(e=>{sa=f=>{f=new WebAssembly.Instance(f,wa());d(f);e()}});self.onunhandledrejection=
c=>{throw c.reason||c;};function b(c){try{var d=c.data,e=d.cmd;if("load"===e){let f=[];self.onmessage=g=>f.push(g);self.startWorker=()=>{postMessage({cmd:"loaded"});for(let g of f)b(g);self.onmessage=b};for(const g of d.handlers)if(!h[g]||h[g].proxy)h[g]=(...l)=>{postMessage({ci:"callHandler",Hi:g,args:l})},"print"==g&&(ra=h[g]),"printErr"==g&&(p=h[g]);xa=d.wasmMemory;ya();za=Aa(d.wasmOffsetConverter);sa(d.wasmModule)}else if("run"===e){Ba(d.pthread_ptr,0,0,1,0,0);Ca(d.pthread_ptr);Da();Ea();ua||=
!0;try{Fa(d.start_routine,d.arg)}catch(f){if("unwind"!=f)throw f;}}else"cancel"===e?va()&&Ga(-1):"setimmediate"!==d.target&&("checkMailbox"===e?ua&&Ha():e&&(p(`worker: received unknown command ${e}`),p(d)))}catch(f){throw Ia(),f;}}self.onmessage=b}var Ja;h.wasmBinary&&(Ja=h.wasmBinary);var xa,Ka,La=!1,Ma,r,t,Na,Oa,u,v,w,x;
function ya(){var a=xa.buffer;h.HEAP8=r=new Int8Array(a);h.HEAP16=Na=new Int16Array(a);h.HEAPU8=t=new Uint8Array(a);h.HEAPU16=Oa=new Uint16Array(a);h.HEAP32=u=new Int32Array(a);h.HEAPU32=v=new Uint32Array(a);h.HEAPF32=w=new Float32Array(a);h.HEAPF64=x=new Float64Array(a)}
if(!m){if(h.wasmMemory)xa=h.wasmMemory;else{var Pa=h.INITIAL_MEMORY||67108864;xa=new WebAssembly.Memory({initial:Pa/65536,maximum:Pa/65536,shared:!0});if(!(xa.buffer instanceof SharedArrayBuffer))throw p("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),k&&p("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");}ya()}var Qa=[],Ra=[],Sa=[],Ta=[],Ua=0,Va=null,Wa=null;function Xa(){Ua++;h.monitorRunDependencies?.(Ua)}function Ya(){Ua--;h.monitorRunDependencies?.(Ua);if(0==Ua&&(null!==Va&&(clearInterval(Va),Va=null),Wa)){var a=Wa;Wa=null;a()}}function Za(a){h.onAbort?.(a);a="Aborted("+a+")";p(a);La=!0;Ma=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var $a=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),ab;
function bb(a){if(a==ab&&Ja)return new Uint8Array(Ja);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}function cb(a){return Ja?Promise.resolve().then(()=>bb(a)):ka(a).then(b=>new Uint8Array(b),()=>bb(a))}var za;
function db(a,b){function c(){var n=0,q=0;do{var y=g[e++];n+=(y&127)<<q;q+=7}while(y&128);return n}function d(){var n=c();c();0!=(n&1)&&c()}var e=8,f=0;this.Rh={};this.yh=[];this.Uh={};var g=a;a:for(;e<g.length;){a=g[e++];var l=c()+e;switch(a){case 2:for(a=c();0<a--;)switch(e=c()+e,e=c()+e,g[e++]){case 0:++f;c();break;case 1:c();d();break;case 2:d();break;case 3:e+=2;break;case 4:++e,c()}break;case 10:for(a=c();0<a--;)l=c(),this.Rh[f++]=e,this.yh.push(e),e+=l;break a}e=l}b=WebAssembly.Module.customSections(b,
"name");if(b=b.length?b[0]:void 0)for(g=new Uint8Array(b),e=0;e<g.length;)if(b=g[e++],f=c(),1!=b)e+=f;else for(a=c();0<a--;)b=c(),f=c(),this.Uh[b]=z(g,e,f),e+=f}function Aa(a){var b=Object.create(db.prototype);return Object.assign(b,a)}function eb(a,b,c){var d;return cb(a).then(e=>{d=e;return WebAssembly.instantiate(e,b)}).then(e=>{za=new db(d,e.module);return e}).then(c,e=>{p(`failed to asynchronously prepare wasm: ${e}`);Za(e)})}
function fb(a,b){var c=ab;Ja||"function"!=typeof WebAssembly.instantiateStreaming||$a(c)||na(c)||k||"function"!=typeof fetch?eb(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>{var e=WebAssembly.instantiateStreaming(d,a),f=d.clone().arrayBuffer();return e.then(function(g){f.then(l=>{za=new db(new Uint8Array(l),g.module);b(g)},l=>p(`failed to initialize offset-converter: ${l}`))},function(g){p(`wasm streaming compile failed: ${g}`);p("falling back to ArrayBuffer instantiation");return eb(c,a,b)})})}
function wa(){gb={mf:hb,ld:ib,c:jb,af:kb,O:lb,Hb:mb,ab:nb,cc:ob,lb:pb,_a:qb,gb:rb,P:sb,$a:tb,wb:ub,xf:vb,Fa:wb,Tf:xb,ua:yb,$:zb,Hd:Ab,Q:Bb,If:Ca,Sd:Cb,vb:Db,Xa:Eb,mb:Fb,ob:Gb,nb:Hb,pb:Ib,Ya:Jb,n:Kb,kb:Lb,Va:Mb,qb:Nb,jb:Ob,rb:Pb,sb:Qb,Wa:Rb,ub:Sb,tb:Tb,bb:Ub,b:Vb,N:Wb,ad:Xb,l:Yb,m:Zb,cb:$b,hb:ac,Tb:bc,Rc:cc,g:dc,e:ec,q:fc,d:gc,fb:hc,ib:ic,Aa:jc,za:kc,rd:lc,Ra:mc,Uc:nc,ya:oc,xa:pc,Qc:qc,Sc:rc,wa:uc,va:vc,Xb:wc,ta:xc,Nb:yc,Zc:zc,Ja:zc,sa:Ac,ra:Bc,qa:Cc,pa:Dc,oa:Ec,dd:Fc,na:Gc,ma:Hc,la:Ic,ka:Jc,tc:Kc,
uc:Lc,wc:Mc,vc:Nc,ja:Oc,ia:Pc,ha:Qc,fc:Rc,ga:Sc,fa:Tc,ea:Uc,xd:Vc,da:Wc,vd:Xc,rc:Yc,ca:Zc,ba:$c,yd:ad,aa:bd,_:cd,Z:dd,Y:ed,X:fd,W:gd,td:hd,Ta:jd,V:kd,Zb:ld,U:md,gc:nd,T:od,Mb:pd,Yc:qd,Ia:qd,S:rd,R:sd,Sf:td,Rf:ud,Qf:vd,Pf:wd,Of:xd,kc:yd,Da:yd,Id:yd,Jd:yd,xb:yd,kd:zd,Dd:zd,Ea:zd,Nf:Ad,jc:Bd,Ca:Bd,Ed:Bd,Fd:Bd,Gd:Bd,Bd:Cd,Mf:Dd,Lf:Ed,qd:Fd,Qa:Gd,Tc:Hd,ic:Id,Kf:Jd,Jf:Kd,_c:Ld,Hf:Md,Gf:Nd,bd:Od,Ff:Pd,Ef:Qd,Cf:Rd,ud:Sd,Ua:Td,Bf:Ud,_b:Vd,Af:Wd,Lb:Xd,Xc:Yd,Ha:Yd,Df:Zd,zf:$d,yf:ae,mc:be,nc:ce,pc:de,wf:ee,vf:fe,
uf:ge,$b:he,tf:ie,md:je,sf:ke,rf:le,Fc:me,qf:ne,ac:oe,dc:pe,Vc:qe,pf:re,zb:se,Gb:te,nf:ue,of:ve,La:we,Na:xe,Ka:we,od:ye,Ma:xe,pd:ze,Oa:Ae,lf:Be,Pb:Ce,Qb:De,jf:Ee,hf:Fe,gf:Ge,kf:He,ff:Ie,sc:Je,bc:Ke,ef:Le,df:Me,Oc:Ne,oc:Oe,qc:Pe,$e:Qe,cf:Re,bf:Se,Gc:Te,Mc:Ue,Lc:Ue,Ye:Ve,_e:We,Ze:Xe,Xe:Ye,Db:Ze,Cb:$e,We:af,Ve:bf,Ue:cf,Te:df,sd:ef,Sa:ff,Se:gf,Yb:hf,Qe:jf,hc:kf,Pe:lf,Kb:mf,Wc:nf,Ga:nf,Oe:of,Ne:pf,$c:qf,Jb:rf,Me:sf,Le:tf,Fb:uf,Eb:vf,Pa:wf,Cd:xf,Ke:yf,Je:zf,Ie:Af,cd:Bf,Ib:Cf,He:Df,Ub:Ef,Rb:Ff,Wb:Gf,Vb:Hf,
Ge:If,Fe:Jf,Ee:Kf,De:Lf,Ce:Mf,Be:Nf,Ae:Of,ze:Pf,ye:Qf,xe:Rf,Ad:Sf,we:Tf,ve:Uf,ue:Vf,te:Wf,Bb:Xf,Ab:Yf,se:Zf,zd:$f,Pc:ag,re:bg,qe:cg,pe:dg,oe:eg,Ec:fg,Ac:gg,ne:hg,le:ig,ke:jg,je:kg,Dc:lg,zc:mg,ie:ng,he:og,ge:pg,fe:qg,Cc:rg,yc:sg,ee:tg,de:ug,ce:vg,ae:wg,Bc:xg,xc:yg,lc:zg,$d:Ag,jd:Bg,hd:Cg,_d:Dg,id:Eg,fd:Fg,Zd:Gg,gd:Hg,ed:Ig,nd:Jg,Yd:Kg,Xd:Lg,Wd:Mg,Vd:Ng,Ud:Og,Td:Pg,Rd:Qg,Qd:Rg,Pd:Sg,Od:Tg,Ob:Ug,Ba:Ug,Kd:Ug,Ld:Ug,yb:Ug,Kc:Vg,Ic:Wg,Jc:Xg,Hc:Yg,Nc:Zg,Nd:$g,Md:ah,ec:bh,k:ch,db:dh,M:eh,Vf:fh,C:gh,r:hh,E:ih,
f:jh,i:kh,F:lh,u:mh,p:nh,o:oh,x:ph,v:qh,w:rh,K:sh,I:th,H:uh,L:vh,J:wh,y:xh,t:yh,z:zh,B:Ah,A:Bh,D:Ch,s:Dh,G:Eh,eb:Fh,j:Gh,be:Hh,me:Ih,Re:Jh,h:Kh,Sb:Lh,Za:Mh,Uf:Nh,a:xa,wd:Oh};return{a:gb}}
var Th={8209556:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.li!==h.canvas&&(d.mh=h.createContext(h.canvas,!1,!0),d.li=h.canvas);if(d.w!==a||d.h!==b||d.vi!==d.mh)d.image=d.mh.createImageData(a,b),d.w=a,d.h=b,d.vi=d.mh;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=u[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.oi!==a&&(d.ni=new Int32Array(a.buffer),d.pi=new Uint8Array(a.buffer),d.oi=a),
a=d.ni,c=a.length,a.set(u.subarray(b,b+c)),a=d.pi,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.mh.putImageData(d.image,0,0)},8211024:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=
b.length;l<n;){var q=u[e];b[l]=q&255;b[l+1]=q>>8&255;b[l+2]=q>>16&255;b[l+3]=q>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(u.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=A(c.length+1);B(c,t,d,c.length+1);return d},8212012:a=>{h.canvas&&(h.canvas.style.cursor=a?z(t,a):"")},8212095:()=>{h.canvas&&(h.canvas.style.cursor="none")},8212164:()=>window.innerWidth,8212194:()=>window.innerHeight,8212225:a=>
{a=(a?z(t,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");var b=Array(Ph(a)+1);B(a,b,0,b.length);a=b;b=A(a.length);a.subarray||a.slice||(a=new Uint8Array(a));t.set(a,b);return b},8212450:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,8212597:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,8212831:a=>
{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.gg||("undefined"!==typeof AudioContext?b.gg=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.gg=new webkitAudioContext),b.gg&&"undefined"===typeof navigator.userActivation&&Qh(b.gg));return void 0===b.gg?-1:0},8213383:()=>h.SDL2.gg.sampleRate,8213451:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.capture.lh&&(clearInterval(g.capture.lh),g.capture.lh=void 0,g.capture.vh=void 0);g.capture.Th=g.gg.createMediaStreamSource(l);
g.capture.kh=g.gg.createScriptProcessor(b,a,1);g.capture.kh.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Ph=n.inputBuffer,Rh(c,[d]))};g.capture.Th.connect(g.capture.kh);g.capture.kh.connect(g.gg.destination);g.capture.stream=l}var g=h.SDL2;g.capture.vh=g.gg.createBuffer(a,b,g.gg.sampleRate);g.capture.vh.getChannelData(0).fill(0);g.capture.lh=setInterval(function(){g.capture.Ph=g.capture.vh;Rh(c,[d])},b/g.gg.sampleRate*1E3);void 0!==
navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},8215144:(a,b,c,d)=>{var e=h.SDL2;e.audio.kh=e.gg.createScriptProcessor(b,0,a);e.audio.kh.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.lh&&(clearInterval(e.audio.lh),e.audio.lh=void 0,e.audio.vh=void 0),e.audio.Ih=f.outputBuffer,Rh(c,[d]))};
e.audio.kh.connect(e.gg.destination);"suspended"===e.gg.state&&(e.audio.vh=e.gg.createBuffer(a,b,e.gg.sampleRate),e.audio.vh.getChannelData(0).fill(0),e.audio.lh=setInterval(function(){"undefined"!==typeof navigator.userActivation&&navigator.userActivation.hasBeenActive&&e.gg.resume();e.audio.Ih=e.audio.vh;Rh(c,[d]);e.audio.Ih=void 0},b/e.gg.sampleRate*1E3))},8216319:(a,b)=>{for(var c=h.SDL2,d=c.capture.Ph.numberOfChannels,e=0;e<d;++e){var f=c.capture.Ph.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+
f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Sh(a+4*g,f[g]);else for(g=0;g<b;++g)Sh(a+4*(g*d+e),f[g])}},8216924:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=c.audio.Ih.numberOfChannels,e=0;e<d;++e){var f=c.audio.Ih.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=w[a+(g*d+e)]}},8217413:a=>{var b=h.SDL2;if(a){void 0!==b.capture.lh&&clearInterval(b.capture.lh);
if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.kh&&(b.capture.kh.onaudioprocess=function(){},b.capture.kh.disconnect());void 0!==b.capture.Th&&b.capture.Th.disconnect();b.capture=void 0}else void 0!=b.audio.kh&&b.audio.kh.disconnect(),void 0!==b.audio.lh&&clearInterval(b.audio.lh),b.audio=void 0;void 0!==b.gg&&void 0===b.audio&&void 0===b.capture&&(b.gg.close(),b.gg=void 0)}};
function oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Uh=a=>{a.terminate();a.onmessage=()=>{}},Zh=a=>{0==Vh.length&&(Wh(),Xh(Vh[0]));var b=Vh.pop();if(!b)return 6;Yh.push(b);C[a.sh]=b;b.sh=a.sh;var c={cmd:"run",start_routine:a.yi,arg:a.ai,pthread_ptr:a.sh};k&&b.unref();b.postMessage(c,a.zi);return 0},D=0,E=(a,b,c,...d)=>{for(var e=d.length,f=$h(),g=ai(8*e),l=g>>3,n=0;n<d.length;n++)x[l+n]=d[n];a=bi(a,b,e,g,c);ci(f);return a};
function Oh(a){if(m)return E(0,0,1,a);Ma=a;if(!(di||0<D)){for(var b of Yh)Uh(b);for(b of Vh)Uh(b);Vh=[];Yh=[];C=[];h.onExit?.(a);La=!0}ha(a,new oa(a))}var ei=a=>{a instanceof oa||"unwind"==a||ha(1,a)};function fi(a){if(m)return E(1,0,0,a);Jh(a)}var Jh=a=>{Ma=a;if(m)throw fi(a),"unwind";Oh(a)},Vh=[],Yh=[],gi=[],C={};function hi(){for(var a=navigator.hardwareConcurrency;a--;)Wh();Qa.unshift(()=>{Xa();ii(()=>Ya())})}var ki=a=>{var b=a.sh;delete C[b];Vh.push(a);Yh.splice(Yh.indexOf(a),1);a.sh=0;ji(b)};
function Ea(){gi.forEach(a=>a())}
var Xh=a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.cmd;if(f.targetThread&&f.targetThread!=va()){var l=C[f.targetThread];l?l.postMessage(f,f.transferList):p(`Internal error! Worker sent a message "${g}" to target pthread ${f.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===g)Ha();else if("spawnThread"===g)Zh(f);else if("cleanupThread"===g)ki(C[f.thread]);else if("killThread"===g)f=f.thread,g=C[f],delete C[f],Uh(g),ji(f),Yh.splice(Yh.indexOf(g),1),g.sh=0;else if("cancelThread"===
g)C[f.thread].postMessage({cmd:"cancel"});else if("loaded"===g)a.loaded=!0,k&&!a.sh&&a.unref(),b(a);else if("alert"===g)alert(`Thread ${f.threadId}: ${f.text}`);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===g)h[f.handler](...f.args);else g&&p(`worker sent an unknown command ${g}`)};a.onerror=f=>{p(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};k&&(a.on("message",f=>a.onmessage({data:f})),a.on("error",f=>a.onerror(f)));var c=[],d=["onExit",
"onAbort","print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({cmd:"load",handlers:c,wasmMemory:xa,wasmModule:Ka,wasmOffsetConverter:za})});function ii(a){m?a():Promise.all(Vh.map(Xh)).then(a)}function Wh(){var a=ia;h.mainScriptUrlOrBlob&&(a=h.mainScriptUrlOrBlob,"string"!=typeof a&&(a=URL.createObjectURL(a)));a=new Worker(a,{workerData:"em-pthread",name:"em-pthread"});Vh.push(a)}
var li,mi="undefined"!=typeof TextDecoder?new TextDecoder:void 0,z=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&mi)return mi.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&
1023))}}else d+=String.fromCharCode(e)}return d},ni=a=>{for(;0<a.length;)a.shift()(h)},Da=()=>{var a=va(),b=v[a+52>>2];oi(b,b-v[a+56>>2]);ci(b)},Fa=(a,b)=>{D=0;a=pi(a,b);di||0<D?Ma=a:Ga(a)},di=h.noExitRuntime||!0;
function Sh(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":r[a]=b;break;case "i8":r[a]=b;break;case "i16":Na[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":Za("to do setValue(i64) use WASM_BIGINT");case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":v[a>>2]=b;break;default:Za(`invalid type for setValue: ${c}`)}}
var qi=(a,b)=>a?z(t,a,b):"",hb=(a,b,c,d)=>{Za(`Assertion failed: ${a?z(t,a):""}, at: `+[b?b?z(t,b):"":"unknown filename",c,d?d?z(t,d):"":"unknown function"])},ib=(a,b)=>dynCall_vi(a,b);class ri{constructor(a){this.th=a-24}}var si=0,ti=0,jb=(a,b,c)=>{var d=new ri(a);v[d.th+16>>2]=0;v[d.th+4>>2]=b;v[d.th+8>>2]=c;si=a;ti++;throw si;};function ui(a,b,c,d){return m?E(2,0,1,a,b,c,d):kb(a,b,c,d)}
var kb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return p("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(m&&0===e.length)return ui(a,b,c,d);a={yi:c,sh:a,ai:d,zi:e};return m?(a.ci="spawnThread",postMessage(a,e),0):Zh(a)};function lb(a,b,c){return m?E(3,0,1,a,b,c):0}function mb(a,b){if(m)return E(4,0,1,a,b)}
var B=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function nb(a,b,c){if(m)return E(5,0,1,a,b,c)}
function ob(a,b,c){return m?E(6,0,1,a,b,c):0}function pb(a,b){if(m)return E(7,0,1,a,b)}function qb(a,b,c){if(m)return E(8,0,1,a,b,c)}function rb(a,b,c,d){if(m)return E(9,0,1,a,b,c,d)}function sb(a,b,c,d){if(m)return E(10,0,1,a,b,c,d)}var Ph=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b};function tb(a,b,c,d){if(m)return E(11,0,1,a,b,c,d)}function ub(a,b){if(m)return E(12,0,1,a,b)}
var vb=()=>{Za("")},wb=()=>1,xb=a=>{Ba(a,!ba,1,!aa,16777216,!1);Ea()},vi=a=>{if(!La)try{if(a(),!(di||0<D))try{m?Ga(Ma):Jh(Ma)}catch(b){ei(b)}}catch(b){ei(b)}},Ca=a=>{"function"===typeof Atomics.Bi&&(Atomics.Bi(u,a>>2,a).value.then(Ha),Atomics.store(u,a+128>>2,1))},Ha=()=>{var a=va();a&&(Ca(a),vi(wi))},yb=(a,b)=>{a==b?setTimeout(Ha):m?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=C[a])&&a.postMessage({cmd:"checkMailbox"})},xi=[],zb=(a,b,c,d,e)=>{xi.length=d;e>>=3;for(var f=0;f<d;f++)xi[f]=x[e+
f];a=b?Th[b]:yi[a];li=c;c=a(...xi);li=0;return c};function Ab(){if(m)return E(13,0,1);di=!1;D=0}
var Bb=a=>{m?postMessage({cmd:"cleanupThread",thread:a}):ki(C[a])},Cb=a=>{k&&C[a].ref()},Ii=(a,b)=>{zi=a;Ai=b;if(Bi)if(Ci||(D+=1,Ci=!0),0==a)Di=function(){var d=Math.max(0,Ei+b-gc())|0;setTimeout(Fi,d)};else if(1==a)Di=function(){Gi(Fi)};else if(2==a){if("undefined"==typeof Hi)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Hi=function(d){c.push(d);if(ba){let e;(e=h).setImmediates??
(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Hi=setImmediate;Di=function(){Hi(Fi)}}},gc;gc=()=>performance.timeOrigin+performance.now();
var Oi=a=>{function b(){return c<Ji?(--D,!1):!0}Bi=a;var c=Ji;Ci=!1;Fi=function(){if(!La)if(0<Ki.length){var d=Ki.shift();d.Gi(d.ai);if(Li){var e=Li,f=0==e%1?e-1:Math.floor(e);Li=d.Di?f:(8*e+(f+.5))/9}h.setStatus&&(d=h.statusMessage||"Please wait...",e=Li,f=Mi.Fi,e?e<f?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(d):h.setStatus(""));b()&&setTimeout(Fi,0)}else if(b())if(Ni=Ni+1|0,1==zi&&1<Ai&&0!=Ni%Ai)Di();else{0==zi&&(Ei=gc());if(F)for(d=F.Ah,F.Ah=F.Dh,F.Dh=d,d=F.uh,F.uh=
F.Nh,F.Nh=d,d=0;21>=d;++d)F.uh[d]=0;La||h.preMainLoop&&!1===h.preMainLoop()||(vi(a),h.postMainLoop?.());b()&&("object"==typeof SDL&&SDL.audio?.Ni?.(),Di())}}},Pi=(a,b)=>{D+=1;return setTimeout(()=>{--D;vi(a)},b)},Ci=!1,Di=null,Ji=0,Bi=null,zi=0,Ai=0,Ni=0,Ki=[];function Qi(){Di=null;Ji++}function Ri(){Ji++;var a=zi,b=Ai,c=Bi;Bi=null;Oi(c);Ii(a,b);Di()}var Mi={},Ei,Fi,Li,Si=!1,Ti=!1,Ui=[];
function Vi(){function a(){Ti=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Wi){Wi=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Ti&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Xi=!1,Yi=void 0,Zi=void 0;
function $i(){if(!Si)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var aj=0;function Gi(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===aj)aj=b+1E3/60;else for(;b+2>=aj;)aj+=1E3/60;setTimeout(a,Math.max(aj-b,0))}}var bj=[];function cj(){var a=h.canvas;bj.forEach(b=>b(a.width,a.height))}
function dj(a,b,c){b&&c?(a.Ci=b,a.ui=c):(b=a.Ci,c=a.ui);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Zi?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var ej={},Hi,Wi,G=12288,fj=!1,gj=0,hj=0,ij=0,I={alpha:!1,depth:!1,stencil:!1,antialias:!1},jj={},kj;function Db(a){if(m)return E(14,0,1,a);if(12448==a)return G=12288,1;G=12300;return 0}
function Eb(a,b,c,d,e){if(m)c=E(15,0,1,a,b,c,d,e);else if(62E3!=a)G=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)I.alpha=0<u[b+4>>2];else if(12325==a)I.depth=0<u[b+4>>2];else if(12326==a)I.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+4>>2],I.antialias=0<a;else if(12338==a)a=u[b+4>>2],I.antialias=1==a;else if(12544==a)I.Ji=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>2]=1),c&&0<d&&(v[c>>2]=62002),G=12288,c=1):(G=12300,c=0)}return c}
var lj=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},mj=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},
nj=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},oj=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},pj=1,qj=[],rj={},J=[],sj=[],tj=[],uj=[],K=[],vj=[],L={},M=[],N=[],wj=[],xj=[],yj=[1,1,2,2,4,4,4,2,3,4,8],zj={},Aj={},Bj=4,Cj=0,Dj=a=>{for(var b=pj++,c=a.length;c<b;c++)a[c]=null;return b},Ej=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=P[c](),g=f&&Dj(d);f?(f.name=g,d[g]=f):Q||=1282;u[b+4*e>>2]=g}},Gj=a=>{Fj=!1;for(var b=0;b<F.gi;++b){var c=F.qh[b];if(c.Bh&&c.enabled){Fj=!0;var d=c.Mh;d=0<d?a*d:c.size*yj[c.type-5120]*a;var e=32-Math.clz32(0===
d?0:d-1);var f=F.Ah[e],g=F.uh[e];F.uh[e]=F.uh[e]+1&63;var l=f[g];l?e=l:(l=P.getParameter(34964),f[g]=P.createBuffer(),P.bindBuffer(34962,f[g]),P.bufferData(34962,1<<e,35048),P.bindBuffer(34962,l),e=f[g]);P.bindBuffer(34962,e);P.bufferSubData(34962,0,t.subarray(c.th,c.th+d));c.Zh.call(P,b,c.size,c.type,c.Vh,c.Mh,0)}}},Ij=(a,b)=>{a.yh||(a.yh=a.getContext,a.getContext=function(d,e){e=a.yh(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Sh?a.getContext("webgl2",b):a.getContext("webgl",
b);return c?Hj(c,b):0},Hj=(a,b)=>{var c=A(8);v[c+4>>2]=va();var d={handle:c,attributes:b,version:b.Sh,fh:a};a.canvas&&(a.canvas.ph=d);L[c]=d;("undefined"==typeof b.si||b.si)&&Jj(d);d.gi=d.fh.getParameter(34921);d.qh=[];for(a=0;a<d.gi;a++)d.qh[a]={enabled:!1,Bh:!1,size:0,type:0,Vh:0,Mh:0,th:0,Zh:null};d.uh=[];d.Nh=[];d.uh.length=d.Nh.length=22;d.Ah=[];d.Dh=[];d.Ah.length=d.Dh.length=22;d.zh=[];d.zh.length=22;for(a=0;21>=a;++a){d.zh[a]=null;d.uh[a]=d.Nh[a]=0;d.Ah[a]=[];d.Dh[a]=[];b=d.Ah[a];var e=d.Dh[a];
b.length=e.length=64;for(var f=0;64>f;++f)b[f]=e[f]=null}return c},Kj=a=>{F=L[a];h.mh=P=F?.fh},Jj=a=>{a||=F;if(!a.wi){a.wi=!0;var b=a.fh;lj(b);mj(b);nj(b);b.Ei=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Ki=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.ih=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.ih)b.ih=b.getExtension("EXT_disjoint_timer_query");b.Mi=b.getExtension("WEBGL_multi_draw");oj(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},Lj={},Q,F,Fj;function Fb(a,b,c,d){if(m)return E(16,0,1,a,b,c,d);if(62E3!=a)return G=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return G=12292,0;d+=8}if(2>a||3<a)return G=12293,0;I.Sh=a-1;I.Li=0;kj=Ij(h.canvas,I);if(0!=kj)return G=12288,Kj(kj),h.Ai=!0,Ui.forEach(function(e){e()}),Kj(null),62004;G=12297;return 0}
function Gb(a,b,c,d){if(m)return E(17,0,1,a,b,c,d);if(62E3!=a)return G=12296,0;if(62002!=b)return G=12293,0;G=12288;return 62006}function Hb(a,b){if(m)return E(18,0,1,a,b);if(62E3!=a)return G=12296,0;if(62004!=b)return G=12294,0;a=kj;F===L[a]&&(F=null);if("object"==typeof Mj)for(var c=L[a].fh.canvas,d=0;d<Nj.length;++d)Nj[d].target!=c||Oj(d--);L[a]&&L[a].fh.canvas&&(L[a].fh.canvas.ph=void 0);Pj(L[a].handle);L[a]=null;G=12288;gj==b&&(gj=0);return 1}
function Ib(a,b){if(m)return E(19,0,1,a,b);if(62E3!=a)return G=12296,0;if(62006!=b)return G=12301,1;hj==b&&(hj=0);ij==b&&(ij=0);G=12288;return 1}
function Jb(a,b,c,d){if(m)return E(20,0,1,a,b,c,d);if(62E3!=a)return G=12296,0;if(62002!=b)return G=12293,0;if(!d)return G=12300,0;G=12288;switch(c){case 12320:return u[d>>2]=I.alpha?32:24,1;case 12321:return u[d>>2]=I.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>2]=I.depth?24:0,1;case 12326:return u[d>>2]=I.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;
case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>2]=I.antialias?4:0,1;case 12338:return u[d>>2]=I.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;
case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return G=12292,0}}function Kb(a){if(m)return E(21,0,1,a);G=12288;return 0!=a&&1!=a?0:62E3}function Lb(){return m?E(22,0,1):G}function Mb(a,b,c){if(m)return E(23,0,1,a,b,c);if(62E3!=a)return G=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);fj=!0;G=12288;return 1}
function Nb(a,b,c,d){if(m)return E(24,0,1,a,b,c,d);if(62E3!=a)return G=12296,0;if(0!=d&&62004!=d)return G=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return G=12301,0;Kj(d?kj:null);gj=d;ij=b;hj=c;G=12288;return 1}var Qj=a=>{var b=Ph(a)+1,c=A(b);c&&B(a,t,c,b);return c};
function Ob(a,b){if(m)return E(25,0,1,a,b);if(62E3!=a)return G=12296,0;G=12288;if(jj[b])return jj[b];switch(b){case 12371:a=Qj("Emscripten");break;case 12372:a=Qj("1.4 Emscripten EGL");break;case 12373:a=Qj("");break;case 12429:a=Qj("OpenGL_ES");break;default:return G=12300,0}return jj[b]=a}function Pb(a,b){if(m)return E(26,0,1,a,b);if(fj)if(h.mh)if(h.mh.isContextLost())G=12302;else return G=12288,1;else G=12290;else G=12289;return 0}
function Qb(a,b){if(m)return E(27,0,1,a,b);if(62E3!=a)return G=12296,0;0==b?Ii(0,0):Ii(1,b);G=12288;return 1}function Rb(a){if(m)return E(28,0,1,a);if(62E3!=a)return G=12296,0;ij=hj=gj=0;fj=!1;G=12288;return 1}function Sb(){if(m)return E(29,0,1);G=12288;return 1}function Tb(a){if(m)return E(30,0,1,a);G=12288;return 1}
var Rj=[],Sj=(a,b)=>{Rj.length=0;for(var c;c=t[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Rj.push(112==c?v[b>>2]:105==c?u[b>>2]:x[b>>3]);b+=d?8:4}return Rj},Ub=(a,b,c)=>{b=Sj(b,c);return Th[a](...b)},Tj=(a,b,c)=>{b=Sj(b,c);return m?E(0,a,1,...b):Th[a](...b)},Vb=(a,b,c)=>Tj(a,b,c),Wb=(a,b,c)=>Tj(a,b,c),Xb=()=>{Qi();Bi=null},Yb=()=>{},Zb=()=>Date.now(),Uj=0,Vj=[];
function Wj(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of Vj)if(e.Xh==a&&d(e.bi,c))return;Vj.push({Xh:a,ii:b,bi:c});Vj.sort((f,g)=>f.ii<g.ii)}function Xj(a){Vj=Vj.filter(b=>b.Xh!=a)}function Yj(){return navigator.userActivation?navigator.userActivation.isActive:Uj&&Zj.Fh}function ak(){if(Yj()){var a=Vj;Vj=[];for(var b of a)b.Xh(...b.bi)}}var Nj=[];
function Oj(a){var b=Nj[a];b.target.removeEventListener(b.mg,b.ei,b.gh);Nj.splice(a,1)}function R(a){if(!a.target)return-4;if(a.hh)a.ei=function(c){++Uj;Zj=a;ak();a.jh(c);ak();--Uj},a.target.addEventListener(a.mg,a.ei,a.gh),Nj.push(a);else for(var b=0;b<Nj.length;++b)Nj[b].target==a.target&&Nj[b].mg==a.mg&&Oj(b--);return 0}function S(a){switch(a){case 1:return 0;case 2:return li;default:return a}}function bk(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
function ck(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var Mj={},Zj,dk,ek,fk,gk,hk,ik,jk,kk,lk,mk,nk,ok,pk={},qk=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],T=a=>{a=2<a?a?z(t,a):"":a;return qk[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},rk=(a,b,c)=>{a=T(a);if(!a||a.di)return-4;u[b>>2]=a.width;u[c>>2]=a.height;return 0};function sk(a,b,c){return m?E(32,0,1,a,b,c):rk(a,b,c)}
var tk=a=>{var b=Ph(a)+1,c=ai(b);B(a,t,c,b);return c},uk=a=>{var b=$h(),c=ai(8),d=c+4;a=tk(a.id);T(a)?rk(a,c,d):sk(a,c,d);c=[u[c>>2],u[d>>2]];ci(b);return c},vk=(a,b,c)=>{a=T(a);if(!a||a.di)return-4;var d=!1;a.ph?.fh&&(d=a.ph.fh.getParameter(2978),d=0===d[0]&&0===d[1]&&d[2]===a.width&&d[3]===a.height);a.width=b;a.height=c;d&&a.ph.fh.viewport(0,0,b,c);return 0};function wk(a,b,c){return m?E(33,0,1,a,b,c):vk(a,b,c)}
var jh=(a,b,c)=>T(a)?vk(a,b,c):wk(a,b,c),xk=(a,b,c)=>{if(a.di){var d=$h();a=tk(a.id);jh(a,b,c);ci(d)}else a.width=b,a.height=c},yk=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),xk(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=q,a.style.paddingRight=
y,a.style.paddingTop=H,a.style.paddingBottom=Z,a.style.marginLeft=O,a.style.marginRight=sc,a.style.marginTop=tc,a.style.marginBottom=tl,document.body.style.margin=ul,document.documentElement.style.overflow=vl,document.body.scroll=wl,a.style.rh=xl,a.ph&&a.ph.fh.viewport(0,0,d,e),pk.wh&&(pk.Gh?U(pk.Gh,pk.wh,37,0,pk.Hh):V(pk.wh,37,0,pk.Hh)))}var c=uk(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,q=a.style.paddingLeft,y=a.style.paddingRight,
H=a.style.paddingTop,Z=a.style.paddingBottom,O=a.style.marginLeft,sc=a.style.marginRight,tc=a.style.marginTop,tl=a.style.marginBottom,ul=document.body.style.margin,vl=document.documentElement.style.overflow,wl=document.body.scroll,xl=a.style.rh;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},zk=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Ak=a=>0>qk.indexOf(a)?a.getBoundingClientRect():
{left:0,top:0},Bk=(a,b)=>{if(0!=b.Wh||0!=b.Oh){yk(a);var c=b.xi?innerWidth:screen.width,d=b.xi?innerHeight:screen.height,e=Ak(a),f=e.width;e=e.height;var g=uk(a),l=g[0];g=g[1];3==b.Wh?(zk(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Wh&&(c*g<l*d?(f=g*c/l,zk(a,(d-f)/2,0),d=f):(f=l*d/g,zk(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.ti&&(a.style.rh=
"optimizeSpeed",a.style.rh="-moz-crisp-edges",a.style.rh="-o-crisp-edges",a.style.rh="-webkit-optimize-contrast",a.style.rh="optimize-contrast",a.style.rh="crisp-edges",a.style.rh="pixelated");f=2==b.Oh?devicePixelRatio:1;0!=b.Oh&&(c=c*f|0,d=d*f|0,xk(a,c,d),a.ph&&a.ph.fh.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return ck()?-3:-1;pk=b;b.wh&&(b.Gh?U(b.Gh,b.wh,37,0,b.Hh):V(b.wh,37,0,
b.Hh));return 0};function $b(){if(m)return E(31,0,1);if(!ck())return-1;Xj(Bk);var a=qk[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0}var Ck=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0};function ac(){if(m)return E(34,0,1);Xj(Ck);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0}
var bc=()=>{D+=1;throw"unwind";};function cc(a){if(m)return E(35,0,1,a);Ab();Jh(a)}function dc(){return m?E(36,0,1):"number"==typeof devicePixelRatio&&devicePixelRatio||1}function ec(a,b,c){if(m)return E(37,0,1,a,b,c);a=T(a);if(!a)return-4;a=Ak(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0}
var Dk=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)r[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];r[a+1104]=b.connected;u[a+1108>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;B(b.id,t,a+1112,64);B(b.mapping,t,a+1176,64)};
function fc(a,b){if(m)return E(38,0,1,a,b);if(0>a||a>=dk.length)return-5;if(!dk[a])return-7;Dk(b,dk[a]);return 0}function hc(){return m?E(39,0,1):dk.length}function ic(a,b){if(m)return E(40,0,1,a,b);u[a>>2]=screen.width;u[b>>2]=screen.height}
var jc=a=>P.activeTexture(a),kc=(a,b)=>{P.attachShader(J[a],K[b])},lc=(a,b)=>{P.beginQuery(a,M[b])},mc=(a,b)=>{P.ih.beginQueryEXT(a,M[b])},nc=a=>P.beginTransformFeedback(a),oc=(a,b,c)=>{P.bindAttribLocation(J[a],b,c?z(t,c):"")},pc=(a,b)=>{34962==a?P.xh=b:34963==a&&(P.Ch=b);35051==a?P.Qh=b:35052==a&&(P.nh=b);P.bindBuffer(a,qj[b])},qc=(a,b,c)=>{P.bindBufferBase(a,b,qj[c])},rc=(a,b,c,d,e)=>{P.bindBufferRange(a,b,qj[c],d,e)},uc=(a,b)=>{P.bindFramebuffer(a,sj[b])},vc=(a,b)=>{P.bindRenderbuffer(a,tj[b])},
wc=(a,b)=>{P.bindSampler(a,N[b])},xc=(a,b)=>{P.bindTexture(a,uj[b])},yc=(a,b)=>{P.bindTransformFeedback(a,wj[b])},zc=a=>{P.bindVertexArray(vj[a]);a=P.getParameter(34965);P.Ch=a?a.name|0:0},Ac=(a,b,c,d)=>P.blendColor(a,b,c,d),Bc=a=>P.blendEquation(a),Cc=(a,b)=>P.blendEquationSeparate(a,b),Dc=(a,b)=>P.blendFunc(a,b),Ec=(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),Fc=(a,b,c,d,e,f,g,l,n,q)=>P.blitFramebuffer(a,b,c,d,e,f,g,l,n,q),Gc=(a,b,c,d)=>{2<=F.version?c&&b?P.bufferData(a,t,d,c,b):P.bufferData(a,b,d):
P.bufferData(a,c?t.subarray(c,c+b):b,d)},Hc=(a,b,c,d)=>{2<=F.version?c&&P.bufferSubData(a,b,t,d,c):P.bufferSubData(a,b,t.subarray(d,d+c))},Ic=a=>P.checkFramebufferStatus(a),Jc=a=>P.clear(a),Kc=(a,b,c,d)=>P.clearBufferfi(a,b,c,d),Lc=(a,b,c)=>{P.clearBufferfv(a,b,w,c>>2)},Mc=(a,b,c)=>{P.clearBufferiv(a,b,u,c>>2)},Nc=(a,b,c)=>{P.clearBufferuiv(a,b,v,c>>2)},Oc=(a,b,c,d)=>P.clearColor(a,b,c,d),Pc=a=>P.clearDepth(a),Qc=a=>P.clearStencil(a),Rc=(a,b,c,d)=>P.clientWaitSync(xj[a],b,(c>>>0)+4294967296*d),Sc=
(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},Tc=a=>{P.compileShader(K[a])},Uc=(a,b,c,d,e,f,g,l)=>{2<=F.version?P.nh||!g?P.compressedTexImage2D(a,b,c,d,e,f,g,l):P.compressedTexImage2D(a,b,c,d,e,f,t,l,g):P.compressedTexImage2D(a,b,c,d,e,f,l?t.subarray(l,l+g):null)},Vc=(a,b,c,d,e,f,g,l,n)=>{P.nh?P.compressedTexImage3D(a,b,c,d,e,f,g,l,n):P.compressedTexImage3D(a,b,c,d,e,f,g,t,n,l)},Wc=(a,b,c,d,e,f,g,l,n)=>{2<=F.version?P.nh||!l?P.compressedTexSubImage2D(a,b,c,d,e,f,g,l,n):P.compressedTexSubImage2D(a,b,c,
d,e,f,g,t,n,l):P.compressedTexSubImage2D(a,b,c,d,e,f,g,n?t.subarray(n,n+l):null)},Xc=(a,b,c,d,e,f,g,l,n,q,y)=>{P.nh?P.compressedTexSubImage3D(a,b,c,d,e,f,g,l,n,q,y):P.compressedTexSubImage3D(a,b,c,d,e,f,g,l,n,t,y,q)},Yc=(a,b,c,d,e)=>P.copyBufferSubData(a,b,c,d,e),Zc=(a,b,c,d,e,f,g,l)=>P.copyTexImage2D(a,b,c,d,e,f,g,l),$c=(a,b,c,d,e,f,g,l)=>P.copyTexSubImage2D(a,b,c,d,e,f,g,l),ad=(a,b,c,d,e,f,g,l,n)=>P.copyTexSubImage3D(a,b,c,d,e,f,g,l,n),bd=()=>{var a=Dj(J),b=P.createProgram();b.name=a;b.Lh=b.Jh=
b.Kh=0;b.Yh=1;J[a]=b;return a},cd=a=>{var b=Dj(K);K[b]=P.createShader(a);return b},dd=a=>P.cullFace(a),ed=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=qj[d];e&&(P.deleteBuffer(e),e.name=0,qj[d]=null,d==P.xh&&(P.xh=0),d==P.Ch&&(P.Ch=0),d==P.Qh&&(P.Qh=0),d==P.nh&&(P.nh=0))}},fd=(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=sj[d];e&&(P.deleteFramebuffer(e),e.name=0,sj[d]=null)}},gd=a=>{if(a){var b=J[a];b?(P.deleteProgram(b),b.name=0,J[a]=null):Q||=1281}},hd=(a,b)=>{for(var c=0;c<a;c++){var d=
u[b+4*c>>2],e=M[d];e&&(P.deleteQuery(e),M[d]=null)}},jd=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=M[d];e&&(P.ih.deleteQueryEXT(e),M[d]=null)}},kd=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=tj[d];e&&(P.deleteRenderbuffer(e),e.name=0,tj[d]=null)}},ld=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=N[d];e&&(P.deleteSampler(e),e.name=0,N[d]=null)}},md=a=>{if(a){var b=K[a];b?(P.deleteShader(b),K[a]=null):Q||=1281}},nd=a=>{if(a){var b=xj[a];b?(P.deleteSync(b),b.name=0,xj[a]=null):Q||=1281}},
od=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=uj[d];e&&(P.deleteTexture(e),e.name=0,uj[d]=null)}},pd=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=wj[d];e&&(P.deleteTransformFeedback(e),e.name=0,wj[d]=null)}},qd=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];P.deleteVertexArray(vj[d]);vj[d]=null}},rd=a=>P.depthFunc(a),sd=a=>{P.depthMask(!!a)},td=(a,b)=>P.depthRange(a,b),ud=(a,b)=>{P.detachShader(J[a],K[b])},vd=a=>P.disable(a),wd=a=>{F.qh[a].enabled=!1;P.disableVertexAttribArray(a)},xd=(a,
b,c)=>{Gj(b+c);P.drawArrays(a,b,c);Fj&&P.bindBuffer(34962,qj[P.xh])},yd=(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},Ek=[],zd=(a,b)=>{for(var c=Ek[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];P.drawBuffers(c)},Ad=(a,b,c,d)=>{if(!P.Ch){var e=1*yj[c-5120]*b;var f=32-Math.clz32(0===e?0:e-1);var g=F.zh[f];g?f=g:(g=P.getParameter(34965),F.zh[f]=P.createBuffer(),P.bindBuffer(34963,F.zh[f]),P.bufferData(34963,1<<f,35048),P.bindBuffer(34963,g),f=F.zh[f]);P.bindBuffer(34963,f);P.bufferSubData(34963,0,t.subarray(d,d+e));
d=0}Gj(b);P.drawElements(a,b,c,d);Fj&&P.bindBuffer(34962,qj[P.xh]);P.Ch||P.bindBuffer(34963,null)},Bd=(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},Cd=(a,b,c,d,e,f)=>{Ad(a,d,e,f)},Dd=a=>P.enable(a),Ed=a=>{F.qh[a].enabled=!0;P.enableVertexAttribArray(a)},Fd=a=>P.endQuery(a),Gd=a=>{P.ih.endQueryEXT(a)},Hd=()=>P.endTransformFeedback(),Id=(a,b)=>(a=P.fenceSync(a,b))?(b=Dj(xj),a.name=b,xj[b]=a,b):0,Jd=()=>P.finish(),Kd=()=>P.flush(),Fk=a=>{switch(a){case 34962:a=34964;break;case 34963:a=34965;break;
case 35051:a=35053;break;case 35052:a=35055;break;case 35982:a=35983;break;case 36662:a=36662;break;case 36663:a=36663;break;case 35345:a=35368}return(a=P.getParameter(a))?a.name|0:0},Gk=a=>{switch(a){case 34962:case 34963:case 36662:case 36663:case 35051:case 35052:case 35882:case 35982:case 35345:return!0;default:return!1}},Ld=(a,b,c)=>{if(Gk(a)){var d=rj[Fk(a)];d?d.$h&16?0>b||0>c||b+c>d.length?(Q||=1281,p("invalid range in glFlushMappedBufferRange")):P.bufferSubData(a,d.offset,t.subarray(d.oh+
b,d.oh+b+c)):(Q||=1282,p("buffer was not mapped with GL_MAP_FLUSH_EXPLICIT_BIT in glFlushMappedBufferRange")):(Q||=1282,p("buffer was never mapped in glFlushMappedBufferRange"))}else Q||=1280,p("GL_INVALID_ENUM in glFlushMappedBufferRange")},Md=(a,b,c,d)=>{P.framebufferRenderbuffer(a,b,c,tj[d])},Nd=(a,b,c,d,e)=>{P.framebufferTexture2D(a,b,c,uj[d],e)},Od=(a,b,c,d,e)=>{P.framebufferTextureLayer(a,b,uj[c],d,e)},Pd=a=>P.frontFace(a),Qd=(a,b)=>{Ej(a,b,"createBuffer",qj)},Rd=(a,b)=>{Ej(a,b,"createFramebuffer",
sj)},Sd=(a,b)=>{Ej(a,b,"createQuery",M)},Td=(a,b)=>{for(var c=0;c<a;c++){var d=P.ih.createQueryEXT();if(!d){for(Q||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=Dj(M);d.name=e;M[e]=d;u[b+4*c>>2]=e}},Ud=(a,b)=>{Ej(a,b,"createRenderbuffer",tj)},Vd=(a,b)=>{Ej(a,b,"createSampler",N)},Wd=(a,b)=>{Ej(a,b,"createTexture",uj)},Xd=(a,b)=>{Ej(a,b,"createTransformFeedback",wj)},Yd=(a,b)=>{Ej(a,b,"createVertexArray",vj)},Zd=a=>P.generateMipmap(a),Hk=(a,b,c,d,e,f,g,l)=>{b=J[b];if(a=P[a](b,c))d=l&&B(a.name,t,l,d),e&&(u[e>>
2]=d),f&&(u[f>>2]=a.size),g&&(u[g>>2]=a.type)},$d=(a,b,c,d,e,f,g)=>{Hk("getActiveAttrib",a,b,c,d,e,f,g)},ae=(a,b,c,d,e,f,g)=>{Hk("getActiveUniform",a,b,c,d,e,f,g)},be=(a,b,c,d,e)=>{a=J[a];if(a=P.getActiveUniformBlockName(a,b))e&&0<c?(c=B(a,t,e,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0)},ce=(a,b,c,d)=>{if(d)if(a=J[a],35393==c)u[d>>2]=P.getActiveUniformBlockName(a,b).length+1;else{if(a=P.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)u[d+4*c>>2]=a[c];else u[d>>2]=a}else Q||=
1281},de=(a,b,c,d,e)=>{if(e)if(0<b&&0==c)Q||=1281;else{a=J[a];for(var f=[],g=0;g<b;g++)f.push(u[c+4*g>>2]);if(a=P.getActiveUniforms(a,f,d))for(b=a.length,g=0;g<b;g++)u[e+4*g>>2]=a[g]}else Q||=1281},ee=(a,b,c,d)=>{a=P.getAttachedShaders(J[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=K.indexOf(a[b])},fe=(a,b)=>P.getAttribLocation(J[a],b?z(t,b):""),Ik=(a,b)=>{v[a>>2]=b;v[a+4>>2]=(b-v[a>>2])/4294967296};function Jk(){var a=oj(P);return a=a.concat(a.map(b=>"GL_"+b))}
var Kk=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(Q||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=P.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>F.version){Q||=1282;return}d=Jk().length;break;case 33307:case 33308:if(2>F.version){Q||=1280;return}d=33307==a?3:0}if(void 0===d)switch(e=P.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Q||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=
0;break;default:Q||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:r[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){Q||=1280;p(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:Q||=1280;p(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:Ik(b,d);break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:r[b]=d?1:0}}else Q||=1281},ge=(a,b)=>Kk(a,b,4),he=(a,b,c)=>{c?Ik(c,P.getBufferParameter(a,b)):Q||=1281},ie=(a,b,c)=>{c?u[c>>2]=P.getBufferParameter(a,b):Q||=1281},je=(a,b,c)=>{if(35005==b){b=0;if(a=rj[Fk(a)])b=a.oh;u[c>>2]=b}else Q||=1280,p("GL_INVALID_ENUM in glGetBufferPointerv")},ke=()=>{var a=P.getError()||Q;Q=0;return a},le=(a,b)=>Kk(a,b,2),me=(a,b)=>P.getFragDataLocation(J[a],b?z(t,b):""),ne=(a,b,c,d)=>
{a=P.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Lk=(a,b,c,d)=>{if(c){b=P.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:Q||=1280;return}else if(b instanceof WebGLBuffer)a=b.name|0;else{Q||=1280;return}break;default:Q||=1280;return}switch(d){case 1:Ik(c,a);break;case 0:u[c>>2]=a;break;case 2:w[c>>
2]=a;break;case 4:r[c]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else Q||=1281},oe=(a,b,c)=>Lk(a,b,c,1),pe=(a,b)=>{Kk(a,b,1)},qe=(a,b,c)=>Lk(a,b,c,0),re=(a,b)=>Kk(a,b,0),se=(a,b,c,d,e)=>{if(0>d)Q||=1281;else if(e){if(a=P.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)u[e+4*b>>2]=a[b]}else Q||=1281},te=()=>{Q||=1282},ue=(a,b,c,d)=>{a=P.getProgramInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,t,d,b):0;c&&(u[c>>2]=b)},ve=
(a,b,c)=>{if(c)if(a>=pj)Q||=1281;else if(a=J[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.Lh)for(b=0;b<P.getProgramParameter(a,35718);++b)a.Lh=Math.max(a.Lh,P.getActiveUniform(a,b).name.length+1);u[c>>2]=a.Lh}else if(35722==b){if(!a.Jh)for(b=0;b<P.getProgramParameter(a,35721);++b)a.Jh=Math.max(a.Jh,P.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Jh}else if(35381==b){if(!a.Kh)for(b=0;b<P.getProgramParameter(a,35382);++b)a.Kh=Math.max(a.Kh,
P.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Kh}else u[c>>2]=P.getProgramParameter(a,b);else Q||=1281},we=(a,b,c)=>{if(c){a=M[a];b=2>F.version?P.ih.getQueryObjectEXT(a,b):P.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Ik(c,d)}else Q||=1281},xe=(a,b,c)=>{if(c){a=P.ih.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else Q||=1281},ye=(a,b,c)=>{if(c){a=P.getQueryParameter(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else Q||=1281},ze=(a,b,c)=>
{c?u[c>>2]=P.getQuery(a,b):Q||=1281},Ae=(a,b,c)=>{c?u[c>>2]=P.ih.getQueryEXT(a,b):Q||=1281},Be=(a,b,c)=>{c?u[c>>2]=P.getRenderbufferParameter(a,b):Q||=1281},Ce=(a,b,c)=>{c?w[c>>2]=P.getSamplerParameter(N[a],b):Q||=1281},De=(a,b,c)=>{c?u[c>>2]=P.getSamplerParameter(N[a],b):Q||=1281},Ee=(a,b,c,d)=>{a=P.getShaderInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,t,d,b):0;c&&(u[c>>2]=b)},Fe=(a,b,c,d)=>{a=P.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},
Ge=(a,b,c,d)=>{if(a=P.getShaderSource(K[a]))b=0<b&&d?B(a,t,d,b):0,c&&(u[c>>2]=b)},He=(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(K[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(K[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=P.getShaderParameter(K[a],b):Q||=1281},Ie=a=>{var b=zj[a];if(!b){switch(a){case 7939:b=Qj(Jk().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=P.getParameter(a))||(Q||=1280);b=b?Qj(b):0;break;case 7938:b=P.getParameter(7938);b=2<=
F.version?`OpenGL ES 3.0 (${b})`:`OpenGL ES 2.0 (${b})`;b=Qj(b);break;case 35724:b=P.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Qj(b);break;default:Q||=1280}zj[a]=b}return b},Je=(a,b)=>{if(2>F.version)return Q||=1282,0;var c=Aj[a];if(c)return 0>b||b>=c.length?(Q||=1281,0):c[b];switch(a){case 7939:return c=Jk().map(Qj),c=Aj[a]=c,0>b||b>=c.length?(Q||=1281,0):c[b];default:return Q||=
1280,0}},Ke=(a,b,c,d,e)=>{0>c?Q||=1281:e?(a=P.getSyncParameter(xj[a],b),null!==a&&(u[e>>2]=a,d&&(u[d>>2]=1))):Q||=1281},Le=(a,b,c)=>{c?w[c>>2]=P.getTexParameter(a,b):Q||=1281},Me=(a,b,c)=>{c?u[c>>2]=P.getTexParameter(a,b):Q||=1281},Ne=(a,b,c,d,e,f,g)=>{a=J[a];if(a=P.getTransformFeedbackVarying(a,b))g&&0<c?(c=B(a.name,t,g,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0),e&&(u[e>>2]=a.size),f&&(u[f>>2]=a.type)},Oe=(a,b)=>P.getUniformBlockIndex(J[a],b?z(t,b):""),Pe=(a,b,c,d)=>{if(d)if(0<b&&(0==c||0==d))Q||=1281;else{a=
J[a];for(var e=[],f=0;f<b;f++)e.push(qi(u[c+4*f>>2]));if(a=P.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)u[d+4*f>>2]=a[f]}else Q||=1281},Mk=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Nk=a=>{var b=a.Eh,c=a.ki,d;if(!b)for(a.Eh=b={},a.ji={},d=0;d<P.getProgramParameter(a,35718);++d){var e=P.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Mk(f);g=0<g?f.slice(0,g):f;var l=a.Yh;a.Yh+=e;c[g]=[e,l];for(f=0;f<e;++f)b[l]=f,a.ji[l++]=g}},Qe=(a,b)=>{b=b?z(t,b):"";if(a=J[a]){Nk(a);var c=a.Eh,d=0,e=b,f=Mk(b);
0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.ki[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else Q||=1281;return-1},W=a=>{var b=P.mi;if(b){var c=b.Eh[a];"number"==typeof c&&(b.Eh[a]=c=P.getUniformLocation(b,b.ji[a]+(0<c?`[${c}]`:"")));return c}Q||=1282},Ok=(a,b,c,d)=>{if(c)if(a=J[a],Nk(a),a=P.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];
break;case 2:w[c+4*b>>2]=a[b]}else Q||=1281},Re=(a,b,c)=>{Ok(a,b,c,2)},Se=(a,b,c)=>{Ok(a,b,c,0)},Te=(a,b,c)=>Ok(a,b,c,0),Pk=(a,b,c,d)=>{if(c)if(F.qh[a].enabled&&p("glGetVertexAttrib*v on client-side array: not supported, bad data returned"),a=P.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+
4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else Q||=1281},Ue=(a,b,c)=>{Pk(a,b,c,0)},Ve=(a,b,c)=>{c?(F.qh[a].enabled&&p("glGetVertexAttribPointer on client-side array: not supported, bad data returned"),u[c>>2]=P.getVertexAttribOffset(a,b)):Q||=1281},We=(a,b,c)=>{Pk(a,b,c,2)},Xe=(a,b,c)=>{Pk(a,b,c,5)},Ye=(a,b)=>P.hint(a,b),Ze=(a,b,c)=>{for(var d=Ek[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];P.invalidateFramebuffer(a,d)},$e=(a,b,c,d,e,f,g)=>{for(var l=Ek[b],n=0;n<b;n++)l[n]=u[c+4*n>>2];P.invalidateSubFramebuffer(a,
l,d,e,f,g)},af=a=>(a=qj[a])?P.isBuffer(a):0,bf=a=>P.isEnabled(a),cf=a=>(a=sj[a])?P.isFramebuffer(a):0,df=a=>(a=J[a])?P.isProgram(a):0,ef=a=>(a=M[a])?P.isQuery(a):0,ff=a=>(a=M[a])?P.ih.isQueryEXT(a):0,gf=a=>(a=tj[a])?P.isRenderbuffer(a):0,hf=a=>(a=N[a])?P.isSampler(a):0,jf=a=>(a=K[a])?P.isShader(a):0,kf=a=>P.isSync(xj[a]),lf=a=>(a=uj[a])?P.isTexture(a):0,mf=a=>P.isTransformFeedback(wj[a]),nf=a=>(a=vj[a])?P.isVertexArray(a):0,of=a=>P.lineWidth(a),pf=a=>{a=J[a];P.linkProgram(a);a.Eh=0;a.ki={}},qf=(a,
b,c,d)=>{if(0!=(d&33))return p("glMapBufferRange access does not support MAP_READ or MAP_UNSYNCHRONIZED"),0;if(0==(d&2))return p("glMapBufferRange access must include MAP_WRITE"),0;if(0==(d&12))return p("glMapBufferRange access must include INVALIDATE_BUFFER or INVALIDATE_RANGE"),0;if(!Gk(a))return Q||=1280,p("GL_INVALID_ENUM in glMapBufferRange"),0;var e=A(c);a=Fk(a);if(!e)return 0;rj[a]||(rj[a]={});a=rj[a];a.offset=b;a.length=c;a.oh=e;a.$h=d;return e},rf=()=>P.pauseTransformFeedback(),sf=(a,b)=>
{3317==a?Bj=b:3314==a&&(Cj=b);P.pixelStorei(a,b)},tf=(a,b)=>P.polygonOffset(a,b),uf=()=>{Q||=1280},vf=()=>{Q||=1280},wf=(a,b)=>{P.ih.queryCounterEXT(M[a],b)},xf=a=>P.readBuffer(a),Qk=a=>{a-=5120;return 0==a?r:1==a?t:2==a?Na:4==a?u:6==a?w:5==a||28922==a||28520==a||30779==a||30782==a?v:Oa},Rk=(a,b,c,d,e)=>{a=Qk(a);b=d*((Cj||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Bj-1&-Bj);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},
yf=(a,b,c,d,e,f,g)=>{if(2<=F.version)if(P.Qh)P.readPixels(a,b,c,d,e,f,g);else{var l=Qk(f);g>>>=31-Math.clz32(l.BYTES_PER_ELEMENT);P.readPixels(a,b,c,d,e,f,l,g)}else(l=Rk(f,e,c,d,g))?P.readPixels(a,b,c,d,e,f,l):Q||=1280},zf=()=>{},Af=(a,b,c,d)=>P.renderbufferStorage(a,b,c,d),Bf=(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),Cf=()=>P.resumeTransformFeedback(),Df=(a,b)=>{P.sampleCoverage(a,!!b)},Ef=(a,b,c)=>{P.samplerParameterf(N[a],b,c)},Ff=(a,b,c)=>{P.samplerParameterf(N[a],b,w[c>>2])},Gf=
(a,b,c)=>{P.samplerParameteri(N[a],b,c)},Hf=(a,b,c)=>{P.samplerParameteri(N[a],b,u[c>>2])},If=(a,b,c,d)=>P.scissor(a,b,c,d),Jf=()=>{Q||=1280},Kf=(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=qi(v[c+4*f>>2],d?v[d+4*f>>2]:void 0);P.shaderSource(K[a],e)},Lf=(a,b,c)=>P.stencilFunc(a,b,c),Mf=(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),Nf=a=>P.stencilMask(a),Of=(a,b)=>P.stencilMaskSeparate(a,b),Pf=(a,b,c)=>P.stencilOp(a,b,c),Qf=(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),Rf=(a,b,c,d,e,f,g,l,n)=>{if(2<=F.version){if(P.nh){P.texImage2D(a,
b,c,d,e,f,g,l,n);return}if(n){var q=Qk(l);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,f,g,l,q,n);return}}q=n?Rk(l,g,d,e,n):null;P.texImage2D(a,b,c,d,e,f,g,l,q)},Sf=(a,b,c,d,e,f,g,l,n,q)=>{if(P.nh)P.texImage3D(a,b,c,d,e,f,g,l,n,q);else if(q){var y=Qk(n);P.texImage3D(a,b,c,d,e,f,g,l,n,y,q>>>31-Math.clz32(y.BYTES_PER_ELEMENT))}else P.texImage3D(a,b,c,d,e,f,g,l,n,null)},Tf=(a,b,c)=>P.texParameterf(a,b,c),Uf=(a,b,c)=>{P.texParameterf(a,b,w[c>>2])},Vf=(a,b,c)=>P.texParameteri(a,b,c),
Wf=(a,b,c)=>{P.texParameteri(a,b,u[c>>2])},Xf=(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),Yf=(a,b,c,d,e,f)=>P.texStorage3D(a,b,c,d,e,f),Zf=(a,b,c,d,e,f,g,l,n)=>{if(2<=F.version){if(P.nh){P.texSubImage2D(a,b,c,d,e,f,g,l,n);return}if(n){var q=Qk(l);P.texSubImage2D(a,b,c,d,e,f,g,l,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}n=n?Rk(l,g,e,f,n):null;P.texSubImage2D(a,b,c,d,e,f,g,l,n)},$f=(a,b,c,d,e,f,g,l,n,q,y)=>{if(P.nh)P.texSubImage3D(a,b,c,d,e,f,g,l,n,q,y);else if(y){var H=Qk(q);P.texSubImage3D(a,b,
c,d,e,f,g,l,n,q,H,y>>>31-Math.clz32(H.BYTES_PER_ELEMENT))}else P.texSubImage3D(a,b,c,d,e,f,g,l,n,q,null)},ag=(a,b,c,d)=>{a=J[a];for(var e=[],f=0;f<b;f++)e.push(qi(u[c+4*f>>2]));P.transformFeedbackVaryings(a,e,d)},bg=(a,b)=>{P.uniform1f(W(a),b)},Sk=[],cg=(a,b,c)=>{if(2<=F.version)b&&P.uniform1fv(W(a),w,c>>2,b);else{if(288>=b)for(var d=Sk[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);P.uniform1fv(W(a),d)}},dg=(a,b)=>{P.uniform1i(W(a),b)},Tk=[],eg=(a,b,c)=>{if(2<=F.version)b&&P.uniform1iv(W(a),
u,c>>2,b);else{if(288>=b)for(var d=Tk[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);P.uniform1iv(W(a),d)}},fg=(a,b)=>{P.uniform1ui(W(a),b)},gg=(a,b,c)=>{b&&P.uniform1uiv(W(a),v,c>>2,b)},hg=(a,b,c)=>{P.uniform2f(W(a),b,c)},ig=(a,b,c)=>{if(2<=F.version)b&&P.uniform2fv(W(a),w,c>>2,2*b);else{if(144>=b)for(var d=Sk[2*b],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);P.uniform2fv(W(a),d)}},jg=(a,b,c)=>{P.uniform2i(W(a),b,c)},kg=(a,b,c)=>{if(2<=
F.version)b&&P.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b)for(var d=Tk[2*b],e=0;e<2*b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2];else d=u.subarray(c>>2,c+8*b>>2);P.uniform2iv(W(a),d)}},lg=(a,b,c)=>{P.uniform2ui(W(a),b,c)},mg=(a,b,c)=>{b&&P.uniform2uiv(W(a),v,c>>2,2*b)},ng=(a,b,c,d)=>{P.uniform3f(W(a),b,c,d)},og=(a,b,c)=>{if(2<=F.version)b&&P.uniform3fv(W(a),w,c>>2,3*b);else{if(96>=b)for(var d=Sk[3*b],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>
2,c+12*b>>2);P.uniform3fv(W(a),d)}},pg=(a,b,c,d)=>{P.uniform3i(W(a),b,c,d)},qg=(a,b,c)=>{if(2<=F.version)b&&P.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b)for(var d=Tk[3*b],e=0;e<3*b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2];else d=u.subarray(c>>2,c+12*b>>2);P.uniform3iv(W(a),d)}},rg=(a,b,c,d)=>{P.uniform3ui(W(a),b,c,d)},sg=(a,b,c)=>{b&&P.uniform3uiv(W(a),v,c>>2,3*b)},tg=(a,b,c,d,e)=>{P.uniform4f(W(a),b,c,d,e)},ug=(a,b,c)=>{if(2<=F.version)b&&P.uniform4fv(W(a),w,c>>2,4*b);else{if(72>=
b){var d=Sk[4*b],e=w;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);P.uniform4fv(W(a),d)}},vg=(a,b,c,d,e)=>{P.uniform4i(W(a),b,c,d,e)},wg=(a,b,c)=>{if(2<=F.version)b&&P.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b)for(var d=Tk[4*b],e=0;e<4*b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2];else d=u.subarray(c>>2,c+16*b>>2);P.uniform4iv(W(a),d)}},xg=(a,b,c,d,e)=>{P.uniform4ui(W(a),
b,c,d,e)},yg=(a,b,c)=>{b&&P.uniform4uiv(W(a),v,c>>2,4*b)},zg=(a,b,c)=>{a=J[a];P.uniformBlockBinding(a,b,c)},Ag=(a,b,c,d)=>{if(2<=F.version)b&&P.uniformMatrix2fv(W(a),!!c,w,d>>2,4*b);else{if(72>=b)for(var e=Sk[4*b],f=0;f<4*b;f+=4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2];else e=w.subarray(d>>2,d+16*b>>2);P.uniformMatrix2fv(W(a),!!c,e)}},Bg=(a,b,c,d)=>{b&&P.uniformMatrix2x3fv(W(a),!!c,w,d>>2,6*b)},Cg=(a,b,c,d)=>{b&&P.uniformMatrix2x4fv(W(a),!!c,w,d>>2,8*
b)},Dg=(a,b,c,d)=>{if(2<=F.version)b&&P.uniformMatrix3fv(W(a),!!c,w,d>>2,9*b);else{if(32>=b)for(var e=Sk[9*b],f=0;f<9*b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2];else e=w.subarray(d>>2,d+36*b>>2);P.uniformMatrix3fv(W(a),!!c,e)}},Eg=(a,b,c,d)=>{b&&P.uniformMatrix3x2fv(W(a),!!c,w,d>>2,6*b)},Fg=(a,b,c,d)=>{b&&P.uniformMatrix3x4fv(W(a),
!!c,w,d>>2,12*b)},Gg=(a,b,c,d)=>{if(2<=F.version)b&&P.uniformMatrix4fv(W(a),!!c,w,d>>2,16*b);else{if(18>=b){var e=Sk[16*b],f=w;d>>=2;for(var g=0;g<16*b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(W(a),!!c,e)}},Hg=(a,b,c,d)=>{b&&P.uniformMatrix4x2fv(W(a),
!!c,w,d>>2,8*b)},Ig=(a,b,c,d)=>{b&&P.uniformMatrix4x3fv(W(a),!!c,w,d>>2,12*b)},Jg=a=>{if(!Gk(a))return Q||=1280,p("GL_INVALID_ENUM in glUnmapBuffer"),0;var b=rj[Fk(a)];if(!b||!b.oh)return Q||=1282,p("buffer was never mapped in glUnmapBuffer"),0;b.$h&16||(2<=F.version?P.bufferSubData(a,b.offset,t,b.oh,b.length):P.bufferSubData(a,b.offset,t.subarray(b.oh,b.oh+b.length)));Pj(b.oh);b.oh=0;return 1},Kg=a=>{a=J[a];P.useProgram(a);P.mi=a},Lg=a=>{P.validateProgram(J[a])},Mg=(a,b)=>P.vertexAttrib1f(a,b),Ng=
(a,b)=>{P.vertexAttrib1f(a,w[b>>2])},Og=(a,b,c)=>P.vertexAttrib2f(a,b,c),Pg=(a,b)=>{P.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},Qg=(a,b,c,d)=>P.vertexAttrib3f(a,b,c,d),Rg=(a,b)=>{P.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},Sg=(a,b,c,d,e)=>P.vertexAttrib4f(a,b,c,d,e),Tg=(a,b)=>{P.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Ug=(a,b)=>{P.vertexAttribDivisor(a,b)},Vg=(a,b,c,d,e)=>P.vertexAttribI4i(a,b,c,d,e),Wg=(a,b)=>{P.vertexAttribI4i(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Xg=(a,b,
c,d,e)=>P.vertexAttribI4ui(a,b,c,d,e),Yg=(a,b)=>{P.vertexAttribI4ui(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},Zg=(a,b,c,d,e)=>{var f=F.qh[a];P.xh?(f.Bh=!1,P.vertexAttribIPointer(a,b,c,d,e)):(f.size=b,f.type=c,f.Vh=!1,f.Mh=d,f.th=e,f.Bh=!0,f.Zh=function(g,l,n,q,y,H){this.vertexAttribIPointer(g,l,n,y,H)})},$g=(a,b,c,d,e,f)=>{var g=F.qh[a];P.xh?(g.Bh=!1,P.vertexAttribPointer(a,b,c,!!d,e,f)):(g.size=b,g.type=c,g.Vh=d,g.Mh=e,g.th=f,g.Bh=!0,g.Zh=function(l,n,q,y,H,Z){this.vertexAttribPointer(l,n,q,y,H,
Z)})},ah=(a,b,c,d)=>P.viewport(a,b,c,d),bh=(a,b,c,d)=>{P.waitSync(xj[a],b,(c>>>0)+4294967296*d)},ch=()=>1,Uk=(a,b)=>{if(!ck())return-1;a=T(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Yj()?Bk(a,b):b.ri?(Wj(Bk,1,[a,b]),1):-2:-3:-4};function dh(a,b,c){return m?E(41,0,1,a,b,c):Uk(a,{Wh:u[c>>2],Oh:u[c+4>>2],ti:u[c+8>>2],ri:b,Gh:u[c+20>>2],wh:u[c+12>>2],Hh:u[c+16>>2]})}function eh(a,b){if(m)return E(42,0,1,a,b);a=T(a);return a?a.requestPointerLock?Yj()?Ck(a):b?(Wj(Ck,2,[a]),1):-2:-1:-4}
var fh=()=>{Za("OOM")};function gh(){if(m)return E(43,0,1);try{if(navigator.getGamepads)return(dk=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1}var Vk=(a,b)=>{var c={target:T(2),mg:"beforeunload",hh:b,jh:(d=event)=>{var e=V(b,28,0,a);e&&=e?z(t,e):"";if(e)return d.preventDefault(),d.returnValue=e},gh:!0};return R(c)};function hh(a,b,c){return m?E(44,0,1,a,b,c):"undefined"==typeof onbeforeunload?-1:1!==c?-5:Vk(a,b)}
var Wk=(a,b,c,d,e,f,g)=>{g=S(g);ek||=A(256);a={target:T(a),mg:f,hh:d,jh:(l=event)=>{var n=bk(l.target),q=l.target.id?l.target.id:"",y=g?A(256):ek;B(n,t,y+0,128);B(q,t,y+128,128);g?U(g,d,e,y,b):V(d,e,y,b)&&l.preventDefault()},gh:c};return R(a)};function ih(a,b,c,d,e){return m?E(45,0,1,a,b,c,d,e):Wk(a,b,c,d,12,"blur",e)}function kh(a,b,c){if(m)return E(46,0,1,a,b,c);a=T(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0}
function lh(a,b,c,d,e){return m?E(47,0,1,a,b,c,d,e):Wk(a,b,c,d,13,"focus",e)}
var Xk=(a,b,c,d,e,f)=>{f=S(f);gk||=A(276);return R({target:a,mg:e,hh:d,jh:(g=event)=>{var l=f?A(276):gk,n=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,q=!!n;r[l]=q;r[l+1]=ck();var y=q?n:fk,H=y?.id||"";B(bk(y),t,l+2,128);B(H,t,l+130,128);u[l+260>>2]=y?y.clientWidth:0;u[l+264>>2]=y?y.clientHeight:0;u[l+268>>2]=screen.width;u[l+272>>2]=screen.height;q&&(fk=n);f?U(f,d,19,l,b):V(d,19,l,b)&&g.preventDefault()},gh:c})};
function mh(a,b,c,d,e){if(m)return E(48,0,1,a,b,c,d,e);if(!ck())return-1;a=T(a);if(!a)return-4;Xk(a,b,c,d,"webkitfullscreenchange",e);return Xk(a,b,c,d,"fullscreenchange",e)}var Yk=(a,b,c,d,e,f)=>{f=S(f);hk||=A(1240);b={target:T(2),Fh:!0,mg:e,hh:c,jh:(g=event)=>{var l=f?A(1240):hk;Dk(l,g.gamepad);f?U(f,c,d,l,a):V(c,d,l,a)&&g.preventDefault()},gh:b};return R(b)};function nh(a,b,c,d){return m?E(49,0,1,a,b,c,d):gh()?-1:Yk(a,b,c,26,"gamepadconnected",d)}
function oh(a,b,c,d){return m?E(50,0,1,a,b,c,d):gh()?-1:Yk(a,b,c,27,"gamepaddisconnected",d)}
var Zk=(a,b,c,d,e,f,g)=>{g=S(g);ik||=A(160);a={target:T(a),mg:f,hh:d,jh:l=>{var n=g?A(160):ik;x[n>>3]=l.timeStamp;var q=n>>2;u[q+2]=l.location;r[n+12]=l.ctrlKey;r[n+13]=l.shiftKey;r[n+14]=l.altKey;r[n+15]=l.metaKey;r[n+16]=l.repeat;u[q+5]=l.charCode;u[q+6]=l.keyCode;u[q+7]=l.which;B(l.key||"",t,n+32,32);B(l.code||"",t,n+64,32);B(l.char||"",t,n+96,32);B(l.locale||"",t,n+128,32);g?U(g,d,e,n,b):V(d,e,n,b)&&l.preventDefault()},gh:c};return R(a)};
function ph(a,b,c,d,e){return m?E(51,0,1,a,b,c,d,e):Zk(a,b,c,d,2,"keydown",e)}function qh(a,b,c,d,e){return m?E(52,0,1,a,b,c,d,e):Zk(a,b,c,d,1,"keypress",e)}function rh(a,b,c,d,e){return m?E(53,0,1,a,b,c,d,e):Zk(a,b,c,d,3,"keyup",e)}
var $k=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;Na[2*d+14]=b.button;Na[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=Ak(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},al=(a,b,c,d,e,f,g)=>{g=S(g);jk||=A(64);a=T(a);return R({target:a,Fh:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,mg:f,hh:d,jh:(l=event)=>{$k(jk,l,a);if(g){var n=A(64);
$k(n,l,a);U(g,d,e,n,b)}else V(d,e,jk,b)&&l.preventDefault()},gh:c})};function sh(a,b,c,d,e){return m?E(54,0,1,a,b,c,d,e):al(a,b,c,d,5,"mousedown",e)}function th(a,b,c,d,e){return m?E(55,0,1,a,b,c,d,e):al(a,b,c,d,33,"mouseenter",e)}function uh(a,b,c,d,e){return m?E(56,0,1,a,b,c,d,e):al(a,b,c,d,34,"mouseleave",e)}function vh(a,b,c,d,e){return m?E(57,0,1,a,b,c,d,e):al(a,b,c,d,8,"mousemove",e)}function wh(a,b,c,d,e){return m?E(58,0,1,a,b,c,d,e):al(a,b,c,d,6,"mouseup",e)}
var bl=(a,b,c,d,e,f)=>{f=S(f);kk||=A(257);return R({target:a,mg:e,hh:d,jh:(g=event)=>{var l=f?A(257):kk,n=document.pointerLockElement||document.yh||document.Rh||document.Uh;r[l]=!!n;var q=n?.id||"";B(bk(n),t,l+1,128);B(q,t,l+129,128);f?U(f,d,20,l,b):V(d,20,l,b)&&g.preventDefault()},gh:c})};
function xh(a,b,c,d,e){if(m)return E(59,0,1,a,b,c,d,e);if(!document||!document.body||!(document.body.requestPointerLock||document.body.yh||document.body.Rh||document.body.Uh))return-1;a=T(a);if(!a)return-4;bl(a,b,c,d,"mozpointerlockchange",e);bl(a,b,c,d,"webkitpointerlockchange",e);bl(a,b,c,d,"mspointerlockchange",e);return bl(a,b,c,d,"pointerlockchange",e)}
var cl=(a,b,c,d,e)=>{e=S(e);lk||=A(36);a=T(a);return R({target:a,mg:"resize",hh:d,jh:(f=event)=>{if(f.target==a){var g=document.body;if(g){var l=e?A(36):lk;u[l>>2]=0;u[l+4>>2]=g.clientWidth;u[l+8>>2]=g.clientHeight;u[l+12>>2]=innerWidth;u[l+16>>2]=innerHeight;u[l+20>>2]=outerWidth;u[l+24>>2]=outerHeight;u[l+28>>2]=pageXOffset|0;u[l+32>>2]=pageYOffset|0;e?U(e,d,10,l,b):V(d,10,l,b)&&f.preventDefault()}}},gh:c})};function yh(a,b,c,d,e){return m?E(60,0,1,a,b,c,d,e):cl(a,b,c,d,e)}
var dl=(a,b,c,d,e,f,g)=>{g=S(g);mk||=A(1552);a=T(a);return R({target:a,Fh:"touchstart"==f||"touchend"==f,mg:f,hh:d,jh:l=>{var n={},q=l.touches;for(var y of q)y.fi=y.hi=0,n[y.identifier]=y;for(var H of l.changedTouches)H.fi=1,n[H.identifier]=H;for(var Z of l.targetTouches)n[Z.identifier].hi=1;q=g?A(1552):mk;x[q>>3]=l.timeStamp;r[q+12]=l.ctrlKey;r[q+13]=l.shiftKey;r[q+14]=l.altKey;r[q+15]=l.metaKey;y=q+16;H=Ak(a);Z=0;for(let O of Object.values(n))if(n=y>>2,u[n]=O.identifier,u[n+1]=O.screenX,u[n+2]=
O.screenY,u[n+3]=O.clientX,u[n+4]=O.clientY,u[n+5]=O.pageX,u[n+6]=O.pageY,r[y+28]=O.fi,r[y+29]=O.hi,u[n+8]=O.clientX-(H.left|0),u[n+9]=O.clientY-(H.top|0),y+=48,31<++Z)break;u[q+8>>2]=Z;g?U(g,d,e,q,b):V(d,e,q,b)&&l.preventDefault()},gh:c})};function zh(a,b,c,d,e){return m?E(61,0,1,a,b,c,d,e):dl(a,b,c,d,25,"touchcancel",e)}function Ah(a,b,c,d,e){return m?E(62,0,1,a,b,c,d,e):dl(a,b,c,d,23,"touchend",e)}function Bh(a,b,c,d,e){return m?E(63,0,1,a,b,c,d,e):dl(a,b,c,d,24,"touchmove",e)}
function Ch(a,b,c,d,e){return m?E(64,0,1,a,b,c,d,e):dl(a,b,c,d,22,"touchstart",e)}var el=(a,b,c,d)=>{var e=qk[1];d=S(d);nk||=A(8);return R({target:e,mg:"visibilitychange",hh:c,jh:(f=event)=>{var g=d?A(8):nk,l=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);r[g]=document.hidden;u[g+4>>2]=l;d?U(d,c,21,g,a):V(c,21,g,a)&&f.preventDefault()},gh:b})};function Dh(a,b,c,d){return m?E(65,0,1,a,b,c,d):qk[1]?el(a,b,c,d):-4}
var fl=(a,b,c,d,e)=>{e=S(e);ok||=A(96);return R({target:a,Fh:!0,mg:"wheel",hh:d,jh:(f=event)=>{var g=e?A(96):ok;$k(g,f,a);x[g+64>>3]=f.deltaX;x[g+72>>3]=f.deltaY;x[g+80>>3]=f.deltaZ;u[g+88>>2]=f.deltaMode;e?U(e,d,9,g,b):V(d,9,g,b)&&f.preventDefault()},gh:c})};function Eh(a,b,c,d,e){return m?E(66,0,1,a,b,c,d,e):(a=T(a))?"undefined"!=typeof a.onwheel?fl(a,b,c,d,e):-1:-4}function Fh(a){return m?E(67,0,1,a):document.title=a?z(t,a):""}
var Gh=a=>gl(b=>Pi(b,a)),hl={},jl=()=>{if(!il){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in hl)void 0===hl[b]?delete a[b]:a[b]=hl[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);il=c}return il},il;
function Hh(a,b){if(m)return E(68,0,1,a,b);var c=0;jl().forEach((d,e)=>{var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)r[e++]=d.charCodeAt(f);r[e]=0;c+=d.length+1});return 0}function Ih(a,b){if(m)return E(69,0,1,a,b);var c=jl();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);v[b>>2]=d;return 0}function Kh(a){return m?E(70,0,1,a):52}function Lh(a,b,c,d){return m?E(71,0,1,a,b,c,d):52}function Mh(a,b,c,d,e){return m?E(72,0,1,a,b,c,d,e):70}var kl=[null,[],[]];
function Nh(a,b,c,d){if(m)return E(73,0,1,a,b,c,d);for(var e=0,f=0;f<c;f++){var g=v[b>>2],l=v[b+4>>2];b+=8;for(var n=0;n<l;n++){var q=t[g+n],y=kl[a];0===q||10===q?((1===a?ra:p)(z(y,0)),y.length=0):y.push(q)}e+=l}v[d>>2]=e;return 0}
var ll=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Qh=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&ll(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Rh=(a,b=[])=>{var c="vi".replace(/p/g,"i");(0,h["dynCall_"+c])(a,...b)},ml=a=>{try{a()}catch(b){Za(b)}};
function nl(){var a=X,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{ol.push(c);try{return d(...e)}finally{La||(ol.pop(),pl&&1===ql&&0===ol.length&&(ql=0,D+=1,ml(rl),"undefined"!=typeof Fibers&&Fibers.Pi()))}}:d;return b}var ql=0,pl=null,sl=0,ol=[],yl={},zl={},Al=0,Bl=null,Cl=[];function Dl(){var a=A(4108),b=a+12;v[a>>2]=b;v[a+4>>2]=b+4096;b=ol[0];var c=yl[b];void 0===c&&(c=Al++,yl[b]=c,zl[c]=b);u[a+8>>2]=c;return a}function El(){var a=X[zl[u[pl+8>>2]]];--D;return a()}
function gl(a){if(!La){if(0===ql){var b=!1,c=!1;a((d=0)=>{if(!La&&(sl=d,b=!0,c)){ql=2;ml(()=>Fl(pl));"undefined"!=typeof ej&&Bi&&Ri();d=!1;try{var e=El()}catch(l){e=l,d=!0}var f=!1;if(!pl){var g=Bl;g&&(Bl=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(ql=1,pl=Dl(),"undefined"!=typeof ej&&Bi&&Qi(),ml(()=>Gl(pl)))}else 2===ql?(ql=0,ml(Hl),Pj(pl),pl=null,Cl.forEach(vi)):Za(`invalid state: ${ql}`);return sl}}m?di=!1:hi();
h.requestFullscreen=function(a,b){function c(){Si=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=$i,Yi&&d.requestPointerLock(),Si=!0,Zi?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>2]|8388608),dj(h.canvas),cj()):dj(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Zi?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=
v[SDL.screen>>2]&-8388609),dj(h.canvas),cj()):dj(d));h.onFullScreen?.(Si);h.onFullscreen?.(Si)}Yi=a;Zi=b;"undefined"==typeof Yi&&(Yi=!0);"undefined"==typeof Zi&&(Zi=!1);var d=h.canvas;Xi||(Xi=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=Gi;h.setCanvasSize=function(a,b,c){dj(h.canvas,a,b);c||cj()};h.pauseMainLoop=Qi;h.resumeMainLoop=Ri;
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.mh&&a==h.canvas)return h.mh;var e;if(b){var f={antialias:!1,alpha:!1,Sh:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Lj&&(e=Ij(a,f)))var l=L[e].fh}else l=a.getContext("2d");if(!l)return null;c&&(h.mh=l,b&&Kj(e),h.Ai=b,Ui.forEach(n=>n()),Vi());return l};
for(var P,Y=0;32>Y;++Y)Ek.push(Array(Y));var Il=new Float32Array(288);for(Y=0;288>=Y;++Y)Sk[Y]=Il.subarray(0,Y);var Jl=new Int32Array(288);for(Y=0;288>=Y;++Y)Tk[Y]=Jl.subarray(0,Y);
var yi=[Oh,fi,ui,lb,mb,nb,ob,pb,qb,rb,sb,tb,ub,Ab,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,$b,sk,wk,ac,cc,dc,ec,fc,hc,ic,dh,eh,gh,hh,ih,kh,lh,mh,nh,oh,ph,qh,rh,sh,th,uh,vh,wh,xh,yh,zh,Ah,Bh,Ch,Dh,Eh,Fh,Hh,Ih,Kh,Lh,Mh,Nh],gb,X=function(){function a(c,d){X=c.exports;X=nl();gi.push(X.Yf);Ra.unshift(X.Wf);Ka=d;Ya();return X}var b=wa();Xa();if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return p(`Module.instantiateWasm callback failed with error: ${c}`),!1}ab||=$a("bombermaaan.wasm")?
"bombermaaan.wasm":h.locateFile?h.locateFile("bombermaaan.wasm",ja):ja+"bombermaaan.wasm";fb(b,function(c){a(c.instance,c.module)});return{}}(),Kl=h._main=(a,b)=>(Kl=h._main=X.Xf)(a,b),va=()=>(va=X.Zf)(),U=(a,b,c,d,e)=>(U=X._f)(a,b,c,d,e),Ba=(a,b,c,d,e,f)=>(Ba=X.$f)(a,b,c,d,e,f),Ia=()=>(Ia=X.ag)(),bi=(a,b,c,d,e)=>(bi=X.bg)(a,b,c,d,e),ji=a=>(ji=X.cg)(a),Ga=a=>(Ga=X.dg)(a),wi=()=>(wi=X.eg)(),Pj=a=>(Pj=X.fg)(a),A=a=>(A=X.hg)(a),oi=(a,b)=>(oi=X.ig)(a,b),ci=a=>(ci=X.jg)(a),ai=a=>(ai=X.kg)(a),$h=()=>($h=
X.lg)(),pi=h.dynCall_ii=(a,b)=>(pi=h.dynCall_ii=X.ng)(a,b),dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=X.og)(a,b,c),dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=X.pg)(a,b);h.dynCall_viiii=(a,b,c,d,e)=>(h.dynCall_viiii=X.qg)(a,b,c,d,e);h.dynCall_iiiii=(a,b,c,d,e)=>(h.dynCall_iiiii=X.rg)(a,b,c,d,e);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=X.sg)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=X.tg)(a,b);var V=h.dynCall_iiii=(a,b,c,d)=>(V=h.dynCall_iiii=X.ug)(a,b,c,d);
h.dynCall_i=a=>(h.dynCall_i=X.vg)(a);var dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=X.wg)(a),dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=X.xg)(a,b,c);h.dynCall_iiiiii=(a,b,c,d,e,f)=>(h.dynCall_iiiiii=X.yg)(a,b,c,d,e,f);h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=X.zg)(a,b,c,d,e,f);h.dynCall_viii=(a,b,c,d)=>(h.dynCall_viii=X.Ag)(a,b,c,d);h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,l)=>(h.dynCall_iiiiiiii=X.Bg)(a,b,c,d,e,f,g,l);
h.dynCall_iiiiiiiiii=(a,b,c,d,e,f,g,l,n,q)=>(h.dynCall_iiiiiiiiii=X.Cg)(a,b,c,d,e,f,g,l,n,q);h.dynCall_iiiiiiiiiiiiiiff=(a,b,c,d,e,f,g,l,n,q,y,H,Z,O,sc,tc)=>(h.dynCall_iiiiiiiiiiiiiiff=X.Dg)(a,b,c,d,e,f,g,l,n,q,y,H,Z,O,sc,tc);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,l,n)=>(h.dynCall_iiiiiiiii=X.Eg)(a,b,c,d,e,f,g,l,n);h.dynCall_viiiiiii=(a,b,c,d,e,f,g,l)=>(h.dynCall_viiiiiii=X.Fg)(a,b,c,d,e,f,g,l);h.dynCall_viiiiiiiiiii=(a,b,c,d,e,f,g,l,n,q,y,H)=>(h.dynCall_viiiiiiiiiii=X.Gg)(a,b,c,d,e,f,g,l,n,q,y,H);
h.dynCall_iiiiiidiiff=(a,b,c,d,e,f,g,l,n,q,y)=>(h.dynCall_iiiiiidiiff=X.Hg)(a,b,c,d,e,f,g,l,n,q,y);h.dynCall_iid=(a,b,c)=>(h.dynCall_iid=X.Ig)(a,b,c);h.dynCall_di=(a,b)=>(h.dynCall_di=X.Jg)(a,b);h.dynCall_iiiiiiji=(a,b,c,d,e,f,g,l,n)=>(h.dynCall_iiiiiiji=X.Kg)(a,b,c,d,e,f,g,l,n);h.dynCall_iji=(a,b,c,d)=>(h.dynCall_iji=X.Lg)(a,b,c,d);h.dynCall_fi=(a,b)=>(h.dynCall_fi=X.Mg)(a,b);h.dynCall_iif=(a,b,c)=>(h.dynCall_iif=X.Ng)(a,b,c);
h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=X.Og)(a,b,c,d,e,f,g);h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=X.Pg)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=X.Qg)(a,b);h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,l,n)=>(h.dynCall_viiiiiiii=X.Rg)(a,b,c,d,e,f,g,l,n);h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,l,n,q)=>(h.dynCall_viiiiiiiii=X.Sg)(a,b,c,d,e,f,g,l,n,q);h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=X.Tg)(a,b,c);h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=X.Ug)(a,b,c);
h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=X.Vg)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=X.Wg)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=X.Xg)(a,b,c,d);h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=X.Yg)(a,b,c,d,e);h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=X.Zg)(a,b,c,d,e,f);h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_viiiiii=X._g)(a,b,c,d,e,f,g);h.dynCall_viiiiiiiiii=(a,b,c,d,e,f,g,l,n,q,y)=>(h.dynCall_viiiiiiiiii=X.$g)(a,b,c,d,e,f,g,l,n,q,y);
h.dynCall_viifi=(a,b,c,d,e)=>(h.dynCall_viifi=X.ah)(a,b,c,d,e);var Gl=a=>(Gl=X.bh)(a),rl=()=>(rl=X.ch)(),Fl=a=>(Fl=X.dh)(a),Hl=()=>(Hl=X.eh)(),Ll;Wa=function Ml(){Ll||Nl();Ll||(Wa=Ml)};function Ol(a=[]){var b=Kl;a.unshift(fa);var c=a.length,d=ai(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=tk(g);e+=4});v[e>>2]=0;try{var f=b(c,d);Jh(f,!0)}catch(g){ei(g)}}
function Nl(){var a=ea;function b(){if(!Ll&&(Ll=!0,h.calledRun=!0,!La&&(m||ni(Ra),m||ni(Sa),h.onRuntimeInitialized?.(),Pl&&Ol(a),!m))){if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Ta.unshift(c)}ni(Ta)}}if(!(0<Ua))if(m)m||ni(Ra),startWorker(h);else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Qa.unshift(h.preRun.shift());ni(Qa);0<Ua||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},
1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Pl=!0;h.noInitialRun&&(Pl=!1);Nl();
