var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,l="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,m=ba&&"em-pthread"==self.name;if(l){var ca=require("worker_threads");global.Worker=ca.Worker;m=(ba=!ca.wj)&&"em-pthread"==ca.workerData}
var ea=Object.assign({},h),fa=[],ha="./this.program",ia=(a,b)=>{throw b;},ja="undefined"!=typeof document?document.currentScript?.src:void 0;l?ja=__filename:ba&&(ja=self.location.href);var ka="",la,ma;
if(l){var fs=require("fs"),na=require("path");ka=__dirname+"/";ma=a=>{a=oa(a)?new URL(a):na.normalize(a);return fs.readFileSync(a)};la=a=>{a=oa(a)?new URL(a):na.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!h.thisProgram&&1<process.argv.length&&(ha=process.argv[1].replace(/\\/g,"/"));fa=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof pa||a.context instanceof pa))throw a;
});ia=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?ka=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ka=document.currentScript.src),ka=ka.startsWith("blob:")?"":ka.substr(0,ka.replace(/[?#].*/,"").lastIndexOf("/")+1),l||(ba&&(ma=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),la=a=>oa(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=
()=>{(200==d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url))));l&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var qa=console.log.bind(console),ta=console.error.bind(console);l&&(qa=(...a)=>fs.writeSync(1,a.join(" ")+"\n"),ta=(...a)=>fs.writeSync(2,a.join(" ")+"\n"));var ua=h.print||qa,q=h.printErr||ta;
Object.assign(h,ea);ea=null;h.arguments&&(fa=h.arguments);h.thisProgram&&(ha=h.thisProgram);h.quit&&(ia=h.quit);
if(m){var va;if(l){var wa=ca.parentPort;wa.on("message",c=>onmessage({data:c}));Object.assign(globalThis,{self:global,importScripts:()=>{},postMessage:c=>wa.postMessage(c),performance:global.performance||{now:Date.now}})}var xa=!1;function a(...c){c=c.join(" ");l?fs.writeSync(2,c+"\n"):console.error(c)}h.printErr||(q=a);self.alert=function(...c){postMessage({xi:"alert",text:c.join(" "),Fj:ya()})};h.instantiateWasm=(c,d)=>new Promise(e=>{va=f=>{f=new WebAssembly.Instance(f,za());d(f);e()}});self.onunhandledrejection=
c=>{throw c.reason||c;};function b(c){try{var d=c.data,e=d.cmd;if("load"===e){let f=[];self.onmessage=g=>f.push(g);self.startWorker=()=>{postMessage({cmd:"loaded"});for(let g of f)b(g);self.onmessage=b};for(const g of d.handlers)if(!h[g]||h[g].proxy)h[g]=(...k)=>{postMessage({xi:"callHandler",vj:g,args:k})},"print"==g&&(ua=h[g]),"printErr"==g&&(q=h[g]);Aa=d.wasmMemory;Ba();Ca=Da(d.wasmOffsetConverter);va(d.wasmModule)}else if("run"===e){Ea(d.pthread_ptr,0,0,1,0,0);Fa(d.pthread_ptr);Ga();Ha();xa||=
!0;try{Ia(d.start_routine,d.arg)}catch(f){if("unwind"!=f)throw f;}}else"cancel"===e?ya()&&Ja(-1):"setimmediate"!==d.target&&("checkMailbox"===e?xa&&Ka():e&&(q(`worker: received unknown command ${e}`),q(d)))}catch(f){throw La(),f;}}self.onmessage=b}var Ma;h.wasmBinary&&(Ma=h.wasmBinary);var Aa,Na,Oa=!1,Pa,r,u,Qa,Ra,v,w,x,y;
function Ba(){var a=Aa.buffer;h.HEAP8=r=new Int8Array(a);h.HEAP16=Qa=new Int16Array(a);h.HEAPU8=u=new Uint8Array(a);h.HEAPU16=Ra=new Uint16Array(a);h.HEAP32=v=new Int32Array(a);h.HEAPU32=w=new Uint32Array(a);h.HEAPF32=x=new Float32Array(a);h.HEAPF64=y=new Float64Array(a)}
if(!m){if(h.wasmMemory)Aa=h.wasmMemory;else{var Sa=h.INITIAL_MEMORY||67108864;Aa=new WebAssembly.Memory({initial:Sa/65536,maximum:Sa/65536,shared:!0});if(!(Aa.buffer instanceof SharedArrayBuffer))throw q("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),l&&q("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");}Ba()}var Ta=[],Ua=[],Va=[],Wa=[];function Xa(){m||(h.noFSInit||Ya||(Ya=!0,h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?Za("stdin",h.stdin):$a("/dev/tty","/dev/stdin"),h.stdout?Za("stdout",null,h.stdout):$a("/dev/tty","/dev/stdout"),h.stderr?Za("stderr",null,h.stderr):$a("/dev/tty1","/dev/stderr"),ab("/dev/stdin",0),ab("/dev/stdout",1),ab("/dev/stderr",1)),bb=!1,cb(Ua))}var db=0,eb=null,fb=null;function gb(){db++;h.monitorRunDependencies?.(db)}
function hb(){db--;h.monitorRunDependencies?.(db);if(0==db&&(null!==eb&&(clearInterval(eb),eb=null),fb)){var a=fb;fb=null;a()}}function ib(a){h.onAbort?.(a);a="Aborted("+a+")";q(a);Oa=!0;Pa=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var jb=a=>a.startsWith("data:application/octet-stream;base64,"),oa=a=>a.startsWith("file://"),kb;function lb(a){if(a==kb&&Ma)return new Uint8Array(Ma);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}
function mb(a){return Ma?Promise.resolve().then(()=>lb(a)):la(a).then(b=>new Uint8Array(b),()=>lb(a))}var Ca;
function nb(a,b){function c(){var n=0,p=0;do{var t=g[e++];n+=(t&127)<<p;p+=7}while(t&128);return n}function d(){var n=c();c();0!=(n&1)&&c()}var e=8,f=0;this.gi={};this.ph=[];this.ji={};var g=a;a:for(;e<g.length;){a=g[e++];var k=c()+e;switch(a){case 2:for(a=c();0<a--;)switch(e=c()+e,e=c()+e,g[e++]){case 0:++f;c();break;case 1:c();d();break;case 2:d();break;case 3:e+=2;break;case 4:++e,c()}break;case 10:for(a=c();0<a--;)k=c(),this.gi[f++]=e,this.ph.push(e),e+=k;break a}e=k}b=WebAssembly.Module.customSections(b,
"name");if(b=b.length?b[0]:void 0)for(g=new Uint8Array(b),e=0;e<g.length;)if(b=g[e++],f=c(),1!=b)e+=f;else for(a=c();0<a--;)b=c(),f=c(),this.ji[b]=z(g,e,f),e+=f}function Da(a){var b=Object.create(nb.prototype);return Object.assign(b,a)}function ob(a,b,c){var d;return mb(a).then(e=>{d=e;return WebAssembly.instantiate(e,b)}).then(e=>{Ca=new nb(d,e.module);return e}).then(c,e=>{q(`failed to asynchronously prepare wasm: ${e}`);ib(e)})}
function qb(a,b){var c=kb;Ma||"function"!=typeof WebAssembly.instantiateStreaming||jb(c)||oa(c)||l||"function"!=typeof fetch?ob(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>{var e=WebAssembly.instantiateStreaming(d,a),f=d.clone().arrayBuffer();return e.then(function(g){f.then(k=>{Ca=new nb(new Uint8Array(k),g.module);b(g)},k=>q(`failed to initialize offset-converter: ${k}`))},function(g){q(`wasm streaming compile failed: ${g}`);q("falling back to ArrayBuffer instantiation");return ob(c,a,b)})})}
function za(){rb={mf:sb,ld:tb,c:ub,af:vb,O:wb,Hb:xb,ab:yb,cc:zb,lb:Ab,_a:Bb,gb:Cb,P:Db,$a:Eb,wb:Fb,xf:Gb,Fa:Hb,Tf:Ib,ua:Jb,$:Kb,Hd:Lb,Q:Mb,If:Fa,Sd:Nb,vb:Ob,Xa:Pb,mb:Qb,ob:Rb,nb:Sb,pb:Tb,Ya:Ub,n:Vb,kb:Wb,Va:Xb,qb:Yb,jb:Zb,rb:$b,sb:ac,Wa:cc,ub:dc,tb:ec,bb:fc,b:gc,N:hc,ad:ic,l:jc,m:kc,cb:lc,hb:mc,Tb:nc,Rc:oc,g:pc,e:qc,q:rc,d:sc,fb:tc,ib:uc,Aa:vc,za:wc,rd:xc,Ra:yc,Uc:zc,ya:Ac,xa:Bc,Qc:Cc,Sc:Dc,wa:Ec,va:Fc,Xb:Gc,ta:Hc,Nb:Ic,Zc:Jc,Ja:Jc,sa:Kc,ra:Lc,qa:Mc,pa:Nc,oa:Oc,dd:Pc,na:Qc,ma:Rc,la:Sc,ka:Tc,tc:Uc,
uc:Vc,wc:Wc,vc:Xc,ja:Yc,ia:Zc,ha:$c,fc:ad,ga:bd,fa:cd,ea:dd,xd:ed,da:fd,vd:gd,rc:hd,ca:jd,ba:kd,yd:ld,aa:md,_:nd,Z:od,Y:pd,X:qd,W:rd,td:sd,Ta:td,V:ud,Zb:vd,U:wd,gc:xd,T:yd,Mb:zd,Yc:Ad,Ia:Ad,S:Bd,R:Cd,Sf:Dd,Rf:Ed,Qf:Fd,Pf:Gd,Of:Hd,kc:Id,Da:Id,Id,Jd:Id,xb:Id,kd:Jd,Dd:Jd,Ea:Jd,Nf:Kd,jc:Ld,Ca:Ld,Ed:Ld,Fd:Ld,Gd:Ld,Bd:Md,Mf:Nd,Lf:Od,qd:Pd,Qa:Qd,Tc:Rd,ic:Sd,Kf:Td,Jf:Ud,_c:Vd,Hf:Wd,Gf:Xd,bd:Yd,Ff:Zd,Ef:$d,Cf:ae,ud:be,Ua:ce,Bf:de,_b:ee,Af:fe,Lb:ge,Xc:he,Ha:he,Df:ie,zf:je,yf:ke,mc:le,nc:me,pc:ne,wf:oe,vf:pe,
uf:qe,$b:re,tf:se,md:te,sf:ue,rf:ve,Fc:we,qf:xe,ac:ye,dc:ze,Vc:Ae,pf:Be,zb:Ce,Gb:De,nf:Ee,of:Fe,La:Ge,Na:He,Ka:Ge,od:Ie,Ma:He,pd:Je,Oa:Ke,lf:Le,Pb:Me,Qb:Ne,jf:Oe,hf:Pe,gf:Qe,kf:Re,ff:Se,sc:Te,bc:Ue,ef:Ve,df:We,Oc:Xe,oc:Ye,qc:Ze,$e,cf:af,bf,Gc:cf,Mc:df,Lc:df,Ye:ef,_e:ff,Ze:gf,Xe:hf,Db:jf,Cb:kf,We:lf,Ve:mf,Ue:nf,Te:of,sd:pf,Sa:qf,Se:rf,Yb:sf,Qe:tf,hc:uf,Pe:vf,Kb:wf,Wc:xf,Ga:xf,Oe:yf,Ne:zf,$c:Af,Jb:Bf,Me:Cf,Le:Df,Fb:Ef,Eb:Ff,Pa:Gf,Cd:Hf,Ke:If,Je:Jf,Ie:Kf,cd:Lf,Ib:Mf,He:Nf,Ub:Of,Rb:Pf,Wb:Qf,Vb:Rf,Ge:Sf,
Fe:Tf,Ee:Uf,De:Vf,Ce:Wf,Be:Xf,Ae:Yf,ze:Zf,ye:$f,xe:ag,Ad:bg,we:cg,ve:dg,ue:eg,te:fg,Bb:gg,Ab:hg,se:ig,zd:jg,Pc:kg,re:lg,qe:mg,pe:ng,oe:og,Ec:pg,Ac:qg,ne:rg,le:sg,ke:tg,je:ug,Dc:vg,zc:wg,ie:xg,he:yg,ge:zg,fe:Ag,Cc:Bg,yc:Cg,ee:Dg,de:Eg,ce:Fg,ae:Gg,Bc:Hg,xc:Ig,lc:Jg,$d:Kg,jd:Lg,hd:Mg,_d:Ng,id:Og,fd:Pg,Zd:Qg,gd:Rg,ed:Sg,nd:Tg,Yd:Ug,Xd:Vg,Wd:Wg,Vd:Xg,Ud:Yg,Td:Zg,Rd:$g,Qd:ah,Pd:bh,Od:ch,Ob:dh,Ba:dh,Kd:dh,Ld:dh,yb:dh,Kc:eh,Ic:fh,Jc:gh,Hc:hh,Nc:ih,Nd:jh,Md:kh,ec:lh,k:mh,db:nh,M:oh,Vf:ph,C:qh,r:rh,E:sh,f:th,
i:uh,F:vh,u:wh,p:xh,o:yh,x:zh,v:Ah,w:Bh,K:Ch,I:Dh,H:Eh,L:Fh,J:Gh,y:Hh,t:Ih,z:Jh,B:Kh,A:Lh,D:Mh,s:Nh,G:Oh,eb:Ph,j:Qh,be:Rh,me:Sh,Re:Th,h:Uh,Sb:Vh,Za:Wh,Uf:Xh,a:Aa,wd:Yh};return{a:rb}}
var A,C,ci={8209860:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Mi!==h.canvas&&(d.th=h.createContext(h.canvas,!1,!0),d.Mi=h.canvas);if(d.w!==a||d.h!==b||d.Vi!==d.th)d.image=d.th.createImageData(a,b),d.w=a,d.h=b,d.Vi=d.th;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=v[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Pi!==a&&(d.Oi=new Int32Array(a.buffer),d.Qi=new Uint8Array(a.buffer),d.Pi=
a),a=d.Oi,c=a.length,a.set(v.subarray(b,b+c)),a=d.Qi,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.th.putImageData(d.image,0,0)},8211328:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var k=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=
b.length;k<n;){var p=v[e];b[k]=p&255;b[k+1]=p>>8&255;b[k+2]=p>>16&255;b[k+3]=p>>24&255;e++;k+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(v.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);E(c,u,d,c.length+1);return d},8212316:a=>{h.canvas&&(h.canvas.style.cursor=a?z(u,a):"")},8212399:()=>{h.canvas&&(h.canvas.style.cursor="none")},8212468:()=>window.innerWidth,8212498:()=>window.innerHeight,8212529:a=>
{a=(a?z(u,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");a=Zh(a);var b=D(a.length);a.subarray||a.slice||(a=new Uint8Array(a));u.set(a,b);return b},8212754:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,8212901:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,8213135:a=>{"undefined"===typeof h.SDL2&&
(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.hh||("undefined"!==typeof AudioContext?b.hh=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.hh=new webkitAudioContext),b.hh&&"undefined"===typeof navigator.userActivation&&$h(b.hh));return void 0===b.hh?-1:0},8213687:()=>h.SDL2.hh.sampleRate,8213755:(a,b,c,d)=>{function e(){}function f(k){void 0!==g.capture.sh&&(clearInterval(g.capture.sh),g.capture.sh=void 0,g.capture.Jh=void 0);g.capture.ii=g.hh.createMediaStreamSource(k);g.capture.rh=
g.hh.createScriptProcessor(b,a,1);g.capture.rh.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.ei=n.inputBuffer,ai(c,[d]))};g.capture.ii.connect(g.capture.rh);g.capture.rh.connect(g.hh.destination);g.capture.stream=k}var g=h.SDL2;g.capture.Jh=g.hh.createBuffer(a,b,g.hh.sampleRate);g.capture.Jh.getChannelData(0).fill(0);g.capture.sh=setInterval(function(){g.capture.ei=g.capture.Jh;ai(c,[d])},b/g.hh.sampleRate*1E3);void 0!==navigator.mediaDevices&&
void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},8215448:(a,b,c,d)=>{var e=h.SDL2;e.audio.rh=e.hh.createScriptProcessor(b,0,a);e.audio.rh.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.sh&&(clearInterval(e.audio.sh),e.audio.sh=void 0,e.audio.Jh=void 0),e.audio.Vh=f.outputBuffer,ai(c,[d]))};e.audio.rh.connect(e.hh.destination);
"suspended"===e.hh.state&&(e.audio.Jh=e.hh.createBuffer(a,b,e.hh.sampleRate),e.audio.Jh.getChannelData(0).fill(0),e.audio.sh=setInterval(function(){"undefined"!==typeof navigator.userActivation&&navigator.userActivation.hasBeenActive&&e.hh.resume();e.audio.Vh=e.audio.Jh;ai(c,[d]);e.audio.Vh=void 0},b/e.hh.sampleRate*1E3))},8216623:(a,b)=>{for(var c=h.SDL2,d=c.capture.ei.numberOfChannels,e=0;e<d;++e){var f=c.capture.ei.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+
f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)bi(a+4*g,f[g]);else for(g=0;g<b;++g)bi(a+4*(g*d+e),f[g])}},8217228:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=c.audio.Vh.numberOfChannels,e=0;e<d;++e){var f=c.audio.Vh.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=x[a+(g*d+e)]}},8217717:a=>{var b=h.SDL2;if(a){void 0!==b.capture.sh&&clearInterval(b.capture.sh);
if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.rh&&(b.capture.rh.onaudioprocess=function(){},b.capture.rh.disconnect());void 0!==b.capture.ii&&b.capture.ii.disconnect();b.capture=void 0}else void 0!=b.audio.rh&&b.audio.rh.disconnect(),void 0!==b.audio.sh&&clearInterval(b.audio.sh),b.audio=void 0;void 0!==b.hh&&void 0===b.audio&&void 0===b.capture&&(b.hh.close(),b.hh=void 0)}};
function pa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var di=a=>{a.terminate();a.onmessage=()=>{}},ji=a=>{0==ei.length&&(fi(),gi(ei[0]));var b=ei.pop();if(!b)return 6;hi.push(b);ii[a.Fh]=b;b.Fh=a.Fh;var c={cmd:"run",start_routine:a.dj,arg:a.ui,pthread_ptr:a.Fh};l&&b.unref();b.postMessage(c,a.ej);return 0},F=0,G=(a,b,c,...d)=>{for(var e=d.length,f=ki(),g=li(8*e),k=g>>3,n=0;n<d.length;n++)y[k+n]=d[n];a=mi(a,b,e,g,c);ni(f);return a};
function Yh(a){if(m)return G(0,0,1,a);Pa=a;if(!(oi||0<F)){for(var b of hi)di(b);for(b of ei)di(b);ei=[];hi=[];ii=[];h.onExit?.(a);Oa=!0}ia(a,new pa(a))}var pi=a=>{a instanceof pa||"unwind"==a||ia(1,a)};function qi(a){if(m)return G(1,0,0,a);Th(a)}var Th=a=>{Pa=a;if(m)throw qi(a),"unwind";Yh(a)},ei=[],hi=[],ri=[],ii={};function si(){for(var a=navigator.hardwareConcurrency;a--;)fi();Ta.unshift(()=>{gb();ti(()=>hb())})}var vi=a=>{var b=a.Fh;delete ii[b];ei.push(a);hi.splice(hi.indexOf(a),1);a.Fh=0;ui(b)};
function Ha(){ri.forEach(a=>a())}
var gi=a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.cmd;if(f.targetThread&&f.targetThread!=ya()){var k=ii[f.targetThread];k?k.postMessage(f,f.transferList):q(`Internal error! Worker sent a message "${g}" to target pthread ${f.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===g)Ka();else if("spawnThread"===g)ji(f);else if("cleanupThread"===g)vi(ii[f.thread]);else if("killThread"===g)f=f.thread,g=ii[f],delete ii[f],di(g),ui(f),hi.splice(hi.indexOf(g),1),g.Fh=0;else if("cancelThread"===
g)ii[f.thread].postMessage({cmd:"cancel"});else if("loaded"===g)a.loaded=!0,l&&!a.Fh&&a.unref(),b(a);else if("alert"===g)alert(`Thread ${f.threadId}: ${f.text}`);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===g)h[f.handler](...f.args);else g&&q(`worker sent an unknown command ${g}`)};a.onerror=f=>{q(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};l&&(a.on("message",f=>a.onmessage({data:f})),a.on("error",f=>a.onerror(f)));var c=[],d=["onExit",
"onAbort","print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({cmd:"load",handlers:c,wasmMemory:Aa,wasmModule:Na,wasmOffsetConverter:Ca})});function ti(a){m?a():Promise.all(ei.map(gi)).then(a)}function fi(){var a=ja;h.mainScriptUrlOrBlob&&(a=h.mainScriptUrlOrBlob,"string"!=typeof a&&(a=URL.createObjectURL(a)));a=new Worker(a,{workerData:"em-pthread",name:"em-pthread"});ei.push(a)}
var wi,xi="undefined"!=typeof TextDecoder?new TextDecoder:void 0,z=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&xi)return xi.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&
1023))}}else d+=String.fromCharCode(e)}return d},cb=a=>{for(;0<a.length;)a.shift()(h)},Ga=()=>{var a=ya(),b=w[a+52>>2];yi(b,b-w[a+56>>2]);ni(b)},Ia=(a,b)=>{F=0;a=zi(a,b);oi||0<F?Pa=a:Ja(a)},oi=h.noExitRuntime||!0;
function bi(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":r[a]=b;break;case "i8":r[a]=b;break;case "i16":Qa[a>>1]=b;break;case "i32":v[a>>2]=b;break;case "i64":ib("to do setValue(i64) use WASM_BIGINT");case "float":x[a>>2]=b;break;case "double":y[a>>3]=b;break;case "*":w[a>>2]=b;break;default:ib(`invalid type for setValue: ${c}`)}}
var Ai=(a,b)=>a?z(u,a,b):"",sb=(a,b,c,d)=>{ib(`Assertion failed: ${a?z(u,a):""}, at: `+[b?b?z(u,b):"":"unknown filename",c,d?d?z(u,d):"":"unknown function"])},tb=(a,b)=>dynCall_vi(a,b);class Bi{constructor(a){this.Bh=a-24}}var Ci=0,Di=0,ub=(a,b,c)=>{var d=new Bi(a);w[d.Bh+16>>2]=0;w[d.Bh+4>>2]=b;w[d.Bh+8>>2]=c;Ci=a;Di++;throw Ci;};function Ei(a,b,c,d){return m?G(2,0,1,a,b,c,d):vb(a,b,c,d)}
var vb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return q("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(m&&0===e.length)return Ei(a,b,c,d);a={dj:c,Fh:a,ui:d,ej:e};return m?(a.xi="spawnThread",postMessage(a,e),0):ji(a)};function Fi(){var a=v[+Gi>>2];Gi+=4;return a}
var Hi=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ii=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Hi(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ji=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Ki=a=>{if("/"===
a)return"/";a=Ii(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Li=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return c=>(c.set(crypto.getRandomValues(new Uint8Array(c.byteLength))),c);if(l)try{var a=require("crypto");if(a.randomFillSync)return c=>a.randomFillSync(c);var b=a.randomBytes;return c=>(c.set(b(c.byteLength)),c)}catch(c){}ib("initRandomDevice")},Mi=a=>(Mi=Li())(a),Ni=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=
0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Hi(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Oi=[],Pi=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},E=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=
65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function Zh(a,b){var c=Array(Pi(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}var Qi=[];function Ri(a,b){Qi[a]={input:[],output:[],Ah:b};Si(a,Ti)}
var Ti={open(a){var b=Qi[a.node.rdev];if(!b)throw new H(43);a.tty=b;a.seekable=!1},close(a){a.tty.Ah.fsync(a.tty)},fsync(a){a.tty.Ah.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Ah.Bi)throw new H(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Ah.Bi(a.tty)}catch(k){throw new H(29);}if(void 0===g&&0===e)throw new H(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Ah.li)throw new H(60);try{for(var e=0;e<d;e++)a.tty.Ah.li(a.tty,b[c+
e])}catch(f){throw new H(29);}d&&(a.node.timestamp=Date.now());return e}},Ui={Bi(){a:{if(!Oi.length){var a=null;if(l){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Oi=Zh(a,!0)}a=Oi.shift()}return a},li(a,b){null===b||10===b?(ua(z(a.output,
0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(ua(z(a.output,0)),a.output=[])},Yi(){return{mj:25856,oj:5,lj:191,nj:35387,kj:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Zi(){return 0},$i(){return[24,80]}},Vi={li(a,b){null===b||10===b?(q(z(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){a.output&&0<a.output.length&&(q(z(a.output,0)),a.output=[])}};
function Wi(a,b){var c=a.mg?a.mg.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.mg,a.mg=new Uint8Array(b),0<a.ih&&a.mg.set(c.subarray(0,a.ih),0))}
var I={wh:null,zh(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.wh||(I.wh={dir:{node:{vh:I.gg.vh,xh:I.gg.xh,lookup:I.gg.lookup,$h:I.gg.$h,rename:I.gg.rename,unlink:I.gg.unlink,rmdir:I.gg.rmdir,readdir:I.gg.readdir,symlink:I.gg.symlink},stream:{Ih:I.gh.Ih}},file:{node:{vh:I.gg.vh,xh:I.gg.xh},stream:{Ih:I.gh.Ih,read:I.gh.read,write:I.gh.write,ti:I.gh.ti,Ei:I.gh.Ei,Gi:I.gh.Gi}},link:{node:{vh:I.gg.vh,xh:I.gg.xh,readlink:I.gg.readlink},
stream:{}},wi:{node:{vh:I.gg.vh,xh:I.gg.xh},stream:Xi}});c=Yi(a,b,c,d);16384===(c.mode&61440)?(c.gg=I.wh.dir.node,c.gh=I.wh.dir.stream,c.mg={}):32768===(c.mode&61440)?(c.gg=I.wh.file.node,c.gh=I.wh.file.stream,c.ih=0,c.mg=null):40960===(c.mode&61440)?(c.gg=I.wh.link.node,c.gh=I.wh.link.stream):8192===(c.mode&61440)&&(c.gg=I.wh.wi.node,c.gh=I.wh.wi.stream);c.timestamp=Date.now();a&&(a.mg[b]=c,a.timestamp=c.timestamp);return c},uj(a){return a.mg?a.mg.subarray?a.mg.subarray(0,a.ih):new Uint8Array(a.mg):
new Uint8Array(0)},gg:{vh(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ih:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Li=4096;b.blocks=Math.ceil(b.size/b.Li);return b},xh(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==
b.size&&(b=b.size,a.ih!=b))if(0==b)a.mg=null,a.ih=0;else{var c=a.mg;a.mg=new Uint8Array(b);c&&a.mg.set(c.subarray(0,Math.min(b,a.ih)));a.ih=b}},lookup(){throw Zi[44];},$h(a,b,c,d){return I.createNode(a,b,c,d)},rename(a,b,c){if(16384===(a.mode&61440)){try{var d=$i(b,c)}catch(f){}if(d)for(var e in d.mg)throw new H(55);}delete a.parent.mg[a.name];a.parent.timestamp=Date.now();a.name=c;b.mg[c]=a;b.timestamp=a.parent.timestamp},unlink(a,b){delete a.mg[b];a.timestamp=Date.now()},rmdir(a,b){var c=$i(a,b),
d;for(d in c.mg)throw new H(55);delete a.mg[b];a.timestamp=Date.now()},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.mg))b.push(c);return b},symlink(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},gh:{read(a,b,c,d,e){var f=a.node.mg;if(e>=a.node.ih)return 0;a=Math.min(a.node.ih-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;
a.timestamp=Date.now();if(b.subarray&&(!a.mg||a.mg.subarray)){if(f)return a.mg=b.subarray(c,c+d),a.ih=d;if(0===a.ih&&0===e)return a.mg=b.slice(c,c+d),a.ih=d;if(e+d<=a.ih)return a.mg.set(b.subarray(c,c+d),e),d}Wi(a,e+d);if(a.mg.subarray&&b.subarray)a.mg.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.mg[e+f]=b[c+f];a.ih=Math.max(a.ih,e+d);return d},Ih(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ih);if(0>b)throw new H(28);return b},ti(a,b,c){Wi(a.node,b+c);a.node.ih=Math.max(a.node.ih,
b+c)},Ei(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);a=a.node.mg;if(e&2||a.buffer!==r.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;ib();b=void 0;if(!b)throw new H(48);r.set(a,b)}else c=!1,b=a.byteOffset;return{Bh:b,jj:c}},Gi(a,b,c,d){I.gh.write(a,b,0,d,c,!1);return 0}}},aj=h.preloadPlugins||[],bj=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},cj=null,dj={},ej=[],fj=1,gj=null,bb=!0,H=class{constructor(a){this.name="ErrnoError";
this.jh=a}},Zi={},hj=class{constructor(){this.ph={};this.node=null}get flags(){return this.ph.flags}set flags(a){this.ph.flags=a}get position(){return this.ph.position}set position(a){this.ph.position=a}},ij=class{constructor(a,b,c,d){a||=this;this.parent=a;this.zh=a.zh;this.ai=null;this.id=fj++;this.name=b;this.mode=c;this.gg={};this.gh={};this.rdev=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=
146:this.mode&=-147}};function jj(a,b={}){a=Ni(a);if(!a)return{path:"",node:null};b=Object.assign({Ai:!0,mi:0},b);if(8<b.mi)throw new H(32);a=a.split("/").filter(g=>!!g);for(var c=cj,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=$i(c,a[e]);d=Ii(d+"/"+a[e]);c.ai&&(!f||f&&b.Ai)&&(c=c.ai.root);if(!f||b.Wh)for(f=0;40960===(c.mode&61440);)if(c=kj(d),d=Ni(Ji(d),c),c=jj(d,{mi:b.mi+1}).node,40<f++)throw new H(32);}return{path:d,node:c}}
function lj(a){for(var b;;){if(a===a.parent)return a=a.zh.Fi,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function mj(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%gj.length}function $i(a,b){var c=16384===(a.mode&61440)?(c=nj(a,"x"))?c:a.gg.lookup?0:2:54;if(c)throw new H(c);for(c=gj[mj(a.id,b)];c;c=c.bj){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.gg.lookup(a,b)}
function Yi(a,b,c,d){a=new ij(a,b,c,d);b=mj(a.parent.id,a.name);a.bj=gj[b];return gj[b]=a}function oj(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function nj(a,b){if(bb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function pj(a,b){try{return $i(a,b),20}catch(c){}return nj(a,"wx")}function qj(a){a=ej[a];if(!a)throw new H(8);return a}
function rj(a,b=-1){a=Object.assign(new hj,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!ej[b])break a;throw new H(33);}a.fd=b;return ej[b]=a}function sj(a,b=-1){a=rj(a,b);a.gh?.rj?.(a);return a}var Xi={open(a){a.gh=dj[a.node.rdev].gh;a.gh.open?.(a)},Ih(){throw new H(70);}};function Si(a,b){dj[a]={gh:b}}
function tj(a,b){var c="/"===b;if(c&&cj)throw new H(10);if(!c&&b){var d=jj(b,{Ai:!1});b=d.path;d=d.node;if(d.ai)throw new H(10);if(16384!==(d.mode&61440))throw new H(54);}b={type:a,Dj:{},Fi:b,aj:[]};a=a.zh(b);a.zh=b;b.root=a;c?cj=a:d&&(d.ai=b,d.zh&&d.zh.aj.push(b))}function uj(a,b,c){var d=jj(a,{parent:!0}).node;a=Ki(a);if(!a||"."===a||".."===a)throw new H(28);var e=pj(d,a);if(e)throw new H(e);if(!d.gg.$h)throw new H(63);return d.gg.$h(d,a,b,c)}
function vj(a,b){return uj(a,(void 0!==b?b:511)&1023|16384,0)}function wj(a,b,c){"undefined"==typeof c&&(c=b,b=438);uj(a,b|8192,c)}function $a(a,b){if(!Ni(a))throw new H(44);var c=jj(b,{parent:!0}).node;if(!c)throw new H(44);b=Ki(b);var d=pj(c,b);if(d)throw new H(d);if(!c.gg.symlink)throw new H(63);c.gg.symlink(c,b,a)}function kj(a){a=jj(a).node;if(!a)throw new H(44);if(!a.gg.readlink)throw new H(28);return Ni(lj(a.parent),a.gg.readlink(a))}
function xj(a,b){a=jj(a,{Wh:!b}).node;if(!a)throw new H(44);if(!a.gg.vh)throw new H(63);return a.gg.vh(a)}function yj(a){return xj(a,!0)}
function ab(a,b,c){if(""===a)throw new H(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Ii(a);try{e=jj(a,{Wh:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new H(20);}else e=uj(a,c,0),d=!0;if(!e)throw new H(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new H(54);
if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==oj(b)||b&512)?31:nj(e,oj(b)):44))throw new H(c);if(b&512&&!d){c=e;c="string"==typeof c?jj(c,{Wh:!0}).node:c;if(!c.gg.xh)throw new H(63);if(16384===(c.mode&61440))throw new H(31);if(32768!==(c.mode&61440))throw new H(28);if(d=nj(c,"w"))throw new H(d);c.gg.xh(c,{size:0,timestamp:Date.now()})}b&=-131713;e=rj({node:e,path:lj(e),flags:b,seekable:!0,position:0,gh:e.gh,fj:[],error:!1});e.gh.open&&e.gh.open(e);!h.logReadFiles||b&1||(zj||=
{},a in zj||(zj[a]=1));return e}function Aj(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.gh.Ih)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.gh.Ih(a,b,c);a.fj=[];return a.position}var Ya;
function Za(a,b,c){a=Ii("/dev/"+a);var d=bj(!!b,!!c);Bj||=64;var e=Bj++<<8|0;Si(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,k,n){for(var p=0,t=0;t<n;t++){try{var B=b()}catch(J){throw new H(29);}if(void 0===B&&0===p)throw new H(6);if(null===B||void 0===B)break;p++;g[k+t]=B}p&&(f.node.timestamp=Date.now());return p},write(f,g,k,n){for(var p=0;p<n;p++)try{c(g[k+p])}catch(t){throw new H(29);}n&&(f.node.timestamp=Date.now());return p}});wj(a,d,e)}var Bj,K={},zj;
function Cj(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":qj(a).path;if(0==b.length){if(!c)throw new H(44);return a}return Ii(a+"/"+b)}
function Dj(a,b,c){a=a(b);v[c>>2]=a.dev;v[c+4>>2]=a.mode;w[c+8>>2]=a.nlink;v[c+12>>2]=a.uid;v[c+16>>2]=a.gid;v[c+20>>2]=a.rdev;C=[a.size>>>0,(A=a.size,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[c+24>>2]=C[0];v[c+28>>2]=C[1];v[c+32>>2]=4096;v[c+36>>2]=a.blocks;b=a.atime.getTime();var d=a.mtime.getTime(),e=a.ctime.getTime();C=[Math.floor(b/1E3)>>>0,(A=Math.floor(b/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>
0))/4294967296)>>>0:0)];v[c+40>>2]=C[0];v[c+44>>2]=C[1];w[c+48>>2]=b%1E3*1E3;C=[Math.floor(d/1E3)>>>0,(A=Math.floor(d/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[c+56>>2]=C[0];v[c+60>>2]=C[1];w[c+64>>2]=d%1E3*1E3;C=[Math.floor(e/1E3)>>>0,(A=Math.floor(e/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[c+72>>2]=C[0];v[c+76>>2]=C[1];w[c+80>>2]=e%1E3*1E3;C=[a.ino>>>0,(A=a.ino,1<=+Math.abs(A)?
0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[c+88>>2]=C[0];v[c+92>>2]=C[1];return 0}var Gi=void 0;
function wb(a,b,c){if(m)return G(3,0,1,a,b,c);Gi=c;try{var d=qj(a);switch(b){case 0:var e=Fi();if(0>e)break;for(;ej[e];)e++;return sj(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Fi(),d.flags|=e,0;case 12:return e=Fi(),Qa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.jh}}
function xb(a,b){if(m)return G(4,0,1,a,b);try{var c=qj(a);return Dj(xj,c.path,b)}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.jh}}
function yb(a,b,c){if(m)return G(5,0,1,a,b,c);try{var d=qj(a);if(!d.Hh){var e=jj(d.path,{Wh:!0}).node;if(!e.gg.readdir)throw new H(54);var f=e.gg.readdir(e);d.Hh=f}a=0;for(var g=Aj(d,0,1),k=Math.floor(g/280);k<d.Hh.length&&a+280<=c;){var n=d.Hh[k];if("."===n){var p=d.node.id;var t=4}else if(".."===n)p=jj(d.path,{parent:!0}).node.id,t=4;else{var B=$i(d.node,n);p=B.id;t=8192===(B.mode&61440)?2:16384===(B.mode&61440)?4:40960===(B.mode&61440)?10:8}C=[p>>>0,(A=p,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>
0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[b+a>>2]=C[0];v[b+a+4>>2]=C[1];C=[280*(k+1)>>>0,(A=280*(k+1),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[b+a+8>>2]=C[0];v[b+a+12>>2]=C[1];Qa[b+a+16>>1]=280;r[b+a+18]=t;E(n,u,b+a+19,256);a+=280;k+=1}Aj(d,280*k,0);return a}catch(J){if("undefined"==typeof K||"ErrnoError"!==J.name)throw J;return-J.jh}}
function zb(a,b,c){if(m)return G(6,0,1,a,b,c);Gi=c;try{var d=qj(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Ah.Yi){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Fi();v[e>>2]=25856;v[e+4>>2]=5;v[e+8>>2]=191;v[e+12>>2]=35387;for(var f=0;32>f;f++)r[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Ah.Zi)for(e=Fi(),a=[],f=0;32>f;f++)a.push(r[e+
f+17]);return 0;case 21519:if(!d.tty)return-59;e=Fi();return v[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=Fi();if(!d.gh.Xi)throw new H(59);return d.gh.Xi(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Ah.$i&&(f=[24,80],e=Fi(),Qa[e>>1]=f[0],Qa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof K||"ErrnoError"!==g.name)throw g;return-g.jh}}
function Ab(a,b){if(m)return G(7,0,1,a,b);try{return a=a?z(u,a):"",Dj(yj,a,b)}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return-c.jh}}function Bb(a,b,c){if(m)return G(8,0,1,a,b,c);try{return b=b?z(u,b):"",b=Cj(a,b),b=Ii(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),vj(b,c),0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.jh}}
function Cb(a,b,c,d){if(m)return G(9,0,1,a,b,c,d);try{b=b?z(u,b):"";var e=d&256;b=Cj(a,b,d&4096);return Dj(e?yj:xj,b,c)}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.jh}}function Db(a,b,c,d){if(m)return G(10,0,1,a,b,c,d);Gi=d;try{b=b?z(u,b):"";b=Cj(a,b);var e=d?Fi():0;return ab(b,c,e).fd}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.jh}}
function Eb(a,b,c,d){if(m)return G(11,0,1,a,b,c,d);try{b=b?z(u,b):"";b=Cj(a,b);if(0>=d)return-28;var e=kj(b),f=Math.min(d,Pi(e)),g=r[c+f];E(e,u,c,d+1);r[c+f]=g;return f}catch(k){if("undefined"==typeof K||"ErrnoError"!==k.name)throw k;return-k.jh}}function Fb(a,b){if(m)return G(12,0,1,a,b);try{return a=a?z(u,a):"",Dj(xj,a,b)}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return-c.jh}}
var Gb=()=>{ib("")},Hb=()=>1,Ib=a=>{Ea(a,!ba,1,!aa,16777216,!1);Ha()},Ej=a=>{if(!Oa)try{if(a(),!(oi||0<F))try{m?Ja(Pa):Th(Pa)}catch(b){pi(b)}}catch(b){pi(b)}},Fa=a=>{"function"===typeof Atomics.hj&&(Atomics.hj(v,a>>2,a).value.then(Ka),Atomics.store(v,a+128>>2,1))},Ka=()=>{var a=ya();a&&(Fa(a),Ej(Fj))},Jb=(a,b)=>{a==b?setTimeout(Ka):m?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=ii[a])&&a.postMessage({cmd:"checkMailbox"})},Gj=[],Kb=(a,b,c,d,e)=>{Gj.length=d;e>>=3;for(var f=0;f<d;f++)Gj[f]=y[e+
f];a=b?ci[b]:Hj[a];wi=c;c=a(...Gj);wi=0;return c};function Lb(){if(m)return G(13,0,1);oi=!1;F=0}
var Mb=a=>{m?postMessage({cmd:"cleanupThread",thread:a}):vi(ii[a])},Nb=a=>{l&&ii[a].ref()},Rj=(a,b)=>{Ij=a;Jj=b;if(Kj)if(Lj||(F+=1,Lj=!0),0==a)Mj=function(){var d=Math.max(0,Nj+b-sc())|0;setTimeout(Oj,d)};else if(1==a)Mj=function(){Pj(Oj)};else if(2==a){if("undefined"==typeof Qj)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Qj=function(d){c.push(d);if(ba){let e;(e=h).setImmediates??
(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Qj=setImmediate;Mj=function(){Qj(Oj)}}},sc;sc=()=>performance.timeOrigin+performance.now();
var Xj=a=>{function b(){return c<Sj?(--F,!1):!0}Kj=a;var c=Sj;Lj=!1;Oj=function(){if(!Oa)if(0<Tj.length){var d=Tj.shift();d.tj(d.ui);if(Uj){var e=Uj,f=0==e%1?e-1:Math.floor(e);Uj=d.pj?f:(8*e+(f+.5))/9}h.setStatus&&(d=h.statusMessage||"Please wait...",e=Uj,f=Vj.sj,e?e<f?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(d):h.setStatus(""));b()&&setTimeout(Oj,0)}else if(b())if(Wj=Wj+1|0,1==Ij&&1<Jj&&0!=Wj%Jj)Mj();else{0==Ij&&(Nj=sc());if(L)for(d=L.Nh,L.Nh=L.Qh,L.Qh=d,d=L.Gh,L.Gh=
L.ci,L.ci=d,d=0;21>=d;++d)L.Gh[d]=0;Oa||h.preMainLoop&&!1===h.preMainLoop()||(Ej(a),h.postMainLoop?.());b()&&("object"==typeof SDL&&SDL.audio?.Ej?.(),Mj())}}},Yj=(a,b)=>{F+=1;return setTimeout(()=>{--F;Ej(a)},b)},Lj=!1,Mj=null,Sj=0,Kj=null,Ij=0,Jj=0,Wj=0,Tj=[];function Zj(){Mj=null;Sj++}function ak(){Sj++;var a=Ij,b=Jj,c=Kj;Kj=null;Xj(c);Rj(a,b);Mj()}var Vj={},Nj,Oj,Uj,bk=!1,ck=!1,dk=[];
function ek(){function a(){ck=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!fk){fk=!0;aj.push({canHandle:function(c){return!h.Cj&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:gk(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:gk(d)}));var k=URL.createObjectURL(g),n=new Image;n.onload=()=>{var p=document.createElement("canvas");
p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(k);e?.(c)};n.onerror=()=>{q(`Image ${k} could not be decoded`);f?.()};n.src=k}});aj.push({canHandle:function(c){return!h.Bj&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,k=URL.createObjectURL(new Blob([c],{type:gk(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){q(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",t=0,B=0,J=0;J<c.length;J++)for(t=t<<8|c[J],B+=8;6<=B;){var O=t>>B-6&63;B-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[O]}2==B?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],p+="=="):4==B&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+p;f(n)}};n.src=k;Yj(()=>{f(n)},1E4)}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!ck&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var hk=!1,ik=void 0,jk=void 0;function kk(){if(!bk)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var lk=0;
function Pj(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===lk)lk=b+1E3/60;else for(;b+2>=lk;)lk+=1E3/60;setTimeout(a,Math.max(lk-b,0))}}function gk(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var mk=[];function nk(){var a=h.canvas;mk.forEach(b=>b(a.width,a.height))}
function ok(a,b,c){b&&c?(a.ij=b,a.Ui=c):(b=a.ij,c=a.Ui);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}jk?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var pk={},Qj,fk,M=12288,qk=!1,rk=0,sk=0,tk=0,N={alpha:!1,depth:!1,stencil:!1,antialias:!1},uk={},vk;function Ob(a){if(m)return G(14,0,1,a);if(12448==a)return M=12288,1;M=12300;return 0}
function Pb(a,b,c,d,e){if(m)c=G(15,0,1,a,b,c,d,e);else if(62E3!=a)M=12296,c=0;else{if(b)for(;;){a=v[b>>2];if(12321==a)N.alpha=0<v[b+4>>2];else if(12325==a)N.depth=0<v[b+4>>2];else if(12326==a)N.stencil=0<v[b+4>>2];else if(12337==a)a=v[b+4>>2],N.antialias=0<a;else if(12338==a)a=v[b+4>>2],N.antialias=1==a;else if(12544==a)N.xj=12547!=v[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(v[e>>2]=1),c&&0<d&&(w[c>>2]=62002),M=12288,c=1):(M=12300,c=0)}return c}
var wk=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},xk=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},
yk=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},zk=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Ak=1,Bk=[],Ck={},P=[],Dk=[],Ek=[],Fk=[],Q=[],Gk=[],Hk={},R=[],Ik=[],Jk=[],Kk=[],Lk=[1,1,2,2,4,4,4,2,3,4,8],Mk={},Nk={},Ok=4,Pk=0,Qk=a=>{for(var b=Ak++,c=a.length;c<b;c++)a[c]=null;return b},Rk=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=S[c](),g=f&&Qk(d);f?(f.name=g,d[g]=f):T||=1282;v[b+4*e>>2]=g}},Tk=a=>{Sk=!1;for(var b=0;b<L.Di;++b){var c=L.Dh[b];if(c.Oh&&c.enabled){Sk=!0;var d=c.bi;d=0<d?a*d:c.size*Lk[c.type-5120]*a;var e=32-Math.clz32(0===
d?0:d-1);var f=L.Nh[e],g=L.Gh[e];L.Gh[e]=L.Gh[e]+1&63;var k=f[g];k?e=k:(k=S.getParameter(34964),f[g]=S.createBuffer(),S.bindBuffer(34962,f[g]),S.bufferData(34962,1<<e,35048),S.bindBuffer(34962,k),e=f[g]);S.bindBuffer(34962,e);S.bufferSubData(34962,0,u.subarray(c.Bh,c.Bh+d));c.ri.call(S,b,c.size,c.type,c.ki,c.bi,0)}}},Vk=(a,b)=>{a.ph||(a.ph=a.getContext,a.getContext=function(d,e){e=a.ph(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.hi?a.getContext("webgl2",b):a.getContext("webgl",
b);return c?Uk(c,b):0},Uk=(a,b)=>{var c=D(8);w[c+4>>2]=ya();var d={handle:c,attributes:b,version:b.hi,lh:a};a.canvas&&(a.canvas.Ch=d);Hk[c]=d;("undefined"==typeof b.Si||b.Si)&&Wk(d);d.Di=d.lh.getParameter(34921);d.Dh=[];for(a=0;a<d.Di;a++)d.Dh[a]={enabled:!1,Oh:!1,size:0,type:0,ki:0,bi:0,Bh:0,ri:null};d.Gh=[];d.ci=[];d.Gh.length=d.ci.length=22;d.Nh=[];d.Qh=[];d.Nh.length=d.Qh.length=22;d.Mh=[];d.Mh.length=22;for(a=0;21>=a;++a){d.Mh[a]=null;d.Gh[a]=d.ci[a]=0;d.Nh[a]=[];d.Qh[a]=[];b=d.Nh[a];var e=d.Qh[a];
b.length=e.length=64;for(var f=0;64>f;++f)b[f]=e[f]=null}return c},Xk=a=>{L=Hk[a];h.th=S=L?.lh},Wk=a=>{a||=L;if(!a.Wi){a.Wi=!0;var b=a.lh;wk(b);xk(b);yk(b);b.qj=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.yj=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.oh=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.oh)b.oh=b.getExtension("EXT_disjoint_timer_query");b.Aj=b.getExtension("WEBGL_multi_draw");zk(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},Yk={},T,L,Sk;function Qb(a,b,c,d){if(m)return G(16,0,1,a,b,c,d);if(62E3!=a)return M=12296,0;for(a=1;;){b=v[d>>2];if(12440==b)a=v[d+4>>2];else if(12344==b)break;else return M=12292,0;d+=8}if(2>a||3<a)return M=12293,0;N.hi=a-1;N.zj=0;vk=Vk(h.canvas,N);if(0!=vk)return M=12288,Xk(vk),h.gj=!0,dk.forEach(function(e){e()}),Xk(null),62004;M=12297;return 0}
function Rb(a,b,c,d){if(m)return G(17,0,1,a,b,c,d);if(62E3!=a)return M=12296,0;if(62002!=b)return M=12293,0;M=12288;return 62006}function Sb(a,b){if(m)return G(18,0,1,a,b);if(62E3!=a)return M=12296,0;if(62004!=b)return M=12294,0;a=vk;L===Hk[a]&&(L=null);if("object"==typeof Zk)for(var c=Hk[a].lh.canvas,d=0;d<$k.length;++d)$k[d].target!=c||al(d--);Hk[a]&&Hk[a].lh.canvas&&(Hk[a].lh.canvas.Ch=void 0);bl(Hk[a].handle);Hk[a]=null;M=12288;rk==b&&(rk=0);return 1}
function Tb(a,b){if(m)return G(19,0,1,a,b);if(62E3!=a)return M=12296,0;if(62006!=b)return M=12301,1;sk==b&&(sk=0);tk==b&&(tk=0);M=12288;return 1}
function Ub(a,b,c,d){if(m)return G(20,0,1,a,b,c,d);if(62E3!=a)return M=12296,0;if(62002!=b)return M=12293,0;if(!d)return M=12300,0;M=12288;switch(c){case 12320:return v[d>>2]=N.alpha?32:24,1;case 12321:return v[d>>2]=N.alpha?8:0,1;case 12322:return v[d>>2]=8,1;case 12323:return v[d>>2]=8,1;case 12324:return v[d>>2]=8,1;case 12325:return v[d>>2]=N.depth?24:0,1;case 12326:return v[d>>2]=N.stencil?8:0,1;case 12327:return v[d>>2]=12344,1;case 12328:return v[d>>2]=62002,1;case 12329:return v[d>>2]=0,1;
case 12330:return v[d>>2]=4096,1;case 12331:return v[d>>2]=16777216,1;case 12332:return v[d>>2]=4096,1;case 12333:return v[d>>2]=0,1;case 12334:return v[d>>2]=0,1;case 12335:return v[d>>2]=12344,1;case 12337:return v[d>>2]=N.antialias?4:0,1;case 12338:return v[d>>2]=N.antialias?1:0,1;case 12339:return v[d>>2]=4,1;case 12340:return v[d>>2]=12344,1;case 12341:case 12342:case 12343:return v[d>>2]=-1,1;case 12345:case 12346:return v[d>>2]=0,1;case 12347:return v[d>>2]=0,1;case 12348:return v[d>>2]=1;
case 12349:case 12350:return v[d>>2]=0,1;case 12351:return v[d>>2]=12430,1;case 12352:return v[d>>2]=4,1;case 12354:return v[d>>2]=0,1;default:return M=12292,0}}function Vb(a){if(m)return G(21,0,1,a);M=12288;return 0!=a&&1!=a?0:62E3}function Wb(){return m?G(22,0,1):M}function Xb(a,b,c){if(m)return G(23,0,1,a,b,c);if(62E3!=a)return M=12296,0;b&&(v[b>>2]=1);c&&(v[c>>2]=4);qk=!0;M=12288;return 1}
function Yb(a,b,c,d){if(m)return G(24,0,1,a,b,c,d);if(62E3!=a)return M=12296,0;if(0!=d&&62004!=d)return M=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return M=12301,0;Xk(d?vk:null);rk=d;tk=b;sk=c;M=12288;return 1}var cl=a=>{var b=Pi(a)+1,c=D(b);c&&E(a,u,c,b);return c};
function Zb(a,b){if(m)return G(25,0,1,a,b);if(62E3!=a)return M=12296,0;M=12288;if(uk[b])return uk[b];switch(b){case 12371:a=cl("Emscripten");break;case 12372:a=cl("1.4 Emscripten EGL");break;case 12373:a=cl("");break;case 12429:a=cl("OpenGL_ES");break;default:return M=12300,0}return uk[b]=a}function $b(a,b){if(m)return G(26,0,1,a,b);if(qk)if(h.th)if(h.th.isContextLost())M=12302;else return M=12288,1;else M=12290;else M=12289;return 0}
function ac(a,b){if(m)return G(27,0,1,a,b);if(62E3!=a)return M=12296,0;0==b?Rj(0,0):Rj(1,b);M=12288;return 1}function cc(a){if(m)return G(28,0,1,a);if(62E3!=a)return M=12296,0;tk=sk=rk=0;qk=!1;M=12288;return 1}function dc(){if(m)return G(29,0,1);M=12288;return 1}function ec(a){if(m)return G(30,0,1,a);M=12288;return 1}
var dl=[],el=(a,b)=>{dl.length=0;for(var c;c=u[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;dl.push(112==c?w[b>>2]:105==c?v[b>>2]:y[b>>3]);b+=d?8:4}return dl},fc=(a,b,c)=>{b=el(b,c);return ci[a](...b)},fl=(a,b,c)=>{b=el(b,c);return m?G(0,a,1,...b):ci[a](...b)},gc=(a,b,c)=>fl(a,b,c),hc=(a,b,c)=>fl(a,b,c),ic=()=>{Zj();Kj=null},jc=()=>{},kc=()=>Date.now(),gl=0,hl=[];
function il(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var k in f)if(f[k]!=g[k])return!1;return!0}for(var e of hl)if(e.oi==a&&d(e.vi,c))return;hl.push({oi:a,Ii:b,vi:c});hl.sort((f,g)=>f.Ii<g.Ii)}function jl(a){hl=hl.filter(b=>b.oi!=a)}function kl(){return navigator.userActivation?navigator.userActivation.isActive:gl&&ll.Sh}function ml(){if(kl()){var a=hl;hl=[];for(var b of a)b.oi(...b.vi)}}var $k=[];
function al(a){var b=$k[a];b.target.removeEventListener(b.kh,b.zi,b.mh);$k.splice(a,1)}function nl(a){if(!a.target)return-4;if(a.nh)a.zi=function(c){++gl;ll=a;ml();a.qh(c);ml();--gl},a.target.addEventListener(a.kh,a.zi,a.mh),$k.push(a);else for(var b=0;b<$k.length;++b)$k[b].target==a.target&&$k[b].kh==a.kh&&al(b--);return 0}function ol(a){switch(a){case 1:return 0;case 2:return wi;default:return a}}function pl(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
function ql(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var Zk={},ll,rl,sl,tl,ul,vl,wl,xl,yl,zl,Al,Bl,Cl,Dl={},El=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],U=a=>{a=2<a?a?z(u,a):"":a;return El[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},Fl=(a,b,c)=>{a=U(a);if(!a||a.yi)return-4;v[b>>2]=a.width;v[c>>2]=a.height;return 0};function Gl(a,b,c){return m?G(32,0,1,a,b,c):Fl(a,b,c)}
var Hl=a=>{var b=Pi(a)+1,c=li(b);E(a,u,c,b);return c},Il=a=>{var b=ki(),c=li(8),d=c+4;a=Hl(a.id);U(a)?Fl(a,c,d):Gl(a,c,d);c=[v[c>>2],v[d>>2]];ni(b);return c},Jl=(a,b,c)=>{a=U(a);if(!a||a.yi)return-4;var d=!1;a.Ch?.lh&&(d=a.Ch.lh.getParameter(2978),d=0===d[0]&&0===d[1]&&d[2]===a.width&&d[3]===a.height);a.width=b;a.height=c;d&&a.Ch.lh.viewport(0,0,b,c);return 0};function Kl(a,b,c){return m?G(33,0,1,a,b,c):Jl(a,b,c)}
var th=(a,b,c)=>U(a)?Jl(a,b,c):Kl(a,b,c),Ll=(a,b,c)=>{if(a.yi){var d=ki();a=Hl(a.id);th(a,b,c);ni(d)}else a.width=b,a.height=c},Ml=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Ll(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=k,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=
t,a.style.paddingTop=B,a.style.paddingBottom=J,a.style.marginLeft=O,a.style.marginRight=da,a.style.marginTop=ra,a.style.marginBottom=sa,document.body.style.margin=bc,document.documentElement.style.overflow=pb,document.body.scroll=Im,a.style.Eh=Jm,a.Ch&&a.Ch.lh.viewport(0,0,d,e),Dl.Kh&&(Dl.Th?V(Dl.Th,Dl.Kh,37,0,Dl.Uh):W(Dl.Kh,37,0,Dl.Uh)))}var c=Il(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,k=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,t=a.style.paddingRight,
B=a.style.paddingTop,J=a.style.paddingBottom,O=a.style.marginLeft,da=a.style.marginRight,ra=a.style.marginTop,sa=a.style.marginBottom,bc=document.body.style.margin,pb=document.documentElement.style.overflow,Im=document.body.scroll,Jm=a.style.Eh;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},Nl=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Ol=a=>0>El.indexOf(a)?a.getBoundingClientRect():
{left:0,top:0},Pl=(a,b)=>{if(0!=b.ni||0!=b.di){Ml(a);var c=b.cj?innerWidth:screen.width,d=b.cj?innerHeight:screen.height,e=Ol(a),f=e.width;e=e.height;var g=Il(a),k=g[0];g=g[1];3==b.ni?(Nl(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.ni&&(c*g<k*d?(f=g*c/k,Nl(a,(d-f)/2,0),d=f):(f=k*d/g,Nl(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Ti&&(a.style.Eh=
"optimizeSpeed",a.style.Eh="-moz-crisp-edges",a.style.Eh="-o-crisp-edges",a.style.Eh="-webkit-optimize-contrast",a.style.Eh="optimize-contrast",a.style.Eh="crisp-edges",a.style.Eh="pixelated");f=2==b.di?devicePixelRatio:1;0!=b.di&&(c=c*f|0,d=d*f|0,Ll(a,c,d),a.Ch&&a.Ch.lh.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return ql()?-3:-1;Dl=b;b.Kh&&(b.Th?V(b.Th,b.Kh,37,0,b.Uh):W(b.Kh,37,0,
b.Uh));return 0};function lc(){if(m)return G(31,0,1);if(!ql())return-1;jl(Pl);var a=El[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0}var Ql=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0};function mc(){if(m)return G(34,0,1);jl(Ql);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0}
var nc=()=>{F+=1;throw"unwind";};function oc(a){if(m)return G(35,0,1,a);Lb();Th(a)}function pc(){return m?G(36,0,1):"number"==typeof devicePixelRatio&&devicePixelRatio||1}function qc(a,b,c){if(m)return G(37,0,1,a,b,c);a=U(a);if(!a)return-4;a=Ol(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0}
var Rl=(a,b)=>{y[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)y[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)y[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)r[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];r[a+1104]=b.connected;v[a+1108>>2]=b.index;v[a+8>>2]=b.axes.length;v[a+12>>2]=b.buttons.length;E(b.id,u,a+1112,64);E(b.mapping,u,a+1176,64)};
function rc(a,b){if(m)return G(38,0,1,a,b);if(0>a||a>=rl.length)return-5;if(!rl[a])return-7;Rl(b,rl[a]);return 0}function tc(){return m?G(39,0,1):rl.length}function uc(a,b){if(m)return G(40,0,1,a,b);v[a>>2]=screen.width;v[b>>2]=screen.height}
var vc=a=>S.activeTexture(a),wc=(a,b)=>{S.attachShader(P[a],Q[b])},xc=(a,b)=>{S.beginQuery(a,R[b])},yc=(a,b)=>{S.oh.beginQueryEXT(a,R[b])},zc=a=>S.beginTransformFeedback(a),Ac=(a,b,c)=>{S.bindAttribLocation(P[a],b,c?z(u,c):"")},Bc=(a,b)=>{34962==a?S.Lh=b:34963==a&&(S.Ph=b);35051==a?S.fi=b:35052==a&&(S.uh=b);S.bindBuffer(a,Bk[b])},Cc=(a,b,c)=>{S.bindBufferBase(a,b,Bk[c])},Dc=(a,b,c,d,e)=>{S.bindBufferRange(a,b,Bk[c],d,e)},Ec=(a,b)=>{S.bindFramebuffer(a,Dk[b])},Fc=(a,b)=>{S.bindRenderbuffer(a,Ek[b])},
Gc=(a,b)=>{S.bindSampler(a,Ik[b])},Hc=(a,b)=>{S.bindTexture(a,Fk[b])},Ic=(a,b)=>{S.bindTransformFeedback(a,Jk[b])},Jc=a=>{S.bindVertexArray(Gk[a]);a=S.getParameter(34965);S.Ph=a?a.name|0:0},Kc=(a,b,c,d)=>S.blendColor(a,b,c,d),Lc=a=>S.blendEquation(a),Mc=(a,b)=>S.blendEquationSeparate(a,b),Nc=(a,b)=>S.blendFunc(a,b),Oc=(a,b,c,d)=>S.blendFuncSeparate(a,b,c,d),Pc=(a,b,c,d,e,f,g,k,n,p)=>S.blitFramebuffer(a,b,c,d,e,f,g,k,n,p),Qc=(a,b,c,d)=>{2<=L.version?c&&b?S.bufferData(a,u,d,c,b):S.bufferData(a,b,d):
S.bufferData(a,c?u.subarray(c,c+b):b,d)},Rc=(a,b,c,d)=>{2<=L.version?c&&S.bufferSubData(a,b,u,d,c):S.bufferSubData(a,b,u.subarray(d,d+c))},Sc=a=>S.checkFramebufferStatus(a),Tc=a=>S.clear(a),Uc=(a,b,c,d)=>S.clearBufferfi(a,b,c,d),Vc=(a,b,c)=>{S.clearBufferfv(a,b,x,c>>2)},Wc=(a,b,c)=>{S.clearBufferiv(a,b,v,c>>2)},Xc=(a,b,c)=>{S.clearBufferuiv(a,b,w,c>>2)},Yc=(a,b,c,d)=>S.clearColor(a,b,c,d),Zc=a=>S.clearDepth(a),$c=a=>S.clearStencil(a),ad=(a,b,c,d)=>S.clientWaitSync(Kk[a],b,(c>>>0)+4294967296*d),bd=
(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},cd=a=>{S.compileShader(Q[a])},dd=(a,b,c,d,e,f,g,k)=>{2<=L.version?S.uh||!g?S.compressedTexImage2D(a,b,c,d,e,f,g,k):S.compressedTexImage2D(a,b,c,d,e,f,u,k,g):S.compressedTexImage2D(a,b,c,d,e,f,k?u.subarray(k,k+g):null)},ed=(a,b,c,d,e,f,g,k,n)=>{S.uh?S.compressedTexImage3D(a,b,c,d,e,f,g,k,n):S.compressedTexImage3D(a,b,c,d,e,f,g,u,n,k)},fd=(a,b,c,d,e,f,g,k,n)=>{2<=L.version?S.uh||!k?S.compressedTexSubImage2D(a,b,c,d,e,f,g,k,n):S.compressedTexSubImage2D(a,b,c,
d,e,f,g,u,n,k):S.compressedTexSubImage2D(a,b,c,d,e,f,g,n?u.subarray(n,n+k):null)},gd=(a,b,c,d,e,f,g,k,n,p,t)=>{S.uh?S.compressedTexSubImage3D(a,b,c,d,e,f,g,k,n,p,t):S.compressedTexSubImage3D(a,b,c,d,e,f,g,k,n,u,t,p)},hd=(a,b,c,d,e)=>S.copyBufferSubData(a,b,c,d,e),jd=(a,b,c,d,e,f,g,k)=>S.copyTexImage2D(a,b,c,d,e,f,g,k),kd=(a,b,c,d,e,f,g,k)=>S.copyTexSubImage2D(a,b,c,d,e,f,g,k),ld=(a,b,c,d,e,f,g,k,n)=>S.copyTexSubImage3D(a,b,c,d,e,f,g,k,n),md=()=>{var a=Qk(P),b=S.createProgram();b.name=a;b.Zh=b.Xh=
b.Yh=0;b.pi=1;P[a]=b;return a},nd=a=>{var b=Qk(Q);Q[b]=S.createShader(a);return b},od=a=>S.cullFace(a),pd=(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Bk[d];e&&(S.deleteBuffer(e),e.name=0,Bk[d]=null,d==S.Lh&&(S.Lh=0),d==S.Ph&&(S.Ph=0),d==S.fi&&(S.fi=0),d==S.uh&&(S.uh=0))}},qd=(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=Dk[d];e&&(S.deleteFramebuffer(e),e.name=0,Dk[d]=null)}},rd=a=>{if(a){var b=P[a];b?(S.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},sd=(a,b)=>{for(var c=0;c<a;c++){var d=
v[b+4*c>>2],e=R[d];e&&(S.deleteQuery(e),R[d]=null)}},td=(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=R[d];e&&(S.oh.deleteQueryEXT(e),R[d]=null)}},ud=(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Ek[d];e&&(S.deleteRenderbuffer(e),e.name=0,Ek[d]=null)}},vd=(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Ik[d];e&&(S.deleteSampler(e),e.name=0,Ik[d]=null)}},wd=a=>{if(a){var b=Q[a];b?(S.deleteShader(b),Q[a]=null):T||=1281}},xd=a=>{if(a){var b=Kk[a];b?(S.deleteSync(b),b.name=0,Kk[a]=null):T||=1281}},
yd=(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Fk[d];e&&(S.deleteTexture(e),e.name=0,Fk[d]=null)}},zd=(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Jk[d];e&&(S.deleteTransformFeedback(e),e.name=0,Jk[d]=null)}},Ad=(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];S.deleteVertexArray(Gk[d]);Gk[d]=null}},Bd=a=>S.depthFunc(a),Cd=a=>{S.depthMask(!!a)},Dd=(a,b)=>S.depthRange(a,b),Ed=(a,b)=>{S.detachShader(P[a],Q[b])},Fd=a=>S.disable(a),Gd=a=>{L.Dh[a].enabled=!1;S.disableVertexAttribArray(a)},Hd=(a,
b,c)=>{Tk(b+c);S.drawArrays(a,b,c);Sk&&S.bindBuffer(34962,Bk[S.Lh])},Id=(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},Sl=[],Jd=(a,b)=>{for(var c=Sl[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];S.drawBuffers(c)},Kd=(a,b,c,d)=>{if(!S.Ph){var e=1*Lk[c-5120]*b;var f=32-Math.clz32(0===e?0:e-1);var g=L.Mh[f];g?f=g:(g=S.getParameter(34965),L.Mh[f]=S.createBuffer(),S.bindBuffer(34963,L.Mh[f]),S.bufferData(34963,1<<f,35048),S.bindBuffer(34963,g),f=L.Mh[f]);S.bindBuffer(34963,f);S.bufferSubData(34963,0,u.subarray(d,d+e));
d=0}Tk(b);S.drawElements(a,b,c,d);Sk&&S.bindBuffer(34962,Bk[S.Lh]);S.Ph||S.bindBuffer(34963,null)},Ld=(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},Md=(a,b,c,d,e,f)=>{Kd(a,d,e,f)},Nd=a=>S.enable(a),Od=a=>{L.Dh[a].enabled=!0;S.enableVertexAttribArray(a)},Pd=a=>S.endQuery(a),Qd=a=>{S.oh.endQueryEXT(a)},Rd=()=>S.endTransformFeedback(),Sd=(a,b)=>(a=S.fenceSync(a,b))?(b=Qk(Kk),a.name=b,Kk[b]=a,b):0,Td=()=>S.finish(),Ud=()=>S.flush(),Tl=a=>{switch(a){case 34962:a=34964;break;case 34963:a=34965;break;
case 35051:a=35053;break;case 35052:a=35055;break;case 35982:a=35983;break;case 36662:a=36662;break;case 36663:a=36663;break;case 35345:a=35368}return(a=S.getParameter(a))?a.name|0:0},Ul=a=>{switch(a){case 34962:case 34963:case 36662:case 36663:case 35051:case 35052:case 35882:case 35982:case 35345:return!0;default:return!1}},Vd=(a,b,c)=>{if(Ul(a)){var d=Ck[Tl(a)];d?d.si&16?0>b||0>c||b+c>d.length?(T||=1281,q("invalid range in glFlushMappedBufferRange")):S.bufferSubData(a,d.offset,u.subarray(d.yh+
b,d.yh+b+c)):(T||=1282,q("buffer was not mapped with GL_MAP_FLUSH_EXPLICIT_BIT in glFlushMappedBufferRange")):(T||=1282,q("buffer was never mapped in glFlushMappedBufferRange"))}else T||=1280,q("GL_INVALID_ENUM in glFlushMappedBufferRange")},Wd=(a,b,c,d)=>{S.framebufferRenderbuffer(a,b,c,Ek[d])},Xd=(a,b,c,d,e)=>{S.framebufferTexture2D(a,b,c,Fk[d],e)},Yd=(a,b,c,d,e)=>{S.framebufferTextureLayer(a,b,Fk[c],d,e)},Zd=a=>S.frontFace(a),$d=(a,b)=>{Rk(a,b,"createBuffer",Bk)},ae=(a,b)=>{Rk(a,b,"createFramebuffer",
Dk)},be=(a,b)=>{Rk(a,b,"createQuery",R)},ce=(a,b)=>{for(var c=0;c<a;c++){var d=S.oh.createQueryEXT();if(!d){for(T||=1282;c<a;)v[b+4*c++>>2]=0;break}var e=Qk(R);d.name=e;R[e]=d;v[b+4*c>>2]=e}},de=(a,b)=>{Rk(a,b,"createRenderbuffer",Ek)},ee=(a,b)=>{Rk(a,b,"createSampler",Ik)},fe=(a,b)=>{Rk(a,b,"createTexture",Fk)},ge=(a,b)=>{Rk(a,b,"createTransformFeedback",Jk)},he=(a,b)=>{Rk(a,b,"createVertexArray",Gk)},ie=a=>S.generateMipmap(a),Vl=(a,b,c,d,e,f,g,k)=>{b=P[b];if(a=S[a](b,c))d=k&&E(a.name,u,k,d),e&&
(v[e>>2]=d),f&&(v[f>>2]=a.size),g&&(v[g>>2]=a.type)},je=(a,b,c,d,e,f,g)=>{Vl("getActiveAttrib",a,b,c,d,e,f,g)},ke=(a,b,c,d,e,f,g)=>{Vl("getActiveUniform",a,b,c,d,e,f,g)},le=(a,b,c,d,e)=>{a=P[a];if(a=S.getActiveUniformBlockName(a,b))e&&0<c?(c=E(a,u,e,c),d&&(v[d>>2]=c)):d&&(v[d>>2]=0)},me=(a,b,c,d)=>{if(d)if(a=P[a],35393==c)v[d>>2]=S.getActiveUniformBlockName(a,b).length+1;else{if(a=S.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)v[d+4*c>>2]=a[c];else v[d>>2]=a}else T||=
1281},ne=(a,b,c,d,e)=>{if(e)if(0<b&&0==c)T||=1281;else{a=P[a];for(var f=[],g=0;g<b;g++)f.push(v[c+4*g>>2]);if(a=S.getActiveUniforms(a,f,d))for(b=a.length,g=0;g<b;g++)v[e+4*g>>2]=a[g]}else T||=1281},oe=(a,b,c,d)=>{a=S.getAttachedShaders(P[a]);var e=a.length;e>b&&(e=b);v[c>>2]=e;for(b=0;b<e;++b)v[d+4*b>>2]=Q.indexOf(a[b])},pe=(a,b)=>S.getAttribLocation(P[a],b?z(u,b):""),Wl=(a,b)=>{w[a>>2]=b;w[a+4>>2]=(b-w[a>>2])/4294967296};function Xl(){var a=zk(S);return a=a.concat(a.map(b=>"GL_"+b))}
var Yl=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(T||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=S.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>L.version){T||=1282;return}d=Xl().length;break;case 33307:case 33308:if(2>L.version){T||=1280;return}d=33307==a?3:0}if(void 0===d)switch(e=S.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=
0;break;default:T||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:v[b+4*a>>2]=e[a];break;case 2:x[b+4*a>>2]=e[a];break;case 4:r[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){T||=1280;q(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:T||=1280;q(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:Wl(b,d);break;case 0:v[b>>2]=d;break;case 2:x[b>>2]=d;break;case 4:r[b]=d?1:0}}else T||=1281},qe=(a,b)=>Yl(a,b,4),re=(a,b,c)=>{c?Wl(c,S.getBufferParameter(a,b)):T||=1281},se=(a,b,c)=>{c?v[c>>2]=S.getBufferParameter(a,b):T||=1281},te=(a,b,c)=>{if(35005==b){b=0;if(a=Ck[Tl(a)])b=a.yh;v[c>>2]=b}else T||=1280,q("GL_INVALID_ENUM in glGetBufferPointerv")},ue=()=>{var a=S.getError()||T;T=0;return a},ve=(a,b)=>Yl(a,b,2),we=(a,b)=>S.getFragDataLocation(P[a],b?z(u,b):""),xe=(a,b,c,d)=>
{a=S.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;v[d>>2]=a},Zl=(a,b,c,d)=>{if(c){b=S.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:T||=1280;return}else if(b instanceof WebGLBuffer)a=b.name|0;else{T||=1280;return}break;default:T||=1280;return}switch(d){case 1:Wl(c,a);break;case 0:v[c>>2]=a;break;case 2:x[c>>
2]=a;break;case 4:r[c]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else T||=1281},ye=(a,b,c)=>Zl(a,b,c,1),ze=(a,b)=>{Yl(a,b,1)},Ae=(a,b,c)=>Zl(a,b,c,0),Be=(a,b)=>Yl(a,b,0),Ce=(a,b,c,d,e)=>{if(0>d)T||=1281;else if(e){if(a=S.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)v[e+4*b>>2]=a[b]}else T||=1281},De=()=>{T||=1282},Ee=(a,b,c,d)=>{a=S.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,u,d,b):0;c&&(v[c>>2]=b)},Fe=
(a,b,c)=>{if(c)if(a>=Ak)T||=1281;else if(a=P[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.Zh)for(b=0;b<S.getProgramParameter(a,35718);++b)a.Zh=Math.max(a.Zh,S.getActiveUniform(a,b).name.length+1);v[c>>2]=a.Zh}else if(35722==b){if(!a.Xh)for(b=0;b<S.getProgramParameter(a,35721);++b)a.Xh=Math.max(a.Xh,S.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.Xh}else if(35381==b){if(!a.Yh)for(b=0;b<S.getProgramParameter(a,35382);++b)a.Yh=Math.max(a.Yh,
S.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Yh}else v[c>>2]=S.getProgramParameter(a,b);else T||=1281},Ge=(a,b,c)=>{if(c){a=R[a];b=2>L.version?S.oh.getQueryObjectEXT(a,b):S.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Wl(c,d)}else T||=1281},He=(a,b,c)=>{if(c){a=S.oh.getQueryObjectEXT(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T||=1281},Ie=(a,b,c)=>{if(c){a=S.getQueryParameter(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T||=1281},Je=(a,b,c)=>
{c?v[c>>2]=S.getQuery(a,b):T||=1281},Ke=(a,b,c)=>{c?v[c>>2]=S.oh.getQueryEXT(a,b):T||=1281},Le=(a,b,c)=>{c?v[c>>2]=S.getRenderbufferParameter(a,b):T||=1281},Me=(a,b,c)=>{c?x[c>>2]=S.getSamplerParameter(Ik[a],b):T||=1281},Ne=(a,b,c)=>{c?v[c>>2]=S.getSamplerParameter(Ik[a],b):T||=1281},Oe=(a,b,c,d)=>{a=S.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,u,d,b):0;c&&(v[c>>2]=b)},Pe=(a,b,c,d)=>{a=S.getShaderPrecisionFormat(a,b);v[c>>2]=a.rangeMin;v[c+4>>2]=a.rangeMax;v[d>>2]=a.precision},
Qe=(a,b,c,d)=>{if(a=S.getShaderSource(Q[a]))b=0<b&&d?E(a,u,d,b):0,c&&(v[c>>2]=b)},Re=(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(Q[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=S.getShaderParameter(Q[a],b):T||=1281},Se=a=>{var b=Mk[a];if(!b){switch(a){case 7939:b=cl(Xl().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=S.getParameter(a))||(T||=1280);b=b?cl(b):0;break;case 7938:b=S.getParameter(7938);b=2<=
L.version?`OpenGL ES 3.0 (${b})`:`OpenGL ES 2.0 (${b})`;b=cl(b);break;case 35724:b=S.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=cl(b);break;default:T||=1280}Mk[a]=b}return b},Te=(a,b)=>{if(2>L.version)return T||=1282,0;var c=Nk[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Xl().map(cl),c=Nk[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=
1280,0}},Ue=(a,b,c,d,e)=>{0>c?T||=1281:e?(a=S.getSyncParameter(Kk[a],b),null!==a&&(v[e>>2]=a,d&&(v[d>>2]=1))):T||=1281},Ve=(a,b,c)=>{c?x[c>>2]=S.getTexParameter(a,b):T||=1281},We=(a,b,c)=>{c?v[c>>2]=S.getTexParameter(a,b):T||=1281},Xe=(a,b,c,d,e,f,g)=>{a=P[a];if(a=S.getTransformFeedbackVarying(a,b))g&&0<c?(c=E(a.name,u,g,c),d&&(v[d>>2]=c)):d&&(v[d>>2]=0),e&&(v[e>>2]=a.size),f&&(v[f>>2]=a.type)},Ye=(a,b)=>S.getUniformBlockIndex(P[a],b?z(u,b):""),Ze=(a,b,c,d)=>{if(d)if(0<b&&(0==c||0==d))T||=1281;else{a=
P[a];for(var e=[],f=0;f<b;f++)e.push(Ai(v[c+4*f>>2]));if(a=S.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)v[d+4*f>>2]=a[f]}else T||=1281},$l=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),am=a=>{var b=a.Rh,c=a.Ki,d;if(!b)for(a.Rh=b={},a.Ji={},d=0;d<S.getProgramParameter(a,35718);++d){var e=S.getActiveUniform(a,d);var f=e.name;e=e.size;var g=$l(f);g=0<g?f.slice(0,g):f;var k=a.pi;a.pi+=e;c[g]=[e,k];for(f=0;f<e;++f)b[k]=f,a.Ji[k++]=g}},$e=(a,b)=>{b=b?z(u,b):"";if(a=P[a]){am(a);var c=a.Rh,d=0,e=b,f=$l(b);
0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Ki[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else T||=1281;return-1},X=a=>{var b=S.Ni;if(b){var c=b.Rh[a];"number"==typeof c&&(b.Rh[a]=c=S.getUniformLocation(b,b.Ji[a]+(0<c?`[${c}]`:"")));return c}T||=1282},bm=(a,b,c,d)=>{if(c)if(a=P[a],am(a),a=S.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:x[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];
break;case 2:x[c+4*b>>2]=a[b]}else T||=1281},af=(a,b,c)=>{bm(a,b,c,2)},bf=(a,b,c)=>{bm(a,b,c,0)},cf=(a,b,c)=>bm(a,b,c,0),cm=(a,b,c,d)=>{if(c)if(L.Dh[a].enabled&&q("glGetVertexAttrib*v on client-side array: not supported, bad data returned"),a=S.getVertexAttrib(a,b),34975==b)v[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:x[c>>2]=a;break;case 5:v[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:x[c+
4*b>>2]=a[b];break;case 5:v[c+4*b>>2]=Math.fround(a[b])}else T||=1281},df=(a,b,c)=>{cm(a,b,c,0)},ef=(a,b,c)=>{c?(L.Dh[a].enabled&&q("glGetVertexAttribPointer on client-side array: not supported, bad data returned"),v[c>>2]=S.getVertexAttribOffset(a,b)):T||=1281},ff=(a,b,c)=>{cm(a,b,c,2)},gf=(a,b,c)=>{cm(a,b,c,5)},hf=(a,b)=>S.hint(a,b),jf=(a,b,c)=>{for(var d=Sl[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];S.invalidateFramebuffer(a,d)},kf=(a,b,c,d,e,f,g)=>{for(var k=Sl[b],n=0;n<b;n++)k[n]=v[c+4*n>>2];S.invalidateSubFramebuffer(a,
k,d,e,f,g)},lf=a=>(a=Bk[a])?S.isBuffer(a):0,mf=a=>S.isEnabled(a),nf=a=>(a=Dk[a])?S.isFramebuffer(a):0,of=a=>(a=P[a])?S.isProgram(a):0,pf=a=>(a=R[a])?S.isQuery(a):0,qf=a=>(a=R[a])?S.oh.isQueryEXT(a):0,rf=a=>(a=Ek[a])?S.isRenderbuffer(a):0,sf=a=>(a=Ik[a])?S.isSampler(a):0,tf=a=>(a=Q[a])?S.isShader(a):0,uf=a=>S.isSync(Kk[a]),vf=a=>(a=Fk[a])?S.isTexture(a):0,wf=a=>S.isTransformFeedback(Jk[a]),xf=a=>(a=Gk[a])?S.isVertexArray(a):0,yf=a=>S.lineWidth(a),zf=a=>{a=P[a];S.linkProgram(a);a.Rh=0;a.Ki={}},Af=(a,
b,c,d)=>{if(0!=(d&33))return q("glMapBufferRange access does not support MAP_READ or MAP_UNSYNCHRONIZED"),0;if(0==(d&2))return q("glMapBufferRange access must include MAP_WRITE"),0;if(0==(d&12))return q("glMapBufferRange access must include INVALIDATE_BUFFER or INVALIDATE_RANGE"),0;if(!Ul(a))return T||=1280,q("GL_INVALID_ENUM in glMapBufferRange"),0;var e=D(c);a=Tl(a);if(!e)return 0;Ck[a]||(Ck[a]={});a=Ck[a];a.offset=b;a.length=c;a.yh=e;a.si=d;return e},Bf=()=>S.pauseTransformFeedback(),Cf=(a,b)=>
{3317==a?Ok=b:3314==a&&(Pk=b);S.pixelStorei(a,b)},Df=(a,b)=>S.polygonOffset(a,b),Ef=()=>{T||=1280},Ff=()=>{T||=1280},Gf=(a,b)=>{S.oh.queryCounterEXT(R[a],b)},Hf=a=>S.readBuffer(a),dm=a=>{a-=5120;return 0==a?r:1==a?u:2==a?Qa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?w:Ra},em=(a,b,c,d,e)=>{a=dm(a);b=d*((Pk||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Ok-1&-Ok);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},
If=(a,b,c,d,e,f,g)=>{if(2<=L.version)if(S.fi)S.readPixels(a,b,c,d,e,f,g);else{var k=dm(f);g>>>=31-Math.clz32(k.BYTES_PER_ELEMENT);S.readPixels(a,b,c,d,e,f,k,g)}else(k=em(f,e,c,d,g))?S.readPixels(a,b,c,d,e,f,k):T||=1280},Jf=()=>{},Kf=(a,b,c,d)=>S.renderbufferStorage(a,b,c,d),Lf=(a,b,c,d,e)=>S.renderbufferStorageMultisample(a,b,c,d,e),Mf=()=>S.resumeTransformFeedback(),Nf=(a,b)=>{S.sampleCoverage(a,!!b)},Of=(a,b,c)=>{S.samplerParameterf(Ik[a],b,c)},Pf=(a,b,c)=>{S.samplerParameterf(Ik[a],b,x[c>>2])},
Qf=(a,b,c)=>{S.samplerParameteri(Ik[a],b,c)},Rf=(a,b,c)=>{S.samplerParameteri(Ik[a],b,v[c>>2])},Sf=(a,b,c,d)=>S.scissor(a,b,c,d),Tf=()=>{T||=1280},Uf=(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=Ai(w[c+4*f>>2],d?w[d+4*f>>2]:void 0);S.shaderSource(Q[a],e)},Vf=(a,b,c)=>S.stencilFunc(a,b,c),Wf=(a,b,c,d)=>S.stencilFuncSeparate(a,b,c,d),Xf=a=>S.stencilMask(a),Yf=(a,b)=>S.stencilMaskSeparate(a,b),Zf=(a,b,c)=>S.stencilOp(a,b,c),$f=(a,b,c,d)=>S.stencilOpSeparate(a,b,c,d),ag=(a,b,c,d,e,f,g,k,n)=>{if(2<=L.version){if(S.uh){S.texImage2D(a,
b,c,d,e,f,g,k,n);return}if(n){var p=dm(k);n>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);S.texImage2D(a,b,c,d,e,f,g,k,p,n);return}}p=n?em(k,g,d,e,n):null;S.texImage2D(a,b,c,d,e,f,g,k,p)},bg=(a,b,c,d,e,f,g,k,n,p)=>{if(S.uh)S.texImage3D(a,b,c,d,e,f,g,k,n,p);else if(p){var t=dm(n);S.texImage3D(a,b,c,d,e,f,g,k,n,t,p>>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else S.texImage3D(a,b,c,d,e,f,g,k,n,null)},cg=(a,b,c)=>S.texParameterf(a,b,c),dg=(a,b,c)=>{S.texParameterf(a,b,x[c>>2])},eg=(a,b,c)=>S.texParameteri(a,b,c),
fg=(a,b,c)=>{S.texParameteri(a,b,v[c>>2])},gg=(a,b,c,d,e)=>S.texStorage2D(a,b,c,d,e),hg=(a,b,c,d,e,f)=>S.texStorage3D(a,b,c,d,e,f),ig=(a,b,c,d,e,f,g,k,n)=>{if(2<=L.version){if(S.uh){S.texSubImage2D(a,b,c,d,e,f,g,k,n);return}if(n){var p=dm(k);S.texSubImage2D(a,b,c,d,e,f,g,k,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}n=n?em(k,g,e,f,n):null;S.texSubImage2D(a,b,c,d,e,f,g,k,n)},jg=(a,b,c,d,e,f,g,k,n,p,t)=>{if(S.uh)S.texSubImage3D(a,b,c,d,e,f,g,k,n,p,t);else if(t){var B=dm(p);S.texSubImage3D(a,b,
c,d,e,f,g,k,n,p,B,t>>>31-Math.clz32(B.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,b,c,d,e,f,g,k,n,p,null)},kg=(a,b,c,d)=>{a=P[a];for(var e=[],f=0;f<b;f++)e.push(Ai(v[c+4*f>>2]));S.transformFeedbackVaryings(a,e,d)},lg=(a,b)=>{S.uniform1f(X(a),b)},fm=[],mg=(a,b,c)=>{if(2<=L.version)b&&S.uniform1fv(X(a),x,c>>2,b);else{if(288>=b)for(var d=fm[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);S.uniform1fv(X(a),d)}},ng=(a,b)=>{S.uniform1i(X(a),b)},gm=[],og=(a,b,c)=>{if(2<=L.version)b&&S.uniform1iv(X(a),
v,c>>2,b);else{if(288>=b)for(var d=gm[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);S.uniform1iv(X(a),d)}},pg=(a,b)=>{S.uniform1ui(X(a),b)},qg=(a,b,c)=>{b&&S.uniform1uiv(X(a),w,c>>2,b)},rg=(a,b,c)=>{S.uniform2f(X(a),b,c)},sg=(a,b,c)=>{if(2<=L.version)b&&S.uniform2fv(X(a),x,c>>2,2*b);else{if(144>=b)for(var d=fm[2*b],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);S.uniform2fv(X(a),d)}},tg=(a,b,c)=>{S.uniform2i(X(a),b,c)},ug=(a,b,c)=>{if(2<=
L.version)b&&S.uniform2iv(X(a),v,c>>2,2*b);else{if(144>=b)for(var d=gm[2*b],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2];else d=v.subarray(c>>2,c+8*b>>2);S.uniform2iv(X(a),d)}},vg=(a,b,c)=>{S.uniform2ui(X(a),b,c)},wg=(a,b,c)=>{b&&S.uniform2uiv(X(a),w,c>>2,2*b)},xg=(a,b,c,d)=>{S.uniform3f(X(a),b,c,d)},yg=(a,b,c)=>{if(2<=L.version)b&&S.uniform3fv(X(a),x,c>>2,3*b);else{if(96>=b)for(var d=fm[3*b],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>
2,c+12*b>>2);S.uniform3fv(X(a),d)}},zg=(a,b,c,d)=>{S.uniform3i(X(a),b,c,d)},Ag=(a,b,c)=>{if(2<=L.version)b&&S.uniform3iv(X(a),v,c>>2,3*b);else{if(96>=b)for(var d=gm[3*b],e=0;e<3*b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2];else d=v.subarray(c>>2,c+12*b>>2);S.uniform3iv(X(a),d)}},Bg=(a,b,c,d)=>{S.uniform3ui(X(a),b,c,d)},Cg=(a,b,c)=>{b&&S.uniform3uiv(X(a),w,c>>2,3*b)},Dg=(a,b,c,d,e)=>{S.uniform4f(X(a),b,c,d,e)},Eg=(a,b,c)=>{if(2<=L.version)b&&S.uniform4fv(X(a),x,c>>2,4*b);else{if(72>=
b){var d=fm[4*b],e=x;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);S.uniform4fv(X(a),d)}},Fg=(a,b,c,d,e)=>{S.uniform4i(X(a),b,c,d,e)},Gg=(a,b,c)=>{if(2<=L.version)b&&S.uniform4iv(X(a),v,c>>2,4*b);else{if(72>=b)for(var d=gm[4*b],e=0;e<4*b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2];else d=v.subarray(c>>2,c+16*b>>2);S.uniform4iv(X(a),d)}},Hg=(a,b,c,d,e)=>{S.uniform4ui(X(a),
b,c,d,e)},Ig=(a,b,c)=>{b&&S.uniform4uiv(X(a),w,c>>2,4*b)},Jg=(a,b,c)=>{a=P[a];S.uniformBlockBinding(a,b,c)},Kg=(a,b,c,d)=>{if(2<=L.version)b&&S.uniformMatrix2fv(X(a),!!c,x,d>>2,4*b);else{if(72>=b)for(var e=fm[4*b],f=0;f<4*b;f+=4)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2];else e=x.subarray(d>>2,d+16*b>>2);S.uniformMatrix2fv(X(a),!!c,e)}},Lg=(a,b,c,d)=>{b&&S.uniformMatrix2x3fv(X(a),!!c,x,d>>2,6*b)},Mg=(a,b,c,d)=>{b&&S.uniformMatrix2x4fv(X(a),!!c,x,d>>2,8*
b)},Ng=(a,b,c,d)=>{if(2<=L.version)b&&S.uniformMatrix3fv(X(a),!!c,x,d>>2,9*b);else{if(32>=b)for(var e=fm[9*b],f=0;f<9*b;f+=9)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2],e[f+4]=x[d+(4*f+16)>>2],e[f+5]=x[d+(4*f+20)>>2],e[f+6]=x[d+(4*f+24)>>2],e[f+7]=x[d+(4*f+28)>>2],e[f+8]=x[d+(4*f+32)>>2];else e=x.subarray(d>>2,d+36*b>>2);S.uniformMatrix3fv(X(a),!!c,e)}},Og=(a,b,c,d)=>{b&&S.uniformMatrix3x2fv(X(a),!!c,x,d>>2,6*b)},Pg=(a,b,c,d)=>{b&&S.uniformMatrix3x4fv(X(a),
!!c,x,d>>2,12*b)},Qg=(a,b,c,d)=>{if(2<=L.version)b&&S.uniformMatrix4fv(X(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=fm[16*b],f=x;d>>=2;for(var g=0;g<16*b;g+=16){var k=d+g;e[g]=f[k];e[g+1]=f[k+1];e[g+2]=f[k+2];e[g+3]=f[k+3];e[g+4]=f[k+4];e[g+5]=f[k+5];e[g+6]=f[k+6];e[g+7]=f[k+7];e[g+8]=f[k+8];e[g+9]=f[k+9];e[g+10]=f[k+10];e[g+11]=f[k+11];e[g+12]=f[k+12];e[g+13]=f[k+13];e[g+14]=f[k+14];e[g+15]=f[k+15]}}else e=x.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(X(a),!!c,e)}},Rg=(a,b,c,d)=>{b&&S.uniformMatrix4x2fv(X(a),
!!c,x,d>>2,8*b)},Sg=(a,b,c,d)=>{b&&S.uniformMatrix4x3fv(X(a),!!c,x,d>>2,12*b)},Tg=a=>{if(!Ul(a))return T||=1280,q("GL_INVALID_ENUM in glUnmapBuffer"),0;var b=Ck[Tl(a)];if(!b||!b.yh)return T||=1282,q("buffer was never mapped in glUnmapBuffer"),0;b.si&16||(2<=L.version?S.bufferSubData(a,b.offset,u,b.yh,b.length):S.bufferSubData(a,b.offset,u.subarray(b.yh,b.yh+b.length)));bl(b.yh);b.yh=0;return 1},Ug=a=>{a=P[a];S.useProgram(a);S.Ni=a},Vg=a=>{S.validateProgram(P[a])},Wg=(a,b)=>S.vertexAttrib1f(a,b),Xg=
(a,b)=>{S.vertexAttrib1f(a,x[b>>2])},Yg=(a,b,c)=>S.vertexAttrib2f(a,b,c),Zg=(a,b)=>{S.vertexAttrib2f(a,x[b>>2],x[b+4>>2])},$g=(a,b,c,d)=>S.vertexAttrib3f(a,b,c,d),ah=(a,b)=>{S.vertexAttrib3f(a,x[b>>2],x[b+4>>2],x[b+8>>2])},bh=(a,b,c,d,e)=>S.vertexAttrib4f(a,b,c,d,e),ch=(a,b)=>{S.vertexAttrib4f(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},dh=(a,b)=>{S.vertexAttribDivisor(a,b)},eh=(a,b,c,d,e)=>S.vertexAttribI4i(a,b,c,d,e),fh=(a,b)=>{S.vertexAttribI4i(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},gh=(a,b,
c,d,e)=>S.vertexAttribI4ui(a,b,c,d,e),hh=(a,b)=>{S.vertexAttribI4ui(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},ih=(a,b,c,d,e)=>{var f=L.Dh[a];S.Lh?(f.Oh=!1,S.vertexAttribIPointer(a,b,c,d,e)):(f.size=b,f.type=c,f.ki=!1,f.bi=d,f.Bh=e,f.Oh=!0,f.ri=function(g,k,n,p,t,B){this.vertexAttribIPointer(g,k,n,t,B)})},jh=(a,b,c,d,e,f)=>{var g=L.Dh[a];S.Lh?(g.Oh=!1,S.vertexAttribPointer(a,b,c,!!d,e,f)):(g.size=b,g.type=c,g.ki=d,g.bi=e,g.Bh=f,g.Oh=!0,g.ri=function(k,n,p,t,B,J){this.vertexAttribPointer(k,n,p,t,B,
J)})},kh=(a,b,c,d)=>S.viewport(a,b,c,d),lh=(a,b,c,d)=>{S.waitSync(Kk[a],b,(c>>>0)+4294967296*d)},mh=()=>1,hm=(a,b)=>{if(!ql())return-1;a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?kl()?Pl(a,b):b.Ri?(il(Pl,1,[a,b]),1):-2:-3:-4};function nh(a,b,c){return m?G(41,0,1,a,b,c):hm(a,{ni:v[c>>2],di:v[c+4>>2],Ti:v[c+8>>2],Ri:b,Th:v[c+20>>2],Kh:v[c+12>>2],Uh:v[c+16>>2]})}function oh(a,b){if(m)return G(42,0,1,a,b);a=U(a);return a?a.requestPointerLock?kl()?Ql(a):b?(il(Ql,2,[a]),1):-2:-1:-4}
var ph=()=>{ib("OOM")};function qh(){if(m)return G(43,0,1);try{if(navigator.getGamepads)return(rl=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1}var im=(a,b)=>{var c={target:U(2),kh:"beforeunload",nh:b,qh:(d=event)=>{var e=W(b,28,0,a);e&&=e?z(u,e):"";if(e)return d.preventDefault(),d.returnValue=e},mh:!0};return nl(c)};function rh(a,b,c){return m?G(44,0,1,a,b,c):"undefined"==typeof onbeforeunload?-1:1!==c?-5:im(a,b)}
var jm=(a,b,c,d,e,f,g)=>{g=ol(g);sl||=D(256);a={target:U(a),kh:f,nh:d,qh:(k=event)=>{var n=pl(k.target),p=k.target.id?k.target.id:"",t=g?D(256):sl;E(n,u,t+0,128);E(p,u,t+128,128);g?V(g,d,e,t,b):W(d,e,t,b)&&k.preventDefault()},mh:c};return nl(a)};function sh(a,b,c,d,e){return m?G(45,0,1,a,b,c,d,e):jm(a,b,c,d,12,"blur",e)}function uh(a,b,c){if(m)return G(46,0,1,a,b,c);a=U(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0}
function vh(a,b,c,d,e){return m?G(47,0,1,a,b,c,d,e):jm(a,b,c,d,13,"focus",e)}
var km=(a,b,c,d,e,f)=>{f=ol(f);ul||=D(276);return nl({target:a,kh:e,nh:d,qh:(g=event)=>{var k=f?D(276):ul,n=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,p=!!n;r[k]=p;r[k+1]=ql();var t=p?n:tl,B=t?.id||"";E(pl(t),u,k+2,128);E(B,u,k+130,128);v[k+260>>2]=t?t.clientWidth:0;v[k+264>>2]=t?t.clientHeight:0;v[k+268>>2]=screen.width;v[k+272>>2]=screen.height;p&&(tl=n);f?V(f,d,19,k,b):W(d,19,k,b)&&g.preventDefault()},mh:c})};
function wh(a,b,c,d,e){if(m)return G(48,0,1,a,b,c,d,e);if(!ql())return-1;a=U(a);if(!a)return-4;km(a,b,c,d,"webkitfullscreenchange",e);return km(a,b,c,d,"fullscreenchange",e)}var lm=(a,b,c,d,e,f)=>{f=ol(f);vl||=D(1240);b={target:U(2),Sh:!0,kh:e,nh:c,qh:(g=event)=>{var k=f?D(1240):vl;Rl(k,g.gamepad);f?V(f,c,d,k,a):W(c,d,k,a)&&g.preventDefault()},mh:b};return nl(b)};function xh(a,b,c,d){return m?G(49,0,1,a,b,c,d):qh()?-1:lm(a,b,c,26,"gamepadconnected",d)}
function yh(a,b,c,d){return m?G(50,0,1,a,b,c,d):qh()?-1:lm(a,b,c,27,"gamepaddisconnected",d)}
var mm=(a,b,c,d,e,f,g)=>{g=ol(g);wl||=D(160);a={target:U(a),kh:f,nh:d,qh:k=>{var n=g?D(160):wl;y[n>>3]=k.timeStamp;var p=n>>2;v[p+2]=k.location;r[n+12]=k.ctrlKey;r[n+13]=k.shiftKey;r[n+14]=k.altKey;r[n+15]=k.metaKey;r[n+16]=k.repeat;v[p+5]=k.charCode;v[p+6]=k.keyCode;v[p+7]=k.which;E(k.key||"",u,n+32,32);E(k.code||"",u,n+64,32);E(k.char||"",u,n+96,32);E(k.locale||"",u,n+128,32);g?V(g,d,e,n,b):W(d,e,n,b)&&k.preventDefault()},mh:c};return nl(a)};
function zh(a,b,c,d,e){return m?G(51,0,1,a,b,c,d,e):mm(a,b,c,d,2,"keydown",e)}function Ah(a,b,c,d,e){return m?G(52,0,1,a,b,c,d,e):mm(a,b,c,d,1,"keypress",e)}function Bh(a,b,c,d,e){return m?G(53,0,1,a,b,c,d,e):mm(a,b,c,d,3,"keyup",e)}
var nm=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;Qa[2*d+14]=b.button;Qa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=Ol(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},om=(a,b,c,d,e,f,g)=>{g=ol(g);xl||=D(64);a=U(a);return nl({target:a,Sh:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,kh:f,nh:d,qh:(k=event)=>{nm(xl,k,a);if(g){var n=D(64);
nm(n,k,a);V(g,d,e,n,b)}else W(d,e,xl,b)&&k.preventDefault()},mh:c})};function Ch(a,b,c,d,e){return m?G(54,0,1,a,b,c,d,e):om(a,b,c,d,5,"mousedown",e)}function Dh(a,b,c,d,e){return m?G(55,0,1,a,b,c,d,e):om(a,b,c,d,33,"mouseenter",e)}function Eh(a,b,c,d,e){return m?G(56,0,1,a,b,c,d,e):om(a,b,c,d,34,"mouseleave",e)}function Fh(a,b,c,d,e){return m?G(57,0,1,a,b,c,d,e):om(a,b,c,d,8,"mousemove",e)}function Gh(a,b,c,d,e){return m?G(58,0,1,a,b,c,d,e):om(a,b,c,d,6,"mouseup",e)}
var pm=(a,b,c,d,e,f)=>{f=ol(f);yl||=D(257);return nl({target:a,kh:e,nh:d,qh:(g=event)=>{var k=f?D(257):yl,n=document.pointerLockElement||document.ph||document.gi||document.ji;r[k]=!!n;var p=n?.id||"";E(pl(n),u,k+1,128);E(p,u,k+129,128);f?V(f,d,20,k,b):W(d,20,k,b)&&g.preventDefault()},mh:c})};
function Hh(a,b,c,d,e){if(m)return G(59,0,1,a,b,c,d,e);if(!document||!document.body||!(document.body.requestPointerLock||document.body.ph||document.body.gi||document.body.ji))return-1;a=U(a);if(!a)return-4;pm(a,b,c,d,"mozpointerlockchange",e);pm(a,b,c,d,"webkitpointerlockchange",e);pm(a,b,c,d,"mspointerlockchange",e);return pm(a,b,c,d,"pointerlockchange",e)}
var qm=(a,b,c,d,e)=>{e=ol(e);zl||=D(36);a=U(a);return nl({target:a,kh:"resize",nh:d,qh:(f=event)=>{if(f.target==a){var g=document.body;if(g){var k=e?D(36):zl;v[k>>2]=0;v[k+4>>2]=g.clientWidth;v[k+8>>2]=g.clientHeight;v[k+12>>2]=innerWidth;v[k+16>>2]=innerHeight;v[k+20>>2]=outerWidth;v[k+24>>2]=outerHeight;v[k+28>>2]=pageXOffset|0;v[k+32>>2]=pageYOffset|0;e?V(e,d,10,k,b):W(d,10,k,b)&&f.preventDefault()}}},mh:c})};function Ih(a,b,c,d,e){return m?G(60,0,1,a,b,c,d,e):qm(a,b,c,d,e)}
var rm=(a,b,c,d,e,f,g)=>{g=ol(g);Al||=D(1552);a=U(a);return nl({target:a,Sh:"touchstart"==f||"touchend"==f,kh:f,nh:d,qh:k=>{var n={},p=k.touches;for(var t of p)t.Ci=t.Hi=0,n[t.identifier]=t;for(var B of k.changedTouches)B.Ci=1,n[B.identifier]=B;for(var J of k.targetTouches)n[J.identifier].Hi=1;p=g?D(1552):Al;y[p>>3]=k.timeStamp;r[p+12]=k.ctrlKey;r[p+13]=k.shiftKey;r[p+14]=k.altKey;r[p+15]=k.metaKey;t=p+16;B=Ol(a);J=0;for(let O of Object.values(n))if(n=t>>2,v[n]=O.identifier,v[n+1]=O.screenX,v[n+2]=
O.screenY,v[n+3]=O.clientX,v[n+4]=O.clientY,v[n+5]=O.pageX,v[n+6]=O.pageY,r[t+28]=O.Ci,r[t+29]=O.Hi,v[n+8]=O.clientX-(B.left|0),v[n+9]=O.clientY-(B.top|0),t+=48,31<++J)break;v[p+8>>2]=J;g?V(g,d,e,p,b):W(d,e,p,b)&&k.preventDefault()},mh:c})};function Jh(a,b,c,d,e){return m?G(61,0,1,a,b,c,d,e):rm(a,b,c,d,25,"touchcancel",e)}function Kh(a,b,c,d,e){return m?G(62,0,1,a,b,c,d,e):rm(a,b,c,d,23,"touchend",e)}function Lh(a,b,c,d,e){return m?G(63,0,1,a,b,c,d,e):rm(a,b,c,d,24,"touchmove",e)}
function Mh(a,b,c,d,e){return m?G(64,0,1,a,b,c,d,e):rm(a,b,c,d,22,"touchstart",e)}var sm=(a,b,c,d)=>{var e=El[1];d=ol(d);Bl||=D(8);return nl({target:e,kh:"visibilitychange",nh:c,qh:(f=event)=>{var g=d?D(8):Bl,k=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);r[g]=document.hidden;v[g+4>>2]=k;d?V(d,c,21,g,a):W(c,21,g,a)&&f.preventDefault()},mh:b})};function Nh(a,b,c,d){return m?G(65,0,1,a,b,c,d):El[1]?sm(a,b,c,d):-4}
var tm=(a,b,c,d,e)=>{e=ol(e);Cl||=D(96);return nl({target:a,Sh:!0,kh:"wheel",nh:d,qh:(f=event)=>{var g=e?D(96):Cl;nm(g,f,a);y[g+64>>3]=f.deltaX;y[g+72>>3]=f.deltaY;y[g+80>>3]=f.deltaZ;v[g+88>>2]=f.deltaMode;e?V(e,d,9,g,b):W(d,9,g,b)&&f.preventDefault()},mh:c})};function Oh(a,b,c,d,e){return m?G(66,0,1,a,b,c,d,e):(a=U(a))?"undefined"!=typeof a.onwheel?tm(a,b,c,d,e):-1:-4}function Ph(a){return m?G(67,0,1,a):document.title=a?z(u,a):""}
var Qh=a=>um(b=>Yj(b,a)),wm={},ym=()=>{if(!xm){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ha||"./this.program"},b;for(b in wm)void 0===wm[b]?delete a[b]:a[b]=wm[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);xm=c}return xm},xm;
function Rh(a,b){if(m)return G(68,0,1,a,b);var c=0;ym().forEach((d,e)=>{var f=b+c;e=w[a+4*e>>2]=f;for(f=0;f<d.length;++f)r[e++]=d.charCodeAt(f);r[e]=0;c+=d.length+1});return 0}function Sh(a,b){if(m)return G(69,0,1,a,b);var c=ym();w[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);w[b>>2]=d;return 0}
function Uh(a){if(m)return G(70,0,1,a);try{var b=qj(a);if(null===b.fd)throw new H(8);b.Hh&&(b.Hh=null);try{b.gh.close&&b.gh.close(b)}catch(c){throw c;}finally{ej[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return c.jh}}
function Vh(a,b,c,d){if(m)return G(71,0,1,a,b,c,d);try{a:{var e=qj(a);a=b;for(var f,g=b=0;g<c;g++){var k=w[a>>2],n=w[a+4>>2];a+=8;var p=e,t=f,B=r;if(0>n||0>t)throw new H(28);if(null===p.fd)throw new H(8);if(1===(p.flags&2097155))throw new H(8);if(16384===(p.node.mode&61440))throw new H(31);if(!p.gh.read)throw new H(28);var J="undefined"!=typeof t;if(!J)t=p.position;else if(!p.seekable)throw new H(70);var O=p.gh.read(p,B,k,n,t);J||(p.position+=O);var da=O;if(0>da){var ra=-1;break a}b+=da;if(da<n)break;
"undefined"!=typeof f&&(f+=da)}ra=b}w[d>>2]=ra;return 0}catch(sa){if("undefined"==typeof K||"ErrnoError"!==sa.name)throw sa;return sa.jh}}
function Wh(a,b,c,d,e){if(m)return G(72,0,1,a,b,c,d,e);b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=qj(a);Aj(f,b,d);C=[f.position>>>0,(A=f.position,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[e>>2]=C[0];v[e+4>>2]=C[1];f.Hh&&0===b&&0===d&&(f.Hh=null);return 0}catch(g){if("undefined"==typeof K||"ErrnoError"!==g.name)throw g;return g.jh}}
function Xh(a,b,c,d){if(m)return G(73,0,1,a,b,c,d);try{a:{var e=qj(a);a=b;for(var f,g=b=0;g<c;g++){var k=w[a>>2],n=w[a+4>>2];a+=8;var p=e,t=k,B=n,J=f,O=r;if(0>B||0>J)throw new H(28);if(null===p.fd)throw new H(8);if(0===(p.flags&2097155))throw new H(8);if(16384===(p.node.mode&61440))throw new H(31);if(!p.gh.write)throw new H(28);p.seekable&&p.flags&1024&&Aj(p,0,2);var da="undefined"!=typeof J;if(!da)J=p.position;else if(!p.seekable)throw new H(70);var ra=p.gh.write(p,O,t,B,J,void 0);da||(p.position+=
ra);var sa=ra;if(0>sa){var bc=-1;break a}b+=sa;"undefined"!=typeof f&&(f+=sa)}bc=b}w[d>>2]=bc;return 0}catch(pb){if("undefined"==typeof K||"ErrnoError"!==pb.name)throw pb;return pb.jh}}var zm=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},$h=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&zm(d,c,()=>{"suspended"===a.state&&a.resume()})})})},ai=(a,b=[])=>{var c="vi".replace(/p/g,"i");(0,h["dynCall_"+c])(a,...b)},Am=a=>{try{a()}catch(b){ib(b)}};
function Bm(){var a=Y,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{Cm.push(c);try{return d(...e)}finally{Oa||(Cm.pop(),Dm&&1===Em&&0===Cm.length&&(Em=0,F+=1,Am(Fm),"undefined"!=typeof Fibers&&Fibers.Gj()))}}:d;return b}var Em=0,Dm=null,Gm=0,Cm=[],Hm={},Km={},Lm=0,Mm=null,Nm=[];function Om(){var a=D(4108),b=a+12;w[a>>2]=b;w[a+4>>2]=b+4096;b=Cm[0];var c=Hm[b];void 0===c&&(c=Lm++,Hm[b]=c,Km[c]=b);v[a+8>>2]=c;return a}function Pm(){var a=Y[Km[v[Dm+8>>2]]];--F;return a()}
function um(a){if(!Oa){if(0===Em){var b=!1,c=!1;a((d=0)=>{if(!Oa&&(Gm=d,b=!0,c)){Em=2;Am(()=>Qm(Dm));"undefined"!=typeof pk&&Kj&&ak();d=!1;try{var e=Pm()}catch(k){e=k,d=!0}var f=!1;if(!Dm){var g=Mm;g&&(Mm=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(Em=1,Dm=Om(),"undefined"!=typeof pk&&Kj&&Zj(),Am(()=>Rm(Dm)))}else 2===Em?(Em=0,Am(Sm),bl(Dm),Dm=null,Nm.forEach(Ej)):ib(`invalid state: ${Em}`);return Gm}}m?oi=!1:si();[44].forEach(a=>{Zi[a]=new H(a);Zi[a].stack="<generic error, no stack>"});
gj=Array(4096);tj(I,"/");vj("/tmp");vj("/home");vj("/home/web_user");(function(){vj("/dev");Si(259,{read:()=>0,write:(d,e,f,g)=>g});wj("/dev/null",259);Ri(1280,Ui);Ri(1536,Vi);wj("/dev/tty",1280);wj("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Mi(a).byteLength);return a[--b]};Za("random",c);Za("urandom",c);vj("/dev/shm");vj("/dev/shm/tmp")})();
(function(){vj("/proc");var a=vj("/proc/self");vj("/proc/self/fd");tj({zh(){var b=Yi(a,"fd",16895,73);b.gg={lookup(c,d){var e=qj(+d);c={parent:null,zh:{Fi:"fake"},gg:{readlink:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();
h.requestFullscreen=function(a,b){function c(){bk=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=kk,ik&&d.requestPointerLock(),bk=!0,jk?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=w[SDL.screen>>2]|8388608),ok(h.canvas),nk()):ok(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),jk?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=
w[SDL.screen>>2]&-8388609),ok(h.canvas),nk()):ok(d));h.onFullScreen?.(bk);h.onFullscreen?.(bk)}ik=a;jk=b;"undefined"==typeof ik&&(ik=!0);"undefined"==typeof jk&&(jk=!1);var d=h.canvas;hk||(hk=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=Pj;h.setCanvasSize=function(a,b,c){ok(h.canvas,a,b);c||nk()};h.pauseMainLoop=Zj;h.resumeMainLoop=ak;
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.th&&a==h.canvas)return h.th;var e;if(b){var f={antialias:!1,alpha:!1,hi:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Yk&&(e=Vk(a,f)))var k=Hk[e].lh}else k=a.getContext("2d");if(!k)return null;c&&(h.th=k,b&&Xk(e),h.gj=b,dk.forEach(n=>n()),ek());return k};
for(var S,Z=0;32>Z;++Z)Sl.push(Array(Z));var Tm=new Float32Array(288);for(Z=0;288>=Z;++Z)fm[Z]=Tm.subarray(0,Z);var Um=new Int32Array(288);for(Z=0;288>=Z;++Z)gm[Z]=Um.subarray(0,Z);
var Hj=[Yh,qi,Ei,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Lb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,cc,dc,ec,lc,Gl,Kl,mc,oc,pc,qc,rc,tc,uc,nh,oh,qh,rh,sh,uh,vh,wh,xh,yh,zh,Ah,Bh,Ch,Dh,Eh,Fh,Gh,Hh,Ih,Jh,Kh,Lh,Mh,Nh,Oh,Ph,Rh,Sh,Uh,Vh,Wh,Xh],rb,Y=function(){function a(c,d){Y=c.exports;Y=Bm();ri.push(Y.Yf);Ua.unshift(Y.Wf);Na=d;hb();return Y}var b=za();gb();if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return q(`Module.instantiateWasm callback failed with error: ${c}`),!1}kb||=jb("bombermaaan.wasm")?
"bombermaaan.wasm":h.locateFile?h.locateFile("bombermaaan.wasm",ka):ka+"bombermaaan.wasm";qb(b,function(c){a(c.instance,c.module)});return{}}(),Vm=h._main=(a,b)=>(Vm=h._main=Y.Xf)(a,b),ya=()=>(ya=Y.Zf)(),V=(a,b,c,d,e)=>(V=Y._f)(a,b,c,d,e),Ea=(a,b,c,d,e,f)=>(Ea=Y.$f)(a,b,c,d,e,f),La=()=>(La=Y.ag)(),mi=(a,b,c,d,e)=>(mi=Y.bg)(a,b,c,d,e),ui=a=>(ui=Y.cg)(a),Ja=a=>(Ja=Y.dg)(a),Fj=()=>(Fj=Y.eg)(),bl=a=>(bl=Y.fg)(a),D=a=>(D=Y.hg)(a),yi=(a,b)=>(yi=Y.ig)(a,b),ni=a=>(ni=Y.jg)(a),li=a=>(li=Y.kg)(a),ki=()=>(ki=
Y.lg)(),zi=h.dynCall_ii=(a,b)=>(zi=h.dynCall_ii=Y.ng)(a,b),dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=Y.og)(a,b,c),dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=Y.pg)(a,b);h.dynCall_viiii=(a,b,c,d,e)=>(h.dynCall_viiii=Y.qg)(a,b,c,d,e);h.dynCall_iiiii=(a,b,c,d,e)=>(h.dynCall_iiiii=Y.rg)(a,b,c,d,e);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=Y.sg)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=Y.tg)(a,b);var W=h.dynCall_iiii=(a,b,c,d)=>(W=h.dynCall_iiii=Y.ug)(a,b,c,d);
h.dynCall_i=a=>(h.dynCall_i=Y.vg)(a);var dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=Y.wg)(a),dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=Y.xg)(a,b,c);h.dynCall_iiiiii=(a,b,c,d,e,f)=>(h.dynCall_iiiiii=Y.yg)(a,b,c,d,e,f);h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=Y.zg)(a,b,c,d,e,f);h.dynCall_viii=(a,b,c,d)=>(h.dynCall_viii=Y.Ag)(a,b,c,d);h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,k)=>(h.dynCall_iiiiiiii=Y.Bg)(a,b,c,d,e,f,g,k);
h.dynCall_iiiiiiiiii=(a,b,c,d,e,f,g,k,n,p)=>(h.dynCall_iiiiiiiiii=Y.Cg)(a,b,c,d,e,f,g,k,n,p);h.dynCall_iiiiiiiiiiiiiiff=(a,b,c,d,e,f,g,k,n,p,t,B,J,O,da,ra)=>(h.dynCall_iiiiiiiiiiiiiiff=Y.Dg)(a,b,c,d,e,f,g,k,n,p,t,B,J,O,da,ra);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,k,n)=>(h.dynCall_iiiiiiiii=Y.Eg)(a,b,c,d,e,f,g,k,n);h.dynCall_viiiiiii=(a,b,c,d,e,f,g,k)=>(h.dynCall_viiiiiii=Y.Fg)(a,b,c,d,e,f,g,k);h.dynCall_viiiiiiiiiii=(a,b,c,d,e,f,g,k,n,p,t,B)=>(h.dynCall_viiiiiiiiiii=Y.Gg)(a,b,c,d,e,f,g,k,n,p,t,B);
h.dynCall_iiiiiidiiff=(a,b,c,d,e,f,g,k,n,p,t)=>(h.dynCall_iiiiiidiiff=Y.Hg)(a,b,c,d,e,f,g,k,n,p,t);h.dynCall_iiiiiiiiiiii=(a,b,c,d,e,f,g,k,n,p,t,B)=>(h.dynCall_iiiiiiiiiiii=Y.Ig)(a,b,c,d,e,f,g,k,n,p,t,B);h.dynCall_iid=(a,b,c)=>(h.dynCall_iid=Y.Jg)(a,b,c);h.dynCall_di=(a,b)=>(h.dynCall_di=Y.Kg)(a,b);h.dynCall_iiiiiiji=(a,b,c,d,e,f,g,k,n)=>(h.dynCall_iiiiiiji=Y.Lg)(a,b,c,d,e,f,g,k,n);h.dynCall_iji=(a,b,c,d)=>(h.dynCall_iji=Y.Mg)(a,b,c,d);h.dynCall_fi=(a,b)=>(h.dynCall_fi=Y.Ng)(a,b);
h.dynCall_iif=(a,b,c)=>(h.dynCall_iif=Y.Og)(a,b,c);h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=Y.Pg)(a,b,c,d,e,f,g);h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=Y.Qg)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=Y.Rg)(a,b);h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,k,n)=>(h.dynCall_viiiiiiii=Y.Sg)(a,b,c,d,e,f,g,k,n);h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,k,n,p)=>(h.dynCall_viiiiiiiii=Y.Tg)(a,b,c,d,e,f,g,k,n,p);h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=Y.Ug)(a,b,c);
h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=Y.Vg)(a,b,c);h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=Y.Wg)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=Y.Xg)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=Y.Yg)(a,b,c,d);h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=Y.Zg)(a,b,c,d,e);h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=Y._g)(a,b,c,d,e,f);h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_viiiiii=Y.$g)(a,b,c,d,e,f,g);
h.dynCall_viiiiiiiiii=(a,b,c,d,e,f,g,k,n,p,t)=>(h.dynCall_viiiiiiiiii=Y.ah)(a,b,c,d,e,f,g,k,n,p,t);h.dynCall_viifi=(a,b,c,d,e)=>(h.dynCall_viifi=Y.bh)(a,b,c,d,e);var Rm=a=>(Rm=Y.ch)(a),Fm=()=>(Fm=Y.dh)(),Qm=a=>(Qm=Y.eh)(a),Sm=()=>(Sm=Y.fh)(),Wm;fb=function Xm(){Wm||Ym();Wm||(fb=Xm)};function Zm(a=[]){var b=Vm;a.unshift(ha);var c=a.length,d=li(4*(c+1)),e=d;a.forEach(g=>{w[e>>2]=Hl(g);e+=4});w[e>>2]=0;try{var f=b(c,d);Th(f,!0)}catch(g){pi(g)}}
function Ym(){var a=fa;function b(){if(!Wm&&(Wm=!0,h.calledRun=!0,!Oa&&(Xa(),m||cb(Va),h.onRuntimeInitialized?.(),$m&&Zm(a),!m))){if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Wa.unshift(c)}cb(Wa)}}if(!(0<db))if(m)Xa(),startWorker(h);else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ta.unshift(h.preRun.shift());cb(Ta);0<db||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},
1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var $m=!0;h.noInitialRun&&($m=!1);Ym();
