var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,l="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,m=ba&&"em-pthread"==self.name;if(l){var ca=require("worker_threads");global.Worker=ca.Worker;m=(ba=!ca.ti)&&"em-pthread"==ca.workerData}
var da=Object.assign({},h),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},ia="undefined"!=typeof document?document.currentScript?.src:void 0;l?ia=__filename:ba&&(ia=self.location.href);var ja="",ka,la;
if(l){var fs=require("fs"),ma=require("path");ja=__dirname+"/";la=a=>{a=na(a)?new URL(a):ma.normalize(a);return fs.readFileSync(a)};ka=a=>{a=na(a)?new URL(a):ma.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!h.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof oa||a.context instanceof oa))throw a;
});ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?ja=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ja=document.currentScript.src),ja=ja.startsWith("blob:")?"":ja.substr(0,ja.replace(/[?#].*/,"").lastIndexOf("/")+1),l||(ba&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=a=>na(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=
()=>{(200==d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url))));l&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var pa=console.log.bind(console),qa=console.error.bind(console);l&&(pa=(...a)=>fs.writeSync(1,a.join(" ")+"\n"),qa=(...a)=>fs.writeSync(2,a.join(" ")+"\n"));var ra=h.print||pa,p=h.printErr||qa;
Object.assign(h,da);da=null;h.arguments&&(ea=h.arguments);h.thisProgram&&(fa=h.thisProgram);h.quit&&(ha=h.quit);
if(m){var sa;if(l){var ta=ca.parentPort;ta.on("message",c=>onmessage({data:c}));Object.assign(globalThis,{self:global,importScripts:()=>{},postMessage:c=>ta.postMessage(c),performance:global.performance||{now:Date.now}})}var ua=!1;function a(...c){c=c.join(" ");l?fs.writeSync(2,c+"\n"):console.error(c)}h.printErr||(p=a);self.alert=function(...c){postMessage({Nh:"alert",text:c.join(" "),zi:va()})};h.instantiateWasm=(c,d)=>new Promise(e=>{sa=f=>{f=new WebAssembly.Instance(f,wa());d(f);e()}});self.onunhandledrejection=
c=>{throw c.reason||c;};function b(c){try{var d=c.data,e=d.cmd;if("load"===e){let f=[];self.onmessage=g=>f.push(g);self.startWorker=()=>{postMessage({cmd:"loaded"});for(let g of f)b(g);self.onmessage=b};for(const g of d.handlers)if(!h[g]||h[g].proxy)h[g]=(...k)=>{postMessage({Nh:"callHandler",si:g,args:k})},"print"==g&&(ra=h[g]),"printErr"==g&&(p=h[g]);xa=d.wasmMemory;ya();za=Aa(d.wasmOffsetConverter);sa(d.wasmModule)}else if("run"===e){Ba(d.pthread_ptr,0,0,1,0,0);Ca(d.pthread_ptr);Da();Ea();ua||=
!0;try{Fa(d.start_routine,d.arg)}catch(f){if("unwind"!=f)throw f;}}else"cancel"===e?va()&&Ga(-1):"setimmediate"!==d.target&&("checkMailbox"===e?ua&&Ha():e&&(p(`worker: received unknown command ${e}`),p(d)))}catch(f){throw Ia(),f;}}self.onmessage=b}var Ja;h.wasmBinary&&(Ja=h.wasmBinary);var xa,Ka,La=!1,Ma,r,t,Na,Oa,u,v,w,x;
function ya(){var a=xa.buffer;h.HEAP8=r=new Int8Array(a);h.HEAP16=Na=new Int16Array(a);h.HEAPU8=t=new Uint8Array(a);h.HEAPU16=Oa=new Uint16Array(a);h.HEAP32=u=new Int32Array(a);h.HEAPU32=v=new Uint32Array(a);h.HEAPF32=w=new Float32Array(a);h.HEAPF64=x=new Float64Array(a)}
if(!m){if(h.wasmMemory)xa=h.wasmMemory;else{var Pa=h.INITIAL_MEMORY||67108864;xa=new WebAssembly.Memory({initial:Pa/65536,maximum:Pa/65536,shared:!0});if(!(xa.buffer instanceof SharedArrayBuffer))throw p("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),l&&p("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");}ya()}var Qa=[],Ra=[],Sa=[],Ta=[],Ua=0,Va=null,Wa=null;function Xa(){Ua++;h.monitorRunDependencies?.(Ua)}function Ya(){Ua--;h.monitorRunDependencies?.(Ua);if(0==Ua&&(null!==Va&&(clearInterval(Va),Va=null),Wa)){var a=Wa;Wa=null;a()}}function Za(a){h.onAbort?.(a);a="Aborted("+a+")";p(a);La=!0;Ma=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var $a=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),ab;
function bb(a){if(a==ab&&Ja)return new Uint8Array(Ja);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}function cb(a){return Ja?Promise.resolve().then(()=>bb(a)):ka(a).then(b=>new Uint8Array(b),()=>bb(a))}var za;
function db(a,b){function c(){var n=0,q=0;do{var y=g[e++];n+=(y&127)<<q;q+=7}while(y&128);return n}function d(){var n=c();c();0!=(n&1)&&c()}var e=8,f=0;this.Ah={};this.eh=[];this.zh={};var g=a;a:for(;e<g.length;){a=g[e++];var k=c()+e;switch(a){case 2:for(a=c();0<a--;)switch(e=c()+e,e=c()+e,g[e++]){case 0:++f;c();break;case 1:c();d();break;case 2:d();break;case 3:e+=2;break;case 4:++e,c()}break;case 10:for(a=c();0<a--;)k=c(),this.Ah[f++]=e,this.eh.push(e),e+=k;break a}e=k}b=WebAssembly.Module.customSections(b,
"name");if(b=b.length?b[0]:void 0)for(g=new Uint8Array(b),e=0;e<g.length;)if(b=g[e++],f=c(),1!=b)e+=f;else for(a=c();0<a--;)b=c(),f=c(),this.zh[b]=z(g,e,f),e+=f}function Aa(a){var b=Object.create(db.prototype);return Object.assign(b,a)}function eb(a,b,c){var d;return cb(a).then(e=>{d=e;return WebAssembly.instantiate(e,b)}).then(e=>{za=new db(d,e.module);return e}).then(c,e=>{p(`failed to asynchronously prepare wasm: ${e}`);Za(e)})}
function fb(a,b){var c=ab;Ja||"function"!=typeof WebAssembly.instantiateStreaming||$a(c)||na(c)||l||"function"!=typeof fetch?eb(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>{var e=WebAssembly.instantiateStreaming(d,a),f=d.clone().arrayBuffer();return e.then(function(g){f.then(k=>{za=new db(new Uint8Array(k),g.module);b(g)},k=>p(`failed to initialize offset-converter: ${k}`))},function(g){p(`wasm streaming compile failed: ${g}`);p("falling back to ArrayBuffer instantiation");return eb(c,a,b)})})}
function wa(){gb={af:hb,bd:ib,Re:jb,M:kb,nc:lb,Ic:mb,mf:nb,Da:ob,If:pb,sa:qb,Z:rb,xd:sb,O:tb,xf:Ca,Id:ub,tb:vb,eb:wb,kb:xb,mb:yb,lb:zb,nb:Ab,fb:Bb,m:Cb,jb:Db,Za:Eb,ob:Fb,ib:Gb,pb:Hb,qb:Ib,_a:Jb,sb:Kb,rb:Lb,ab:Mb,b:Nb,k:Ob,l:Pb,bb:Qb,gb:Rb,Jb:Sb,g:Tb,e:Ub,K:Vb,d:Wb,Ib:Xb,hb:Yb,Fa:Zb,Ea:$b,od:ac,Va:bc,Rc:cc,Ca:dc,Ba:ec,Oc:fc,Pc:gc,Aa:hc,za:ic,Tb:jc,ya:kc,Lb:lc,Wc:mc,Na:mc,xa:nc,wa:oc,va:pc,ua:sc,ta:tc,$c:uc,ra:vc,qa:wc,pa:xc,oa:yc,qc:zc,rc:Ac,tc:Bc,sc:Cc,na:Dc,ma:Ec,la:Fc,ac:Gc,ka:Hc,ja:Ic,ia:Jc,td:Kc,
ha:Lc,sd:Mc,oc:Nc,ga:Oc,fa:Pc,ud:Qc,ea:Rc,da:Sc,ca:Tc,ba:Uc,aa:Vc,$:Wc,qd:Xc,Xa:Yc,_:Zc,Vb:$c,Y:ad,bc:bd,X:cd,Kb:dd,Vc:ed,Ma:ed,W:fd,V:gd,U:hd,T:jd,S:kd,R:ld,Q:md,gc:nd,Ia:nd,Ed:nd,Fd:nd,ub:nd,hd:od,Ad:od,Ja:od,P:pd,fc:qd,Ha:qd,Bd:qd,Cd:qd,Dd:qd,yd:rd,Hf:sd,Gf:td,nd:ud,Ua:vd,Qc:wd,ec:xd,Ff:yd,Ef:zd,Xc:Ad,Df:Bd,Cf:Cd,Zc:Dd,Bf:Ed,Af:Fd,yf:Gd,rd:Hd,Ya:Id,wf:Jd,Wb:Kd,vf:Ld,Hb:Md,Uc:Nd,La:Nd,zf:Od,uf:Pd,tf:Qd,ic:Rd,jc:Sd,lc:Td,sf:Ud,rf:Vd,qf:Wd,Xb:Xd,pf:Yd,id:Zd,of:$d,nf:ae,Cc:be,lf:ce,Yb:de,_b:ee,Sc:fe,
kf:ge,wb:he,Db:ie,hf:je,jf:ke,Pa:le,Ra:me,Oa:le,kd:ne,Qa:me,ld:oe,Sa:pe,gf:qe,Nb:re,Ob:se,ef:te,df:ue,cf:ve,ff:we,bf:xe,pc:ye,Zb:ze,$e:Ae,_e:Be,Mc:Ce,kc:De,mc:Ee,Xe:Fe,Ze:Ge,Ye:He,Dc:Ie,Kc:Je,Jc:Je,Ue:Ke,We:Le,Ve:Me,Te:Ne,Ab:Oe,zb:Pe,Se:Qe,Qe:Re,Pe:Se,Oe:Te,pd:Ue,Wa:Ve,Ne:We,Ub:Xe,Me:Ye,dc:Ze,Le:$e,Gb:af,Tc:bf,Ka:bf,Ke:cf,Je:df,Yc:ef,Fb:ff,Ie:gf,He:hf,Cb:jf,Bb:kf,Ta:lf,zd:mf,Ge:nf,Fe:of,Ee:pf,_c:qf,Eb:rf,De:sf,Qb:tf,Pb:uf,Sb:vf,Rb:wf,Ce:xf,Be:yf,Ae:zf,ze:Af,ye:Bf,xe:Cf,we:Df,ve:Ef,ue:Ff,te:Gf,wd:Hf,
se:If,re:Jf,qe:Kf,pe:Lf,yb:Mf,xb:Nf,oe:Of,vd:Pf,Nc:Qf,ne:Rf,me:Sf,le:Tf,ke:Uf,Bc:Vf,xc:Wf,je:Xf,ie:Yf,he:Zf,ge:$f,Ac:ag,wc:bg,fe:cg,ee:dg,de:eg,be:fg,zc:gg,vc:hg,ae:ig,$d:jg,_d:kg,Zd:lg,yc:mg,uc:ng,hc:og,Yd:pg,gd:qg,ed:rg,Xd:sg,fd:tg,cd:ug,Wd:vg,dd:wg,ad:xg,jd:yg,Vd:zg,Ud:Ag,Sd:Bg,Rd:Cg,Qd:Dg,Pd:Eg,Od:Fg,Nd:Gg,Md:Hg,Ld:Ig,Mb:Jg,Ga:Jg,Gd:Jg,Hd:Jg,vb:Jg,Hc:Kg,Fc:Lg,Gc:Mg,Ec:Ng,Lc:Og,Kd:Pg,Jd:Qg,$b:Rg,j:Sg,cb:Tg,I:Ug,Kf:Vg,L:Wg,n:Xg,z:Yg,f:Zg,h:$g,A:ah,q:bh,J:ch,H:dh,t:eh,r:fh,s:gh,F:hh,D:ih,C:jh,G:kh,
E:lh,u:mh,p:nh,v:oh,x:ph,w:qh,y:rh,o:sh,B:th,db:uh,i:vh,Td:wh,ce:xh,c:yh,N:zh,cc:Ah,$a:Bh,Jf:Ch,a:xa,md:Dh};return{a:gb}}
var Ih={1861940:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Xh!==h.canvas&&(d.Wg=h.createContext(h.canvas,!1,!0),d.Xh=h.canvas);if(d.w!==a||d.h!==b||d.fi!==d.Wg)d.image=d.Wg.createImageData(a,b),d.w=a,d.h=b,d.fi=d.Wg;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=u[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.$h!==a&&(d.Zh=new Int32Array(a.buffer),d.ai=new Uint8Array(a.buffer),d.$h=a),
a=d.Zh,c=a.length,a.set(u.subarray(b,b+c)),a=d.ai,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Wg.putImageData(d.image,0,0)},1863409:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var k=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=
b.length;k<n;){var q=u[e];b[k]=q&255;b[k+1]=q>>8&255;b[k+2]=q>>16&255;b[k+3]=q>>24&255;e++;k+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(u.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=A(c.length+1);B(c,t,d,c.length+1);return d},1864398:a=>{h.canvas&&(h.canvas.style.cursor=a?z(t,a):"")},1864481:()=>{h.canvas&&(h.canvas.style.cursor="none")},1864550:()=>window.innerWidth,1864580:()=>window.innerHeight,1864611:()=>
"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,1864758:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,1864992:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.Xf||("undefined"!==typeof AudioContext?b.Xf=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.Xf=new webkitAudioContext),b.Xf&&Eh(b.Xf));return void 0===
b.Xf?-1:0},1865485:()=>h.SDL2.Xf.sampleRate,1865553:(a,b,c,d)=>{function e(){}function f(k){void 0!==g.capture.lh&&(clearTimeout(g.capture.lh),g.capture.lh=void 0);g.capture.uh=g.Xf.createMediaStreamSource(k);g.capture.Qg=g.Xf.createScriptProcessor(b,a,1);g.capture.Qg.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Ch=n.inputBuffer,Fh(c,[d]))};g.capture.uh.connect(g.capture.Qg);g.capture.Qg.connect(g.Xf.destination);g.capture.stream=k}
var g=h.SDL2;g.capture.wh=g.Xf.createBuffer(a,b,g.Xf.sampleRate);g.capture.wh.getChannelData(0).fill(0);g.capture.lh=setTimeout(function(){g.capture.Ch=g.capture.wh;Fh(c,[d])},b/g.Xf.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},1867205:(a,b,c,d)=>{var e=h.SDL2;e.audio.Qg=e.Xf.createScriptProcessor(b,
0,a);e.audio.Qg.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Ph=f.outputBuffer,Fh(c,[d]))};e.audio.Qg.connect(e.Xf.destination)},1867615:(a,b)=>{for(var c=h.SDL2,d=c.capture.Ch.numberOfChannels,e=0;e<d;++e){var f=c.capture.Ch.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Gh(a+4*g,f[g]);else for(g=0;g<b;++g)Gh(a+4*(g*d+e),f[g])}},1868220:(a,b)=>{for(var c=
h.SDL2,d=c.audio.Ph.numberOfChannels,e=0;e<d;++e){var f=c.audio.Ph.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=w[a+(g*d+e<<2)>>2]}},1868700:a=>{var b=h.SDL2;if(a){void 0!==b.capture.lh&&clearTimeout(b.capture.lh);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==
b.capture.Qg&&(b.capture.Qg.onaudioprocess=function(){},b.capture.Qg.disconnect(),b.capture.Qg=void 0);void 0!==b.capture.uh&&(b.capture.uh.disconnect(),b.capture.uh=void 0);void 0!==b.capture.wh&&(b.capture.wh=void 0);b.capture=void 0}else void 0!=b.audio.Qg&&(b.audio.Qg.disconnect(),b.audio.Qg=void 0),b.audio=void 0;void 0!==b.Xf&&void 0===b.audio&&void 0===b.capture&&(b.Xf.close(),b.Xf=void 0)},1869872:a=>{a=(a?z(t,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===
a&&(a="i");var b=Array(Hh(a)+1);B(a,b,0,b.length);a=b;b=A(a.length);a.subarray||a.slice||(a=new Uint8Array(a));t.set(a,b);return b}};function oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Jh=a=>{a.terminate();a.onmessage=()=>{}},Oh=a=>{0==Kh.length&&(Lh(),Mh(Kh[0]));var b=Kh.pop();if(!b)return 6;Nh.push(b);C[a.bh]=b;b.bh=a.bh;var c={cmd:"run",start_routine:a.ii,arg:a.Lh,pthread_ptr:a.bh};l&&b.unref();b.postMessage(c,a.ji);return 0},D=0,E=(a,b,c,...d)=>{for(var e=d.length,f=Ph(),g=Qh(8*e),k=g>>3,n=0;n<d.length;n++)x[k+n]=d[n];a=Rh(a,b,e,g,c);Sh(f);return a};
function Dh(a){if(m)return E(0,0,1,a);Ma=a;if(!(Th||0<D)){for(var b of Nh)Jh(b);for(b of Kh)Jh(b);Kh=[];Nh=[];C=[];h.onExit?.(a);La=!0}ha(a,new oa(a))}var Uh=a=>{a instanceof oa||"unwind"==a||ha(1,a)};function Vh(a){if(m)return E(1,0,0,a);yh(a)}var yh=a=>{Ma=a;if(m)throw Vh(a),"unwind";Dh(a)},Kh=[],Nh=[],Wh=[],C={};function Xh(){for(var a=navigator.hardwareConcurrency;a--;)Lh();Qa.unshift(()=>{Xa();Yh(()=>Ya())})}var $h=a=>{var b=a.bh;delete C[b];Kh.push(a);Nh.splice(Nh.indexOf(a),1);a.bh=0;Zh(b)};
function Ea(){Wh.forEach(a=>a())}
var Mh=a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.cmd;if(f.targetThread&&f.targetThread!=va()){var k=C[f.targetThread];k?k.postMessage(f,f.transferList):p(`Internal error! Worker sent a message "${g}" to target pthread ${f.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===g)Ha();else if("spawnThread"===g)Oh(f);else if("cleanupThread"===g)$h(C[f.thread]);else if("killThread"===g)f=f.thread,g=C[f],delete C[f],Jh(g),Zh(f),Nh.splice(Nh.indexOf(g),1),g.bh=0;else if("cancelThread"===
g)C[f.thread].postMessage({cmd:"cancel"});else if("loaded"===g)a.loaded=!0,l&&!a.bh&&a.unref(),b(a);else if("alert"===g)alert(`Thread ${f.threadId}: ${f.text}`);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===g)h[f.handler](...f.args);else g&&p(`worker sent an unknown command ${g}`)};a.onerror=f=>{p(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};l&&(a.on("message",f=>a.onmessage({data:f})),a.on("error",f=>a.onerror(f)));var c=[],d=["onExit",
"onAbort","print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({cmd:"load",handlers:c,wasmMemory:xa,wasmModule:Ka,wasmOffsetConverter:za})});function Yh(a){m?a():Promise.all(Kh.map(Mh)).then(a)}function Lh(){var a=ia;h.mainScriptUrlOrBlob&&(a=h.mainScriptUrlOrBlob,"string"!=typeof a&&(a=URL.createObjectURL(a)));a=new Worker(a,{workerData:"em-pthread",name:"em-pthread"});Kh.push(a)}
var ai,bi="undefined"!=typeof TextDecoder?new TextDecoder:void 0,z=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&bi)return bi.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&
1023))}}else d+=String.fromCharCode(e)}return d},ci=a=>{for(;0<a.length;)a.shift()(h)},Da=()=>{var a=va(),b=v[a+52>>2];di(b,b-v[a+56>>2]);Sh(b)},Fa=(a,b)=>{D=0;a=ei(a,b);Th||0<D?Ma=a:Ga(a)},Th=h.noExitRuntime||!0;
function Gh(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":r[a]=b;break;case "i8":r[a]=b;break;case "i16":Na[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":Za("to do setValue(i64) use WASM_BIGINT");case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":v[a>>2]=b;break;default:Za(`invalid type for setValue: ${c}`)}}
var fi=(a,b)=>a?z(t,a,b):"",hb=(a,b,c,d)=>{Za(`Assertion failed: ${a?z(t,a):""}, at: `+[b?b?z(t,b):"":"unknown filename",c,d?d?z(t,d):"":"unknown function"])},ib=(a,b)=>dynCall_vi(a,b);function gi(a,b,c,d){return m?E(2,0,1,a,b,c,d):jb(a,b,c,d)}
var jb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return p("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(m&&0===e.length)return gi(a,b,c,d);a={ii:c,bh:a,Lh:d,ji:e};return m?(a.Nh="spawnThread",postMessage(a,e),0):Oh(a)};function kb(a,b,c){return m?E(3,0,1,a,b,c):0}function lb(a,b,c){return m?E(4,0,1,a,b,c):0}function mb(a,b,c,d){if(m)return E(5,0,1,a,b,c,d)}
var nb=()=>{Za("")},ob=()=>1,pb=a=>{Ba(a,!ba,1,!aa,16777216,!1);Ea()},hi=a=>{if(!La)try{if(a(),!(Th||0<D))try{m?Ga(Ma):yh(Ma)}catch(b){Uh(b)}}catch(b){Uh(b)}},Ca=a=>{"function"===typeof Atomics.li&&(Atomics.li(u,a>>2,a).value.then(Ha),Atomics.store(u,a+128>>2,1))},Ha=()=>{var a=va();a&&(Ca(a),hi(ii))},qb=(a,b)=>{a==b?setTimeout(Ha):m?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=C[a])&&a.postMessage({cmd:"checkMailbox"})},ji=[],rb=(a,b,c,d,e)=>{ji.length=d;e>>=3;for(var f=0;f<d;f++)ji[f]=x[e+
f];a=b?Ih[b]:ki[a];ai=c;c=a(...ji);ai=0;return c};function sb(){if(m)return E(6,0,1);Th=!1;D=0}
var tb=a=>{m?postMessage({cmd:"cleanupThread",thread:a}):$h(C[a])},ub=a=>{l&&C[a].ref()},ui=(a,b)=>{li=a;mi=b;if(ni)if(oi||(D+=1,oi=!0),0==a)pi=function(){var d=Math.max(0,qi+b-Wb())|0;setTimeout(ri,d)};else if(1==a)pi=function(){si(ri)};else if(2==a){if("undefined"==typeof ti)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);ti=function(d){c.push(d);if(ba){let e;(e=h).setImmediates??
(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else ti=setImmediate;pi=function(){ti(ri)}}},Wb;Wb=()=>performance.timeOrigin+performance.now();
var Ai=a=>{function b(){return c<vi?(--D,!1):!0}ni=a;var c=vi;oi=!1;ri=function(){if(!La)if(0<wi.length){var d=wi.shift();d.ri(d.Lh);if(xi){var e=xi,f=0==e%1?e-1:Math.floor(e);xi=d.ni?f:(8*e+(f+.5))/9}h.setStatus&&(d=h.statusMessage||"Please wait...",e=xi,f=yi.pi,e?e<f?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(d):h.setStatus(""));b()&&setTimeout(ri,0)}else if(b())if(zi=zi+1|0,1==li&&1<mi&&0!=zi%mi)pi();else{0==li&&(qi=Wb());if(F)for(d=F.ih,F.ih=F.mh,F.mh=d,d=F.dh,F.dh=
F.yh,F.yh=d,d=0;21>=d;++d)F.dh[d]=0;La||h.preMainLoop&&!1===h.preMainLoop()||(hi(a),h.postMainLoop?.());b()&&("object"==typeof SDL&&SDL.audio?.yi?.(),pi())}}},Bi=(a,b)=>{D+=1;return setTimeout(()=>{--D;hi(a)},b)},oi=!1,pi=null,vi=0,ni=null,li=0,mi=0,zi=0,wi=[];function Ci(){pi=null;vi++}function Di(){vi++;var a=li,b=mi,c=ni;ni=null;Ai(c);ui(a,b);pi()}var yi={},qi,ri,xi,Ei=!1,Fi=!1,Gi=[];
function Hi(){function a(){Fi=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Ii){Ii=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Fi&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Ji=!1,Ki=void 0,Li=void 0;
function Mi(){if(!Ei)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Ni=0;function si(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Ni)Ni=b+1E3/60;else for(;b+2>=Ni;)Ni+=1E3/60;setTimeout(a,Math.max(Ni-b,0))}}var Oi=[];function Pi(){var a=h.canvas;Oi.forEach(b=>b(a.width,a.height))}
function Qi(a,b,c){b&&c?(a.mi=b,a.ei=c):(b=a.mi,c=a.ei);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Li?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Ri={},ti,Ii,G=12288,Si=!1,Ti=0,Ui=0,Vi=0,I={alpha:!1,depth:!1,stencil:!1,antialias:!1},Wi={},Xi;function vb(a){if(m)return E(7,0,1,a);if(12448==a)return G=12288,1;G=12300;return 0}
function wb(a,b,c,d,e){if(m)c=E(8,0,1,a,b,c,d,e);else if(62E3!=a)G=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)I.alpha=0<u[b+4>>2];else if(12325==a)I.depth=0<u[b+4>>2];else if(12326==a)I.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+4>>2],I.antialias=0<a;else if(12338==a)a=u[b+4>>2],I.antialias=1==a;else if(12544==a)I.ui=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>2]=1),c&&0<d&&(v[c>>2]=62002),G=12288,c=1):(G=12300,c=0)}return c}
var Yi=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Zi=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},
$i=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},aj=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},bj=1,cj=[],dj={},J=[],ej=[],fj=[],gj=[],K=[],hj=[],L={},M=[],N=[],ij=[],jj=[],kj=[1,1,2,2,4,4,4,2,3,4,8],lj={},mj={},nj=4,oj=0,pj=a=>{for(var b=bj++,c=a.length;c<b;c++)a[c]=null;return b},qj=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=P[c](),g=f&&pj(d);f?(f.name=g,d[g]=f):Q||=1282;u[b+4*e>>2]=g}},sj=a=>{rj=!1;for(var b=0;b<F.Sh;++b){var c=F.$g[b];if(c.jh&&c.enabled){rj=!0;var d=c.xh;d=0<d?a*d:c.size*kj[c.type-5120]*a;var e=32-Math.clz32(0===
d?0:d-1);var f=F.ih[e],g=F.dh[e];F.dh[e]=F.dh[e]+1&63;var k=f[g];k?e=k:(k=P.getParameter(34964),f[g]=P.createBuffer(),P.bindBuffer(34962,f[g]),P.bufferData(34962,1<<e,35048),P.bindBuffer(34962,k),e=f[g]);P.bindBuffer(34962,e);P.bufferSubData(34962,0,t.subarray(c.vh,c.vh+d));c.Jh.call(P,b,c.size,c.type,c.Fh,c.xh,0)}}},uj=(a,b)=>{a.eh||(a.eh=a.getContext,a.getContext=function(d,e){e=a.eh(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Eh?a.getContext("webgl2",b):a.getContext("webgl",
b);return c?tj(c,b):0},tj=(a,b)=>{var c=A(8);v[c+4>>2]=va();var d={handle:c,attributes:b,version:b.Eh,Rg:a};a.canvas&&(a.canvas.Zg=d);L[c]=d;("undefined"==typeof b.ci||b.ci)&&vj(d);d.Sh=d.Rg.getParameter(34921);d.$g=[];for(a=0;a<d.Sh;a++)d.$g[a]={enabled:!1,jh:!1,size:0,type:0,Fh:0,xh:0,vh:0,Jh:null};d.dh=[];d.yh=[];d.dh.length=d.yh.length=22;d.ih=[];d.mh=[];d.ih.length=d.mh.length=22;d.hh=[];d.hh.length=22;for(a=0;21>=a;++a){d.hh[a]=null;d.dh[a]=d.yh[a]=0;d.ih[a]=[];d.mh[a]=[];b=d.ih[a];var e=d.mh[a];
b.length=e.length=64;for(var f=0;64>f;++f)b[f]=e[f]=null}return c},wj=a=>{F=L[a];h.Wg=P=F?.Rg},vj=a=>{a||=F;if(!a.gi){a.gi=!0;var b=a.Rg;Yi(b);Zi(b);$i(b);b.oi=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.vi=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Ug=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Ug)b.Ug=b.getExtension("EXT_disjoint_timer_query");b.xi=b.getExtension("WEBGL_multi_draw");aj(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},xj={},Q,F,rj;function xb(a,b,c,d){if(m)return E(9,0,1,a,b,c,d);if(62E3!=a)return G=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return G=12292,0;d+=8}if(2>a||3<a)return G=12293,0;I.Eh=a-1;I.wi=0;Xi=uj(h.canvas,I);if(0!=Xi)return G=12288,wj(Xi),h.ki=!0,Gi.forEach(function(e){e()}),wj(null),62004;G=12297;return 0}
function yb(a,b,c,d){if(m)return E(10,0,1,a,b,c,d);if(62E3!=a)return G=12296,0;if(62002!=b)return G=12293,0;G=12288;return 62006}function zb(a,b){if(m)return E(11,0,1,a,b);if(62E3!=a)return G=12296,0;if(62004!=b)return G=12294,0;a=Xi;F===L[a]&&(F=null);if("object"==typeof yj)for(var c=L[a].Rg.canvas,d=0;d<zj.length;++d)zj[d].target!=c||Aj(d--);L[a]&&L[a].Rg.canvas&&(L[a].Rg.canvas.Zg=void 0);Bj(L[a].handle);L[a]=null;G=12288;Ti==b&&(Ti=0);return 1}
function Ab(a,b){if(m)return E(12,0,1,a,b);if(62E3!=a)return G=12296,0;if(62006!=b)return G=12301,1;Ui==b&&(Ui=0);Vi==b&&(Vi=0);G=12288;return 1}
function Bb(a,b,c,d){if(m)return E(13,0,1,a,b,c,d);if(62E3!=a)return G=12296,0;if(62002!=b)return G=12293,0;if(!d)return G=12300,0;G=12288;switch(c){case 12320:return u[d>>2]=I.alpha?32:24,1;case 12321:return u[d>>2]=I.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>2]=I.depth?24:0,1;case 12326:return u[d>>2]=I.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;
case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>2]=I.antialias?4:0,1;case 12338:return u[d>>2]=I.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;
case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return G=12292,0}}function Cb(a){if(m)return E(14,0,1,a);G=12288;return 0!=a&&1!=a?0:62E3}function Db(){return m?E(15,0,1):G}function Eb(a,b,c){if(m)return E(16,0,1,a,b,c);if(62E3!=a)return G=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);Si=!0;G=12288;return 1}
function Fb(a,b,c,d){if(m)return E(17,0,1,a,b,c,d);if(62E3!=a)return G=12296,0;if(0!=d&&62004!=d)return G=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return G=12301,0;wj(d?Xi:null);Ti=d;Vi=b;Ui=c;G=12288;return 1}
var Hh=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},B=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=
128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},Cj=a=>{var b=Hh(a)+1,c=A(b);c&&B(a,t,c,b);return c};function Gb(a,b){if(m)return E(18,0,1,a,b);if(62E3!=a)return G=12296,0;G=12288;if(Wi[b])return Wi[b];switch(b){case 12371:a=Cj("Emscripten");break;case 12372:a=Cj("1.4 Emscripten EGL");break;case 12373:a=Cj("");break;case 12429:a=Cj("OpenGL_ES");break;default:return G=12300,0}return Wi[b]=a}
function Hb(a,b){if(m)return E(19,0,1,a,b);if(Si)if(h.Wg)if(h.Wg.isContextLost())G=12302;else return G=12288,1;else G=12290;else G=12289;return 0}function Ib(a,b){if(m)return E(20,0,1,a,b);if(62E3!=a)return G=12296,0;0==b?ui(0,0):ui(1,b);G=12288;return 1}function Jb(a){if(m)return E(21,0,1,a);if(62E3!=a)return G=12296,0;Vi=Ui=Ti=0;Si=!1;G=12288;return 1}function Kb(){if(m)return E(22,0,1);G=12288;return 1}function Lb(a){if(m)return E(23,0,1,a);G=12288;return 1}
var Dj=[],Ej=(a,b)=>{Dj.length=0;for(var c;c=t[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Dj.push(112==c?v[b>>2]:105==c?u[b>>2]:x[b>>3]);b+=d?8:4}return Dj},Mb=(a,b,c)=>{b=Ej(b,c);return Ih[a](...b)},Nb=(a,b,c)=>{b=Ej(b,c);return m?E(0,a,1,...b):Ih[a](...b)},Ob=()=>{},Pb=()=>Date.now(),Fj=0,Gj=[];
function Hj(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var k in f)if(f[k]!=g[k])return!1;return!0}for(var e of Gj)if(e.Hh==a&&d(e.Mh,c))return;Gj.push({Hh:a,Uh:b,Mh:c});Gj.sort((f,g)=>f.Uh<g.Uh)}function Ij(a){Gj=Gj.filter(b=>b.Hh!=a)}function Jj(){return navigator.userActivation?navigator.userActivation.isActive:Fj&&Kj.oh}function Lj(){if(Jj()){var a=Gj;Gj=[];for(var b of a)b.Hh(...b.Mh)}}var zj=[];
function Aj(a){var b=zj[a];b.target.removeEventListener(b.Pg,b.Qh,b.Sg);zj.splice(a,1)}function R(a){if(!a.target)return-4;if(a.Tg)a.Qh=function(c){++Fj;Kj=a;Lj();a.Vg(c);Lj();--Fj},a.target.addEventListener(a.Pg,a.Qh,a.Sg),zj.push(a);else for(var b=0;b<zj.length;++b)zj[b].target==a.target&&zj[b].Pg==a.Pg&&Aj(b--);return 0}function S(a){switch(a){case 1:return 0;case 2:return ai;default:return a}}function Mj(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
function Nj(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var yj={},Kj,Oj,Pj,Qj,Rj,Sj,Tj,Uj,Vj,Wj,Xj,Yj,Zj,ak={},bk=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],T=a=>{a=2<a?a?z(t,a):"":a;return bk[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},ck=(a,b,c)=>{a=T(a);if(!a||a.Oh)return-4;u[b>>2]=a.width;u[c>>2]=a.height;return 0};function dk(a,b,c){return m?E(25,0,1,a,b,c):ck(a,b,c)}
var ek=a=>{var b=Hh(a)+1,c=Qh(b);B(a,t,c,b);return c},fk=a=>{var b=Ph(),c=Qh(8),d=c+4;a=ek(a.id);T(a)?ck(a,c,d):dk(a,c,d);c=[u[c>>2],u[d>>2]];Sh(b);return c},gk=(a,b,c)=>{a=T(a);if(!a||a.Oh)return-4;var d=!1;a.Zg?.Rg&&(d=a.Zg.Rg.getParameter(2978),d=0===d[0]&&0===d[1]&&d[2]===a.width&&d[3]===a.height);a.width=b;a.height=c;d&&a.Zg.Rg.viewport(0,0,b,c);return 0};function hk(a,b,c){return m?E(26,0,1,a,b,c):gk(a,b,c)}
var Zg=(a,b,c)=>T(a)?gk(a,b,c):hk(a,b,c),ik=(a,b,c)=>{if(a.Oh){var d=Ph();a=ek(a.id);Zg(a,b,c);Sh(d)}else a.width=b,a.height=c},jk=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),ik(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=k,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=q,a.style.paddingRight=
y,a.style.paddingTop=H,a.style.paddingBottom=Z,a.style.marginLeft=O,a.style.marginRight=qc,a.style.marginTop=rc,a.style.marginBottom=el,document.body.style.margin=fl,document.documentElement.style.overflow=gl,document.body.scroll=hl,a.style.ah=il,a.Zg&&a.Zg.Rg.viewport(0,0,d,e),ak.fh&&(ak.ph?U(ak.ph,ak.fh,37,0,ak.qh):V(ak.fh,37,0,ak.qh)))}var c=fk(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,k=a.style.backgroundColor,n=document.body.style.backgroundColor,q=a.style.paddingLeft,y=a.style.paddingRight,
H=a.style.paddingTop,Z=a.style.paddingBottom,O=a.style.marginLeft,qc=a.style.marginRight,rc=a.style.marginTop,el=a.style.marginBottom,fl=document.body.style.margin,gl=document.documentElement.style.overflow,hl=document.body.scroll,il=a.style.ah;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},kk=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},lk=a=>0>bk.indexOf(a)?a.getBoundingClientRect():
{left:0,top:0},mk=(a,b)=>{if(0!=b.Gh||0!=b.Bh){jk(a);var c=b.hi?innerWidth:screen.width,d=b.hi?innerHeight:screen.height,e=lk(a),f=e.width;e=e.height;var g=fk(a),k=g[0];g=g[1];3==b.Gh?(kk(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Gh&&(c*g<k*d?(f=g*c/k,kk(a,(d-f)/2,0),d=f):(f=k*d/g,kk(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.di&&(a.style.ah=
"optimizeSpeed",a.style.ah="-moz-crisp-edges",a.style.ah="-o-crisp-edges",a.style.ah="-webkit-optimize-contrast",a.style.ah="optimize-contrast",a.style.ah="crisp-edges",a.style.ah="pixelated");f=2==b.Bh?devicePixelRatio:1;0!=b.Bh&&(c=c*f|0,d=d*f|0,ik(a,c,d),a.Zg&&a.Zg.Rg.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Nj()?-3:-1;ak=b;b.fh&&(b.ph?U(b.ph,b.fh,37,0,b.qh):V(b.fh,37,0,
b.qh));return 0};function Qb(){if(m)return E(24,0,1);if(!Nj())return-1;Ij(mk);var a=bk[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0}var nk=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0};function Rb(){if(m)return E(27,0,1);Ij(nk);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0}
var Sb=()=>{D+=1;throw"unwind";};function Tb(){return m?E(28,0,1):"number"==typeof devicePixelRatio&&devicePixelRatio||1}function Ub(a,b,c){if(m)return E(29,0,1,a,b,c);a=T(a);if(!a)return-4;a=lk(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0}
var ok=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)r[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];r[a+1104]=b.connected;u[a+1108>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;B(b.id,t,a+1112,64);B(b.mapping,t,a+1176,64)};
function Vb(a,b){if(m)return E(30,0,1,a,b);if(0>a||a>=Oj.length)return-5;if(!Oj[a])return-7;ok(b,Oj[a]);return 0}function Xb(){return m?E(31,0,1):Oj.length}function Yb(a,b){if(m)return E(32,0,1,a,b);u[a>>2]=screen.width;u[b>>2]=screen.height}
var Zb=a=>P.activeTexture(a),$b=(a,b)=>{P.attachShader(J[a],K[b])},ac=(a,b)=>{P.beginQuery(a,M[b])},bc=(a,b)=>{P.Ug.beginQueryEXT(a,M[b])},cc=a=>P.beginTransformFeedback(a),dc=(a,b,c)=>{P.bindAttribLocation(J[a],b,c?z(t,c):"")},ec=(a,b)=>{34962==a?P.gh=b:34963==a&&(P.kh=b);35051==a?P.Dh=b:35052==a&&(P.Xg=b);P.bindBuffer(a,cj[b])},fc=(a,b,c)=>{P.bindBufferBase(a,b,cj[c])},gc=(a,b,c,d,e)=>{P.bindBufferRange(a,b,cj[c],d,e)},hc=(a,b)=>{P.bindFramebuffer(a,ej[b])},ic=(a,b)=>{P.bindRenderbuffer(a,fj[b])},
jc=(a,b)=>{P.bindSampler(a,N[b])},kc=(a,b)=>{P.bindTexture(a,gj[b])},lc=(a,b)=>{P.bindTransformFeedback(a,ij[b])},mc=a=>{P.bindVertexArray(hj[a]);a=P.getParameter(34965);P.kh=a?a.name|0:0},nc=(a,b,c,d)=>P.blendColor(a,b,c,d),oc=a=>P.blendEquation(a),pc=(a,b)=>P.blendEquationSeparate(a,b),sc=(a,b)=>P.blendFunc(a,b),tc=(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),uc=(a,b,c,d,e,f,g,k,n,q)=>P.blitFramebuffer(a,b,c,d,e,f,g,k,n,q),vc=(a,b,c,d)=>{2<=F.version?c&&b?P.bufferData(a,t,d,c,b):P.bufferData(a,b,d):
P.bufferData(a,c?t.subarray(c,c+b):b,d)},wc=(a,b,c,d)=>{2<=F.version?c&&P.bufferSubData(a,b,t,d,c):P.bufferSubData(a,b,t.subarray(d,d+c))},xc=a=>P.checkFramebufferStatus(a),yc=a=>P.clear(a),zc=(a,b,c,d)=>P.clearBufferfi(a,b,c,d),Ac=(a,b,c)=>{P.clearBufferfv(a,b,w,c>>2)},Bc=(a,b,c)=>{P.clearBufferiv(a,b,u,c>>2)},Cc=(a,b,c)=>{P.clearBufferuiv(a,b,v,c>>2)},Dc=(a,b,c,d)=>P.clearColor(a,b,c,d),Ec=a=>P.clearDepth(a),Fc=a=>P.clearStencil(a),Gc=(a,b,c,d)=>P.clientWaitSync(jj[a],b,(c>>>0)+4294967296*d),Hc=
(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},Ic=a=>{P.compileShader(K[a])},Jc=(a,b,c,d,e,f,g,k)=>{2<=F.version?P.Xg||!g?P.compressedTexImage2D(a,b,c,d,e,f,g,k):P.compressedTexImage2D(a,b,c,d,e,f,t,k,g):P.compressedTexImage2D(a,b,c,d,e,f,k?t.subarray(k,k+g):null)},Kc=(a,b,c,d,e,f,g,k,n)=>{P.Xg?P.compressedTexImage3D(a,b,c,d,e,f,g,k,n):P.compressedTexImage3D(a,b,c,d,e,f,g,t,n,k)},Lc=(a,b,c,d,e,f,g,k,n)=>{2<=F.version?P.Xg||!k?P.compressedTexSubImage2D(a,b,c,d,e,f,g,k,n):P.compressedTexSubImage2D(a,b,c,
d,e,f,g,t,n,k):P.compressedTexSubImage2D(a,b,c,d,e,f,g,n?t.subarray(n,n+k):null)},Mc=(a,b,c,d,e,f,g,k,n,q,y)=>{P.Xg?P.compressedTexSubImage3D(a,b,c,d,e,f,g,k,n,q,y):P.compressedTexSubImage3D(a,b,c,d,e,f,g,k,n,t,y,q)},Nc=(a,b,c,d,e)=>P.copyBufferSubData(a,b,c,d,e),Oc=(a,b,c,d,e,f,g,k)=>P.copyTexImage2D(a,b,c,d,e,f,g,k),Pc=(a,b,c,d,e,f,g,k)=>P.copyTexSubImage2D(a,b,c,d,e,f,g,k),Qc=(a,b,c,d,e,f,g,k,n)=>P.copyTexSubImage3D(a,b,c,d,e,f,g,k,n),Rc=()=>{var a=pj(J),b=P.createProgram();b.name=a;b.th=b.rh=
b.sh=0;b.Ih=1;J[a]=b;return a},Sc=a=>{var b=pj(K);K[b]=P.createShader(a);return b},Tc=a=>P.cullFace(a),Uc=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=cj[d];e&&(P.deleteBuffer(e),e.name=0,cj[d]=null,d==P.gh&&(P.gh=0),d==P.kh&&(P.kh=0),d==P.Dh&&(P.Dh=0),d==P.Xg&&(P.Xg=0))}},Vc=(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=ej[d];e&&(P.deleteFramebuffer(e),e.name=0,ej[d]=null)}},Wc=a=>{if(a){var b=J[a];b?(P.deleteProgram(b),b.name=0,J[a]=null):Q||=1281}},Xc=(a,b)=>{for(var c=0;c<a;c++){var d=
u[b+4*c>>2],e=M[d];e&&(P.deleteQuery(e),M[d]=null)}},Yc=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=M[d];e&&(P.Ug.deleteQueryEXT(e),M[d]=null)}},Zc=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=fj[d];e&&(P.deleteRenderbuffer(e),e.name=0,fj[d]=null)}},$c=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=N[d];e&&(P.deleteSampler(e),e.name=0,N[d]=null)}},ad=a=>{if(a){var b=K[a];b?(P.deleteShader(b),K[a]=null):Q||=1281}},bd=a=>{if(a){var b=jj[a];b?(P.deleteSync(b),b.name=0,jj[a]=null):Q||=1281}},
cd=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=gj[d];e&&(P.deleteTexture(e),e.name=0,gj[d]=null)}},dd=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=ij[d];e&&(P.deleteTransformFeedback(e),e.name=0,ij[d]=null)}},ed=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];P.deleteVertexArray(hj[d]);hj[d]=null}},fd=a=>P.depthFunc(a),gd=a=>{P.depthMask(!!a)},hd=(a,b)=>P.depthRange(a,b),jd=(a,b)=>{P.detachShader(J[a],K[b])},kd=a=>P.disable(a),ld=a=>{F.$g[a].enabled=!1;P.disableVertexAttribArray(a)},md=(a,
b,c)=>{sj(b+c);P.drawArrays(a,b,c);rj&&P.bindBuffer(34962,cj[P.gh])},nd=(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},pk=[],od=(a,b)=>{for(var c=pk[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];P.drawBuffers(c)},pd=(a,b,c,d)=>{if(!P.kh){var e=1*kj[c-5120]*b;var f=32-Math.clz32(0===e?0:e-1);var g=F.hh[f];g?f=g:(g=P.getParameter(34965),F.hh[f]=P.createBuffer(),P.bindBuffer(34963,F.hh[f]),P.bufferData(34963,1<<f,35048),P.bindBuffer(34963,g),f=F.hh[f]);P.bindBuffer(34963,f);P.bufferSubData(34963,0,t.subarray(d,d+e));
d=0}sj(b);P.drawElements(a,b,c,d);rj&&P.bindBuffer(34962,cj[P.gh]);P.kh||P.bindBuffer(34963,null)},qd=(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},rd=(a,b,c,d,e,f)=>{pd(a,d,e,f)},sd=a=>P.enable(a),td=a=>{F.$g[a].enabled=!0;P.enableVertexAttribArray(a)},ud=a=>P.endQuery(a),vd=a=>{P.Ug.endQueryEXT(a)},wd=()=>P.endTransformFeedback(),xd=(a,b)=>(a=P.fenceSync(a,b))?(b=pj(jj),a.name=b,jj[b]=a,b):0,yd=()=>P.finish(),zd=()=>P.flush(),qk=a=>{switch(a){case 34962:a=34964;break;case 34963:a=34965;break;
case 35051:a=35053;break;case 35052:a=35055;break;case 35982:a=35983;break;case 36662:a=36662;break;case 36663:a=36663;break;case 35345:a=35368}return(a=P.getParameter(a))?a.name|0:0},rk=a=>{switch(a){case 34962:case 34963:case 36662:case 36663:case 35051:case 35052:case 35882:case 35982:case 35345:return!0;default:return!1}},Ad=(a,b,c)=>{if(rk(a)){var d=dj[qk(a)];d?d.Kh&16?0>b||0>c||b+c>d.length?(Q||=1281,p("invalid range in glFlushMappedBufferRange")):P.bufferSubData(a,d.offset,t.subarray(d.Yg+
b,d.Yg+b+c)):(Q||=1282,p("buffer was not mapped with GL_MAP_FLUSH_EXPLICIT_BIT in glFlushMappedBufferRange")):(Q||=1282,p("buffer was never mapped in glFlushMappedBufferRange"))}else Q||=1280,p("GL_INVALID_ENUM in glFlushMappedBufferRange")},Bd=(a,b,c,d)=>{P.framebufferRenderbuffer(a,b,c,fj[d])},Cd=(a,b,c,d,e)=>{P.framebufferTexture2D(a,b,c,gj[d],e)},Dd=(a,b,c,d,e)=>{P.framebufferTextureLayer(a,b,gj[c],d,e)},Ed=a=>P.frontFace(a),Fd=(a,b)=>{qj(a,b,"createBuffer",cj)},Gd=(a,b)=>{qj(a,b,"createFramebuffer",
ej)},Hd=(a,b)=>{qj(a,b,"createQuery",M)},Id=(a,b)=>{for(var c=0;c<a;c++){var d=P.Ug.createQueryEXT();if(!d){for(Q||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=pj(M);d.name=e;M[e]=d;u[b+4*c>>2]=e}},Jd=(a,b)=>{qj(a,b,"createRenderbuffer",fj)},Kd=(a,b)=>{qj(a,b,"createSampler",N)},Ld=(a,b)=>{qj(a,b,"createTexture",gj)},Md=(a,b)=>{qj(a,b,"createTransformFeedback",ij)},Nd=(a,b)=>{qj(a,b,"createVertexArray",hj)},Od=a=>P.generateMipmap(a),sk=(a,b,c,d,e,f,g,k)=>{b=J[b];if(a=P[a](b,c))d=k&&B(a.name,t,k,d),e&&(u[e>>
2]=d),f&&(u[f>>2]=a.size),g&&(u[g>>2]=a.type)},Pd=(a,b,c,d,e,f,g)=>{sk("getActiveAttrib",a,b,c,d,e,f,g)},Qd=(a,b,c,d,e,f,g)=>{sk("getActiveUniform",a,b,c,d,e,f,g)},Rd=(a,b,c,d,e)=>{a=J[a];if(a=P.getActiveUniformBlockName(a,b))e&&0<c?(c=B(a,t,e,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0)},Sd=(a,b,c,d)=>{if(d)if(a=J[a],35393==c)u[d>>2]=P.getActiveUniformBlockName(a,b).length+1;else{if(a=P.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)u[d+4*c>>2]=a[c];else u[d>>2]=a}else Q||=
1281},Td=(a,b,c,d,e)=>{if(e)if(0<b&&0==c)Q||=1281;else{a=J[a];for(var f=[],g=0;g<b;g++)f.push(u[c+4*g>>2]);if(a=P.getActiveUniforms(a,f,d))for(b=a.length,g=0;g<b;g++)u[e+4*g>>2]=a[g]}else Q||=1281},Ud=(a,b,c,d)=>{a=P.getAttachedShaders(J[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=K.indexOf(a[b])},Vd=(a,b)=>P.getAttribLocation(J[a],b?z(t,b):""),tk=(a,b)=>{v[a>>2]=b;v[a+4>>2]=(b-v[a>>2])/4294967296};function uk(){var a=aj(P);return a=a.concat(a.map(b=>"GL_"+b))}
var vk=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(Q||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=P.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>F.version){Q||=1282;return}d=uk().length;break;case 33307:case 33308:if(2>F.version){Q||=1280;return}d=33307==a?3:0}if(void 0===d)switch(e=P.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Q||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=
0;break;default:Q||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:r[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){Q||=1280;p(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:Q||=1280;p(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:tk(b,d);break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:r[b]=d?1:0}}else Q||=1281},Wd=(a,b)=>vk(a,b,4),Xd=(a,b,c)=>{c?tk(c,P.getBufferParameter(a,b)):Q||=1281},Yd=(a,b,c)=>{c?u[c>>2]=P.getBufferParameter(a,b):Q||=1281},Zd=(a,b,c)=>{if(35005==b){b=0;if(a=dj[qk(a)])b=a.Yg;u[c>>2]=b}else Q||=1280,p("GL_INVALID_ENUM in glGetBufferPointerv")},$d=()=>{var a=P.getError()||Q;Q=0;return a},ae=(a,b)=>vk(a,b,2),be=(a,b)=>P.getFragDataLocation(J[a],b?z(t,b):""),ce=(a,b,c,d)=>
{a=P.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},wk=(a,b,c,d)=>{if(c){b=P.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:Q||=1280;return}else if(b instanceof WebGLBuffer)a=b.name|0;else{Q||=1280;return}break;default:Q||=1280;return}switch(d){case 1:tk(c,a);break;case 0:u[c>>2]=a;break;case 2:w[c>>
2]=a;break;case 4:r[c]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else Q||=1281},de=(a,b,c)=>wk(a,b,c,1),ee=(a,b)=>{vk(a,b,1)},fe=(a,b,c)=>wk(a,b,c,0),ge=(a,b)=>vk(a,b,0),he=(a,b,c,d,e)=>{if(0>d)Q||=1281;else if(e){if(a=P.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)u[e+4*b>>2]=a[b]}else Q||=1281},ie=()=>{Q||=1282},je=(a,b,c,d)=>{a=P.getProgramInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,t,d,b):0;c&&(u[c>>2]=b)},ke=
(a,b,c)=>{if(c)if(a>=bj)Q||=1281;else if(a=J[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.th)for(b=0;b<P.getProgramParameter(a,35718);++b)a.th=Math.max(a.th,P.getActiveUniform(a,b).name.length+1);u[c>>2]=a.th}else if(35722==b){if(!a.rh)for(b=0;b<P.getProgramParameter(a,35721);++b)a.rh=Math.max(a.rh,P.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.rh}else if(35381==b){if(!a.sh)for(b=0;b<P.getProgramParameter(a,35382);++b)a.sh=Math.max(a.sh,
P.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.sh}else u[c>>2]=P.getProgramParameter(a,b);else Q||=1281},le=(a,b,c)=>{if(c){a=M[a];b=2>F.version?P.Ug.getQueryObjectEXT(a,b):P.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;tk(c,d)}else Q||=1281},me=(a,b,c)=>{if(c){a=P.Ug.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else Q||=1281},ne=(a,b,c)=>{if(c){a=P.getQueryParameter(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else Q||=1281},oe=(a,b,c)=>
{c?u[c>>2]=P.getQuery(a,b):Q||=1281},pe=(a,b,c)=>{c?u[c>>2]=P.Ug.getQueryEXT(a,b):Q||=1281},qe=(a,b,c)=>{c?u[c>>2]=P.getRenderbufferParameter(a,b):Q||=1281},re=(a,b,c)=>{c?w[c>>2]=P.getSamplerParameter(N[a],b):Q||=1281},se=(a,b,c)=>{c?u[c>>2]=P.getSamplerParameter(N[a],b):Q||=1281},te=(a,b,c,d)=>{a=P.getShaderInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,t,d,b):0;c&&(u[c>>2]=b)},ue=(a,b,c,d)=>{a=P.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},
ve=(a,b,c,d)=>{if(a=P.getShaderSource(K[a]))b=0<b&&d?B(a,t,d,b):0,c&&(u[c>>2]=b)},we=(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(K[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(K[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=P.getShaderParameter(K[a],b):Q||=1281},xe=a=>{var b=lj[a];if(!b){switch(a){case 7939:b=Cj(uk().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=P.getParameter(a))||(Q||=1280);b=b?Cj(b):0;break;case 7938:b=P.getParameter(7938);b=2<=
F.version?`OpenGL ES 3.0 (${b})`:`OpenGL ES 2.0 (${b})`;b=Cj(b);break;case 35724:b=P.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Cj(b);break;default:Q||=1280}lj[a]=b}return b},ye=(a,b)=>{if(2>F.version)return Q||=1282,0;var c=mj[a];if(c)return 0>b||b>=c.length?(Q||=1281,0):c[b];switch(a){case 7939:return c=uk().map(Cj),c=mj[a]=c,0>b||b>=c.length?(Q||=1281,0):c[b];default:return Q||=
1280,0}},ze=(a,b,c,d,e)=>{0>c?Q||=1281:e?(a=P.getSyncParameter(jj[a],b),null!==a&&(u[e>>2]=a,d&&(u[d>>2]=1))):Q||=1281},Ae=(a,b,c)=>{c?w[c>>2]=P.getTexParameter(a,b):Q||=1281},Be=(a,b,c)=>{c?u[c>>2]=P.getTexParameter(a,b):Q||=1281},Ce=(a,b,c,d,e,f,g)=>{a=J[a];if(a=P.getTransformFeedbackVarying(a,b))g&&0<c?(c=B(a.name,t,g,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0),e&&(u[e>>2]=a.size),f&&(u[f>>2]=a.type)},De=(a,b)=>P.getUniformBlockIndex(J[a],b?z(t,b):""),Ee=(a,b,c,d)=>{if(d)if(0<b&&(0==c||0==d))Q||=1281;else{a=
J[a];for(var e=[],f=0;f<b;f++)e.push(fi(u[c+4*f>>2]));if(a=P.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)u[d+4*f>>2]=a[f]}else Q||=1281},xk=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),yk=a=>{var b=a.nh,c=a.Wh,d;if(!b)for(a.nh=b={},a.Vh={},d=0;d<P.getProgramParameter(a,35718);++d){var e=P.getActiveUniform(a,d);var f=e.name;e=e.size;var g=xk(f);g=0<g?f.slice(0,g):f;var k=a.Ih;a.Ih+=e;c[g]=[e,k];for(f=0;f<e;++f)b[k]=f,a.Vh[k++]=g}},Fe=(a,b)=>{b=b?z(t,b):"";if(a=J[a]){yk(a);var c=a.nh,d=0,e=b,f=xk(b);
0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Wh[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else Q||=1281;return-1},W=a=>{var b=P.Yh;if(b){var c=b.nh[a];"number"==typeof c&&(b.nh[a]=c=P.getUniformLocation(b,b.Vh[a]+(0<c?`[${c}]`:"")));return c}Q||=1282},zk=(a,b,c,d)=>{if(c)if(a=J[a],yk(a),a=P.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];
break;case 2:w[c+4*b>>2]=a[b]}else Q||=1281},Ge=(a,b,c)=>{zk(a,b,c,2)},He=(a,b,c)=>{zk(a,b,c,0)},Ie=(a,b,c)=>zk(a,b,c,0),Ak=(a,b,c,d)=>{if(c)if(F.$g[a].enabled&&p("glGetVertexAttrib*v on client-side array: not supported, bad data returned"),a=P.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+
4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else Q||=1281},Je=(a,b,c)=>{Ak(a,b,c,0)},Ke=(a,b,c)=>{c?(F.$g[a].enabled&&p("glGetVertexAttribPointer on client-side array: not supported, bad data returned"),u[c>>2]=P.getVertexAttribOffset(a,b)):Q||=1281},Le=(a,b,c)=>{Ak(a,b,c,2)},Me=(a,b,c)=>{Ak(a,b,c,5)},Ne=(a,b)=>P.hint(a,b),Oe=(a,b,c)=>{for(var d=pk[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];P.invalidateFramebuffer(a,d)},Pe=(a,b,c,d,e,f,g)=>{for(var k=pk[b],n=0;n<b;n++)k[n]=u[c+4*n>>2];P.invalidateSubFramebuffer(a,
k,d,e,f,g)},Qe=a=>(a=cj[a])?P.isBuffer(a):0,Re=a=>P.isEnabled(a),Se=a=>(a=ej[a])?P.isFramebuffer(a):0,Te=a=>(a=J[a])?P.isProgram(a):0,Ue=a=>(a=M[a])?P.isQuery(a):0,Ve=a=>(a=M[a])?P.Ug.isQueryEXT(a):0,We=a=>(a=fj[a])?P.isRenderbuffer(a):0,Xe=a=>(a=N[a])?P.isSampler(a):0,Ye=a=>(a=K[a])?P.isShader(a):0,Ze=a=>P.isSync(jj[a]),$e=a=>(a=gj[a])?P.isTexture(a):0,af=a=>P.isTransformFeedback(ij[a]),bf=a=>(a=hj[a])?P.isVertexArray(a):0,cf=a=>P.lineWidth(a),df=a=>{a=J[a];P.linkProgram(a);a.nh=0;a.Wh={}},ef=(a,
b,c,d)=>{if(0!=(d&33))return p("glMapBufferRange access does not support MAP_READ or MAP_UNSYNCHRONIZED"),0;if(0==(d&2))return p("glMapBufferRange access must include MAP_WRITE"),0;if(0==(d&12))return p("glMapBufferRange access must include INVALIDATE_BUFFER or INVALIDATE_RANGE"),0;if(!rk(a))return Q||=1280,p("GL_INVALID_ENUM in glMapBufferRange"),0;var e=A(c);a=qk(a);if(!e)return 0;dj[a]||(dj[a]={});a=dj[a];a.offset=b;a.length=c;a.Yg=e;a.Kh=d;return e},ff=()=>P.pauseTransformFeedback(),gf=(a,b)=>
{3317==a?nj=b:3314==a&&(oj=b);P.pixelStorei(a,b)},hf=(a,b)=>P.polygonOffset(a,b),jf=()=>{Q||=1280},kf=()=>{Q||=1280},lf=(a,b)=>{P.Ug.queryCounterEXT(M[a],b)},mf=a=>P.readBuffer(a),Bk=a=>{a-=5120;return 0==a?r:1==a?t:2==a?Na:4==a?u:6==a?w:5==a||28922==a||28520==a||30779==a||30782==a?v:Oa},Ck=(a,b,c,d,e)=>{a=Bk(a);b=d*((oj||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+nj-1&-nj);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},
nf=(a,b,c,d,e,f,g)=>{if(2<=F.version)if(P.Dh)P.readPixels(a,b,c,d,e,f,g);else{var k=Bk(f);g>>>=31-Math.clz32(k.BYTES_PER_ELEMENT);P.readPixels(a,b,c,d,e,f,k,g)}else(k=Ck(f,e,c,d,g))?P.readPixels(a,b,c,d,e,f,k):Q||=1280},of=()=>{},pf=(a,b,c,d)=>P.renderbufferStorage(a,b,c,d),qf=(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),rf=()=>P.resumeTransformFeedback(),sf=(a,b)=>{P.sampleCoverage(a,!!b)},tf=(a,b,c)=>{P.samplerParameterf(N[a],b,c)},uf=(a,b,c)=>{P.samplerParameterf(N[a],b,w[c>>2])},vf=
(a,b,c)=>{P.samplerParameteri(N[a],b,c)},wf=(a,b,c)=>{P.samplerParameteri(N[a],b,u[c>>2])},xf=(a,b,c,d)=>P.scissor(a,b,c,d),yf=()=>{Q||=1280},zf=(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=fi(v[c+4*f>>2],d?v[d+4*f>>2]:void 0);P.shaderSource(K[a],e)},Af=(a,b,c)=>P.stencilFunc(a,b,c),Bf=(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),Cf=a=>P.stencilMask(a),Df=(a,b)=>P.stencilMaskSeparate(a,b),Ef=(a,b,c)=>P.stencilOp(a,b,c),Ff=(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),Gf=(a,b,c,d,e,f,g,k,n)=>{if(2<=F.version){if(P.Xg){P.texImage2D(a,
b,c,d,e,f,g,k,n);return}if(n){var q=Bk(k);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,f,g,k,q,n);return}}q=n?Ck(k,g,d,e,n):null;P.texImage2D(a,b,c,d,e,f,g,k,q)},Hf=(a,b,c,d,e,f,g,k,n,q)=>{if(P.Xg)P.texImage3D(a,b,c,d,e,f,g,k,n,q);else if(q){var y=Bk(n);P.texImage3D(a,b,c,d,e,f,g,k,n,y,q>>>31-Math.clz32(y.BYTES_PER_ELEMENT))}else P.texImage3D(a,b,c,d,e,f,g,k,n,null)},If=(a,b,c)=>P.texParameterf(a,b,c),Jf=(a,b,c)=>{P.texParameterf(a,b,w[c>>2])},Kf=(a,b,c)=>P.texParameteri(a,b,c),
Lf=(a,b,c)=>{P.texParameteri(a,b,u[c>>2])},Mf=(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),Nf=(a,b,c,d,e,f)=>P.texStorage3D(a,b,c,d,e,f),Of=(a,b,c,d,e,f,g,k,n)=>{if(2<=F.version){if(P.Xg){P.texSubImage2D(a,b,c,d,e,f,g,k,n);return}if(n){var q=Bk(k);P.texSubImage2D(a,b,c,d,e,f,g,k,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}n=n?Ck(k,g,e,f,n):null;P.texSubImage2D(a,b,c,d,e,f,g,k,n)},Pf=(a,b,c,d,e,f,g,k,n,q,y)=>{if(P.Xg)P.texSubImage3D(a,b,c,d,e,f,g,k,n,q,y);else if(y){var H=Bk(q);P.texSubImage3D(a,b,
c,d,e,f,g,k,n,q,H,y>>>31-Math.clz32(H.BYTES_PER_ELEMENT))}else P.texSubImage3D(a,b,c,d,e,f,g,k,n,q,null)},Qf=(a,b,c,d)=>{a=J[a];for(var e=[],f=0;f<b;f++)e.push(fi(u[c+4*f>>2]));P.transformFeedbackVaryings(a,e,d)},Rf=(a,b)=>{P.uniform1f(W(a),b)},Dk=[],Sf=(a,b,c)=>{if(2<=F.version)b&&P.uniform1fv(W(a),w,c>>2,b);else{if(288>=b)for(var d=Dk[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);P.uniform1fv(W(a),d)}},Tf=(a,b)=>{P.uniform1i(W(a),b)},Ek=[],Uf=(a,b,c)=>{if(2<=F.version)b&&P.uniform1iv(W(a),
u,c>>2,b);else{if(288>=b)for(var d=Ek[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);P.uniform1iv(W(a),d)}},Vf=(a,b)=>{P.uniform1ui(W(a),b)},Wf=(a,b,c)=>{b&&P.uniform1uiv(W(a),v,c>>2,b)},Xf=(a,b,c)=>{P.uniform2f(W(a),b,c)},Yf=(a,b,c)=>{if(2<=F.version)b&&P.uniform2fv(W(a),w,c>>2,2*b);else{if(144>=b)for(var d=Dk[2*b],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);P.uniform2fv(W(a),d)}},Zf=(a,b,c)=>{P.uniform2i(W(a),b,c)},$f=(a,b,c)=>{if(2<=
F.version)b&&P.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b)for(var d=Ek[2*b],e=0;e<2*b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2];else d=u.subarray(c>>2,c+8*b>>2);P.uniform2iv(W(a),d)}},ag=(a,b,c)=>{P.uniform2ui(W(a),b,c)},bg=(a,b,c)=>{b&&P.uniform2uiv(W(a),v,c>>2,2*b)},cg=(a,b,c,d)=>{P.uniform3f(W(a),b,c,d)},dg=(a,b,c)=>{if(2<=F.version)b&&P.uniform3fv(W(a),w,c>>2,3*b);else{if(96>=b)for(var d=Dk[3*b],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>
2,c+12*b>>2);P.uniform3fv(W(a),d)}},eg=(a,b,c,d)=>{P.uniform3i(W(a),b,c,d)},fg=(a,b,c)=>{if(2<=F.version)b&&P.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b)for(var d=Ek[3*b],e=0;e<3*b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2];else d=u.subarray(c>>2,c+12*b>>2);P.uniform3iv(W(a),d)}},gg=(a,b,c,d)=>{P.uniform3ui(W(a),b,c,d)},hg=(a,b,c)=>{b&&P.uniform3uiv(W(a),v,c>>2,3*b)},ig=(a,b,c,d,e)=>{P.uniform4f(W(a),b,c,d,e)},jg=(a,b,c)=>{if(2<=F.version)b&&P.uniform4fv(W(a),w,c>>2,4*b);else{if(72>=
b){var d=Dk[4*b],e=w;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);P.uniform4fv(W(a),d)}},kg=(a,b,c,d,e)=>{P.uniform4i(W(a),b,c,d,e)},lg=(a,b,c)=>{if(2<=F.version)b&&P.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b)for(var d=Ek[4*b],e=0;e<4*b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2];else d=u.subarray(c>>2,c+16*b>>2);P.uniform4iv(W(a),d)}},mg=(a,b,c,d,e)=>{P.uniform4ui(W(a),
b,c,d,e)},ng=(a,b,c)=>{b&&P.uniform4uiv(W(a),v,c>>2,4*b)},og=(a,b,c)=>{a=J[a];P.uniformBlockBinding(a,b,c)},pg=(a,b,c,d)=>{if(2<=F.version)b&&P.uniformMatrix2fv(W(a),!!c,w,d>>2,4*b);else{if(72>=b)for(var e=Dk[4*b],f=0;f<4*b;f+=4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2];else e=w.subarray(d>>2,d+16*b>>2);P.uniformMatrix2fv(W(a),!!c,e)}},qg=(a,b,c,d)=>{b&&P.uniformMatrix2x3fv(W(a),!!c,w,d>>2,6*b)},rg=(a,b,c,d)=>{b&&P.uniformMatrix2x4fv(W(a),!!c,w,d>>2,8*
b)},sg=(a,b,c,d)=>{if(2<=F.version)b&&P.uniformMatrix3fv(W(a),!!c,w,d>>2,9*b);else{if(32>=b)for(var e=Dk[9*b],f=0;f<9*b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2];else e=w.subarray(d>>2,d+36*b>>2);P.uniformMatrix3fv(W(a),!!c,e)}},tg=(a,b,c,d)=>{b&&P.uniformMatrix3x2fv(W(a),!!c,w,d>>2,6*b)},ug=(a,b,c,d)=>{b&&P.uniformMatrix3x4fv(W(a),
!!c,w,d>>2,12*b)},vg=(a,b,c,d)=>{if(2<=F.version)b&&P.uniformMatrix4fv(W(a),!!c,w,d>>2,16*b);else{if(18>=b){var e=Dk[16*b],f=w;d>>=2;for(var g=0;g<16*b;g+=16){var k=d+g;e[g]=f[k];e[g+1]=f[k+1];e[g+2]=f[k+2];e[g+3]=f[k+3];e[g+4]=f[k+4];e[g+5]=f[k+5];e[g+6]=f[k+6];e[g+7]=f[k+7];e[g+8]=f[k+8];e[g+9]=f[k+9];e[g+10]=f[k+10];e[g+11]=f[k+11];e[g+12]=f[k+12];e[g+13]=f[k+13];e[g+14]=f[k+14];e[g+15]=f[k+15]}}else e=w.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(W(a),!!c,e)}},wg=(a,b,c,d)=>{b&&P.uniformMatrix4x2fv(W(a),
!!c,w,d>>2,8*b)},xg=(a,b,c,d)=>{b&&P.uniformMatrix4x3fv(W(a),!!c,w,d>>2,12*b)},yg=a=>{if(!rk(a))return Q||=1280,p("GL_INVALID_ENUM in glUnmapBuffer"),0;var b=dj[qk(a)];if(!b||!b.Yg)return Q||=1282,p("buffer was never mapped in glUnmapBuffer"),0;b.Kh&16||(2<=F.version?P.bufferSubData(a,b.offset,t,b.Yg,b.length):P.bufferSubData(a,b.offset,t.subarray(b.Yg,b.Yg+b.length)));Bj(b.Yg);b.Yg=0;return 1},zg=a=>{a=J[a];P.useProgram(a);P.Yh=a},Ag=a=>{P.validateProgram(J[a])},Bg=(a,b)=>P.vertexAttrib1f(a,b),Cg=
(a,b)=>{P.vertexAttrib1f(a,w[b>>2])},Dg=(a,b,c)=>P.vertexAttrib2f(a,b,c),Eg=(a,b)=>{P.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},Fg=(a,b,c,d)=>P.vertexAttrib3f(a,b,c,d),Gg=(a,b)=>{P.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},Hg=(a,b,c,d,e)=>P.vertexAttrib4f(a,b,c,d,e),Ig=(a,b)=>{P.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Jg=(a,b)=>{P.vertexAttribDivisor(a,b)},Kg=(a,b,c,d,e)=>P.vertexAttribI4i(a,b,c,d,e),Lg=(a,b)=>{P.vertexAttribI4i(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Mg=(a,b,
c,d,e)=>P.vertexAttribI4ui(a,b,c,d,e),Ng=(a,b)=>{P.vertexAttribI4ui(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},Og=(a,b,c,d,e)=>{var f=F.$g[a];P.gh?(f.jh=!1,P.vertexAttribIPointer(a,b,c,d,e)):(f.size=b,f.type=c,f.Fh=!1,f.xh=d,f.vh=e,f.jh=!0,f.Jh=function(g,k,n,q,y,H){this.vertexAttribIPointer(g,k,n,y,H)})},Pg=(a,b,c,d,e,f)=>{var g=F.$g[a];P.gh?(g.jh=!1,P.vertexAttribPointer(a,b,c,!!d,e,f)):(g.size=b,g.type=c,g.Fh=d,g.xh=e,g.vh=f,g.jh=!0,g.Jh=function(k,n,q,y,H,Z){this.vertexAttribPointer(k,n,q,y,H,
Z)})},Qg=(a,b,c,d)=>P.viewport(a,b,c,d),Rg=(a,b,c,d)=>{P.waitSync(jj[a],b,(c>>>0)+4294967296*d)},Sg=()=>1,Fk=(a,b)=>{if(!Nj())return-1;a=T(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Jj()?mk(a,b):b.bi?(Hj(mk,1,[a,b]),1):-2:-3:-4};function Tg(a,b,c){return m?E(33,0,1,a,b,c):Fk(a,{Gh:u[c>>2],Bh:u[c+4>>2],di:u[c+8>>2],bi:b,ph:u[c+20>>2],fh:u[c+12>>2],qh:u[c+16>>2]})}function Ug(a,b){if(m)return E(34,0,1,a,b);a=T(a);return a?a.requestPointerLock?Jj()?nk(a):b?(Hj(nk,2,[a]),1):-2:-1:-4}
var Vg=()=>{Za("OOM")};function Wg(){if(m)return E(35,0,1);try{if(navigator.getGamepads)return(Oj=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1}var Gk=(a,b)=>{var c={target:T(2),Pg:"beforeunload",Tg:b,Vg:(d=event)=>{var e=V(b,28,0,a);e&&=e?z(t,e):"";if(e)return d.preventDefault(),d.returnValue=e},Sg:!0};return R(c)};function Xg(a,b,c){return m?E(36,0,1,a,b,c):"undefined"==typeof onbeforeunload?-1:1!==c?-5:Gk(a,b)}
var Hk=(a,b,c,d,e,f,g)=>{g=S(g);Pj||=A(256);a={target:T(a),Pg:f,Tg:d,Vg:(k=event)=>{var n=Mj(k.target),q=k.target.id?k.target.id:"",y=g?A(256):Pj;B(n,t,y+0,128);B(q,t,y+128,128);g?U(g,d,e,y,b):V(d,e,y,b)&&k.preventDefault()},Sg:c};return R(a)};function Yg(a,b,c,d,e){return m?E(37,0,1,a,b,c,d,e):Hk(a,b,c,d,12,"blur",e)}function $g(a,b,c){if(m)return E(38,0,1,a,b,c);a=T(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0}
function ah(a,b,c,d,e){return m?E(39,0,1,a,b,c,d,e):Hk(a,b,c,d,13,"focus",e)}
var Ik=(a,b,c,d,e,f)=>{f=S(f);Rj||=A(276);return R({target:a,Pg:e,Tg:d,Vg:(g=event)=>{var k=f?A(276):Rj,n=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,q=!!n;r[k]=q;r[k+1]=Nj();var y=q?n:Qj,H=y?.id||"";B(Mj(y),t,k+2,128);B(H,t,k+130,128);u[k+260>>2]=y?y.clientWidth:0;u[k+264>>2]=y?y.clientHeight:0;u[k+268>>2]=screen.width;u[k+272>>2]=screen.height;q&&(Qj=n);f?U(f,d,19,k,b):V(d,19,k,b)&&g.preventDefault()},Sg:c})};
function bh(a,b,c,d,e){if(m)return E(40,0,1,a,b,c,d,e);if(!Nj())return-1;a=T(a);if(!a)return-4;Ik(a,b,c,d,"webkitfullscreenchange",e);return Ik(a,b,c,d,"fullscreenchange",e)}var Jk=(a,b,c,d,e,f)=>{f=S(f);Sj||=A(1240);b={target:T(2),oh:!0,Pg:e,Tg:c,Vg:(g=event)=>{var k=f?A(1240):Sj;ok(k,g.gamepad);f?U(f,c,d,k,a):V(c,d,k,a)&&g.preventDefault()},Sg:b};return R(b)};function ch(a,b,c,d){return m?E(41,0,1,a,b,c,d):Wg()?-1:Jk(a,b,c,26,"gamepadconnected",d)}
function dh(a,b,c,d){return m?E(42,0,1,a,b,c,d):Wg()?-1:Jk(a,b,c,27,"gamepaddisconnected",d)}
var Kk=(a,b,c,d,e,f,g)=>{g=S(g);Tj||=A(160);a={target:T(a),Pg:f,Tg:d,Vg:k=>{var n=g?A(160):Tj;x[n>>3]=k.timeStamp;var q=n>>2;u[q+2]=k.location;r[n+12]=k.ctrlKey;r[n+13]=k.shiftKey;r[n+14]=k.altKey;r[n+15]=k.metaKey;r[n+16]=k.repeat;u[q+5]=k.charCode;u[q+6]=k.keyCode;u[q+7]=k.which;B(k.key||"",t,n+32,32);B(k.code||"",t,n+64,32);B(k.char||"",t,n+96,32);B(k.locale||"",t,n+128,32);g?U(g,d,e,n,b):V(d,e,n,b)&&k.preventDefault()},Sg:c};return R(a)};
function eh(a,b,c,d,e){return m?E(43,0,1,a,b,c,d,e):Kk(a,b,c,d,2,"keydown",e)}function fh(a,b,c,d,e){return m?E(44,0,1,a,b,c,d,e):Kk(a,b,c,d,1,"keypress",e)}function gh(a,b,c,d,e){return m?E(45,0,1,a,b,c,d,e):Kk(a,b,c,d,3,"keyup",e)}
var Lk=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;Na[2*d+14]=b.button;Na[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=lk(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},Mk=(a,b,c,d,e,f,g)=>{g=S(g);Uj||=A(64);a=T(a);return R({target:a,oh:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Pg:f,Tg:d,Vg:(k=event)=>{Lk(Uj,k,a);if(g){var n=A(64);
Lk(n,k,a);U(g,d,e,n,b)}else V(d,e,Uj,b)&&k.preventDefault()},Sg:c})};function hh(a,b,c,d,e){return m?E(46,0,1,a,b,c,d,e):Mk(a,b,c,d,5,"mousedown",e)}function ih(a,b,c,d,e){return m?E(47,0,1,a,b,c,d,e):Mk(a,b,c,d,33,"mouseenter",e)}function jh(a,b,c,d,e){return m?E(48,0,1,a,b,c,d,e):Mk(a,b,c,d,34,"mouseleave",e)}function kh(a,b,c,d,e){return m?E(49,0,1,a,b,c,d,e):Mk(a,b,c,d,8,"mousemove",e)}function lh(a,b,c,d,e){return m?E(50,0,1,a,b,c,d,e):Mk(a,b,c,d,6,"mouseup",e)}
var Nk=(a,b,c,d,e,f)=>{f=S(f);Vj||=A(257);return R({target:a,Pg:e,Tg:d,Vg:(g=event)=>{var k=f?A(257):Vj,n=document.pointerLockElement||document.eh||document.Ah||document.zh;r[k]=!!n;var q=n?.id||"";B(Mj(n),t,k+1,128);B(q,t,k+129,128);f?U(f,d,20,k,b):V(d,20,k,b)&&g.preventDefault()},Sg:c})};
function mh(a,b,c,d,e){if(m)return E(51,0,1,a,b,c,d,e);if(!document||!document.body||!(document.body.requestPointerLock||document.body.eh||document.body.Ah||document.body.zh))return-1;a=T(a);if(!a)return-4;Nk(a,b,c,d,"mozpointerlockchange",e);Nk(a,b,c,d,"webkitpointerlockchange",e);Nk(a,b,c,d,"mspointerlockchange",e);return Nk(a,b,c,d,"pointerlockchange",e)}
var Ok=(a,b,c,d,e)=>{e=S(e);Wj||=A(36);a=T(a);return R({target:a,Pg:"resize",Tg:d,Vg:(f=event)=>{if(f.target==a){var g=document.body;if(g){var k=e?A(36):Wj;u[k>>2]=0;u[k+4>>2]=g.clientWidth;u[k+8>>2]=g.clientHeight;u[k+12>>2]=innerWidth;u[k+16>>2]=innerHeight;u[k+20>>2]=outerWidth;u[k+24>>2]=outerHeight;u[k+28>>2]=pageXOffset|0;u[k+32>>2]=pageYOffset|0;e?U(e,d,10,k,b):V(d,10,k,b)&&f.preventDefault()}}},Sg:c})};function nh(a,b,c,d,e){return m?E(52,0,1,a,b,c,d,e):Ok(a,b,c,d,e)}
var Pk=(a,b,c,d,e,f,g)=>{g=S(g);Xj||=A(1552);a=T(a);return R({target:a,oh:"touchstart"==f||"touchend"==f,Pg:f,Tg:d,Vg:k=>{var n={},q=k.touches;for(var y of q)y.Rh=y.Th=0,n[y.identifier]=y;for(var H of k.changedTouches)H.Rh=1,n[H.identifier]=H;for(var Z of k.targetTouches)n[Z.identifier].Th=1;q=g?A(1552):Xj;x[q>>3]=k.timeStamp;r[q+12]=k.ctrlKey;r[q+13]=k.shiftKey;r[q+14]=k.altKey;r[q+15]=k.metaKey;y=q+16;H=lk(a);Z=0;for(let O of Object.values(n))if(n=y>>2,u[n]=O.identifier,u[n+1]=O.screenX,u[n+2]=
O.screenY,u[n+3]=O.clientX,u[n+4]=O.clientY,u[n+5]=O.pageX,u[n+6]=O.pageY,r[y+28]=O.Rh,r[y+29]=O.Th,u[n+8]=O.clientX-(H.left|0),u[n+9]=O.clientY-(H.top|0),y+=48,31<++Z)break;u[q+8>>2]=Z;g?U(g,d,e,q,b):V(d,e,q,b)&&k.preventDefault()},Sg:c})};function oh(a,b,c,d,e){return m?E(53,0,1,a,b,c,d,e):Pk(a,b,c,d,25,"touchcancel",e)}function ph(a,b,c,d,e){return m?E(54,0,1,a,b,c,d,e):Pk(a,b,c,d,23,"touchend",e)}function qh(a,b,c,d,e){return m?E(55,0,1,a,b,c,d,e):Pk(a,b,c,d,24,"touchmove",e)}
function rh(a,b,c,d,e){return m?E(56,0,1,a,b,c,d,e):Pk(a,b,c,d,22,"touchstart",e)}var Qk=(a,b,c,d)=>{var e=bk[1];d=S(d);Yj||=A(8);return R({target:e,Pg:"visibilitychange",Tg:c,Vg:(f=event)=>{var g=d?A(8):Yj,k=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);r[g]=document.hidden;u[g+4>>2]=k;d?U(d,c,21,g,a):V(c,21,g,a)&&f.preventDefault()},Sg:b})};function sh(a,b,c,d){return m?E(57,0,1,a,b,c,d):bk[1]?Qk(a,b,c,d):-4}
var Rk=(a,b,c,d,e)=>{e=S(e);Zj||=A(96);return R({target:a,oh:!0,Pg:"wheel",Tg:d,Vg:(f=event)=>{var g=e?A(96):Zj;Lk(g,f,a);x[g+64>>3]=f.deltaX;x[g+72>>3]=f.deltaY;x[g+80>>3]=f.deltaZ;u[g+88>>2]=f.deltaMode;e?U(e,d,9,g,b):V(d,9,g,b)&&f.preventDefault()},Sg:c})};function th(a,b,c,d,e){return m?E(58,0,1,a,b,c,d,e):(a=T(a))?"undefined"!=typeof a.onwheel?Rk(a,b,c,d,e):-1:-4}function uh(a){return m?E(59,0,1,a):document.title=a?z(t,a):""}
var vh=a=>Sk(b=>Bi(b,a)),Tk={},Vk=()=>{if(!Uk){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in Tk)void 0===Tk[b]?delete a[b]:a[b]=Tk[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Uk=c}return Uk},Uk;
function wh(a,b){if(m)return E(60,0,1,a,b);var c=0;Vk().forEach((d,e)=>{var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)r[e++]=d.charCodeAt(f);r[e]=0;c+=d.length+1});return 0}function xh(a,b){if(m)return E(61,0,1,a,b);var c=Vk();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);v[b>>2]=d;return 0}function zh(a){return m?E(62,0,1,a):52}function Ah(a,b,c,d){return m?E(63,0,1,a,b,c,d):52}function Bh(a,b,c,d,e){return m?E(64,0,1,a,b,c,d,e):70}var Wk=[null,[],[]];
function Ch(a,b,c,d){if(m)return E(65,0,1,a,b,c,d);for(var e=0,f=0;f<c;f++){var g=v[b>>2],k=v[b+4>>2];b+=8;for(var n=0;n<k;n++){var q=t[g+n],y=Wk[a];0===q||10===q?((1===a?ra:p)(z(y,0)),y.length=0):y.push(q)}e+=k}v[d>>2]=e;return 0}
var Xk=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Eh=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Xk(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Fh=(a,b=[])=>{var c="vi".replace(/p/g,"i");(0,h["dynCall_"+c])(a,...b)},Yk=a=>{try{a()}catch(b){Za(b)}};
function Zk(){var a=X,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{$k.push(c);try{return d(...e)}finally{La||($k.pop(),al&&1===bl&&0===$k.length&&(bl=0,D+=1,Yk(cl),"undefined"!=typeof Fibers&&Fibers.Ai()))}}:d;return b}var bl=0,al=null,dl=0,$k=[],jl={},kl={},ll=0,ml=null,nl=[];function ol(){var a=A(4108),b=a+12;v[a>>2]=b;v[a+4>>2]=b+4096;b=$k[0];var c=jl[b];void 0===c&&(c=ll++,jl[b]=c,kl[c]=b);u[a+8>>2]=c;return a}function pl(){var a=X[kl[u[al+8>>2]]];--D;return a()}
function Sk(a){if(!La){if(0===bl){var b=!1,c=!1;a((d=0)=>{if(!La&&(dl=d,b=!0,c)){bl=2;Yk(()=>ql(al));"undefined"!=typeof Ri&&ni&&Di();d=!1;try{var e=pl()}catch(k){e=k,d=!0}var f=!1;if(!al){var g=ml;g&&(ml=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(bl=1,al=ol(),"undefined"!=typeof Ri&&ni&&Ci(),Yk(()=>rl(al)))}else 2===bl?(bl=0,Yk(sl),Bj(al),al=null,nl.forEach(hi)):Za(`invalid state: ${bl}`);return dl}}m?Th=!1:Xh();
h.requestFullscreen=function(a,b){function c(){Ei=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Mi,Ki&&d.requestPointerLock(),Ei=!0,Li?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>2]|8388608),Qi(h.canvas),Pi()):Qi(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Li?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=
v[SDL.screen>>2]&-8388609),Qi(h.canvas),Pi()):Qi(d));h.onFullScreen?.(Ei);h.onFullscreen?.(Ei)}Ki=a;Li=b;"undefined"==typeof Ki&&(Ki=!0);"undefined"==typeof Li&&(Li=!1);var d=h.canvas;Ji||(Ji=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=si;h.setCanvasSize=function(a,b,c){Qi(h.canvas,a,b);c||Pi()};h.pauseMainLoop=Ci;h.resumeMainLoop=Di;
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.Wg&&a==h.canvas)return h.Wg;var e;if(b){var f={antialias:!1,alpha:!1,Eh:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof xj&&(e=uj(a,f)))var k=L[e].Rg}else k=a.getContext("2d");if(!k)return null;c&&(h.Wg=k,b&&wj(e),h.ki=b,Gi.forEach(n=>n()),Hi());return k};
for(var P,Y=0;32>Y;++Y)pk.push(Array(Y));var tl=new Float32Array(288);for(Y=0;288>=Y;++Y)Dk[Y]=tl.subarray(0,Y);var ul=new Int32Array(288);for(Y=0;288>=Y;++Y)Ek[Y]=ul.subarray(0,Y);
var ki=[Dh,Vh,gi,kb,lb,mb,sb,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Qb,dk,hk,Rb,Tb,Ub,Vb,Xb,Yb,Tg,Ug,Wg,Xg,Yg,$g,ah,bh,ch,dh,eh,fh,gh,hh,ih,jh,kh,lh,mh,nh,oh,ph,qh,rh,sh,th,uh,wh,xh,zh,Ah,Bh,Ch],gb,X=function(){function a(c,d){X=c.exports;X=Zk();Wh.push(X.Nf);Ra.unshift(X.Lf);Ka=d;Ya();return X}var b=wa();Xa();if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return p(`Module.instantiateWasm callback failed with error: ${c}`),!1}ab||=$a("destruct.wasm")?"destruct.wasm":h.locateFile?
h.locateFile("destruct.wasm",ja):ja+"destruct.wasm";fb(b,function(c){a(c.instance,c.module)});return{}}(),vl=h._main=(a,b)=>(vl=h._main=X.Mf)(a,b),va=()=>(va=X.Of)(),U=(a,b,c,d,e)=>(U=X.Pf)(a,b,c,d,e),Ba=(a,b,c,d,e,f)=>(Ba=X.Qf)(a,b,c,d,e,f),Ia=()=>(Ia=X.Rf)(),Rh=(a,b,c,d,e)=>(Rh=X.Sf)(a,b,c,d,e),Zh=a=>(Zh=X.Tf)(a),Ga=a=>(Ga=X.Uf)(a),ii=()=>(ii=X.Vf)(),Bj=a=>(Bj=X.Wf)(a),A=a=>(A=X.Yf)(a),di=(a,b)=>(di=X.Zf)(a,b),Sh=a=>(Sh=X._f)(a),Qh=a=>(Qh=X.$f)(a),Ph=()=>(Ph=X.ag)(),ei=h.dynCall_ii=(a,b)=>(ei=h.dynCall_ii=
X.bg)(a,b),dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=X.cg)(a,b),dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=X.dg)(a,b,c);h.dynCall_viiii=(a,b,c,d,e)=>(h.dynCall_viiii=X.eg)(a,b,c,d,e);h.dynCall_iiiii=(a,b,c,d,e)=>(h.dynCall_iiiii=X.fg)(a,b,c,d,e);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=X.gg)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=X.hg)(a,b);var V=h.dynCall_iiii=(a,b,c,d)=>(V=h.dynCall_iiii=X.ig)(a,b,c,d);h.dynCall_i=a=>(h.dynCall_i=X.jg)(a);
var dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=X.kg)(a),dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=X.lg)(a,b,c);h.dynCall_iiiiii=(a,b,c,d,e,f)=>(h.dynCall_iiiiii=X.mg)(a,b,c,d,e,f);h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=X.ng)(a,b,c,d,e,f);h.dynCall_viii=(a,b,c,d)=>(h.dynCall_viii=X.og)(a,b,c,d);h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,k)=>(h.dynCall_iiiiiiii=X.pg)(a,b,c,d,e,f,g,k);
h.dynCall_iiiiiiiiii=(a,b,c,d,e,f,g,k,n,q)=>(h.dynCall_iiiiiiiiii=X.qg)(a,b,c,d,e,f,g,k,n,q);h.dynCall_iiiiiiiiiiiiiiff=(a,b,c,d,e,f,g,k,n,q,y,H,Z,O,qc,rc)=>(h.dynCall_iiiiiiiiiiiiiiff=X.rg)(a,b,c,d,e,f,g,k,n,q,y,H,Z,O,qc,rc);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,k,n)=>(h.dynCall_iiiiiiiii=X.sg)(a,b,c,d,e,f,g,k,n);h.dynCall_viiiiiii=(a,b,c,d,e,f,g,k)=>(h.dynCall_viiiiiii=X.tg)(a,b,c,d,e,f,g,k);h.dynCall_viiiiiiiiiii=(a,b,c,d,e,f,g,k,n,q,y,H)=>(h.dynCall_viiiiiiiiiii=X.ug)(a,b,c,d,e,f,g,k,n,q,y,H);
h.dynCall_iiiiiidiiff=(a,b,c,d,e,f,g,k,n,q,y)=>(h.dynCall_iiiiiidiiff=X.vg)(a,b,c,d,e,f,g,k,n,q,y);h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=X.wg)(a,b,c,d,e,f,g);h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=X.xg)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=X.yg)(a,b);h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,k,n)=>(h.dynCall_viiiiiiii=X.zg)(a,b,c,d,e,f,g,k,n);h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,k,n,q)=>(h.dynCall_viiiiiiiii=X.Ag)(a,b,c,d,e,f,g,k,n,q);
h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=X.Bg)(a,b,c);h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=X.Cg)(a,b,c);h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=X.Dg)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=X.Eg)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=X.Fg)(a,b,c,d);h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=X.Gg)(a,b,c,d,e);h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=X.Hg)(a,b,c,d,e,f);h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_viiiiii=X.Ig)(a,b,c,d,e,f,g);
h.dynCall_viiiiiiiiii=(a,b,c,d,e,f,g,k,n,q,y)=>(h.dynCall_viiiiiiiiii=X.Jg)(a,b,c,d,e,f,g,k,n,q,y);h.dynCall_viifi=(a,b,c,d,e)=>(h.dynCall_viifi=X.Kg)(a,b,c,d,e);var rl=a=>(rl=X.Lg)(a),cl=()=>(cl=X.Mg)(),ql=a=>(ql=X.Ng)(a),sl=()=>(sl=X.Og)(),wl;Wa=function xl(){wl||yl();wl||(Wa=xl)};function zl(a=[]){var b=vl;a.unshift(fa);var c=a.length,d=Qh(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=ek(g);e+=4});v[e>>2]=0;try{var f=b(c,d);yh(f,!0)}catch(g){Uh(g)}}
function yl(){var a=ea;function b(){if(!wl&&(wl=!0,h.calledRun=!0,!La&&(m||ci(Ra),m||ci(Sa),h.onRuntimeInitialized?.(),Al&&zl(a),!m))){if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Ta.unshift(c)}ci(Ta)}}if(!(0<Ua))if(m)m||ci(Ra),startWorker(h);else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Qa.unshift(h.preRun.shift());ci(Qa);0<Ua||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},
1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Al=!0;h.noInitialRun&&(Al=!1);yl();
