var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="function"==typeof importScripts,l="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,m=ba&&"em-pthread"==self.name;if(l){var ca=require("worker_threads");global.Worker=ca.Worker;m=(ba=!ca.Ai)&&"em-pthread"==ca.workerData}
var da=Object.assign({},h),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},ia="undefined"!=typeof document?document.currentScript?.src:void 0;l?ia=__filename:ba&&(ia=self.location.href);var ja="",ka,la;
if(l){var fs=require("fs"),ma=require("path");ja=__dirname+"/";la=a=>{a=na(a)?new URL(a):ma.normalize(a);return fs.readFileSync(a)};ka=a=>{a=na(a)?new URL(a):ma.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(d,e)=>{d?c(d):b(e.buffer)})})};!h.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);process.on("uncaughtException",a=>{if(!("unwind"===a||a instanceof oa||a.context instanceof oa))throw a;
});ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?ja=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ja=document.currentScript.src),ja=ja.startsWith("blob:")?"":ja.substr(0,ja.replace(/[?#].*/,"").lastIndexOf("/")+1),l||(ba&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ka=a=>na(a)?new Promise((b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=
()=>{(200==d.status||0==d.status&&d.response)&&c(d.response);b(d.status)};d.onerror=b;d.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url))));l&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var pa=console.log.bind(console),qa=console.error.bind(console);l&&(pa=(...a)=>fs.writeSync(1,a.join(" ")+"\n"),qa=(...a)=>fs.writeSync(2,a.join(" ")+"\n"));var ra=h.print||pa,p=h.printErr||qa;
Object.assign(h,da);da=null;h.arguments&&(ea=h.arguments);h.thisProgram&&(fa=h.thisProgram);h.quit&&(ha=h.quit);
if(m){var sa;if(l){var ta=ca.parentPort;ta.on("message",c=>onmessage({data:c}));Object.assign(globalThis,{self:global,importScripts:()=>{},postMessage:c=>ta.postMessage(c),performance:global.performance||{now:Date.now}})}var ua=!1;function a(...c){c=c.join(" ");l?fs.writeSync(2,c+"\n"):console.error(c)}h.printErr||(p=a);self.alert=function(...c){postMessage({Vh:"alert",text:c.join(" "),Gi:va()})};h.instantiateWasm=(c,d)=>new Promise(e=>{sa=f=>{f=new WebAssembly.Instance(f,wa());d(f);e()}});self.onunhandledrejection=
c=>{throw c.reason||c;};function b(c){try{var d=c.data,e=d.cmd;if("load"===e){let f=[];self.onmessage=g=>f.push(g);self.startWorker=()=>{postMessage({cmd:"loaded"});for(let g of f)b(g);self.onmessage=b};for(const g of d.handlers)if(!h[g]||h[g].proxy)h[g]=(...k)=>{postMessage({Vh:"callHandler",zi:g,args:k})},"print"==g&&(ra=h[g]),"printErr"==g&&(p=h[g]);xa=d.wasmMemory;ya();za=Aa(d.wasmOffsetConverter);sa(d.wasmModule)}else if("run"===e){Ba(d.pthread_ptr,0,0,1,0,0);Ca(d.pthread_ptr);Da();Ea();ua||=
!0;try{Fa(d.start_routine,d.arg)}catch(f){if("unwind"!=f)throw f;}}else"cancel"===e?va()&&Ga(-1):"setimmediate"!==d.target&&("checkMailbox"===e?ua&&Ha():e&&(p(`worker: received unknown command ${e}`),p(d)))}catch(f){throw Ia(),f;}}self.onmessage=b}var Ja;h.wasmBinary&&(Ja=h.wasmBinary);var xa,Ka,La=!1,Ma,r,t,Na,Oa,u,v,w,x;
function ya(){var a=xa.buffer;h.HEAP8=r=new Int8Array(a);h.HEAP16=Na=new Int16Array(a);h.HEAPU8=t=new Uint8Array(a);h.HEAPU16=Oa=new Uint16Array(a);h.HEAP32=u=new Int32Array(a);h.HEAPU32=v=new Uint32Array(a);h.HEAPF32=w=new Float32Array(a);h.HEAPF64=x=new Float64Array(a)}
if(!m){if(h.wasmMemory)xa=h.wasmMemory;else{var Pa=h.INITIAL_MEMORY||67108864;xa=new WebAssembly.Memory({initial:Pa/65536,maximum:Pa/65536,shared:!0});if(!(xa.buffer instanceof SharedArrayBuffer))throw p("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),l&&p("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),
Error("bad memory");}ya()}var Qa=[],Ra=[],Sa=[],Ta=[],Ua=0,Va=null,Wa=null;function Xa(){Ua++;h.monitorRunDependencies?.(Ua)}function Ya(){Ua--;h.monitorRunDependencies?.(Ua);if(0==Ua&&(null!==Va&&(clearInterval(Va),Va=null),Wa)){var a=Wa;Wa=null;a()}}function Za(a){h.onAbort?.(a);a="Aborted("+a+")";p(a);La=!0;Ma=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var $a=a=>a.startsWith("data:application/octet-stream;base64,"),na=a=>a.startsWith("file://"),ab;
function bb(a){if(a==ab&&Ja)return new Uint8Array(Ja);if(la)return la(a);throw"both async and sync fetching of the wasm failed";}function cb(a){return Ja?Promise.resolve().then(()=>bb(a)):ka(a).then(b=>new Uint8Array(b),()=>bb(a))}var za;
function db(a,b){function c(){var n=0,q=0;do{var y=g[e++];n+=(y&127)<<q;q+=7}while(y&128);return n}function d(){var n=c();c();0!=(n&1)&&c()}var e=8,f=0;this.Hh={};this.oh=[];this.Gh={};var g=a;a:for(;e<g.length;){a=g[e++];var k=c()+e;switch(a){case 2:for(a=c();0<a--;)switch(e=c()+e,e=c()+e,g[e++]){case 0:++f;c();break;case 1:c();d();break;case 2:d();break;case 3:e+=2;break;case 4:++e,c()}break;case 10:for(a=c();0<a--;)k=c(),this.Hh[f++]=e,this.oh.push(e),e+=k;break a}e=k}b=WebAssembly.Module.customSections(b,
"name");if(b=b.length?b[0]:void 0)for(g=new Uint8Array(b),e=0;e<g.length;)if(b=g[e++],f=c(),1!=b)e+=f;else for(a=c();0<a--;)b=c(),f=c(),this.Gh[b]=z(g,e,f),e+=f}function Aa(a){var b=Object.create(db.prototype);return Object.assign(b,a)}function eb(a,b,c){var d;return cb(a).then(e=>{d=e;return WebAssembly.instantiate(e,b)}).then(e=>{za=new db(d,e.module);return e}).then(c,e=>{p(`failed to asynchronously prepare wasm: ${e}`);Za(e)})}
function fb(a,b){var c=ab;Ja||"function"!=typeof WebAssembly.instantiateStreaming||$a(c)||na(c)||l||"function"!=typeof fetch?eb(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>{var e=WebAssembly.instantiateStreaming(d,a),f=d.clone().arrayBuffer();return e.then(function(g){f.then(k=>{za=new db(new Uint8Array(k),g.module);b(g)},k=>p(`failed to initialize offset-converter: ${k}`))},function(g){p(`wasm streaming compile failed: ${g}`);p("falling back to ArrayBuffer instantiation");return eb(c,a,b)})})}
function wa(){gb={hf:hb,Ec:ib,Ye:jb,N:kb,Db:lb,_b:mb,hb:nb,cb:ob,tc:pb,sb:qb,tf:rb,Ea:sb,Pf:tb,ta:ub,_:vb,_c:wb,P:xb,Ef:Ca,Pd:yb,rb:zb,Wa:Ab,ib:Bb,kb:Cb,jb:Db,lb:Eb,Xa:Fb,m:Gb,gb:Hb,Ua:Ib,mb:Jb,fb:Kb,nb:Lb,ob:Mb,Va:Nb,qb:Ob,pb:Pb,Za:Qb,c:Rb,M:Sb,te:Tb,k:Ub,l:Vb,_a:Wb,db:Xb,Pb:Yb,ie:Zb,g:$b,e:ac,p:bc,d:cc,bb:dc,eb:ec,za:fc,ya:gc,od:hc,Qa:ic,Sc:jc,xa:kc,wa:lc,Oc:mc,Qc:nc,va:oc,ua:pc,Tb:qc,sa:rc,Jb:uc,Xc:vc,Ia:vc,ra:wc,qa:xc,pa:yc,oa:zc,na:Ac,bd:Bc,ma:Cc,la:Dc,ka:Ec,ja:Fc,pc:Gc,qc:Hc,sc:Ic,rc:Jc,ia:Kc,
ha:Lc,ga:Mc,bc:Nc,fa:Oc,ea:Pc,da:Qc,td:Rc,ca:Sc,sd:Tc,nc:Uc,ba:Vc,aa:Wc,ud:Xc,$:Yc,Z:Zc,Y:$c,X:ad,W:bd,V:cd,qd:dd,Sa:ed,U:fd,Vb:gd,T:hd,cc:jd,S:kd,Ib:ld,Wc:md,Ha:md,R:nd,Q:od,Of:pd,Nf:qd,Mf:rd,Lf:sd,Kf:td,gc:ud,Ca:ud,Ed:ud,Fd:ud,tb:ud,id:vd,zd:vd,Da:vd,Jf:wd,fc:xd,Ba:xd,Ad:xd,Bd:xd,Cd:xd,xd:yd,If:zd,Hf:Ad,nd:Bd,Pa:Cd,Rc:Dd,ec:Ed,Gf:Fd,Ff:Gd,Yc:Hd,Df:Id,Cf:Jd,$c:Kd,Bf:Ld,Af:Md,yf:Nd,rd:Od,Ta:Pd,xf:Qd,Wb:Rd,wf:Sd,Hb:Td,Vc:Ud,Ga:Ud,zf:Vd,vf:Wd,uf:Xd,ic:Yd,jc:Zd,lc:$d,sf:ae,rf:be,qf:ce,Xb:de,pf:ee,jd:fe,
of:ge,nf:he,Cc:ie,mf:je,Yb:ke,$b:le,Tc:me,lf:ne,vb:oe,Cb:pe,jf:qe,kf:re,Ka:se,Ma:te,Ja:se,ld:ue,La:te,md:ve,Na:we,gf:xe,Lb:ye,Mb:ze,ef:Ae,df:Be,cf:Ce,ff:De,bf:Ee,oc:Fe,Zb:Ge,af:He,$e:Ie,Mc:Je,kc:Ke,mc:Le,Xe:Me,_e:Ne,Ze:Oe,Dc:Pe,Kc:Qe,Jc:Qe,Ue:Re,We:Se,Ve:Te,Te:Ue,zb:Ve,yb:We,Se:Xe,Re:Ye,Qe:Ze,Pe:$e,pd:af,Ra:bf,Oe:cf,Ub:df,Ne:ef,dc:ff,Me:gf,Gb:hf,Uc:jf,Fa:jf,Le:kf,Ke:lf,Zc:mf,Fb:nf,Je:of,Ie:pf,Bb:qf,Ab:rf,Oa:sf,yd:tf,He:uf,Ge:vf,Fe:wf,ad:xf,Eb:yf,Ee:zf,Qb:Af,Nb:Bf,Sb:Cf,Rb:Df,De:Ef,Ce:Ff,Be:Gf,Ae:Hf,
ze:If,ye:Jf,xe:Kf,we:Lf,ve:Mf,ue:Nf,wd:Of,se:Pf,re:Qf,qe:Rf,pe:Sf,xb:Tf,wb:Uf,oe:Vf,vd:Wf,Nc:Xf,ne:Yf,me:Zf,le:$f,ke:ag,Bc:bg,xc:cg,je:dg,he:eg,ge:fg,fe:gg,Ac:hg,wc:ig,ee:jg,de:kg,ce:lg,be:mg,zc:ng,vc:og,ae:pg,$d:qg,_d:rg,Zd:sg,yc:tg,uc:ug,hc:vg,Yd:wg,hd:xg,fd:yg,Xd:zg,gd:Ag,dd:Bg,Wd:Cg,ed:Dg,cd:Eg,kd:Fg,Vd:Gg,Ud:Hg,Td:Ig,Sd:Jg,Rd:Kg,Qd:Lg,Nd:Mg,Md:Ng,Ld:Og,Kd:Pg,Kb:Qg,Aa:Qg,Gd:Qg,Hd:Qg,ub:Qg,Ic:Rg,Gc:Sg,Hc:Tg,Fc:Ug,Lc:Vg,Jd:Wg,Id:Xg,ac:Yg,j:Zg,$a:$g,L:ah,Rf:bh,B:ch,q:dh,D:eh,f:fh,h:gh,E:hh,t:ih,
o:jh,n:kh,w:lh,u:mh,v:nh,J:oh,H:ph,G:qh,K:rh,I:sh,x:th,s:uh,y:vh,A:wh,z:xh,C:yh,r:zh,F:Ah,ab:Bh,i:Ch,Dd:Dh,Od:Eh,b:Fh,O:Gh,Ob:Hh,Ya:Ih,Qf:Jh,a:xa,Pc:Kh};return{a:gb}}
var Ph={1867512:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.di!==h.canvas&&(d.eh=h.createContext(h.canvas,!1,!0),d.di=h.canvas);if(d.w!==a||d.h!==b||d.mi!==d.eh)d.image=d.eh.createImageData(a,b),d.w=a,d.h=b,d.mi=d.eh;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=u[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.gi!==a&&(d.fi=new Int32Array(a.buffer),d.hi=new Uint8Array(a.buffer),d.gi=a),
a=d.fi,c=a.length,a.set(u.subarray(b,b+c)),a=d.hi,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.eh.putImageData(d.image,0,0)},1868980:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var k=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=
b.length;k<n;){var q=u[e];b[k]=q&255;b[k+1]=q>>8&255;b[k+2]=q>>16&255;b[k+3]=q>>24&255;e++;k+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(u.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=A(c.length+1);B(c,t,d,c.length+1);return d},1869968:a=>{h.canvas&&(h.canvas.style.cursor=a?z(t,a):"")},1870051:()=>{h.canvas&&(h.canvas.style.cursor="none")},1870120:()=>window.innerWidth,1870150:()=>window.innerHeight,1870181:a=>
{a=(a?z(t,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");var b=Array(Lh(a)+1);B(a,b,0,b.length);a=b;b=A(a.length);a.subarray||a.slice||(a=new Uint8Array(a));t.set(a,b);return b},1870406:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,1870553:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,1870787:a=>
{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.cg||("undefined"!==typeof AudioContext?b.cg=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.cg=new webkitAudioContext),b.cg&&"undefined"===typeof navigator.userActivation&&Mh(b.cg));return void 0===b.cg?-1:0},1871339:()=>h.SDL2.cg.sampleRate,1871407:(a,b,c,d)=>{function e(){}function f(k){void 0!==g.capture.dh&&(clearInterval(g.capture.dh),g.capture.dh=void 0,g.capture.mh=void 0);g.capture.Mh=g.cg.createMediaStreamSource(k);
g.capture.bh=g.cg.createScriptProcessor(b,a,1);g.capture.bh.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Jh=n.inputBuffer,Nh(c,[d]))};g.capture.Mh.connect(g.capture.bh);g.capture.bh.connect(g.cg.destination);g.capture.stream=k}var g=h.SDL2;g.capture.mh=g.cg.createBuffer(a,b,g.cg.sampleRate);g.capture.mh.getChannelData(0).fill(0);g.capture.dh=setInterval(function(){g.capture.Jh=g.capture.mh;Nh(c,[d])},b/g.cg.sampleRate*1E3);void 0!==
navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},1873100:(a,b,c,d)=>{var e=h.SDL2;e.audio.bh=e.cg.createScriptProcessor(b,0,a);e.audio.bh.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.dh&&(clearInterval(e.audio.dh),e.audio.dh=void 0,e.audio.mh=void 0),e.audio.zh=f.outputBuffer,Nh(c,[d]))};
e.audio.bh.connect(e.cg.destination);"suspended"===e.cg.state&&(e.audio.mh=e.cg.createBuffer(a,b,e.cg.sampleRate),e.audio.mh.getChannelData(0).fill(0),e.audio.dh=setInterval(function(){"undefined"!==typeof navigator.userActivation&&navigator.userActivation.hasBeenActive&&e.cg.resume();e.audio.zh=e.audio.mh;Nh(c,[d]);e.audio.zh=void 0},b/e.cg.sampleRate*1E3))},1874275:(a,b)=>{for(var c=h.SDL2,d=c.capture.Jh.numberOfChannels,e=0;e<d;++e){var f=c.capture.Jh.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+
f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Oh(a+4*g,f[g]);else for(g=0;g<b;++g)Oh(a+4*(g*d+e),f[g])}},1874880:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=c.audio.zh.numberOfChannels,e=0;e<d;++e){var f=c.audio.zh.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=w[a+(g*d+e)]}},1875369:a=>{var b=h.SDL2;if(a){void 0!==b.capture.dh&&clearInterval(b.capture.dh);
if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.bh&&(b.capture.bh.onaudioprocess=function(){},b.capture.bh.disconnect());void 0!==b.capture.Mh&&b.capture.Mh.disconnect();b.capture=void 0}else void 0!=b.audio.bh&&b.audio.bh.disconnect(),void 0!==b.audio.dh&&clearInterval(b.audio.dh),b.audio=void 0;void 0!==b.cg&&void 0===b.audio&&void 0===b.capture&&(b.cg.close(),b.cg=void 0)}};
function oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Qh=a=>{a.terminate();a.onmessage=()=>{}},Vh=a=>{0==Rh.length&&(Sh(),Th(Rh[0]));var b=Rh.pop();if(!b)return 6;Uh.push(b);C[a.kh]=b;b.kh=a.kh;var c={cmd:"run",start_routine:a.pi,arg:a.Th,pthread_ptr:a.kh};l&&b.unref();b.postMessage(c,a.ri);return 0},D=0,E=(a,b,c,...d)=>{for(var e=d.length,f=Wh(),g=Xh(8*e),k=g>>3,n=0;n<d.length;n++)x[k+n]=d[n];a=Yh(a,b,e,g,c);Zh(f);return a};
function Kh(a){if(m)return E(0,0,1,a);Ma=a;if(!($h||0<D)){for(var b of Uh)Qh(b);for(b of Rh)Qh(b);Rh=[];Uh=[];C=[];h.onExit?.(a);La=!0}ha(a,new oa(a))}var ai=a=>{a instanceof oa||"unwind"==a||ha(1,a)};function bi(a){if(m)return E(1,0,0,a);Fh(a)}var Fh=a=>{Ma=a;if(m)throw bi(a),"unwind";Kh(a)},Rh=[],Uh=[],ci=[],C={};function di(){for(var a=navigator.hardwareConcurrency;a--;)Sh();Qa.unshift(()=>{Xa();ei(()=>Ya())})}var gi=a=>{var b=a.kh;delete C[b];Rh.push(a);Uh.splice(Uh.indexOf(a),1);a.kh=0;fi(b)};
function Ea(){ci.forEach(a=>a())}
var Th=a=>new Promise(b=>{a.onmessage=f=>{f=f.data;var g=f.cmd;if(f.targetThread&&f.targetThread!=va()){var k=C[f.targetThread];k?k.postMessage(f,f.transferList):p(`Internal error! Worker sent a message "${g}" to target pthread ${f.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===g)Ha();else if("spawnThread"===g)Vh(f);else if("cleanupThread"===g)gi(C[f.thread]);else if("killThread"===g)f=f.thread,g=C[f],delete C[f],Qh(g),fi(f),Uh.splice(Uh.indexOf(g),1),g.kh=0;else if("cancelThread"===
g)C[f.thread].postMessage({cmd:"cancel"});else if("loaded"===g)a.loaded=!0,l&&!a.kh&&a.unref(),b(a);else if("alert"===g)alert(`Thread ${f.threadId}: ${f.text}`);else if("setimmediate"===f.target)a.postMessage(f);else if("callHandler"===g)h[f.handler](...f.args);else g&&p(`worker sent an unknown command ${g}`)};a.onerror=f=>{p(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};l&&(a.on("message",f=>a.onmessage({data:f})),a.on("error",f=>a.onerror(f)));var c=[],d=["onExit",
"onAbort","print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({cmd:"load",handlers:c,wasmMemory:xa,wasmModule:Ka,wasmOffsetConverter:za})});function ei(a){m?a():Promise.all(Rh.map(Th)).then(a)}function Sh(){var a=ia;h.mainScriptUrlOrBlob&&(a=h.mainScriptUrlOrBlob,"string"!=typeof a&&(a=URL.createObjectURL(a)));a=new Worker(a,{workerData:"em-pthread",name:"em-pthread"});Rh.push(a)}
var hi,ii="undefined"!=typeof TextDecoder?new TextDecoder:void 0,z=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ii)return ii.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&
1023))}}else d+=String.fromCharCode(e)}return d},ji=a=>{for(;0<a.length;)a.shift()(h)},Da=()=>{var a=va(),b=v[a+52>>2];ki(b,b-v[a+56>>2]);Zh(b)},Fa=(a,b)=>{D=0;a=li(a,b);$h||0<D?Ma=a:Ga(a)},$h=h.noExitRuntime||!0;
function Oh(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":r[a]=b;break;case "i8":r[a]=b;break;case "i16":Na[a>>1]=b;break;case "i32":u[a>>2]=b;break;case "i64":Za("to do setValue(i64) use WASM_BIGINT");case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":v[a>>2]=b;break;default:Za(`invalid type for setValue: ${c}`)}}
var mi=(a,b)=>a?z(t,a,b):"",hb=(a,b,c,d)=>{Za(`Assertion failed: ${a?z(t,a):""}, at: `+[b?b?z(t,b):"":"unknown filename",c,d?d?z(t,d):"":"unknown function"])},ib=(a,b)=>dynCall_vi(a,b);function ni(a,b,c,d){return m?E(2,0,1,a,b,c,d):jb(a,b,c,d)}
var jb=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return p("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var e=[];if(m&&0===e.length)return ni(a,b,c,d);a={pi:c,kh:a,Th:d,ri:e};return m?(a.Vh="spawnThread",postMessage(a,e),0):Vh(a)};function kb(a,b,c){return m?E(3,0,1,a,b,c):0}function lb(a,b){if(m)return E(4,0,1,a,b)}function mb(a,b,c){return m?E(5,0,1,a,b,c):0}function nb(a,b){if(m)return E(6,0,1,a,b)}
function ob(a,b,c,d){if(m)return E(7,0,1,a,b,c,d)}function pb(a,b,c,d){if(m)return E(8,0,1,a,b,c,d)}function qb(a,b){if(m)return E(9,0,1,a,b)}
var rb=()=>{Za("")},sb=()=>1,tb=a=>{Ba(a,!ba,1,!aa,16777216,!1);Ea()},oi=a=>{if(!La)try{if(a(),!($h||0<D))try{m?Ga(Ma):Fh(Ma)}catch(b){ai(b)}}catch(b){ai(b)}},Ca=a=>{"function"===typeof Atomics.ti&&(Atomics.ti(u,a>>2,a).value.then(Ha),Atomics.store(u,a+128>>2,1))},Ha=()=>{var a=va();a&&(Ca(a),oi(pi))},ub=(a,b)=>{a==b?setTimeout(Ha):m?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=C[a])&&a.postMessage({cmd:"checkMailbox"})},qi=[],vb=(a,b,c,d,e)=>{qi.length=d;e>>=3;for(var f=0;f<d;f++)qi[f]=x[e+
f];a=b?Ph[b]:ri[a];hi=c;c=a(...qi);hi=0;return c};function wb(){if(m)return E(10,0,1);$h=!1;D=0}
var xb=a=>{m?postMessage({cmd:"cleanupThread",thread:a}):gi(C[a])},yb=a=>{l&&C[a].ref()},Bi=(a,b)=>{si=a;ti=b;if(ui)if(vi||(D+=1,vi=!0),0==a)wi=function(){var d=Math.max(0,xi+b-cc())|0;setTimeout(yi,d)};else if(1==a)wi=function(){zi(yi)};else if(2==a){if("undefined"==typeof Ai)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ai=function(d){c.push(d);if(ba){let e;(e=h).setImmediates??
(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ai=setImmediate;wi=function(){Ai(yi)}}},cc;cc=()=>performance.timeOrigin+performance.now();
var Hi=a=>{function b(){return c<Ci?(--D,!1):!0}ui=a;var c=Ci;vi=!1;yi=function(){if(!La)if(0<Di.length){var d=Di.shift();d.yi(d.Th);if(Ei){var e=Ei,f=0==e%1?e-1:Math.floor(e);Ei=d.vi?f:(8*e+(f+.5))/9}h.setStatus&&(d=h.statusMessage||"Please wait...",e=Ei,f=Fi.xi,e?e<f?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(d):h.setStatus(""));b()&&setTimeout(yi,0)}else if(b())if(Gi=Gi+1|0,1==si&&1<ti&&0!=Gi%ti)wi();else{0==si&&(xi=cc());if(F)for(d=F.rh,F.rh=F.uh,F.uh=d,d=F.lh,F.lh=
F.Fh,F.Fh=d,d=0;21>=d;++d)F.lh[d]=0;La||h.preMainLoop&&!1===h.preMainLoop()||(oi(a),h.postMainLoop?.());b()&&("object"==typeof SDL&&SDL.audio?.Fi?.(),wi())}}},Ii=(a,b)=>{D+=1;return setTimeout(()=>{--D;oi(a)},b)},vi=!1,wi=null,Ci=0,ui=null,si=0,ti=0,Gi=0,Di=[];function Ji(){wi=null;Ci++}function Ki(){Ci++;var a=si,b=ti,c=ui;ui=null;Hi(c);Bi(a,b);wi()}var Fi={},xi,yi,Ei,Li=!1,Mi=!1,Ni=[];
function Oi(){function a(){Mi=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Pi){Pi=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Mi&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Qi=!1,Ri=void 0,Si=void 0;
function Ti(){if(!Li)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Ui=0;function zi(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Ui)Ui=b+1E3/60;else for(;b+2>=Ui;)Ui+=1E3/60;setTimeout(a,Math.max(Ui-b,0))}}var Vi=[];function Wi(){var a=h.canvas;Vi.forEach(b=>b(a.width,a.height))}
function Xi(a,b,c){b&&c?(a.ui=b,a.li=c):(b=a.ui,c=a.li);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Si?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Yi={},Ai,Pi,G=12288,Zi=!1,$i=0,aj=0,bj=0,I={alpha:!1,depth:!1,stencil:!1,antialias:!1},cj={},dj;function zb(a){if(m)return E(11,0,1,a);if(12448==a)return G=12288,1;G=12300;return 0}
function Ab(a,b,c,d,e){if(m)c=E(12,0,1,a,b,c,d,e);else if(62E3!=a)G=12296,c=0;else{if(b)for(;;){a=u[b>>2];if(12321==a)I.alpha=0<u[b+4>>2];else if(12325==a)I.depth=0<u[b+4>>2];else if(12326==a)I.stencil=0<u[b+4>>2];else if(12337==a)a=u[b+4>>2],I.antialias=0<a;else if(12338==a)a=u[b+4>>2],I.antialias=1==a;else if(12544==a)I.Bi=12547!=u[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(u[e>>2]=1),c&&0<d&&(v[c>>2]=62002),G=12288,c=1):(G=12300,c=0)}return c}
var ej=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},fj=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},
gj=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},hj=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},ij=1,jj=[],kj={},J=[],lj=[],mj=[],nj=[],K=[],oj=[],L={},M=[],N=[],pj=[],qj=[],rj=[1,1,2,2,4,4,4,2,3,4,8],sj={},tj={},uj=4,vj=0,wj=a=>{for(var b=ij++,c=a.length;c<b;c++)a[c]=null;return b},xj=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=P[c](),g=f&&wj(d);f?(f.name=g,d[g]=f):Q||=1282;u[b+4*e>>2]=g}},zj=a=>{yj=!1;for(var b=0;b<F.Zh;++b){var c=F.ih[b];if(c.sh&&c.enabled){yj=!0;var d=c.Eh;d=0<d?a*d:c.size*rj[c.type-5120]*a;var e=32-Math.clz32(0===
d?0:d-1);var f=F.rh[e],g=F.lh[e];F.lh[e]=F.lh[e]+1&63;var k=f[g];k?e=k:(k=P.getParameter(34964),f[g]=P.createBuffer(),P.bindBuffer(34962,f[g]),P.bufferData(34962,1<<e,35048),P.bindBuffer(34962,k),e=f[g]);P.bindBuffer(34962,e);P.bufferSubData(34962,0,t.subarray(c.Dh,c.Dh+d));c.Rh.call(P,b,c.size,c.type,c.Nh,c.Eh,0)}}},Bj=(a,b)=>{a.oh||(a.oh=a.getContext,a.getContext=function(d,e){e=a.oh(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Lh?a.getContext("webgl2",b):a.getContext("webgl",
b);return c?Aj(c,b):0},Aj=(a,b)=>{var c=A(8);v[c+4>>2]=va();var d={handle:c,attributes:b,version:b.Lh,Xg:a};a.canvas&&(a.canvas.hh=d);L[c]=d;("undefined"==typeof b.ji||b.ji)&&Cj(d);d.Zh=d.Xg.getParameter(34921);d.ih=[];for(a=0;a<d.Zh;a++)d.ih[a]={enabled:!1,sh:!1,size:0,type:0,Nh:0,Eh:0,Dh:0,Rh:null};d.lh=[];d.Fh=[];d.lh.length=d.Fh.length=22;d.rh=[];d.uh=[];d.rh.length=d.uh.length=22;d.qh=[];d.qh.length=22;for(a=0;21>=a;++a){d.qh[a]=null;d.lh[a]=d.Fh[a]=0;d.rh[a]=[];d.uh[a]=[];b=d.rh[a];var e=d.uh[a];
b.length=e.length=64;for(var f=0;64>f;++f)b[f]=e[f]=null}return c},Dj=a=>{F=L[a];h.eh=P=F?.Xg},Cj=a=>{a||=F;if(!a.ni){a.ni=!0;var b=a.Xg;ej(b);fj(b);gj(b);b.wi=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Ci=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.$g=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.$g)b.$g=b.getExtension("EXT_disjoint_timer_query");b.Ei=b.getExtension("WEBGL_multi_draw");hj(b).forEach(c=>{c.includes("lose_context")||
c.includes("debug")||b.getExtension(c)})}},Ej={},Q,F,yj;function Bb(a,b,c,d){if(m)return E(13,0,1,a,b,c,d);if(62E3!=a)return G=12296,0;for(a=1;;){b=u[d>>2];if(12440==b)a=u[d+4>>2];else if(12344==b)break;else return G=12292,0;d+=8}if(2>a||3<a)return G=12293,0;I.Lh=a-1;I.Di=0;dj=Bj(h.canvas,I);if(0!=dj)return G=12288,Dj(dj),h.si=!0,Ni.forEach(function(e){e()}),Dj(null),62004;G=12297;return 0}
function Cb(a,b,c,d){if(m)return E(14,0,1,a,b,c,d);if(62E3!=a)return G=12296,0;if(62002!=b)return G=12293,0;G=12288;return 62006}function Db(a,b){if(m)return E(15,0,1,a,b);if(62E3!=a)return G=12296,0;if(62004!=b)return G=12294,0;a=dj;F===L[a]&&(F=null);if("object"==typeof Fj)for(var c=L[a].Xg.canvas,d=0;d<Gj.length;++d)Gj[d].target!=c||Hj(d--);L[a]&&L[a].Xg.canvas&&(L[a].Xg.canvas.hh=void 0);Ij(L[a].handle);L[a]=null;G=12288;$i==b&&($i=0);return 1}
function Eb(a,b){if(m)return E(16,0,1,a,b);if(62E3!=a)return G=12296,0;if(62006!=b)return G=12301,1;aj==b&&(aj=0);bj==b&&(bj=0);G=12288;return 1}
function Fb(a,b,c,d){if(m)return E(17,0,1,a,b,c,d);if(62E3!=a)return G=12296,0;if(62002!=b)return G=12293,0;if(!d)return G=12300,0;G=12288;switch(c){case 12320:return u[d>>2]=I.alpha?32:24,1;case 12321:return u[d>>2]=I.alpha?8:0,1;case 12322:return u[d>>2]=8,1;case 12323:return u[d>>2]=8,1;case 12324:return u[d>>2]=8,1;case 12325:return u[d>>2]=I.depth?24:0,1;case 12326:return u[d>>2]=I.stencil?8:0,1;case 12327:return u[d>>2]=12344,1;case 12328:return u[d>>2]=62002,1;case 12329:return u[d>>2]=0,1;
case 12330:return u[d>>2]=4096,1;case 12331:return u[d>>2]=16777216,1;case 12332:return u[d>>2]=4096,1;case 12333:return u[d>>2]=0,1;case 12334:return u[d>>2]=0,1;case 12335:return u[d>>2]=12344,1;case 12337:return u[d>>2]=I.antialias?4:0,1;case 12338:return u[d>>2]=I.antialias?1:0,1;case 12339:return u[d>>2]=4,1;case 12340:return u[d>>2]=12344,1;case 12341:case 12342:case 12343:return u[d>>2]=-1,1;case 12345:case 12346:return u[d>>2]=0,1;case 12347:return u[d>>2]=0,1;case 12348:return u[d>>2]=1;
case 12349:case 12350:return u[d>>2]=0,1;case 12351:return u[d>>2]=12430,1;case 12352:return u[d>>2]=4,1;case 12354:return u[d>>2]=0,1;default:return G=12292,0}}function Gb(a){if(m)return E(18,0,1,a);G=12288;return 0!=a&&1!=a?0:62E3}function Hb(){return m?E(19,0,1):G}function Ib(a,b,c){if(m)return E(20,0,1,a,b,c);if(62E3!=a)return G=12296,0;b&&(u[b>>2]=1);c&&(u[c>>2]=4);Zi=!0;G=12288;return 1}
function Jb(a,b,c,d){if(m)return E(21,0,1,a,b,c,d);if(62E3!=a)return G=12296,0;if(0!=d&&62004!=d)return G=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return G=12301,0;Dj(d?dj:null);$i=d;bj=b;aj=c;G=12288;return 1}
var Lh=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},B=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=
128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},Jj=a=>{var b=Lh(a)+1,c=A(b);c&&B(a,t,c,b);return c};function Kb(a,b){if(m)return E(22,0,1,a,b);if(62E3!=a)return G=12296,0;G=12288;if(cj[b])return cj[b];switch(b){case 12371:a=Jj("Emscripten");break;case 12372:a=Jj("1.4 Emscripten EGL");break;case 12373:a=Jj("");break;case 12429:a=Jj("OpenGL_ES");break;default:return G=12300,0}return cj[b]=a}
function Lb(a,b){if(m)return E(23,0,1,a,b);if(Zi)if(h.eh)if(h.eh.isContextLost())G=12302;else return G=12288,1;else G=12290;else G=12289;return 0}function Mb(a,b){if(m)return E(24,0,1,a,b);if(62E3!=a)return G=12296,0;0==b?Bi(0,0):Bi(1,b);G=12288;return 1}function Nb(a){if(m)return E(25,0,1,a);if(62E3!=a)return G=12296,0;bj=aj=$i=0;Zi=!1;G=12288;return 1}function Ob(){if(m)return E(26,0,1);G=12288;return 1}function Pb(a){if(m)return E(27,0,1,a);G=12288;return 1}
var Kj=[],Lj=(a,b)=>{Kj.length=0;for(var c;c=t[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Kj.push(112==c?v[b>>2]:105==c?u[b>>2]:x[b>>3]);b+=d?8:4}return Kj},Qb=(a,b,c)=>{b=Lj(b,c);return Ph[a](...b)},Mj=(a,b,c)=>{b=Lj(b,c);return m?E(0,a,1,...b):Ph[a](...b)},Rb=(a,b,c)=>Mj(a,b,c),Sb=(a,b,c)=>Mj(a,b,c),Tb=()=>{Ji();ui=null},Ub=()=>{},Vb=()=>Date.now(),Nj=0,Oj=[];
function Pj(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var k in f)if(f[k]!=g[k])return!1;return!0}for(var e of Oj)if(e.Ph==a&&d(e.Uh,c))return;Oj.push({Ph:a,ai:b,Uh:c});Oj.sort((f,g)=>f.ai<g.ai)}function Qj(a){Oj=Oj.filter(b=>b.Ph!=a)}function Rj(){return navigator.userActivation?navigator.userActivation.isActive:Nj&&Sj.wh}function Tj(){if(Rj()){var a=Oj;Oj=[];for(var b of a)b.Ph(...b.Uh)}}var Gj=[];
function Hj(a){var b=Gj[a];b.target.removeEventListener(b.Wg,b.Xh,b.Yg);Gj.splice(a,1)}function R(a){if(!a.target)return-4;if(a.Zg)a.Xh=function(c){++Nj;Sj=a;Tj();a.ah(c);Tj();--Nj},a.target.addEventListener(a.Wg,a.Xh,a.Yg),Gj.push(a);else for(var b=0;b<Gj.length;++b)Gj[b].target==a.target&&Gj[b].Wg==a.Wg&&Hj(b--);return 0}function S(a){switch(a){case 1:return 0;case 2:return hi;default:return a}}function Uj(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
function Vj(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var Fj={},Sj,Wj,Xj,Yj,Zj,ak,bk,ck,dk,ek,fk,gk,hk,ik={},jk=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],T=a=>{a=2<a?a?z(t,a):"":a;return jk[a]||("undefined"!=typeof document?document.querySelector(a):void 0)},kk=(a,b,c)=>{a=T(a);if(!a||a.Wh)return-4;u[b>>2]=a.width;u[c>>2]=a.height;return 0};function lk(a,b,c){return m?E(29,0,1,a,b,c):kk(a,b,c)}
var mk=a=>{var b=Lh(a)+1,c=Xh(b);B(a,t,c,b);return c},nk=a=>{var b=Wh(),c=Xh(8),d=c+4;a=mk(a.id);T(a)?kk(a,c,d):lk(a,c,d);c=[u[c>>2],u[d>>2]];Zh(b);return c},ok=(a,b,c)=>{a=T(a);if(!a||a.Wh)return-4;var d=!1;a.hh?.Xg&&(d=a.hh.Xg.getParameter(2978),d=0===d[0]&&0===d[1]&&d[2]===a.width&&d[3]===a.height);a.width=b;a.height=c;d&&a.hh.Xg.viewport(0,0,b,c);return 0};function pk(a,b,c){return m?E(30,0,1,a,b,c):ok(a,b,c)}
var fh=(a,b,c)=>T(a)?ok(a,b,c):pk(a,b,c),qk=(a,b,c)=>{if(a.Wh){var d=Wh();a=mk(a.id);fh(a,b,c);Zh(d)}else a.width=b,a.height=c},rk=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),qk(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=k,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=q,a.style.paddingRight=
y,a.style.paddingTop=H,a.style.paddingBottom=Z,a.style.marginLeft=O,a.style.marginRight=sc,a.style.marginTop=tc,a.style.marginBottom=ml,document.body.style.margin=nl,document.documentElement.style.overflow=ol,document.body.scroll=pl,a.style.jh=ql,a.hh&&a.hh.Xg.viewport(0,0,d,e),ik.nh&&(ik.xh?U(ik.xh,ik.nh,37,0,ik.yh):V(ik.nh,37,0,ik.yh)))}var c=nk(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,k=a.style.backgroundColor,n=document.body.style.backgroundColor,q=a.style.paddingLeft,y=a.style.paddingRight,
H=a.style.paddingTop,Z=a.style.paddingBottom,O=a.style.marginLeft,sc=a.style.marginRight,tc=a.style.marginTop,ml=a.style.marginBottom,nl=document.body.style.margin,ol=document.documentElement.style.overflow,pl=document.body.scroll,ql=a.style.jh;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},sk=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},tk=a=>0>jk.indexOf(a)?a.getBoundingClientRect():
{left:0,top:0},uk=(a,b)=>{if(0!=b.Oh||0!=b.Ih){rk(a);var c=b.oi?innerWidth:screen.width,d=b.oi?innerHeight:screen.height,e=tk(a),f=e.width;e=e.height;var g=nk(a),k=g[0];g=g[1];3==b.Oh?(sk(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Oh&&(c*g<k*d?(f=g*c/k,sk(a,(d-f)/2,0),d=f):(f=k*d/g,sk(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.ki&&(a.style.jh=
"optimizeSpeed",a.style.jh="-moz-crisp-edges",a.style.jh="-o-crisp-edges",a.style.jh="-webkit-optimize-contrast",a.style.jh="optimize-contrast",a.style.jh="crisp-edges",a.style.jh="pixelated");f=2==b.Ih?devicePixelRatio:1;0!=b.Ih&&(c=c*f|0,d=d*f|0,qk(a,c,d),a.hh&&a.hh.Xg.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Vj()?-3:-1;ik=b;b.nh&&(b.xh?U(b.xh,b.nh,37,0,b.yh):V(b.nh,37,0,
b.yh));return 0};function Wb(){if(m)return E(28,0,1);if(!Vj())return-1;Qj(uk);var a=jk[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0}var vk=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0};function Xb(){if(m)return E(31,0,1);Qj(vk);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0}
var Yb=()=>{D+=1;throw"unwind";};function Zb(a){if(m)return E(32,0,1,a);wb();Fh(a)}function $b(){return m?E(33,0,1):"number"==typeof devicePixelRatio&&devicePixelRatio||1}function ac(a,b,c){if(m)return E(34,0,1,a,b,c);a=T(a);if(!a)return-4;a=tk(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0}
var wk=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)r[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];r[a+1104]=b.connected;u[a+1108>>2]=b.index;u[a+8>>2]=b.axes.length;u[a+12>>2]=b.buttons.length;B(b.id,t,a+1112,64);B(b.mapping,t,a+1176,64)};
function bc(a,b){if(m)return E(35,0,1,a,b);if(0>a||a>=Wj.length)return-5;if(!Wj[a])return-7;wk(b,Wj[a]);return 0}function dc(){return m?E(36,0,1):Wj.length}function ec(a,b){if(m)return E(37,0,1,a,b);u[a>>2]=screen.width;u[b>>2]=screen.height}
var fc=a=>P.activeTexture(a),gc=(a,b)=>{P.attachShader(J[a],K[b])},hc=(a,b)=>{P.beginQuery(a,M[b])},ic=(a,b)=>{P.$g.beginQueryEXT(a,M[b])},jc=a=>P.beginTransformFeedback(a),kc=(a,b,c)=>{P.bindAttribLocation(J[a],b,c?z(t,c):"")},lc=(a,b)=>{34962==a?P.ph=b:34963==a&&(P.th=b);35051==a?P.Kh=b:35052==a&&(P.fh=b);P.bindBuffer(a,jj[b])},mc=(a,b,c)=>{P.bindBufferBase(a,b,jj[c])},nc=(a,b,c,d,e)=>{P.bindBufferRange(a,b,jj[c],d,e)},oc=(a,b)=>{P.bindFramebuffer(a,lj[b])},pc=(a,b)=>{P.bindRenderbuffer(a,mj[b])},
qc=(a,b)=>{P.bindSampler(a,N[b])},rc=(a,b)=>{P.bindTexture(a,nj[b])},uc=(a,b)=>{P.bindTransformFeedback(a,pj[b])},vc=a=>{P.bindVertexArray(oj[a]);a=P.getParameter(34965);P.th=a?a.name|0:0},wc=(a,b,c,d)=>P.blendColor(a,b,c,d),xc=a=>P.blendEquation(a),yc=(a,b)=>P.blendEquationSeparate(a,b),zc=(a,b)=>P.blendFunc(a,b),Ac=(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),Bc=(a,b,c,d,e,f,g,k,n,q)=>P.blitFramebuffer(a,b,c,d,e,f,g,k,n,q),Cc=(a,b,c,d)=>{2<=F.version?c&&b?P.bufferData(a,t,d,c,b):P.bufferData(a,b,d):
P.bufferData(a,c?t.subarray(c,c+b):b,d)},Dc=(a,b,c,d)=>{2<=F.version?c&&P.bufferSubData(a,b,t,d,c):P.bufferSubData(a,b,t.subarray(d,d+c))},Ec=a=>P.checkFramebufferStatus(a),Fc=a=>P.clear(a),Gc=(a,b,c,d)=>P.clearBufferfi(a,b,c,d),Hc=(a,b,c)=>{P.clearBufferfv(a,b,w,c>>2)},Ic=(a,b,c)=>{P.clearBufferiv(a,b,u,c>>2)},Jc=(a,b,c)=>{P.clearBufferuiv(a,b,v,c>>2)},Kc=(a,b,c,d)=>P.clearColor(a,b,c,d),Lc=a=>P.clearDepth(a),Mc=a=>P.clearStencil(a),Nc=(a,b,c,d)=>P.clientWaitSync(qj[a],b,(c>>>0)+4294967296*d),Oc=
(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},Pc=a=>{P.compileShader(K[a])},Qc=(a,b,c,d,e,f,g,k)=>{2<=F.version?P.fh||!g?P.compressedTexImage2D(a,b,c,d,e,f,g,k):P.compressedTexImage2D(a,b,c,d,e,f,t,k,g):P.compressedTexImage2D(a,b,c,d,e,f,k?t.subarray(k,k+g):null)},Rc=(a,b,c,d,e,f,g,k,n)=>{P.fh?P.compressedTexImage3D(a,b,c,d,e,f,g,k,n):P.compressedTexImage3D(a,b,c,d,e,f,g,t,n,k)},Sc=(a,b,c,d,e,f,g,k,n)=>{2<=F.version?P.fh||!k?P.compressedTexSubImage2D(a,b,c,d,e,f,g,k,n):P.compressedTexSubImage2D(a,b,c,
d,e,f,g,t,n,k):P.compressedTexSubImage2D(a,b,c,d,e,f,g,n?t.subarray(n,n+k):null)},Tc=(a,b,c,d,e,f,g,k,n,q,y)=>{P.fh?P.compressedTexSubImage3D(a,b,c,d,e,f,g,k,n,q,y):P.compressedTexSubImage3D(a,b,c,d,e,f,g,k,n,t,y,q)},Uc=(a,b,c,d,e)=>P.copyBufferSubData(a,b,c,d,e),Vc=(a,b,c,d,e,f,g,k)=>P.copyTexImage2D(a,b,c,d,e,f,g,k),Wc=(a,b,c,d,e,f,g,k)=>P.copyTexSubImage2D(a,b,c,d,e,f,g,k),Xc=(a,b,c,d,e,f,g,k,n)=>P.copyTexSubImage3D(a,b,c,d,e,f,g,k,n),Yc=()=>{var a=wj(J),b=P.createProgram();b.name=a;b.Ch=b.Ah=
b.Bh=0;b.Qh=1;J[a]=b;return a},Zc=a=>{var b=wj(K);K[b]=P.createShader(a);return b},$c=a=>P.cullFace(a),ad=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=jj[d];e&&(P.deleteBuffer(e),e.name=0,jj[d]=null,d==P.ph&&(P.ph=0),d==P.th&&(P.th=0),d==P.Kh&&(P.Kh=0),d==P.fh&&(P.fh=0))}},bd=(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=lj[d];e&&(P.deleteFramebuffer(e),e.name=0,lj[d]=null)}},cd=a=>{if(a){var b=J[a];b?(P.deleteProgram(b),b.name=0,J[a]=null):Q||=1281}},dd=(a,b)=>{for(var c=0;c<a;c++){var d=
u[b+4*c>>2],e=M[d];e&&(P.deleteQuery(e),M[d]=null)}},ed=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=M[d];e&&(P.$g.deleteQueryEXT(e),M[d]=null)}},fd=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=mj[d];e&&(P.deleteRenderbuffer(e),e.name=0,mj[d]=null)}},gd=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=N[d];e&&(P.deleteSampler(e),e.name=0,N[d]=null)}},hd=a=>{if(a){var b=K[a];b?(P.deleteShader(b),K[a]=null):Q||=1281}},jd=a=>{if(a){var b=qj[a];b?(P.deleteSync(b),b.name=0,qj[a]=null):Q||=1281}},
kd=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=nj[d];e&&(P.deleteTexture(e),e.name=0,nj[d]=null)}},ld=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=pj[d];e&&(P.deleteTransformFeedback(e),e.name=0,pj[d]=null)}},md=(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2];P.deleteVertexArray(oj[d]);oj[d]=null}},nd=a=>P.depthFunc(a),od=a=>{P.depthMask(!!a)},pd=(a,b)=>P.depthRange(a,b),qd=(a,b)=>{P.detachShader(J[a],K[b])},rd=a=>P.disable(a),sd=a=>{F.ih[a].enabled=!1;P.disableVertexAttribArray(a)},td=(a,
b,c)=>{zj(b+c);P.drawArrays(a,b,c);yj&&P.bindBuffer(34962,jj[P.ph])},ud=(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},xk=[],vd=(a,b)=>{for(var c=xk[a],d=0;d<a;d++)c[d]=u[b+4*d>>2];P.drawBuffers(c)},wd=(a,b,c,d)=>{if(!P.th){var e=1*rj[c-5120]*b;var f=32-Math.clz32(0===e?0:e-1);var g=F.qh[f];g?f=g:(g=P.getParameter(34965),F.qh[f]=P.createBuffer(),P.bindBuffer(34963,F.qh[f]),P.bufferData(34963,1<<f,35048),P.bindBuffer(34963,g),f=F.qh[f]);P.bindBuffer(34963,f);P.bufferSubData(34963,0,t.subarray(d,d+e));
d=0}zj(b);P.drawElements(a,b,c,d);yj&&P.bindBuffer(34962,jj[P.ph]);P.th||P.bindBuffer(34963,null)},xd=(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},yd=(a,b,c,d,e,f)=>{wd(a,d,e,f)},zd=a=>P.enable(a),Ad=a=>{F.ih[a].enabled=!0;P.enableVertexAttribArray(a)},Bd=a=>P.endQuery(a),Cd=a=>{P.$g.endQueryEXT(a)},Dd=()=>P.endTransformFeedback(),Ed=(a,b)=>(a=P.fenceSync(a,b))?(b=wj(qj),a.name=b,qj[b]=a,b):0,Fd=()=>P.finish(),Gd=()=>P.flush(),yk=a=>{switch(a){case 34962:a=34964;break;case 34963:a=34965;break;
case 35051:a=35053;break;case 35052:a=35055;break;case 35982:a=35983;break;case 36662:a=36662;break;case 36663:a=36663;break;case 35345:a=35368}return(a=P.getParameter(a))?a.name|0:0},zk=a=>{switch(a){case 34962:case 34963:case 36662:case 36663:case 35051:case 35052:case 35882:case 35982:case 35345:return!0;default:return!1}},Hd=(a,b,c)=>{if(zk(a)){var d=kj[yk(a)];d?d.Sh&16?0>b||0>c||b+c>d.length?(Q||=1281,p("invalid range in glFlushMappedBufferRange")):P.bufferSubData(a,d.offset,t.subarray(d.gh+
b,d.gh+b+c)):(Q||=1282,p("buffer was not mapped with GL_MAP_FLUSH_EXPLICIT_BIT in glFlushMappedBufferRange")):(Q||=1282,p("buffer was never mapped in glFlushMappedBufferRange"))}else Q||=1280,p("GL_INVALID_ENUM in glFlushMappedBufferRange")},Id=(a,b,c,d)=>{P.framebufferRenderbuffer(a,b,c,mj[d])},Jd=(a,b,c,d,e)=>{P.framebufferTexture2D(a,b,c,nj[d],e)},Kd=(a,b,c,d,e)=>{P.framebufferTextureLayer(a,b,nj[c],d,e)},Ld=a=>P.frontFace(a),Md=(a,b)=>{xj(a,b,"createBuffer",jj)},Nd=(a,b)=>{xj(a,b,"createFramebuffer",
lj)},Od=(a,b)=>{xj(a,b,"createQuery",M)},Pd=(a,b)=>{for(var c=0;c<a;c++){var d=P.$g.createQueryEXT();if(!d){for(Q||=1282;c<a;)u[b+4*c++>>2]=0;break}var e=wj(M);d.name=e;M[e]=d;u[b+4*c>>2]=e}},Qd=(a,b)=>{xj(a,b,"createRenderbuffer",mj)},Rd=(a,b)=>{xj(a,b,"createSampler",N)},Sd=(a,b)=>{xj(a,b,"createTexture",nj)},Td=(a,b)=>{xj(a,b,"createTransformFeedback",pj)},Ud=(a,b)=>{xj(a,b,"createVertexArray",oj)},Vd=a=>P.generateMipmap(a),Ak=(a,b,c,d,e,f,g,k)=>{b=J[b];if(a=P[a](b,c))d=k&&B(a.name,t,k,d),e&&(u[e>>
2]=d),f&&(u[f>>2]=a.size),g&&(u[g>>2]=a.type)},Wd=(a,b,c,d,e,f,g)=>{Ak("getActiveAttrib",a,b,c,d,e,f,g)},Xd=(a,b,c,d,e,f,g)=>{Ak("getActiveUniform",a,b,c,d,e,f,g)},Yd=(a,b,c,d,e)=>{a=J[a];if(a=P.getActiveUniformBlockName(a,b))e&&0<c?(c=B(a,t,e,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0)},Zd=(a,b,c,d)=>{if(d)if(a=J[a],35393==c)u[d>>2]=P.getActiveUniformBlockName(a,b).length+1;else{if(a=P.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)u[d+4*c>>2]=a[c];else u[d>>2]=a}else Q||=
1281},$d=(a,b,c,d,e)=>{if(e)if(0<b&&0==c)Q||=1281;else{a=J[a];for(var f=[],g=0;g<b;g++)f.push(u[c+4*g>>2]);if(a=P.getActiveUniforms(a,f,d))for(b=a.length,g=0;g<b;g++)u[e+4*g>>2]=a[g]}else Q||=1281},ae=(a,b,c,d)=>{a=P.getAttachedShaders(J[a]);var e=a.length;e>b&&(e=b);u[c>>2]=e;for(b=0;b<e;++b)u[d+4*b>>2]=K.indexOf(a[b])},be=(a,b)=>P.getAttribLocation(J[a],b?z(t,b):""),Bk=(a,b)=>{v[a>>2]=b;v[a+4>>2]=(b-v[a>>2])/4294967296};function Ck(){var a=hj(P);return a=a.concat(a.map(b=>"GL_"+b))}
var Dk=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&(Q||=1280);return;case 34814:case 36345:d=0;break;case 34466:var e=P.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>F.version){Q||=1282;return}d=Ck().length;break;case 33307:case 33308:if(2>F.version){Q||=1280;return}d=33307==a?3:0}if(void 0===d)switch(e=P.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":Q||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=
0;break;default:Q||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:u[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:r[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){Q||=1280;p(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:Q||=1280;p(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:Bk(b,d);break;case 0:u[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:r[b]=d?1:0}}else Q||=1281},ce=(a,b)=>Dk(a,b,4),de=(a,b,c)=>{c?Bk(c,P.getBufferParameter(a,b)):Q||=1281},ee=(a,b,c)=>{c?u[c>>2]=P.getBufferParameter(a,b):Q||=1281},fe=(a,b,c)=>{if(35005==b){b=0;if(a=kj[yk(a)])b=a.gh;u[c>>2]=b}else Q||=1280,p("GL_INVALID_ENUM in glGetBufferPointerv")},ge=()=>{var a=P.getError()||Q;Q=0;return a},he=(a,b)=>Dk(a,b,2),ie=(a,b)=>P.getFragDataLocation(J[a],b?z(t,b):""),je=(a,b,c,d)=>
{a=P.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;u[d>>2]=a},Ek=(a,b,c,d)=>{if(c){b=P.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:Q||=1280;return}else if(b instanceof WebGLBuffer)a=b.name|0;else{Q||=1280;return}break;default:Q||=1280;return}switch(d){case 1:Bk(c,a);break;case 0:u[c>>2]=a;break;case 2:w[c>>
2]=a;break;case 4:r[c]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else Q||=1281},ke=(a,b,c)=>Ek(a,b,c,1),le=(a,b)=>{Dk(a,b,1)},me=(a,b,c)=>Ek(a,b,c,0),ne=(a,b)=>Dk(a,b,0),oe=(a,b,c,d,e)=>{if(0>d)Q||=1281;else if(e){if(a=P.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)u[e+4*b>>2]=a[b]}else Q||=1281},pe=()=>{Q||=1282},qe=(a,b,c,d)=>{a=P.getProgramInfoLog(J[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,t,d,b):0;c&&(u[c>>2]=b)},re=
(a,b,c)=>{if(c)if(a>=ij)Q||=1281;else if(a=J[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.Ch)for(b=0;b<P.getProgramParameter(a,35718);++b)a.Ch=Math.max(a.Ch,P.getActiveUniform(a,b).name.length+1);u[c>>2]=a.Ch}else if(35722==b){if(!a.Ah)for(b=0;b<P.getProgramParameter(a,35721);++b)a.Ah=Math.max(a.Ah,P.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.Ah}else if(35381==b){if(!a.Bh)for(b=0;b<P.getProgramParameter(a,35382);++b)a.Bh=Math.max(a.Bh,
P.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.Bh}else u[c>>2]=P.getProgramParameter(a,b);else Q||=1281},se=(a,b,c)=>{if(c){a=M[a];b=2>F.version?P.$g.getQueryObjectEXT(a,b):P.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Bk(c,d)}else Q||=1281},te=(a,b,c)=>{if(c){a=P.$g.getQueryObjectEXT(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else Q||=1281},ue=(a,b,c)=>{if(c){a=P.getQueryParameter(M[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;u[c>>2]=d}else Q||=1281},ve=(a,b,c)=>
{c?u[c>>2]=P.getQuery(a,b):Q||=1281},we=(a,b,c)=>{c?u[c>>2]=P.$g.getQueryEXT(a,b):Q||=1281},xe=(a,b,c)=>{c?u[c>>2]=P.getRenderbufferParameter(a,b):Q||=1281},ye=(a,b,c)=>{c?w[c>>2]=P.getSamplerParameter(N[a],b):Q||=1281},ze=(a,b,c)=>{c?u[c>>2]=P.getSamplerParameter(N[a],b):Q||=1281},Ae=(a,b,c,d)=>{a=P.getShaderInfoLog(K[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,t,d,b):0;c&&(u[c>>2]=b)},Be=(a,b,c,d)=>{a=P.getShaderPrecisionFormat(a,b);u[c>>2]=a.rangeMin;u[c+4>>2]=a.rangeMax;u[d>>2]=a.precision},
Ce=(a,b,c,d)=>{if(a=P.getShaderSource(K[a]))b=0<b&&d?B(a,t,d,b):0,c&&(u[c>>2]=b)},De=(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(K[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(K[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=P.getShaderParameter(K[a],b):Q||=1281},Ee=a=>{var b=sj[a];if(!b){switch(a){case 7939:b=Jj(Ck().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=P.getParameter(a))||(Q||=1280);b=b?Jj(b):0;break;case 7938:b=P.getParameter(7938);b=2<=
F.version?`OpenGL ES 3.0 (${b})`:`OpenGL ES 2.0 (${b})`;b=Jj(b);break;case 35724:b=P.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Jj(b);break;default:Q||=1280}sj[a]=b}return b},Fe=(a,b)=>{if(2>F.version)return Q||=1282,0;var c=tj[a];if(c)return 0>b||b>=c.length?(Q||=1281,0):c[b];switch(a){case 7939:return c=Ck().map(Jj),c=tj[a]=c,0>b||b>=c.length?(Q||=1281,0):c[b];default:return Q||=
1280,0}},Ge=(a,b,c,d,e)=>{0>c?Q||=1281:e?(a=P.getSyncParameter(qj[a],b),null!==a&&(u[e>>2]=a,d&&(u[d>>2]=1))):Q||=1281},He=(a,b,c)=>{c?w[c>>2]=P.getTexParameter(a,b):Q||=1281},Ie=(a,b,c)=>{c?u[c>>2]=P.getTexParameter(a,b):Q||=1281},Je=(a,b,c,d,e,f,g)=>{a=J[a];if(a=P.getTransformFeedbackVarying(a,b))g&&0<c?(c=B(a.name,t,g,c),d&&(u[d>>2]=c)):d&&(u[d>>2]=0),e&&(u[e>>2]=a.size),f&&(u[f>>2]=a.type)},Ke=(a,b)=>P.getUniformBlockIndex(J[a],b?z(t,b):""),Le=(a,b,c,d)=>{if(d)if(0<b&&(0==c||0==d))Q||=1281;else{a=
J[a];for(var e=[],f=0;f<b;f++)e.push(mi(u[c+4*f>>2]));if(a=P.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)u[d+4*f>>2]=a[f]}else Q||=1281},Fk=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Gk=a=>{var b=a.vh,c=a.ci,d;if(!b)for(a.vh=b={},a.bi={},d=0;d<P.getProgramParameter(a,35718);++d){var e=P.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Fk(f);g=0<g?f.slice(0,g):f;var k=a.Qh;a.Qh+=e;c[g]=[e,k];for(f=0;f<e;++f)b[k]=f,a.bi[k++]=g}},Me=(a,b)=>{b=b?z(t,b):"";if(a=J[a]){Gk(a);var c=a.vh,d=0,e=b,f=Fk(b);
0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.ci[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else Q||=1281;return-1},W=a=>{var b=P.ei;if(b){var c=b.vh[a];"number"==typeof c&&(b.vh[a]=c=P.getUniformLocation(b,b.bi[a]+(0<c?`[${c}]`:"")));return c}Q||=1282},Hk=(a,b,c,d)=>{if(c)if(a=J[a],Gk(a),a=P.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];
break;case 2:w[c+4*b>>2]=a[b]}else Q||=1281},Ne=(a,b,c)=>{Hk(a,b,c,2)},Oe=(a,b,c)=>{Hk(a,b,c,0)},Pe=(a,b,c)=>Hk(a,b,c,0),Ik=(a,b,c,d)=>{if(c)if(F.ih[a].enabled&&p("glGetVertexAttrib*v on client-side array: not supported, bad data returned"),a=P.getVertexAttrib(a,b),34975==b)u[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:u[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:u[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:u[c+4*b>>2]=a[b];break;case 2:w[c+
4*b>>2]=a[b];break;case 5:u[c+4*b>>2]=Math.fround(a[b])}else Q||=1281},Qe=(a,b,c)=>{Ik(a,b,c,0)},Re=(a,b,c)=>{c?(F.ih[a].enabled&&p("glGetVertexAttribPointer on client-side array: not supported, bad data returned"),u[c>>2]=P.getVertexAttribOffset(a,b)):Q||=1281},Se=(a,b,c)=>{Ik(a,b,c,2)},Te=(a,b,c)=>{Ik(a,b,c,5)},Ue=(a,b)=>P.hint(a,b),Ve=(a,b,c)=>{for(var d=xk[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];P.invalidateFramebuffer(a,d)},We=(a,b,c,d,e,f,g)=>{for(var k=xk[b],n=0;n<b;n++)k[n]=u[c+4*n>>2];P.invalidateSubFramebuffer(a,
k,d,e,f,g)},Xe=a=>(a=jj[a])?P.isBuffer(a):0,Ye=a=>P.isEnabled(a),Ze=a=>(a=lj[a])?P.isFramebuffer(a):0,$e=a=>(a=J[a])?P.isProgram(a):0,af=a=>(a=M[a])?P.isQuery(a):0,bf=a=>(a=M[a])?P.$g.isQueryEXT(a):0,cf=a=>(a=mj[a])?P.isRenderbuffer(a):0,df=a=>(a=N[a])?P.isSampler(a):0,ef=a=>(a=K[a])?P.isShader(a):0,ff=a=>P.isSync(qj[a]),gf=a=>(a=nj[a])?P.isTexture(a):0,hf=a=>P.isTransformFeedback(pj[a]),jf=a=>(a=oj[a])?P.isVertexArray(a):0,kf=a=>P.lineWidth(a),lf=a=>{a=J[a];P.linkProgram(a);a.vh=0;a.ci={}},mf=(a,
b,c,d)=>{if(0!=(d&33))return p("glMapBufferRange access does not support MAP_READ or MAP_UNSYNCHRONIZED"),0;if(0==(d&2))return p("glMapBufferRange access must include MAP_WRITE"),0;if(0==(d&12))return p("glMapBufferRange access must include INVALIDATE_BUFFER or INVALIDATE_RANGE"),0;if(!zk(a))return Q||=1280,p("GL_INVALID_ENUM in glMapBufferRange"),0;var e=A(c);a=yk(a);if(!e)return 0;kj[a]||(kj[a]={});a=kj[a];a.offset=b;a.length=c;a.gh=e;a.Sh=d;return e},nf=()=>P.pauseTransformFeedback(),of=(a,b)=>
{3317==a?uj=b:3314==a&&(vj=b);P.pixelStorei(a,b)},pf=(a,b)=>P.polygonOffset(a,b),qf=()=>{Q||=1280},rf=()=>{Q||=1280},sf=(a,b)=>{P.$g.queryCounterEXT(M[a],b)},tf=a=>P.readBuffer(a),Jk=a=>{a-=5120;return 0==a?r:1==a?t:2==a?Na:4==a?u:6==a?w:5==a||28922==a||28520==a||30779==a||30782==a?v:Oa},Kk=(a,b,c,d,e)=>{a=Jk(a);b=d*((vj||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+uj-1&-uj);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},
uf=(a,b,c,d,e,f,g)=>{if(2<=F.version)if(P.Kh)P.readPixels(a,b,c,d,e,f,g);else{var k=Jk(f);g>>>=31-Math.clz32(k.BYTES_PER_ELEMENT);P.readPixels(a,b,c,d,e,f,k,g)}else(k=Kk(f,e,c,d,g))?P.readPixels(a,b,c,d,e,f,k):Q||=1280},vf=()=>{},wf=(a,b,c,d)=>P.renderbufferStorage(a,b,c,d),xf=(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),yf=()=>P.resumeTransformFeedback(),zf=(a,b)=>{P.sampleCoverage(a,!!b)},Af=(a,b,c)=>{P.samplerParameterf(N[a],b,c)},Bf=(a,b,c)=>{P.samplerParameterf(N[a],b,w[c>>2])},Cf=
(a,b,c)=>{P.samplerParameteri(N[a],b,c)},Df=(a,b,c)=>{P.samplerParameteri(N[a],b,u[c>>2])},Ef=(a,b,c,d)=>P.scissor(a,b,c,d),Ff=()=>{Q||=1280},Gf=(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=mi(v[c+4*f>>2],d?v[d+4*f>>2]:void 0);P.shaderSource(K[a],e)},Hf=(a,b,c)=>P.stencilFunc(a,b,c),If=(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),Jf=a=>P.stencilMask(a),Kf=(a,b)=>P.stencilMaskSeparate(a,b),Lf=(a,b,c)=>P.stencilOp(a,b,c),Mf=(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),Nf=(a,b,c,d,e,f,g,k,n)=>{if(2<=F.version){if(P.fh){P.texImage2D(a,
b,c,d,e,f,g,k,n);return}if(n){var q=Jk(k);n>>>=31-Math.clz32(q.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,f,g,k,q,n);return}}q=n?Kk(k,g,d,e,n):null;P.texImage2D(a,b,c,d,e,f,g,k,q)},Of=(a,b,c,d,e,f,g,k,n,q)=>{if(P.fh)P.texImage3D(a,b,c,d,e,f,g,k,n,q);else if(q){var y=Jk(n);P.texImage3D(a,b,c,d,e,f,g,k,n,y,q>>>31-Math.clz32(y.BYTES_PER_ELEMENT))}else P.texImage3D(a,b,c,d,e,f,g,k,n,null)},Pf=(a,b,c)=>P.texParameterf(a,b,c),Qf=(a,b,c)=>{P.texParameterf(a,b,w[c>>2])},Rf=(a,b,c)=>P.texParameteri(a,b,c),
Sf=(a,b,c)=>{P.texParameteri(a,b,u[c>>2])},Tf=(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),Uf=(a,b,c,d,e,f)=>P.texStorage3D(a,b,c,d,e,f),Vf=(a,b,c,d,e,f,g,k,n)=>{if(2<=F.version){if(P.fh){P.texSubImage2D(a,b,c,d,e,f,g,k,n);return}if(n){var q=Jk(k);P.texSubImage2D(a,b,c,d,e,f,g,k,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}n=n?Kk(k,g,e,f,n):null;P.texSubImage2D(a,b,c,d,e,f,g,k,n)},Wf=(a,b,c,d,e,f,g,k,n,q,y)=>{if(P.fh)P.texSubImage3D(a,b,c,d,e,f,g,k,n,q,y);else if(y){var H=Jk(q);P.texSubImage3D(a,b,
c,d,e,f,g,k,n,q,H,y>>>31-Math.clz32(H.BYTES_PER_ELEMENT))}else P.texSubImage3D(a,b,c,d,e,f,g,k,n,q,null)},Xf=(a,b,c,d)=>{a=J[a];for(var e=[],f=0;f<b;f++)e.push(mi(u[c+4*f>>2]));P.transformFeedbackVaryings(a,e,d)},Yf=(a,b)=>{P.uniform1f(W(a),b)},Lk=[],Zf=(a,b,c)=>{if(2<=F.version)b&&P.uniform1fv(W(a),w,c>>2,b);else{if(288>=b)for(var d=Lk[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);P.uniform1fv(W(a),d)}},$f=(a,b)=>{P.uniform1i(W(a),b)},Mk=[],ag=(a,b,c)=>{if(2<=F.version)b&&P.uniform1iv(W(a),
u,c>>2,b);else{if(288>=b)for(var d=Mk[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);P.uniform1iv(W(a),d)}},bg=(a,b)=>{P.uniform1ui(W(a),b)},cg=(a,b,c)=>{b&&P.uniform1uiv(W(a),v,c>>2,b)},dg=(a,b,c)=>{P.uniform2f(W(a),b,c)},eg=(a,b,c)=>{if(2<=F.version)b&&P.uniform2fv(W(a),w,c>>2,2*b);else{if(144>=b)for(var d=Lk[2*b],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);P.uniform2fv(W(a),d)}},fg=(a,b,c)=>{P.uniform2i(W(a),b,c)},gg=(a,b,c)=>{if(2<=
F.version)b&&P.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b)for(var d=Mk[2*b],e=0;e<2*b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2];else d=u.subarray(c>>2,c+8*b>>2);P.uniform2iv(W(a),d)}},hg=(a,b,c)=>{P.uniform2ui(W(a),b,c)},ig=(a,b,c)=>{b&&P.uniform2uiv(W(a),v,c>>2,2*b)},jg=(a,b,c,d)=>{P.uniform3f(W(a),b,c,d)},kg=(a,b,c)=>{if(2<=F.version)b&&P.uniform3fv(W(a),w,c>>2,3*b);else{if(96>=b)for(var d=Lk[3*b],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>
2,c+12*b>>2);P.uniform3fv(W(a),d)}},lg=(a,b,c,d)=>{P.uniform3i(W(a),b,c,d)},mg=(a,b,c)=>{if(2<=F.version)b&&P.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=b)for(var d=Mk[3*b],e=0;e<3*b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2];else d=u.subarray(c>>2,c+12*b>>2);P.uniform3iv(W(a),d)}},ng=(a,b,c,d)=>{P.uniform3ui(W(a),b,c,d)},og=(a,b,c)=>{b&&P.uniform3uiv(W(a),v,c>>2,3*b)},pg=(a,b,c,d,e)=>{P.uniform4f(W(a),b,c,d,e)},qg=(a,b,c)=>{if(2<=F.version)b&&P.uniform4fv(W(a),w,c>>2,4*b);else{if(72>=
b){var d=Lk[4*b],e=w;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);P.uniform4fv(W(a),d)}},rg=(a,b,c,d,e)=>{P.uniform4i(W(a),b,c,d,e)},sg=(a,b,c)=>{if(2<=F.version)b&&P.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b)for(var d=Mk[4*b],e=0;e<4*b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2];else d=u.subarray(c>>2,c+16*b>>2);P.uniform4iv(W(a),d)}},tg=(a,b,c,d,e)=>{P.uniform4ui(W(a),
b,c,d,e)},ug=(a,b,c)=>{b&&P.uniform4uiv(W(a),v,c>>2,4*b)},vg=(a,b,c)=>{a=J[a];P.uniformBlockBinding(a,b,c)},wg=(a,b,c,d)=>{if(2<=F.version)b&&P.uniformMatrix2fv(W(a),!!c,w,d>>2,4*b);else{if(72>=b)for(var e=Lk[4*b],f=0;f<4*b;f+=4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2];else e=w.subarray(d>>2,d+16*b>>2);P.uniformMatrix2fv(W(a),!!c,e)}},xg=(a,b,c,d)=>{b&&P.uniformMatrix2x3fv(W(a),!!c,w,d>>2,6*b)},yg=(a,b,c,d)=>{b&&P.uniformMatrix2x4fv(W(a),!!c,w,d>>2,8*
b)},zg=(a,b,c,d)=>{if(2<=F.version)b&&P.uniformMatrix3fv(W(a),!!c,w,d>>2,9*b);else{if(32>=b)for(var e=Lk[9*b],f=0;f<9*b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2];else e=w.subarray(d>>2,d+36*b>>2);P.uniformMatrix3fv(W(a),!!c,e)}},Ag=(a,b,c,d)=>{b&&P.uniformMatrix3x2fv(W(a),!!c,w,d>>2,6*b)},Bg=(a,b,c,d)=>{b&&P.uniformMatrix3x4fv(W(a),
!!c,w,d>>2,12*b)},Cg=(a,b,c,d)=>{if(2<=F.version)b&&P.uniformMatrix4fv(W(a),!!c,w,d>>2,16*b);else{if(18>=b){var e=Lk[16*b],f=w;d>>=2;for(var g=0;g<16*b;g+=16){var k=d+g;e[g]=f[k];e[g+1]=f[k+1];e[g+2]=f[k+2];e[g+3]=f[k+3];e[g+4]=f[k+4];e[g+5]=f[k+5];e[g+6]=f[k+6];e[g+7]=f[k+7];e[g+8]=f[k+8];e[g+9]=f[k+9];e[g+10]=f[k+10];e[g+11]=f[k+11];e[g+12]=f[k+12];e[g+13]=f[k+13];e[g+14]=f[k+14];e[g+15]=f[k+15]}}else e=w.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(W(a),!!c,e)}},Dg=(a,b,c,d)=>{b&&P.uniformMatrix4x2fv(W(a),
!!c,w,d>>2,8*b)},Eg=(a,b,c,d)=>{b&&P.uniformMatrix4x3fv(W(a),!!c,w,d>>2,12*b)},Fg=a=>{if(!zk(a))return Q||=1280,p("GL_INVALID_ENUM in glUnmapBuffer"),0;var b=kj[yk(a)];if(!b||!b.gh)return Q||=1282,p("buffer was never mapped in glUnmapBuffer"),0;b.Sh&16||(2<=F.version?P.bufferSubData(a,b.offset,t,b.gh,b.length):P.bufferSubData(a,b.offset,t.subarray(b.gh,b.gh+b.length)));Ij(b.gh);b.gh=0;return 1},Gg=a=>{a=J[a];P.useProgram(a);P.ei=a},Hg=a=>{P.validateProgram(J[a])},Ig=(a,b)=>P.vertexAttrib1f(a,b),Jg=
(a,b)=>{P.vertexAttrib1f(a,w[b>>2])},Kg=(a,b,c)=>P.vertexAttrib2f(a,b,c),Lg=(a,b)=>{P.vertexAttrib2f(a,w[b>>2],w[b+4>>2])},Mg=(a,b,c,d)=>P.vertexAttrib3f(a,b,c,d),Ng=(a,b)=>{P.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},Og=(a,b,c,d,e)=>P.vertexAttrib4f(a,b,c,d,e),Pg=(a,b)=>{P.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},Qg=(a,b)=>{P.vertexAttribDivisor(a,b)},Rg=(a,b,c,d,e)=>P.vertexAttribI4i(a,b,c,d,e),Sg=(a,b)=>{P.vertexAttribI4i(a,u[b>>2],u[b+4>>2],u[b+8>>2],u[b+12>>2])},Tg=(a,b,
c,d,e)=>P.vertexAttribI4ui(a,b,c,d,e),Ug=(a,b)=>{P.vertexAttribI4ui(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},Vg=(a,b,c,d,e)=>{var f=F.ih[a];P.ph?(f.sh=!1,P.vertexAttribIPointer(a,b,c,d,e)):(f.size=b,f.type=c,f.Nh=!1,f.Eh=d,f.Dh=e,f.sh=!0,f.Rh=function(g,k,n,q,y,H){this.vertexAttribIPointer(g,k,n,y,H)})},Wg=(a,b,c,d,e,f)=>{var g=F.ih[a];P.ph?(g.sh=!1,P.vertexAttribPointer(a,b,c,!!d,e,f)):(g.size=b,g.type=c,g.Nh=d,g.Eh=e,g.Dh=f,g.sh=!0,g.Rh=function(k,n,q,y,H,Z){this.vertexAttribPointer(k,n,q,y,H,
Z)})},Xg=(a,b,c,d)=>P.viewport(a,b,c,d),Yg=(a,b,c,d)=>{P.waitSync(qj[a],b,(c>>>0)+4294967296*d)},Zg=()=>1,Nk=(a,b)=>{if(!Vj())return-1;a=T(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Rj()?uk(a,b):b.ii?(Pj(uk,1,[a,b]),1):-2:-3:-4};function $g(a,b,c){return m?E(38,0,1,a,b,c):Nk(a,{Oh:u[c>>2],Ih:u[c+4>>2],ki:u[c+8>>2],ii:b,xh:u[c+20>>2],nh:u[c+12>>2],yh:u[c+16>>2]})}function ah(a,b){if(m)return E(39,0,1,a,b);a=T(a);return a?a.requestPointerLock?Rj()?vk(a):b?(Pj(vk,2,[a]),1):-2:-1:-4}
var bh=()=>{Za("OOM")};function ch(){if(m)return E(40,0,1);try{if(navigator.getGamepads)return(Wj=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1}var Ok=(a,b)=>{var c={target:T(2),Wg:"beforeunload",Zg:b,ah:(d=event)=>{var e=V(b,28,0,a);e&&=e?z(t,e):"";if(e)return d.preventDefault(),d.returnValue=e},Yg:!0};return R(c)};function dh(a,b,c){return m?E(41,0,1,a,b,c):"undefined"==typeof onbeforeunload?-1:1!==c?-5:Ok(a,b)}
var Pk=(a,b,c,d,e,f,g)=>{g=S(g);Xj||=A(256);a={target:T(a),Wg:f,Zg:d,ah:(k=event)=>{var n=Uj(k.target),q=k.target.id?k.target.id:"",y=g?A(256):Xj;B(n,t,y+0,128);B(q,t,y+128,128);g?U(g,d,e,y,b):V(d,e,y,b)&&k.preventDefault()},Yg:c};return R(a)};function eh(a,b,c,d,e){return m?E(42,0,1,a,b,c,d,e):Pk(a,b,c,d,12,"blur",e)}function gh(a,b,c){if(m)return E(43,0,1,a,b,c);a=T(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0}
function hh(a,b,c,d,e){return m?E(44,0,1,a,b,c,d,e):Pk(a,b,c,d,13,"focus",e)}
var Qk=(a,b,c,d,e,f)=>{f=S(f);Zj||=A(276);return R({target:a,Wg:e,Zg:d,ah:(g=event)=>{var k=f?A(276):Zj,n=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,q=!!n;r[k]=q;r[k+1]=Vj();var y=q?n:Yj,H=y?.id||"";B(Uj(y),t,k+2,128);B(H,t,k+130,128);u[k+260>>2]=y?y.clientWidth:0;u[k+264>>2]=y?y.clientHeight:0;u[k+268>>2]=screen.width;u[k+272>>2]=screen.height;q&&(Yj=n);f?U(f,d,19,k,b):V(d,19,k,b)&&g.preventDefault()},Yg:c})};
function ih(a,b,c,d,e){if(m)return E(45,0,1,a,b,c,d,e);if(!Vj())return-1;a=T(a);if(!a)return-4;Qk(a,b,c,d,"webkitfullscreenchange",e);return Qk(a,b,c,d,"fullscreenchange",e)}var Rk=(a,b,c,d,e,f)=>{f=S(f);ak||=A(1240);b={target:T(2),wh:!0,Wg:e,Zg:c,ah:(g=event)=>{var k=f?A(1240):ak;wk(k,g.gamepad);f?U(f,c,d,k,a):V(c,d,k,a)&&g.preventDefault()},Yg:b};return R(b)};function jh(a,b,c,d){return m?E(46,0,1,a,b,c,d):ch()?-1:Rk(a,b,c,26,"gamepadconnected",d)}
function kh(a,b,c,d){return m?E(47,0,1,a,b,c,d):ch()?-1:Rk(a,b,c,27,"gamepaddisconnected",d)}
var Sk=(a,b,c,d,e,f,g)=>{g=S(g);bk||=A(160);a={target:T(a),Wg:f,Zg:d,ah:k=>{var n=g?A(160):bk;x[n>>3]=k.timeStamp;var q=n>>2;u[q+2]=k.location;r[n+12]=k.ctrlKey;r[n+13]=k.shiftKey;r[n+14]=k.altKey;r[n+15]=k.metaKey;r[n+16]=k.repeat;u[q+5]=k.charCode;u[q+6]=k.keyCode;u[q+7]=k.which;B(k.key||"",t,n+32,32);B(k.code||"",t,n+64,32);B(k.char||"",t,n+96,32);B(k.locale||"",t,n+128,32);g?U(g,d,e,n,b):V(d,e,n,b)&&k.preventDefault()},Yg:c};return R(a)};
function lh(a,b,c,d,e){return m?E(48,0,1,a,b,c,d,e):Sk(a,b,c,d,2,"keydown",e)}function mh(a,b,c,d,e){return m?E(49,0,1,a,b,c,d,e):Sk(a,b,c,d,1,"keypress",e)}function nh(a,b,c,d,e){return m?E(50,0,1,a,b,c,d,e):Sk(a,b,c,d,3,"keyup",e)}
var Tk=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;Na[2*d+14]=b.button;Na[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=tk(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},Uk=(a,b,c,d,e,f,g)=>{g=S(g);ck||=A(64);a=T(a);return R({target:a,wh:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Wg:f,Zg:d,ah:(k=event)=>{Tk(ck,k,a);if(g){var n=A(64);
Tk(n,k,a);U(g,d,e,n,b)}else V(d,e,ck,b)&&k.preventDefault()},Yg:c})};function oh(a,b,c,d,e){return m?E(51,0,1,a,b,c,d,e):Uk(a,b,c,d,5,"mousedown",e)}function ph(a,b,c,d,e){return m?E(52,0,1,a,b,c,d,e):Uk(a,b,c,d,33,"mouseenter",e)}function qh(a,b,c,d,e){return m?E(53,0,1,a,b,c,d,e):Uk(a,b,c,d,34,"mouseleave",e)}function rh(a,b,c,d,e){return m?E(54,0,1,a,b,c,d,e):Uk(a,b,c,d,8,"mousemove",e)}function sh(a,b,c,d,e){return m?E(55,0,1,a,b,c,d,e):Uk(a,b,c,d,6,"mouseup",e)}
var Vk=(a,b,c,d,e,f)=>{f=S(f);dk||=A(257);return R({target:a,Wg:e,Zg:d,ah:(g=event)=>{var k=f?A(257):dk,n=document.pointerLockElement||document.oh||document.Hh||document.Gh;r[k]=!!n;var q=n?.id||"";B(Uj(n),t,k+1,128);B(q,t,k+129,128);f?U(f,d,20,k,b):V(d,20,k,b)&&g.preventDefault()},Yg:c})};
function th(a,b,c,d,e){if(m)return E(56,0,1,a,b,c,d,e);if(!document||!document.body||!(document.body.requestPointerLock||document.body.oh||document.body.Hh||document.body.Gh))return-1;a=T(a);if(!a)return-4;Vk(a,b,c,d,"mozpointerlockchange",e);Vk(a,b,c,d,"webkitpointerlockchange",e);Vk(a,b,c,d,"mspointerlockchange",e);return Vk(a,b,c,d,"pointerlockchange",e)}
var Wk=(a,b,c,d,e)=>{e=S(e);ek||=A(36);a=T(a);return R({target:a,Wg:"resize",Zg:d,ah:(f=event)=>{if(f.target==a){var g=document.body;if(g){var k=e?A(36):ek;u[k>>2]=0;u[k+4>>2]=g.clientWidth;u[k+8>>2]=g.clientHeight;u[k+12>>2]=innerWidth;u[k+16>>2]=innerHeight;u[k+20>>2]=outerWidth;u[k+24>>2]=outerHeight;u[k+28>>2]=pageXOffset|0;u[k+32>>2]=pageYOffset|0;e?U(e,d,10,k,b):V(d,10,k,b)&&f.preventDefault()}}},Yg:c})};function uh(a,b,c,d,e){return m?E(57,0,1,a,b,c,d,e):Wk(a,b,c,d,e)}
var Xk=(a,b,c,d,e,f,g)=>{g=S(g);fk||=A(1552);a=T(a);return R({target:a,wh:"touchstart"==f||"touchend"==f,Wg:f,Zg:d,ah:k=>{var n={},q=k.touches;for(var y of q)y.Yh=y.$h=0,n[y.identifier]=y;for(var H of k.changedTouches)H.Yh=1,n[H.identifier]=H;for(var Z of k.targetTouches)n[Z.identifier].$h=1;q=g?A(1552):fk;x[q>>3]=k.timeStamp;r[q+12]=k.ctrlKey;r[q+13]=k.shiftKey;r[q+14]=k.altKey;r[q+15]=k.metaKey;y=q+16;H=tk(a);Z=0;for(let O of Object.values(n))if(n=y>>2,u[n]=O.identifier,u[n+1]=O.screenX,u[n+2]=
O.screenY,u[n+3]=O.clientX,u[n+4]=O.clientY,u[n+5]=O.pageX,u[n+6]=O.pageY,r[y+28]=O.Yh,r[y+29]=O.$h,u[n+8]=O.clientX-(H.left|0),u[n+9]=O.clientY-(H.top|0),y+=48,31<++Z)break;u[q+8>>2]=Z;g?U(g,d,e,q,b):V(d,e,q,b)&&k.preventDefault()},Yg:c})};function vh(a,b,c,d,e){return m?E(58,0,1,a,b,c,d,e):Xk(a,b,c,d,25,"touchcancel",e)}function wh(a,b,c,d,e){return m?E(59,0,1,a,b,c,d,e):Xk(a,b,c,d,23,"touchend",e)}function xh(a,b,c,d,e){return m?E(60,0,1,a,b,c,d,e):Xk(a,b,c,d,24,"touchmove",e)}
function yh(a,b,c,d,e){return m?E(61,0,1,a,b,c,d,e):Xk(a,b,c,d,22,"touchstart",e)}var Yk=(a,b,c,d)=>{var e=jk[1];d=S(d);gk||=A(8);return R({target:e,Wg:"visibilitychange",Zg:c,ah:(f=event)=>{var g=d?A(8):gk,k=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);r[g]=document.hidden;u[g+4>>2]=k;d?U(d,c,21,g,a):V(c,21,g,a)&&f.preventDefault()},Yg:b})};function zh(a,b,c,d){return m?E(62,0,1,a,b,c,d):jk[1]?Yk(a,b,c,d):-4}
var Zk=(a,b,c,d,e)=>{e=S(e);hk||=A(96);return R({target:a,wh:!0,Wg:"wheel",Zg:d,ah:(f=event)=>{var g=e?A(96):hk;Tk(g,f,a);x[g+64>>3]=f.deltaX;x[g+72>>3]=f.deltaY;x[g+80>>3]=f.deltaZ;u[g+88>>2]=f.deltaMode;e?U(e,d,9,g,b):V(d,9,g,b)&&f.preventDefault()},Yg:c})};function Ah(a,b,c,d,e){return m?E(63,0,1,a,b,c,d,e):(a=T(a))?"undefined"!=typeof a.onwheel?Zk(a,b,c,d,e):-1:-4}function Bh(a){return m?E(64,0,1,a):document.title=a?z(t,a):""}
var Ch=a=>$k(b=>Ii(b,a)),al={},cl=()=>{if(!bl){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in al)void 0===al[b]?delete a[b]:a[b]=al[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);bl=c}return bl},bl;
function Dh(a,b){if(m)return E(65,0,1,a,b);var c=0;cl().forEach((d,e)=>{var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)r[e++]=d.charCodeAt(f);r[e]=0;c+=d.length+1});return 0}function Eh(a,b){if(m)return E(66,0,1,a,b);var c=cl();v[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);v[b>>2]=d;return 0}function Gh(a){return m?E(67,0,1,a):52}function Hh(a,b,c,d){return m?E(68,0,1,a,b,c,d):52}function Ih(a,b,c,d,e){return m?E(69,0,1,a,b,c,d,e):70}var dl=[null,[],[]];
function Jh(a,b,c,d){if(m)return E(70,0,1,a,b,c,d);for(var e=0,f=0;f<c;f++){var g=v[b>>2],k=v[b+4>>2];b+=8;for(var n=0;n<k;n++){var q=t[g+n],y=dl[a];0===q||10===q?((1===a?ra:p)(z(y,0)),y.length=0):y.push(q)}e+=k}v[d>>2]=e;return 0}
var el=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Mh=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&el(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Nh=(a,b=[])=>{var c="vi".replace(/p/g,"i");(0,h["dynCall_"+c])(a,...b)},fl=a=>{try{a()}catch(b){Za(b)}};
function gl(){var a=X,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{hl.push(c);try{return d(...e)}finally{La||(hl.pop(),il&&1===jl&&0===hl.length&&(jl=0,D+=1,fl(kl),"undefined"!=typeof Fibers&&Fibers.Hi()))}}:d;return b}var jl=0,il=null,ll=0,hl=[],rl={},sl={},tl=0,ul=null,vl=[];function wl(){var a=A(4108),b=a+12;v[a>>2]=b;v[a+4>>2]=b+4096;b=hl[0];var c=rl[b];void 0===c&&(c=tl++,rl[b]=c,sl[c]=b);u[a+8>>2]=c;return a}function xl(){var a=X[sl[u[il+8>>2]]];--D;return a()}
function $k(a){if(!La){if(0===jl){var b=!1,c=!1;a((d=0)=>{if(!La&&(ll=d,b=!0,c)){jl=2;fl(()=>yl(il));"undefined"!=typeof Yi&&ui&&Ki();d=!1;try{var e=xl()}catch(k){e=k,d=!0}var f=!1;if(!il){var g=ul;g&&(ul=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(jl=1,il=wl(),"undefined"!=typeof Yi&&ui&&Ji(),fl(()=>zl(il)))}else 2===jl?(jl=0,fl(Al),Ij(il),il=null,vl.forEach(oi)):Za(`invalid state: ${jl}`);return ll}}m?$h=!1:di();
h.requestFullscreen=function(a,b){function c(){Li=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Ti,Ri&&d.requestPointerLock(),Li=!0,Si?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=v[SDL.screen>>2]|8388608),Xi(h.canvas),Wi()):Xi(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Si?("undefined"!=typeof SDL&&(u[SDL.screen>>2]=
v[SDL.screen>>2]&-8388609),Xi(h.canvas),Wi()):Xi(d));h.onFullScreen?.(Li);h.onFullscreen?.(Li)}Ri=a;Si=b;"undefined"==typeof Ri&&(Ri=!0);"undefined"==typeof Si&&(Si=!1);var d=h.canvas;Qi||(Qi=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=zi;h.setCanvasSize=function(a,b,c){Xi(h.canvas,a,b);c||Wi()};h.pauseMainLoop=Ji;h.resumeMainLoop=Ki;
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.eh&&a==h.canvas)return h.eh;var e;if(b){var f={antialias:!1,alpha:!1,Lh:"undefined"!=typeof WebGL2RenderingContext?2:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Ej&&(e=Bj(a,f)))var k=L[e].Xg}else k=a.getContext("2d");if(!k)return null;c&&(h.eh=k,b&&Dj(e),h.si=b,Ni.forEach(n=>n()),Oi());return k};
for(var P,Y=0;32>Y;++Y)xk.push(Array(Y));var Bl=new Float32Array(288);for(Y=0;288>=Y;++Y)Lk[Y]=Bl.subarray(0,Y);var Cl=new Int32Array(288);for(Y=0;288>=Y;++Y)Mk[Y]=Cl.subarray(0,Y);
var ri=[Kh,bi,ni,kb,lb,mb,nb,ob,pb,qb,wb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Wb,lk,pk,Xb,Zb,$b,ac,bc,dc,ec,$g,ah,ch,dh,eh,gh,hh,ih,jh,kh,lh,mh,nh,oh,ph,qh,rh,sh,th,uh,vh,wh,xh,yh,zh,Ah,Bh,Dh,Eh,Gh,Hh,Ih,Jh],gb,X=function(){function a(c,d){X=c.exports;X=gl();ci.push(X.Uf);Ra.unshift(X.Sf);Ka=d;Ya();return X}var b=wa();Xa();if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return p(`Module.instantiateWasm callback failed with error: ${c}`),!1}ab||=$a("destruct.wasm")?"destruct.wasm":
h.locateFile?h.locateFile("destruct.wasm",ja):ja+"destruct.wasm";fb(b,function(c){a(c.instance,c.module)});return{}}(),Dl=h._main=(a,b)=>(Dl=h._main=X.Tf)(a,b),va=()=>(va=X.Vf)(),U=(a,b,c,d,e)=>(U=X.Wf)(a,b,c,d,e),Ba=(a,b,c,d,e,f)=>(Ba=X.Xf)(a,b,c,d,e,f),Ia=()=>(Ia=X.Yf)(),Yh=(a,b,c,d,e)=>(Yh=X.Zf)(a,b,c,d,e),fi=a=>(fi=X._f)(a),Ga=a=>(Ga=X.$f)(a),pi=()=>(pi=X.ag)(),Ij=a=>(Ij=X.bg)(a),A=a=>(A=X.dg)(a),ki=(a,b)=>(ki=X.eg)(a,b),Zh=a=>(Zh=X.fg)(a),Xh=a=>(Xh=X.gg)(a),Wh=()=>(Wh=X.hg)(),li=h.dynCall_ii=
(a,b)=>(li=h.dynCall_ii=X.ig)(a,b),dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=X.jg)(a,b,c),dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=X.kg)(a,b);h.dynCall_viiii=(a,b,c,d,e)=>(h.dynCall_viiii=X.lg)(a,b,c,d,e);h.dynCall_iiiii=(a,b,c,d,e)=>(h.dynCall_iiiii=X.mg)(a,b,c,d,e);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=X.ng)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=X.og)(a,b);var V=h.dynCall_iiii=(a,b,c,d)=>(V=h.dynCall_iiii=X.pg)(a,b,c,d);
h.dynCall_i=a=>(h.dynCall_i=X.qg)(a);var dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=X.rg)(a),dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=X.sg)(a,b,c);h.dynCall_iiiiii=(a,b,c,d,e,f)=>(h.dynCall_iiiiii=X.tg)(a,b,c,d,e,f);h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=X.ug)(a,b,c,d,e,f);h.dynCall_viii=(a,b,c,d)=>(h.dynCall_viii=X.vg)(a,b,c,d);h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,k)=>(h.dynCall_iiiiiiii=X.wg)(a,b,c,d,e,f,g,k);
h.dynCall_iiiiiiiiii=(a,b,c,d,e,f,g,k,n,q)=>(h.dynCall_iiiiiiiiii=X.xg)(a,b,c,d,e,f,g,k,n,q);h.dynCall_iiiiiiiiiiiiiiff=(a,b,c,d,e,f,g,k,n,q,y,H,Z,O,sc,tc)=>(h.dynCall_iiiiiiiiiiiiiiff=X.yg)(a,b,c,d,e,f,g,k,n,q,y,H,Z,O,sc,tc);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,k,n)=>(h.dynCall_iiiiiiiii=X.zg)(a,b,c,d,e,f,g,k,n);h.dynCall_viiiiiii=(a,b,c,d,e,f,g,k)=>(h.dynCall_viiiiiii=X.Ag)(a,b,c,d,e,f,g,k);h.dynCall_viiiiiiiiiii=(a,b,c,d,e,f,g,k,n,q,y,H)=>(h.dynCall_viiiiiiiiiii=X.Bg)(a,b,c,d,e,f,g,k,n,q,y,H);
h.dynCall_iiiiiidiiff=(a,b,c,d,e,f,g,k,n,q,y)=>(h.dynCall_iiiiiidiiff=X.Cg)(a,b,c,d,e,f,g,k,n,q,y);h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=X.Dg)(a,b,c,d,e,f,g);h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=X.Eg)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=X.Fg)(a,b);h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,k,n)=>(h.dynCall_viiiiiiii=X.Gg)(a,b,c,d,e,f,g,k,n);h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,k,n,q)=>(h.dynCall_viiiiiiiii=X.Hg)(a,b,c,d,e,f,g,k,n,q);
h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=X.Ig)(a,b,c);h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=X.Jg)(a,b,c);h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=X.Kg)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=X.Lg)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=X.Mg)(a,b,c,d);h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=X.Ng)(a,b,c,d,e);h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=X.Og)(a,b,c,d,e,f);h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_viiiiii=X.Pg)(a,b,c,d,e,f,g);
h.dynCall_viiiiiiiiii=(a,b,c,d,e,f,g,k,n,q,y)=>(h.dynCall_viiiiiiiiii=X.Qg)(a,b,c,d,e,f,g,k,n,q,y);h.dynCall_viifi=(a,b,c,d,e)=>(h.dynCall_viifi=X.Rg)(a,b,c,d,e);var zl=a=>(zl=X.Sg)(a),kl=()=>(kl=X.Tg)(),yl=a=>(yl=X.Ug)(a),Al=()=>(Al=X.Vg)(),El;Wa=function Fl(){El||Gl();El||(Wa=Fl)};function Hl(a=[]){var b=Dl;a.unshift(fa);var c=a.length,d=Xh(4*(c+1)),e=d;a.forEach(g=>{v[e>>2]=mk(g);e+=4});v[e>>2]=0;try{var f=b(c,d);Fh(f,!0)}catch(g){ai(g)}}
function Gl(){var a=ea;function b(){if(!El&&(El=!0,h.calledRun=!0,!La&&(m||ji(Ra),m||ji(Sa),h.onRuntimeInitialized?.(),Il&&Hl(a),!m))){if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();Ta.unshift(c)}ji(Ta)}}if(!(0<Ua))if(m)m||ji(Ra),startWorker(h);else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Qa.unshift(h.preRun.shift());ji(Qa);0<Ua||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},
1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Il=!0;h.noInitialRun&&(Il=!1);Gl();
